---
deployment:
  tasks:
    - export DEPLOYPATH=/home/capnachi/cds.noitruxinman.edu.vn/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp admin.php chuyenmon.php csdl.php csdl_export.php index.php login.php logout.php noitru.php noitru_attendance.php noitru_list.php users.php $DEPLOYPATH
