<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/student_card_store.php';
require_login();
require_module('csdl', 'view');

$classes = student_card_class_map();
$students = array_values(array_filter(csdl_students_all(), function ($student) use ($classes) {
    if (empty($student['active'])) return false;
    $class = $classes[(string)($student['class_id'] ?? '')] ?? null;
    return !$class || !function_exists('can_class') || can_class((string)($class['name'] ?? ''));
}));
foreach ($students as &$student) {
    $class = $classes[(string)($student['class_id'] ?? '')] ?? [];
    $student['_class_name'] = (string)($class['name'] ?? '');
    $student['_grade'] = (string)($class['grade'] ?? '');
    $student['_verify_url'] = student_card_verify_url($student);
    $student['_public_code'] = student_card_public_code($student);
    $safeId = preg_replace('/[^a-zA-Z0-9_-]/', '', (string)($student['id'] ?? ''));
    $student['_has_photo'] = $safeId !== '' && is_file(DATA_PATH . '/student_photos/' . $safeId . '.jpg');
}
unset($student);
usort($students, fn($a,$b)=>strnatcasecmp($a['_class_name'],$b['_class_name']) ?: strcasecmp($a['name']??'',$b['name']??''));
$year = csdl_year_current()['label'] ?? SCHOOL_YEAR;
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tạo thẻ học sinh – CDS</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script>
<style>
:root{--card-main:#1f4e79;--card-accent:#f4b400;--card-text:#10243a}
body{background:#eef3f8;color:#203040}.toolbar{position:sticky;top:0;z-index:20;background:#fff;border-bottom:1px solid #dbe4ec}.option-card{background:#fff;border:1px solid #dce5ee;border-radius:14px}.student-list{max-height:420px;overflow:auto}.preview-area{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:12px}.student-card{width:85.6mm;height:53.98mm;background:#fff;border:1px solid #bcc9d5;border-radius:3mm;overflow:hidden;position:relative;color:var(--card-text);box-shadow:0 4px 14px rgba(15,35,55,.10);break-inside:avoid}.student-card.vertical{width:53.98mm;height:85.6mm}.card-top{height:13mm;background:var(--card-main);color:#fff;padding:2.2mm 3mm;display:flex;align-items:center;justify-content:space-between}.school{font-size:8.5pt;font-weight:800;line-height:1.1}.card-title{font-size:8pt;font-weight:900;letter-spacing:.08em}.card-body-x{display:grid;grid-template-columns:24mm 1fr 19mm;gap:2.6mm;padding:3mm}.vertical .card-body-x{grid-template-columns:1fr;text-align:center}.photo{width:22mm;height:29.3mm;object-fit:cover;border:1px solid #aebdca;border-radius:1.5mm;background:#edf1f5}.vertical .photo{width:26mm;height:34.7mm;margin:auto}.student-name{font-size:11pt;font-weight:900;color:var(--card-main);text-transform:uppercase;line-height:1.15;margin-bottom:1.5mm}.info{font-size:7.5pt;line-height:1.55}.qr{width:18mm;height:18mm}.qr img,.qr canvas{width:18mm!important;height:18mm!important}.card-code{font-size:6.5pt;text-align:center;font-weight:700;margin-top:1mm}.card-year{position:absolute;left:3mm;bottom:1.8mm;font-size:6.5pt;color:#53677a}.accent{height:1.2mm;background:var(--card-accent)}.no-photo{display:flex;align-items:center;justify-content:center;font-size:24pt;color:#91a0ad}.hidden-option{display:none!important}
@media print{body{background:#fff}.no-print{display:none!important}.container-fluid{padding:0!important}.preview-area{display:grid;grid-template-columns:repeat(var(--cols,2),85.6mm);gap:5mm;justify-content:center}.student-card{box-shadow:none}.student-card.vertical{width:53.98mm;height:85.6mm}.page-break{break-before:page}@page{size:A4;margin:8mm}}
</style></head><body>
<div class="toolbar no-print"><div class="container-fluid py-2 d-flex justify-content-between align-items-center gap-2"><div><strong><i class="bi bi-person-badge"></i> Tạo thẻ học sinh</strong><div class="small text-muted">Chọn học sinh, mẫu thẻ và nội dung trước khi in.</div></div><div class="d-flex gap-2"><a href="<?= BASE_URL ?>csdl.php?tab=students" class="btn btn-outline-secondary btn-sm">Trở lại</a><button class="btn btn-primary btn-sm" onclick="window.print()"><i class="bi bi-printer"></i> In / Lưu PDF</button></div></div></div>
<div class="container-fluid py-3"><div class="row g-3">
<div class="col-xl-3 no-print"><div class="option-card p-3 mb-3"><h6 class="fw-bold">Bộ lọc học sinh</h6><div class="row g-2"><div class="col-6"><select id="gradeFilter" class="form-select form-select-sm"><option value="">Tất cả khối</option><?php foreach(array_values(array_unique(array_filter(array_map(fn($s)=>$s['_grade'],$students)))) as $g):?><option value="<?=e($g)?>">Khối <?=e($g)?></option><?php endforeach;?></select></div><div class="col-6"><select id="classFilter" class="form-select form-select-sm"><option value="">Tất cả lớp</option><?php foreach(array_values(array_unique(array_filter(array_map(fn($s)=>$s['_class_name'],$students)))) as $c):?><option value="<?=e($c)?>"><?=e($c)?></option><?php endforeach;?></select></div><div class="col-8"><input id="searchFilter" class="form-control form-control-sm" placeholder="Tìm tên, mã HS"></div><div class="col-4"><select id="photoFilter" class="form-select form-select-sm"><option value="">Mọi ảnh</option><option value="yes">Có ảnh</option><option value="no">Chưa ảnh</option></select></div></div><div class="d-flex gap-2 mt-2"><button id="selectVisible" class="btn btn-sm btn-outline-primary">Chọn đang hiện</button><button id="clearAll" class="btn btn-sm btn-outline-secondary">Bỏ chọn</button></div><div class="student-list mt-2" id="studentList"><?php foreach($students as $s):$sid=(string)$s['id'];?><label class="d-flex gap-2 border-bottom py-2 student-choice" data-grade="<?=e($s['_grade'])?>" data-class="<?=e($s['_class_name'])?>" data-photo="<?=$s['_has_photo']?'yes':'no'?>" data-text="<?=e(mb_strtolower(($s['name']??'').' '.($s['code']??''),'UTF-8'))?>"><input class="form-check-input student-check" type="checkbox" value="<?=e($sid)?>" checked><span><strong><?=e($s['name']??'')?></strong><small class="d-block text-muted"><?=e($s['_class_name'])?> · <?=e($s['code']??'')?> · <?=$s['_has_photo']?'Có ảnh':'Chưa ảnh'?></small></span></label><?php endforeach;?></div></div>
<div class="option-card p-3"><h6 class="fw-bold">Tùy chọn thẻ</h6><label class="form-label small mb-0">Mẫu thẻ</label><select id="template" class="form-select form-select-sm mb-2"><option value="horizontal">Thẻ ngang CR80</option><option value="vertical">Thẻ dọc CR80</option></select><div class="row g-2"><div class="col-6"><label class="form-label small mb-0">Màu chính</label><input id="mainColor" type="color" class="form-control form-control-color w-100" value="#1f4e79"></div><div class="col-6"><label class="form-label small mb-0">Màu nhấn</label><input id="accentColor" type="color" class="form-control form-control-color w-100" value="#f4b400"></div></div><hr><div class="form-check"><input class="form-check-input toggle-field" type="checkbox" data-target="dob" checked><label class="form-check-label">Ngày sinh</label></div><div class="form-check"><input class="form-check-input toggle-field" type="checkbox" data-target="gender"><label class="form-check-label">Giới tính</label></div><div class="form-check"><input class="form-check-input toggle-field" type="checkbox" data-target="code" checked><label class="form-check-label">Mã học sinh</label></div><div class="form-check"><input class="form-check-input toggle-field" type="checkbox" data-target="qr" checked><label class="form-check-label">Mã QR xác minh/thư viện</label></div><div class="form-check"><input class="form-check-input toggle-field" type="checkbox" data-target="year" checked><label class="form-check-label">Năm học</label></div><div class="mt-2 small text-muted">Dùng nút In để in trực tiếp hoặc chọn “Lưu dưới dạng PDF” trong hộp thoại in.</div></div></div>
<div class="col-xl-9"><div class="d-flex justify-content-between mb-2"><div><strong id="selectedCount">0</strong> thẻ được chọn</div><div class="small text-muted">Năm học <?=e($year)?></div></div><div id="preview" class="preview-area"></div></div>
</div></div>
<script>
const students=<?=json_encode($students,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const base=<?=json_encode(BASE_URL)?>;const year=<?=json_encode($year)?>;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmtDate(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v||''))return v||'—';let p=v.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
function render(){document.documentElement.style.setProperty('--card-main',mainColor.value);document.documentElement.style.setProperty('--card-accent',accentColor.value);let selected=new Set([...document.querySelectorAll('.student-check:checked')].map(x=>x.value));let html='';students.filter(s=>selected.has(String(s.id))).forEach(s=>{let cls=template.value==='vertical'?'student-card vertical':'student-card';html+=`<article class="${cls}"><div class="accent"></div><div class="card-top"><div class="school"><?=e(SCHOOL_NAME)?></div><div class="card-title">THẺ HỌC SINH</div></div><div class="card-body-x"><img class="photo" src="${base}student_photo.php?id=${encodeURIComponent(s.id)}" onerror="this.outerHTML='<div class=\'photo no-photo\'><i class=\'bi bi-person\'></i></div>'"><div><div class="student-name">${esc(s.name)}</div><div class="info"><div><b>Lớp:</b> ${esc(s._class_name||'—')}</div><div data-field="dob"><b>Ngày sinh:</b> ${esc(fmtDate(s.dob))}</div><div data-field="gender"><b>Giới tính:</b> ${esc(s.gender||'—')}</div><div data-field="code"><b>Mã HS:</b> ${esc(s.code||s._public_code)}</div></div></div><div data-field="qr"><div class="qr" data-url="${esc(s._verify_url)}"></div><div class="card-code">${esc(s._public_code)}</div></div></div><div data-field="year" class="card-year">Năm học: ${esc(year)}</div></article>`});preview.innerHTML=html;selectedCount.textContent=selected.size;document.querySelectorAll('.toggle-field').forEach(t=>document.querySelectorAll(`[data-field="${t.dataset.target}"]`).forEach(el=>el.classList.toggle('hidden-option',!t.checked)));document.querySelectorAll('.qr').forEach(el=>new QRCode(el,{text:el.dataset.url,width:96,height:96,correctLevel:QRCode.CorrectLevel.M}));}
function filter(){let g=gradeFilter.value,c=classFilter.value,p=photoFilter.value,q=searchFilter.value.trim().toLowerCase();document.querySelectorAll('.student-choice').forEach(row=>row.style.display=(!g||row.dataset.grade===g)&&(!c||row.dataset.class===c)&&(!p||row.dataset.photo===p)&&(!q||row.dataset.text.includes(q))?'':'none')}
[gradeFilter,classFilter,photoFilter].forEach(x=>x.addEventListener('change',filter));searchFilter.addEventListener('input',filter);selectVisible.onclick=()=>{document.querySelectorAll('.student-choice').forEach(r=>{if(r.style.display!=='none')r.querySelector('input').checked=true});render()};clearAll.onclick=()=>{document.querySelectorAll('.student-check').forEach(x=>x.checked=false);render()};document.addEventListener('change',e=>{if(e.target.matches('.student-check,.toggle-field,#template,#mainColor,#accentColor'))render()});filter();render();
</script></body></html>