<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/teacher_evaluation.php';
require_login();
register_shutdown_function(function(){ require __DIR__.'/includes/module_switcher.php'; });

$user=current_user()??[];
$isAdmin=($user['role']??'')==='admin';
$isLeader=($user['role']??'')==='totruong'||in_array('totruong',(array)($user['groups']??[]),true);
$canAll=$isAdmin||($user['role']??'')==='bgh'||can_perm_level('td.all_data','view');
$canOpen=$isAdmin||can_perm_level('td.teacher_rating','view')||can_perm_level('td.stats','view')||can_perm_level('cm.baocao.dugio','view');
if(!$canOpen){http_response_code(403);exit('Tài khoản chưa được cấp quyền xem hồ sơ đánh giá giáo viên.');}

$teachers=te_teachers();$linkedName=trim((string)($user['teacher_name']??$user['name']??''));$linkedTeacher=null;
foreach($teachers as $teacher)if(te_norm($teacher['name']??'')===te_norm($linkedName)){$linkedTeacher=$teacher;break;}
$linkedTeam=$linkedTeacher?te_teacher_team($linkedTeacher):'';
$scopeTeachers=array_values(array_filter($teachers,function($teacher)use($canAll,$isLeader,$linkedTeacher,$linkedTeam){
    if($canAll)return true;
    if($isLeader&&$linkedTeam!=='')return te_norm(te_teacher_team($teacher))===te_norm($linkedTeam);
    return $linkedTeacher&&(string)($teacher['id']??'')===(string)($linkedTeacher['id']??'');
}));

$year=csdl_year_current()??['id'=>'','label'=>SCHOOL_YEAR,'start'=>date('Y').'-09-01','end'=>(date('Y')+1).'-05-31'];
$period=te_period($year,(string)($_GET['period_type']??'month'),(string)($_GET['anchor']??date('Y-m-d')),(string)($_GET['from']??''),(string)($_GET['to']??''));
$config=te_config();$observations=te_observations();$fileChecks=te_file_checks();$td=load_json(DATA_PATH.'/thidua.json',['records'=>[]]);$tdRecords=$td['records']??[];
$results=[];foreach($scopeTeachers as $teacher)$results[(string)($teacher['id']??'')]=te_calculate($teacher,$period,$config,$observations,$fileChecks,$tdRecords);
$reviews=te_reviews();
foreach($results as $teacherId=>&$result){$saved=$reviews[te_review_key($period,$teacherId)]??[];if(($saved['status']??'')==='locked'&&is_array($saved['snapshot']??null))$result=$saved['snapshot'];}unset($result);
if(empty($_SESSION['te_csrf']))$_SESSION['te_csrf']=bin2hex(random_bytes(20));$csrf=$_SESSION['te_csrf'];

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Phiên làm việc không hợp lệ.');}
    $action=(string)($_POST['action']??'');
    if($action==='save_config'){
        if(!$isAdmin){http_response_code(403);exit('Chỉ quản trị được sửa công thức đánh giá.');}
        $new=$config;
        $new['version']=2;$new['groups']=[];$groupIds=[];
        foreach((array)($_POST['group_id']??[]) as $i=>$rawId){$id=preg_replace('/[^a-zA-Z0-9_-]/','',(string)$rawId);$name=trim((string)($_POST['group_name'][$i]??''));if($id===''||$name===''||isset($groupIds[$id]))continue;$groupIds[$id]=true;$new['groups'][]=['id'=>$id,'name'=>$name,'max'=>max(0,(float)($_POST['group_max'][$i]??0))];}
        if(!$new['groups']){flash('Cần giữ lại ít nhất một nhóm/cột đánh giá.','danger');header('Location: '.BASE_URL.'danhgia.php?view=settings');exit;}
        $catalog=te_source_catalog();$new['criteria']=[];
        foreach((array)($_POST['criterion_id']??[]) as $i=>$rawId){$id=preg_replace('/[^a-zA-Z0-9_-]/','',(string)$rawId);$name=trim((string)($_POST['criterion_name'][$i]??''));$groupId=(string)($_POST['criterion_group'][$i]??'');$source=(string)($_POST['criterion_source'][$i]??'');$operation=(string)($_POST['criterion_operation'][$i]??'add');if($id===''||$name===''||!isset($groupIds[$groupId])||!isset($catalog[$source]))continue;$new['criteria'][]=['id'=>$id,'name'=>$name,'group_id'=>$groupId,'source'=>$source,'operation'=>$operation==='subtract'?'subtract':'add','points'=>max(0,(float)($_POST['criterion_points'][$i]??0))];}
        $labels=['Hoàn thành xuất sắc','Hoàn thành tốt','Hoàn thành','Không hoàn thành'];$new['ratings']=[];
        foreach($labels as $i=>$label)$new['ratings'][]=['min'=>max(0,(float)($_POST['rating_min'][$i]??0)),'label'=>$label];
        $new['updated_by']=$user['name']??'';$new['updated_at']=date('c');save_json(DATA_PATH.'/teacher_evaluation_config.json',$new);if(function_exists('cds_audit_log'))cds_audit_log('evaluation_config_updated','teacher_evaluation',['version'=>$new['version']??1]);
        flash('Đã lưu công thức đánh giá. Các kỳ đã khóa vẫn giữ nguyên ảnh chụp kết quả.');header('Location: '.BASE_URL.'danhgia.php?view=settings');exit;
    }
    if($action==='review'){
        $teacherId=(string)($_POST['teacher_id']??'');$result=$results[$teacherId]??null;
        if(!$result){http_response_code(403);exit('Giáo viên nằm ngoài phạm vi quản lý.');}
        $status=(string)($_POST['status']??'');$allowed=false;
        if($status==='teacher_checked'&&$linkedTeacher&&(string)($linkedTeacher['id']??'')===$teacherId)$allowed=true;
        if($status==='leader_confirmed'&&$isLeader&&te_norm($result['team'])===te_norm($linkedTeam))$allowed=true;
        if(in_array($status,['approved','locked'],true)&&$canAll)$allowed=true;
        if(!$allowed){http_response_code(403);exit('Bạn không có quyền xác nhận trạng thái này.');}
        $key=te_review_key($period,$teacherId);$old=$reviews[$key]??[];
        if(($old['status']??'')==='locked'&&!$isAdmin){http_response_code(403);exit('Kỳ đánh giá đã khóa.');}
        $reviews[$key]=array_merge($old,['id'=>$key,'period'=>$period,'teacher_id'=>$teacherId,'teacher_name'=>$result['teacher_name'],'team'=>$result['team'],'status'=>$status,'note'=>trim((string)($_POST['note']??'')),'snapshot'=>$result,'updated_by'=>$user['name']??'','updated_at'=>date('c')]);
        save_json(DATA_PATH.'/teacher_evaluation_reviews.json',$reviews);if(function_exists('cds_audit_log'))cds_audit_log('evaluation_status_updated','teacher_evaluation',['teacher_id'=>$teacherId,'period'=>$period['key'],'status'=>$status]);flash('Đã cập nhật trạng thái hồ sơ đánh giá.');header('Location: '.$_SERVER['REQUEST_URI']);exit;
    }
}

$teamFilter=trim((string)($_GET['team']??''));$teacherFilter=trim((string)($_GET['teacher_id']??''));
$filtered=array_values(array_filter($results,fn($row)=>($teamFilter===''||$row['team']===$teamFilter)&&($teacherFilter===''||$row['teacher_id']===$teacherFilter)));
usort($filtered,fn($a,$b)=>$b['total']<=>$a['total']?:strnatcasecmp($a['teacher_name'],$b['teacher_name']));
$teams=array_values(array_unique(array_column($results,'team')));sort($teams,SORT_NATURAL|SORT_FLAG_CASE);
$view=in_array($_GET['view']??'overview',['overview','profile','settings'],true)?($_GET['view']??'overview'):'overview';if($view==='settings'&&!$isAdmin)$view='overview';
$profileId=(string)($_GET['id']??($linkedTeacher['id']??''));$profile=$results[$profileId]??null;
$statusLabels=[''=>'Đang tổng hợp','teacher_checked'=>'Giáo viên đã kiểm tra','leader_confirmed'=>'Tổ trưởng đã xác nhận','approved'=>'BGH đã duyệt','locked'=>'Đã khóa'];
function te_query(array $extra=[]): string {return http_build_query(array_merge($_GET,$extra));}
function te_group_score(array $result,string $id): float {if(isset($result['group_scores'][$id]))return (float)$result['group_scores'][$id];return (float)($result[$id]??0);}
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hồ sơ đánh giá giáo viên – CDS</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<style>
:root{--ev:#315b8a;--ev-dark:#173f65;--ev-soft:#eef5fb}body{background:#f2f6fa;color:#172033;font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.ev-shell{display:grid;grid-template-columns:250px minmax(0,1fr);min-height:100vh}.ev-side{position:sticky;top:0;height:100vh;padding:1rem;background:linear-gradient(180deg,var(--ev-dark),#102f4d);color:#fff}.ev-brand{display:flex;align-items:center;gap:.7rem;color:#fff;text-decoration:none;padding:.4rem .4rem 1.1rem}.ev-brand i{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#ffffff1f}.ev-brand small{display:block;color:#bfdbfe}.ev-nav a{display:flex;align-items:center;gap:.65rem;padding:.68rem .75rem;margin:.18rem 0;border-radius:10px;color:#e5eef7;text-decoration:none;font-weight:650}.ev-nav a.active,.ev-nav a:hover{background:#fff;color:var(--ev-dark)}.ev-back{position:absolute;bottom:1rem;left:1rem;right:1rem}.ev-main{min-width:0;padding:1.25rem}.ev-head{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;margin-bottom:1rem}.ev-card{border:1px solid #dfe8f0;border-radius:16px;background:#fff;box-shadow:0 4px 18px #0f172a0d}.ev-filter{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:.65rem;padding:1rem;margin-bottom:1rem;align-items:end}.ev-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:.7rem;margin-bottom:1rem}.ev-kpis>div{padding:1rem}.ev-kpis strong{display:block;font-size:1.45rem;color:var(--ev)}.ev-kpis span{font-size:.76rem;color:#64748b}.ev-table{min-width:1120px}.ev-table th{background:var(--ev-soft);color:var(--ev-dark);white-space:nowrap;text-align:center}.ev-table td{vertical-align:middle}.ev-score{text-align:center;font-weight:750}.ev-status{display:inline-block;padding:.3rem .55rem;border-radius:999px;background:#e8eef5;font-size:.72rem;font-weight:750}.ev-status.locked{background:#d1e7dd;color:#0f5132}.ev-profile-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem}.ev-metric{padding:1rem}.ev-metric strong{display:block;font-size:1.55rem;color:var(--ev)}.ev-source{padding:1rem;margin-top:1rem}.ev-source table{min-width:760px}.ev-settings{padding:1.2rem}.ev-settings-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.ev-mobile{display:none}@media(max-width:991px){.ev-shell{display:block}.ev-side{display:none}.ev-main{padding:.75rem;padding-bottom:78px}.ev-filter{grid-template-columns:1fr 1fr}.ev-kpis{grid-template-columns:1fr 1fr}.ev-kpis>div:first-child{grid-column:1/-1}.ev-profile-grid,.ev-settings-grid{grid-template-columns:1fr 1fr}.ev-mobile{position:fixed;display:grid;grid-template-columns:repeat(3,1fr);left:0;right:0;bottom:0;z-index:20;padding:.45rem;background:#fff;border-top:1px solid #dbe5ee}.ev-mobile a{text-align:center;color:#64748b;text-decoration:none;font-size:.72rem}.ev-mobile i{display:block;font-size:1.2rem}.ev-mobile a.active{color:var(--ev)}}
</style></head><body><div class="ev-shell"><aside class="ev-side"><a class="ev-brand" href="<?=BASE_URL?>admin.php"><i class="bi bi-person-vcard"></i><span><strong>ĐÁNH GIÁ GIÁO VIÊN</strong><small>Hồ sơ tập trung CDS</small></span></a><nav class="ev-nav"><a class="<?=$view==='overview'?'active':''?>" href="?view=overview"><i class="bi bi-bar-chart-line"></i>Tổng hợp đánh giá</a><a class="<?=$view==='profile'?'active':''?>" href="?view=profile"><i class="bi bi-person-lines-fill"></i>Hồ sơ chuyên môn</a><?php if($isAdmin):?><a class="<?=$view==='settings'?'active':''?>" href="?view=settings"><i class="bi bi-sliders"></i>Tiêu chí và thang điểm</a><?php endif;?></nav><a class="ev-back btn btn-outline-light" href="<?=BASE_URL?>chuyenmon/"><i class="bi bi-arrow-left"></i> Chuyên môn</a></aside><main class="ev-main"><?php show_flash();?><header class="ev-head"><div><h3 class="mb-1"><i class="bi bi-person-check text-primary"></i> <?=$view==='settings'?'Cài đặt đánh giá':($view==='profile'?'Hồ sơ chuyên môn':'Tổng hợp đánh giá giáo viên')?></h3><div class="text-muted">Năm học <?=e($year['label']??SCHOOL_YEAR)?> · Kết quả tạm tính từ dữ liệu nguồn</div></div><span class="badge text-bg-primary p-2"><?=e($user['name']??'')?></span></header>

<?php if($view!=='settings'):?><form class="ev-card ev-filter" method="get"><input type="hidden" name="view" value="<?=$view?>"><div><label class="form-label small fw-semibold">Kỳ đánh giá</label><select class="form-select" name="period_type"><option value="month" <?=$period['type']==='month'?'selected':''?>>Tháng</option><option value="semester" <?=$period['type']==='semester'?'selected':''?>>Học kỳ</option><option value="year" <?=$period['type']==='year'?'selected':''?>>Năm học</option><option value="custom" <?=$period['type']==='custom'?'selected':''?>>Khoảng ngày</option></select></div><div><label class="form-label small fw-semibold">Ngày tham chiếu</label><input class="form-control" type="date" name="anchor" value="<?=e($period['anchor'])?>"></div><div><label class="form-label small fw-semibold">Từ ngày</label><input class="form-control" type="date" name="from" value="<?=e($period['from'])?>"></div><div><label class="form-label small fw-semibold">Đến ngày</label><input class="form-control" type="date" name="to" value="<?=e($period['to'])?>"></div><?php if($view==='overview'):?><div><label class="form-label small fw-semibold">Tổ chuyên môn</label><select class="form-select" name="team"><option value="">Tất cả tổ</option><?php foreach($teams as $team):?><option value="<?=e($team)?>" <?=$team===$teamFilter?'selected':''?>><?=e($team)?></option><?php endforeach;?></select></div><?php else:?><div><label class="form-label small fw-semibold">Giáo viên</label><select class="form-select" name="id"><?php foreach($scopeTeachers as $teacher):?><option value="<?=e($teacher['id']??'')?>" <?=($teacher['id']??'')===$profileId?'selected':''?>><?=e($teacher['name']??'')?></option><?php endforeach;?></select></div><?php endif;?><button class="btn btn-primary"><i class="bi bi-funnel"></i> Xem</button></form><?php endif;?>

<?php if($view==='overview'):$avg=$filtered?array_sum(array_column($filtered,'total'))/count($filtered):0;?><div class="ev-kpis"><div class="ev-card"><strong><?=count($filtered)?></strong><span>Giáo viên</span></div><div class="ev-card"><strong><?=number_format($avg,1)?></strong><span>Điểm trung bình</span></div><div class="ev-card"><strong><?=array_sum(array_column($filtered,'rated_observation_count'))?></strong><span>Tiết dự giờ đã chấm</span></div><div class="ev-card"><strong><?=array_sum(array_column($filtered,'unpermitted_days'))?></strong><span>Ngày nghỉ không phép</span></div><div class="ev-card"><strong><?=array_sum(array_column($filtered,'achievement_count'))?></strong><span>Thành tích</span></div></div><section class="ev-card overflow-hidden"><div class="table-responsive"><table class="table table-hover mb-0 ev-table"><thead><tr><th>STT</th><th class="text-start">Giáo viên</th><th>Tổ</th><?php foreach($config['groups'] as $group):?><th><?=e($group['name'])?><small class="d-block fw-normal">/<?=e($group['max'])?></small></th><?php endforeach;?><th>Tổng</th><th>Xếp loại</th><th>Trạng thái</th><th></th></tr></thead><tbody><?php foreach($filtered as $i=>$row):$review=$reviews[te_review_key($period,$row['teacher_id'])]??[];$status=$review['status']??'';?><tr><td class="text-center"><?=$i+1?></td><td><strong><?=e($row['teacher_name'])?></strong></td><td><?=e($row['team'])?></td><?php foreach($config['groups'] as $group):?><td class="ev-score"><?=number_format(te_group_score($row,$group['id']),1)?></td><?php endforeach;?><td class="ev-score text-primary"><?=number_format($row['total'],1)?></td><td><?=e($row['rating'])?></td><td><span class="ev-status <?=$status==='locked'?'locked':''?>"><?=e($statusLabels[$status]??'Đang tổng hợp')?></span></td><td><a class="btn btn-sm btn-outline-primary" href="?<?=te_query(['view'=>'profile','id'=>$row['teacher_id']])?>">Chi tiết</a></td></tr><?php endforeach;if(!$filtered):?><tr><td colspan="<?=count($config['groups'])+7?>" class="text-center text-muted py-5">Không có giáo viên trong phạm vi được xem.</td></tr><?php endif;?></tbody></table></div></section>

<?php elseif($view==='profile'):?><?php if(!$profile):?><div class="alert alert-warning">Tài khoản chưa liên kết với giáo viên hoặc giáo viên nằm ngoài phạm vi được xem.</div><?php else:$review=$reviews[te_review_key($period,$profile['teacher_id'])]??[];$status=$review['status']??'';?><div class="ev-card p-3 mb-3 d-flex flex-wrap justify-content-between gap-3"><div><h4 class="mb-1"><?=e($profile['teacher_name'])?></h4><div class="text-muted"><?=e($profile['team'])?> · <?=date('d/m/Y',strtotime($period['from']))?>–<?=date('d/m/Y',strtotime($period['to']))?></div></div><div><span class="ev-status <?=$status==='locked'?'locked':''?>"><?=e($statusLabels[$status]??'Đang tổng hợp')?></span><div class="small text-muted mt-1"><?=e($review['updated_by']??'')?> <?=!empty($review['updated_at'])?'· '.date('d/m/Y H:i',strtotime($review['updated_at'])):''?></div></div></div><div class="ev-profile-grid"><?php foreach($config['groups'] as $group):?><div class="ev-card ev-metric"><span><?=e($group['name'])?></span><strong><?=number_format(te_group_score($profile,$group['id']),1)?>/<?=e($group['max'])?></strong><small>Điểm theo tiêu chí đã cấu hình</small></div><?php endforeach;?><div class="ev-card ev-metric"><span>Tổng điểm</span><strong><?=number_format($profile['total'],1)?></strong><small><?=e($profile['rating'])?></small></div></div>
<?php if(!empty($profile['criterion_details'])):?><section class="ev-card ev-source"><h5>Chi tiết công thức đã áp dụng</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tiêu chí</th><th>Nguồn</th><th class="text-center">Số lượng</th><th class="text-center">Điểm/lượt</th><th class="text-center">Cộng/trừ</th></tr></thead><tbody><?php $catalog=te_source_catalog();foreach($profile['criterion_details'] as $detail):?><tr><td><?=e($detail['name']??'')?></td><td><?=e($catalog[$detail['source']??'']??'')?></td><td class="text-center"><?=e($detail['units']??0)?></td><td class="text-center"><?=e($detail['points']??0)?></td><td class="text-center fw-semibold <?=($detail['amount']??0)<0?'text-danger':'text-success'?>"><?=($detail['amount']??0)>0?'+':''?><?=e($detail['amount']??0)?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<section class="ev-card ev-source"><h5>Căn cứ dự giờ</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Ngày</th><th>Môn/lớp</th><th>Bài dạy</th><th>Điểm</th><th>Xếp loại</th></tr></thead><tbody><?php foreach($profile['sources']['observations'] as $row):?><tr><td><?=!empty($row['date'])?date('d/m/Y',strtotime($row['date'])):''?></td><td><?=e(trim(($row['subject']??'').' '.($row['class']??'')))?></td><td><?=e($row['lesson_title']??'')?></td><td><?=e($row['score']??'—')?></td><td><?=e($row['rating']??'')?></td></tr><?php endforeach;if(!$profile['sources']['observations']):?><tr><td colspan="5" class="text-center text-muted">Chưa có dữ liệu trong kỳ.</td></tr><?php endif;?></tbody></table></div></section>
<section class="ev-card ev-source"><h5>Căn cứ kiểm tra hồ sơ chuyên môn</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Ngày</th><th>Người kiểm tra</th><th>Nội dung</th><th>Kết quả</th><th>Xếp loại</th></tr></thead><tbody><?php foreach($profile['sources']['file_checks'] as $row):?><tr><td><?=!empty($row['date'])?date('d/m/Y',strtotime($row['date'])):''?></td><td><?=e($row['inspector_name']??'')?></td><td><?=e($row['content']??'')?></td><td><?=e($row['result']??'')?></td><td><?=e($row['rating']??'')?></td></tr><?php endforeach;if(!$profile['sources']['file_checks']):?><tr><td colspan="5" class="text-center text-muted">Chưa có kết quả kiểm tra hồ sơ trong kỳ.</td></tr><?php endif;?></tbody></table></div></section>
<section class="ev-card ev-source"><h5>Căn cứ ngày công</h5><p class="small text-muted">Có phép: <?=$profile['permitted_days']?> ngày · Không phép: <?=$profile['unpermitted_days']?> ngày · Đi muộn: <?=$profile['late_count']?> lần</p><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Thời gian</th><th>Tình trạng</th><th>Lý do</th><th>Điểm trừ</th></tr></thead><tbody><?php foreach($profile['sources']['attendance'] as $row):?><tr><td><?=e($row['from_date']??$row['date']??'')?>–<?=e($row['to_date']??$row['date']??'')?></td><td><?=e($row['permission']??$row['status']??'')?></td><td><?=e(trim(($row['reason']??'').' '.($row['reason_detail']??'')))?></td><td>Đã tính trong tổng</td></tr><?php endforeach;if(!$profile['sources']['attendance']):?><tr><td colspan="4" class="text-center text-muted">Không có trường hợp bị trừ điểm.</td></tr><?php endif;?></tbody></table></div></section>
<section class="ev-card ev-source"><h5>Căn cứ thành tích</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Ngày</th><th>Thành tích</th><th>Cấp</th><th>Điểm</th></tr></thead><tbody><?php foreach($profile['sources']['achievements'] as $row):?><tr><td><?=e($row['date']??'')?></td><td><?=e($row['title']??'')?></td><td><?=e($row['level']??'')?></td><td><?=e(($row['score']??0)?:($config['achievement_level_points'][$row['level']??'']??0))?></td></tr><?php endforeach;if(!$profile['sources']['achievements']):?><tr><td colspan="4" class="text-center text-muted">Chưa có thành tích trong kỳ.</td></tr><?php endif;?></tbody></table></div></section>
<form method="post" class="ev-card p-3 mt-3"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="review"><input type="hidden" name="teacher_id" value="<?=e($profile['teacher_id'])?>"><label class="form-label fw-semibold">Ý kiến xác nhận</label><textarea class="form-control mb-3" name="note" rows="2"><?=e($review['note']??'')?></textarea><div class="d-flex flex-wrap gap-2"><?php if($linkedTeacher&&$linkedTeacher['id']===$profile['teacher_id']):?><button class="btn btn-outline-primary" name="status" value="teacher_checked">Tôi đã kiểm tra</button><?php endif;?><?php if($isLeader&&te_norm($profile['team'])===te_norm($linkedTeam)):?><button class="btn btn-warning" name="status" value="leader_confirmed">Tổ trưởng xác nhận</button><?php endif;?><?php if($canAll):?><button class="btn btn-success" name="status" value="approved">BGH duyệt</button><button class="btn btn-dark" name="status" value="locked" onclick="return confirm('Khóa kết quả kỳ này?')">Duyệt và khóa</button><?php endif;?></div></form><?php endif;?>

<?php else:$sourceCatalog=te_source_catalog();?><form method="post" class="ev-card ev-settings" id="evaluation-settings"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_config">
<div class="d-flex justify-content-between align-items-center mb-2"><div><h5 class="mb-0">Nhóm/cột đánh giá</h5><small class="text-muted">Mỗi nhóm trở thành một cột trong bảng tổng hợp.</small></div><button class="btn btn-sm btn-outline-primary" type="button" id="add-group"><i class="bi bi-plus-lg"></i> Thêm cột</button></div>
<div class="table-responsive mb-4"><table class="table align-middle" id="groups-table"><thead><tr><th>Tên cột/nhóm</th><th style="width:180px">Điểm tối đa</th><th style="width:60px"></th></tr></thead><tbody><?php foreach($config['groups'] as $group):?><tr><td><input type="hidden" name="group_id[]" value="<?=e($group['id'])?>"><input class="form-control group-name" name="group_name[]" value="<?=e($group['name'])?>" required></td><td><input class="form-control" type="number" min="0" step=".1" name="group_max[]" value="<?=e($group['max'])?>" required></td><td><button class="btn btn-sm btn-outline-danger remove-row" type="button" title="Xóa nhóm"><i class="bi bi-trash"></i></button></td></tr><?php endforeach;?></tbody></table></div>
<div class="d-flex justify-content-between align-items-center mb-2"><div><h5 class="mb-0">Nội dung, tiêu chí và quy định điểm</h5><small class="text-muted">Điểm thực tế = số lượt × điểm/lượt; kết quả nhóm luôn trong khoảng 0 đến điểm tối đa.</small></div><button class="btn btn-sm btn-outline-primary" type="button" id="add-criterion"><i class="bi bi-plus-lg"></i> Thêm tiêu chí</button></div>
<div class="table-responsive mb-4"><table class="table align-middle" id="criteria-table" style="min-width:1050px"><thead><tr><th style="min-width:210px">Nội dung đánh giá</th><th style="min-width:160px">Thuộc nhóm</th><th style="min-width:270px">Dữ liệu dùng để đếm</th><th style="width:130px">Quy định</th><th style="width:130px">Điểm/lượt</th><th style="width:60px"></th></tr></thead><tbody><?php foreach($config['criteria'] as $criterion):?><tr><td><input type="hidden" name="criterion_id[]" value="<?=e($criterion['id'])?>"><input class="form-control" name="criterion_name[]" value="<?=e($criterion['name'])?>" required></td><td><select class="form-select criterion-group" name="criterion_group[]" data-value="<?=e($criterion['group_id'])?>"></select></td><td><select class="form-select" name="criterion_source[]"><?php foreach($sourceCatalog as $source=>$label):?><option value="<?=e($source)?>" <?=$source===($criterion['source']??'')?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></td><td><select class="form-select" name="criterion_operation[]"><option value="add" <?=($criterion['operation']??'add')==='add'?'selected':''?>>Cộng điểm</option><option value="subtract" <?=($criterion['operation']??'')==='subtract'?'selected':''?>>Trừ điểm</option></select></td><td><input class="form-control" type="number" min="0" step=".1" name="criterion_points[]" value="<?=e($criterion['points'])?>" required></td><td><button class="btn btn-sm btn-outline-danger remove-row" type="button" title="Xóa tiêu chí"><i class="bi bi-trash"></i></button></td></tr><?php endforeach;?></tbody></table></div>
<h5>Ngưỡng xếp loại</h5><div class="ev-settings-grid mb-4"><?php foreach(['Hoàn thành xuất sắc','Hoàn thành tốt','Hoàn thành','Không hoàn thành'] as $i=>$label):$found=0;foreach($config['ratings'] as $rating)if(($rating['label']??'')===$label)$found=$rating['min']??0;?><div><label class="form-label"><?=e($label)?></label><input class="form-control" type="number" min="0" step=".1" name="rating_min[<?=$i?>]" value="<?=e($found)?>"></div><?php endforeach;?></div><div class="alert alert-info">Công thức mới chỉ áp dụng cho kết quả đang tổng hợp. Hồ sơ đã khóa giữ nguyên ảnh chụp kết quả tại thời điểm duyệt.</div><button class="btn btn-primary px-4"><i class="bi bi-floppy"></i> Lưu toàn bộ cấu hình</button></form><?php endif;?></main></div><nav class="ev-mobile"><a class="<?=$view==='overview'?'active':''?>" href="?view=overview"><i class="bi bi-bar-chart-line"></i>Tổng hợp</a><a class="<?=$view==='profile'?'active':''?>" href="?view=profile"><i class="bi bi-person-lines-fill"></i>Hồ sơ</a><a href="<?=BASE_URL?>chuyenmon/"><i class="bi bi-journal-bookmark"></i>Chuyên môn</a></nav><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<?php if($view==='settings'):?><script>
(()=>{const groups=document.querySelector('#groups-table tbody'),criteria=document.querySelector('#criteria-table tbody');
const sources=<?=json_encode($sourceCatalog,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT)?>;
function groupOptions(){return [...groups.rows].map(r=>{const id=r.querySelector('[name="group_id[]"]').value,name=r.querySelector('.group-name').value||'Nhóm mới';return `<option value="${id.replace(/[&<>"']/g,'')}">${name.replace(/[&<>]/g,'')}</option>`}).join('')}
function refreshGroups(){document.querySelectorAll('.criterion-group').forEach(s=>{const old=s.value||s.dataset.value;s.innerHTML=groupOptions();if([...s.options].some(o=>o.value===old))s.value=old})}
document.querySelector('#add-group').onclick=()=>{const id='g_'+Date.now();groups.insertAdjacentHTML('beforeend',`<tr><td><input type="hidden" name="group_id[]" value="${id}"><input class="form-control group-name" name="group_name[]" placeholder="Tên nhóm mới" required></td><td><input class="form-control" type="number" min="0" step=".1" name="group_max[]" value="10" required></td><td><button class="btn btn-sm btn-outline-danger remove-row" type="button"><i class="bi bi-trash"></i></button></td></tr>`);refreshGroups()};
document.querySelector('#add-criterion').onclick=()=>{const id='c_'+Date.now(),sourceOptions=Object.entries(sources).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');criteria.insertAdjacentHTML('beforeend',`<tr><td><input type="hidden" name="criterion_id[]" value="${id}"><input class="form-control" name="criterion_name[]" placeholder="Tên nội dung đánh giá" required></td><td><select class="form-select criterion-group" name="criterion_group[]"></select></td><td><select class="form-select" name="criterion_source[]">${sourceOptions}</select></td><td><select class="form-select" name="criterion_operation[]"><option value="add">Cộng điểm</option><option value="subtract">Trừ điểm</option></select></td><td><input class="form-control" type="number" min="0" step=".1" name="criterion_points[]" value="1" required></td><td><button class="btn btn-sm btn-outline-danger remove-row" type="button"><i class="bi bi-trash"></i></button></td></tr>`);refreshGroups()};
document.addEventListener('input',e=>{if(e.target.classList.contains('group-name'))refreshGroups()});document.addEventListener('click',e=>{const button=e.target.closest('.remove-row');if(!button)return;const table=button.closest('table');if(table.id==='groups-table'&&groups.rows.length<=1){alert('Cần giữ lại ít nhất một nhóm đánh giá.');return}button.closest('tr').remove();refreshGroups()});document.querySelector('#evaluation-settings').addEventListener('submit',refreshGroups);refreshGroups();})();
</script><?php endif;?></body></html>
