<?php
require_once __DIR__.'/includes/config.php';require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/google_drive_storage.php';require_admin();$settings=cds_drive_settings();
if($_SERVER['REQUEST_METHOD']==='POST'){
    $json=trim((string)($_POST['service_account_json']??''));$email=$settings['client_email'];$key=$settings['private_key'];
    if($json!==''){$account=json_decode($json,true);if(!is_array($account)||empty($account['client_email'])||empty($account['private_key']))flash('File JSON tài khoản dịch vụ không hợp lệ.','danger');else{$email=$account['client_email'];$key=$account['private_key'];}}
    $next=['enabled'=>!empty($_POST['enabled']),'client_email'=>$email,'private_key'=>$key,'folders'=>['documents'=>trim((string)($_POST['folder_documents']??'')),'plans'=>trim((string)($_POST['folder_plans']??'')),'education_plans'=>trim((string)($_POST['folder_education_plans']??'')),'photos'=>trim((string)($_POST['folder_photos']??''))]];
    if(cds_drive_save_settings($next)){$settings=$next;$test=cds_drive_token($settings);flash(!empty($test['ok'])?'Đã lưu và kết nối Google Drive thành công.':'Đã lưu nhưng chưa kết nối được: '.($test['message']??''),!empty($test['ok'])?'success':'warning');}else flash('Không lưu được cấu hình Drive.','danger');
}
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kho Google Drive – CDS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-4" style="max-width:960px"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="mb-1"><i class="bi bi-google"></i> Kho Google Drive</h2><p class="text-muted mb-0">Cấu hình lưu file theo từng loại dữ liệu.</p></div><a class="btn btn-outline-secondary" href="admin.php">Quay lại</a></div><?php show_flash();?><form method="post" class="card shadow-sm border-0"><div class="card-body p-4"><div class="form-check form-switch mb-4"><input class="form-check-input" type="checkbox" name="enabled" id="enabled" value="1" <?=!empty($settings['enabled'])?'checked':''?>><label class="form-check-label fw-bold" for="enabled">Bật lưu file lên Google Drive</label></div><label class="form-label fw-bold">JSON tài khoản dịch vụ Google</label><textarea class="form-control font-monospace" name="service_account_json" rows="5" placeholder="Dán toàn bộ nội dung file JSON tại đây; để trống nếu không đổi khóa."></textarea><div class="form-text mb-3">Đang dùng: <?=e($settings['client_email']?:'Chưa cấu hình')?>. Khóa chỉ lưu trong thư mục dữ liệu trên host, không đưa lên GitHub.</div><h5 class="mt-4">Thư mục lưu theo loại</h5><p class="text-muted small">Nhập ID nằm sau <code>/folders/</code> trong đường dẫn Google Drive. Với Service Account, nên dùng thư mục thuộc <strong>Bộ nhớ dùng chung (Shared Drive)</strong> và thêm email trên làm thành viên có quyền chỉnh sửa.</p><?php foreach(['documents'=>'Văn bản','plans'=>'Kế hoạch và báo cáo','education_plans'=>'Kế hoạch giáo dục','photos'=>'Ảnh học sinh'] as $key=>$label):?><div class="row align-items-center mb-3"><label class="col-md-4 col-form-label fw-semibold"><?=e($label)?></label><div class="col-md-8"><input class="form-control" name="folder_<?=e($key)?>" value="<?=e($settings['folders'][$key]??'')?>" placeholder="ID thư mục Google Drive"></div></div><?php endforeach;?><button class="btn btn-primary"><i class="bi bi-cloud-check"></i> Lưu và kiểm tra kết nối</button></div></form><div class="alert alert-info mt-3"><strong>Cách thiết lập:</strong> Google Cloud → bật Google Drive API → tạo Service Account → tạo khóa JSON → thêm email Service Account vào Shared Drive → tạo và chọn các thư mục lưu.</div></main></body></html>
