<?php
require_once __DIR__.'/includes/auth.php';require_login();require_once __DIR__.'/includes/olympia_store.php';olympia_ensure_schema();
$weekId=trim((string)($_GET['week']??''));$classId=trim((string)($_GET['class']??''));$week=olympia_week($weekId);$class=olympia_class_map()[$classId]??[];
if(!$week||!olympia_can_class($classId)||!in_array($classId,olympia_week_class_ids($weekId),true)){http_response_code(403);exit('Không có quyền mở màn hình trình chiếu này.');}
$settings=olympia_settings();$fallback=BASE_URL.'assets/olympia-year-3.png';$icon=olympia_asset_url((string)($settings['game_icon']??''),$fallback);$welcomeLogo=olympia_asset_url((string)($settings['welcome_logo']??''),$fallback);$audio=[];foreach(['music_welcome','music_khoi_dong','music_vuot_chuong_ngai_vat','music_tang_toc','music_ve_dich','music_question','sound_end','sound_score'] as $key)$audio[$key]=olympia_asset_url((string)($settings[$key]??''));
$yearDate=(string)($week['open_at']??date('Y-m-d'));$year=(int)substr($yearDate,0,4);if((int)substr($yearDate,5,2)<7)$year--;$schoolYear=$year.' - '.($year+1);$footer='Cuộc thi ĐƯỜNG LÊN ĐỈNH OLYMPIA năm thứ 3 (Vòng sơ loại) - '.SCHOOL_NAME;
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Màn hình Olympia</title><style>
*{box-sizing:border-box}body{margin:0;background:#020716;color:#fff;font-family:Segoe UI,system-ui,sans-serif;overflow:hidden}.screen{height:100dvh;display:flex;flex-direction:column;background:radial-gradient(circle at 50% 20%,#1476c5 0,#071b4d 48%,#020718 100%)}header{flex:0 0 clamp(72px,10vh,108px);display:flex;align-items:center;gap:16px;padding:8px 3vw;border-bottom:3px solid #ffd42a;background:#03143cdd}.logo{width:clamp(48px,5vw,72px);height:clamp(48px,5vw,72px)}.logo img{width:100%;height:100%;object-fit:contain}.title{font-size:clamp(20px,2.4vw,40px);font-weight:950}.class{margin-left:auto;text-align:right;font-size:clamp(18px,2vw,30px);color:#ffd42a;font-weight:800}main{flex:1;min-height:0;display:grid;place-items:center;padding:clamp(12px,2vh,28px) 5vw clamp(52px,7vh,74px)}.welcome,.stage-intro,.summary{width:100%;height:100%;min-height:0;text-align:center;display:flex;flex-direction:column;justify-content:center;align-items:center}.event-logo{display:block;width:min(64vw,820px);height:min(42vh,430px);object-fit:contain;object-position:center;filter:drop-shadow(0 0 24px #ffef6388);animation:float 3s ease-in-out infinite}
.welcome h1{max-width:94vw;font-size:clamp(20px,2.75vw,44px);margin:0 0 1.5vh;line-height:1.08;text-wrap:balance;text-shadow:0 0 18px #71c9ff}
.welcome h2{max-width:94vw;color:#ffe43b;font-size:clamp(17px,2vw,31px);margin:2vh 0 0;line-height:1.15;text-wrap:balance}
.stage-intro h1{font-size:clamp(24px,3vw,48px);margin:1vh}
.stage-name{max-width:96vw;font-size:clamp(38px,6vw,94px);line-height:1.02;font-weight:950;color:#ffea32;text-shadow:0 0 32px #ffc400;letter-spacing:.015em;text-align:center;text-wrap:balance}.stage-name.long{font-size:clamp(32px,5.1vw,78px);letter-spacing:0}
.stage{color:#ffd42a;text-transform:uppercase;letter-spacing:.14em;font-size:clamp(17px,1.8vw,28px);font-weight:900}.question{text-align:center;width:100%;max-width:1500px}.qtext{font-size:clamp(34px,4.8vw,80px);line-height:1.2;font-weight:900;margin:3vh auto}.answer{display:none;background:#06352e;border:2px solid #58e49e;border-radius:18px;padding:2vh 3vw;font-size:clamp(26px,3.4vw,56px);color:#baffd5}.timer{width:110px;height:110px;border:8px solid #ffd42a;border-radius:50%;display:grid;place-items:center;margin:2.5vh auto;font-size:40px;font-weight:950}.summary h1{font-size:clamp(30px,4.8vw,72px);margin:1vh}.winner{display:flex;align-items:center;justify-content:center;gap:18px;margin:1vh auto 2vh;padding:10px 28px;border:2px solid #ffe45a;border-radius:24px;background:#ffdf2922;box-shadow:0 0 32px #ffd52a55;max-width:min(900px,92vw)}.wreath{font-size:clamp(44px,5.5vw,80px)}.winner-name{font-size:clamp(25px,3.2vw,48px);font-weight:950}.winner-score{color:#ffe43b;font-size:clamp(21px,2.5vw,38px);font-weight:900}.ranking{width:min(1050px,92vw);max-height:38vh;overflow:hidden;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px 12px}.rank-row{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:10px;padding:7px 14px;background:#ffffff14;border:1px solid #ffffff25;border-radius:11px;text-align:left;font-size:clamp(14px,1.45vw,22px)}.rank-row b:last-child{color:#ffe43b}.event-footer{position:fixed;left:0;right:0;bottom:0;padding:9px 3vw;background:#020b28ee;border-top:2px solid #e4c82b;text-align:center;font-weight:750;font-size:clamp(12px,1.25vw,19px)}.connection{position:fixed;right:12px;top:8px;opacity:.55;font-size:11px}.paused{font-size:clamp(48px,8vw,125px);font-weight:950;color:#ffe532;text-shadow:0 0 30px #ffcf00}@keyframes float{50%{transform:translateY(-8px)}}@media(max-aspect-ratio:4/3){.event-logo{width:min(80vw,720px);height:min(36vh,360px)}.ranking{grid-template-columns:1fr;max-height:34vh}}
</style></head><body><div class="screen"><header><div class="logo"><img src="<?=e($icon)?>" alt="Logo"></div><div><div class="title">ĐƯỜNG LÊN ĐỈNH OLYMPIA</div><div><?=e($week['title'])?> · Năm học <?=e($schoolYear)?></div></div><div class="class">LỚP <?=e($class['name']??'')?></div></header><main id="main"></main><div class="connection" id="connection">Đang kết nối…</div><footer class="event-footer"><?=e($footer)?></footer></div><audio id="music" preload="auto"></audio><audio id="effect" preload="auto"></audio><script>
const endpoint='<?=BASE_URL?>hoclieu_game_olympia_live.php?week=<?=rawurlencode($weekId)?>&class=<?=rawurlencode($classId)?>',eventLogo=<?=json_encode($welcomeLogo,JSON_UNESCAPED_SLASHES)?>,weekTitle=<?=json_encode((string)$week['title'],JSON_UNESCAPED_UNICODE)?>,schoolYear=<?=json_encode($schoolYear)?>,sounds=<?=json_encode($audio,JSON_UNESCAPED_SLASHES)?>;let last='',lastEvent='',timer=null,pollBusy=false;const main=document.getElementById('main'),conn=document.getElementById('connection'),music=document.getElementById('music'),effect=document.getElementById('effect');Object.values(sounds).filter(Boolean).forEach(url=>{const preload=new Audio();preload.preload='auto';preload.src=url});
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function audioKey(stage){return 'music_'+String(stage||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function play(el,url,loop=false,sentAt=0){if(!url){if(el===music){el.pause();el.removeAttribute('src')}return}const absolute=new URL(url,location.href).href,offset=sentAt?Math.max(0,(Date.now()-Number(sentAt))/1000):0,start=()=>{try{el.currentTime=el.duration&&loop?offset%el.duration:offset}catch(e){}el.play().catch(()=>{conn.textContent='Bấm một lần vào màn hình để bật âm thanh'})};el.loop=loop;if(el.src!==absolute){el.src=url;el.load();el.addEventListener('loadedmetadata',start,{once:true})}else start()}
function soundFor(s){effect.pause();if(['welcome','waiting','intro'].includes(s.status))play(music,sounds.music_welcome,true,s.sent_at);else if(s.status==='stage_intro')play(music,sounds[audioKey(s.stage)]||'',false,s.sent_at);else if(s.status==='question')play(music,sounds.music_question,true,s.sent_at);else if(['scoring','stage_summary','finished'].includes(s.status)){music.pause();play(effect,sounds.sound_end,false,s.sent_at)}else if(s.status==='score_result'){music.pause();play(effect,sounds.sound_score,false,s.sent_at)}}
function rankingHtml(rows){rows=Array.isArray(rows)?rows:[];if(!rows.length)return '<p>Chưa có học sinh ghi điểm.</p>';let top=rows[0],rest=rows.slice(1,13);return `<div class="winner"><div class="wreath">🌿</div><div><div class="stage">CHÚC MỪNG NGƯỜI DẪN ĐẦU</div><div class="winner-name">${esc(top.name)}</div><div class="winner-score">${Number(top.points||0)} ĐIỂM</div></div><div class="wreath">🌿</div></div><div class="ranking">${rest.map((r,i)=>`<div class="rank-row"><b>${i+2}</b><span>${esc(r.name)}</span><b>${Number(r.points||0)} điểm</b></div>`).join('')}</div>`}
function welcome(){main.innerHTML=`<div class="welcome"><h1>CHÀO MỪNG CÁC BẠN ĐẾN VỚI CUỘC THI</h1><img class="event-logo" src="${eventLogo}" alt="Olympia"><h2>${esc(weekTitle)} · NĂM HỌC ${esc(schoolYear)}</h2></div>`}
function draw(s){let key=JSON.stringify(s);if(key===last)return;last=key;clearInterval(timer);const eventKey=String(s?.event_id||[s?.status,s?.stage,s?.question_index].join('|'));if(s&&eventKey!==lastEvent){soundFor(s);lastEvent=eventKey}if(!s||['waiting','intro','welcome'].includes(s.status)){welcome();return}if(s.status==='stage_intro'){const longName=String(s.stage||'').length>16?' long':'';main.innerHTML=`<div class="stage-intro"><img class="event-logo" src="${eventLogo}" alt="Olympia"><h1>PHẦN THI</h1><div class="stage-name${longName}">${esc(s.stage)}</div><h2>NĂM HỌC ${esc(schoolYear)}</h2></div>`;return}if(s.status==='paused'){main.innerHTML=`<div class="stage-intro"><img class="event-logo" src="${eventLogo}" alt="Olympia"><div class="paused">TẠM DỪNG</div><h2>CUỘC THI SẼ TIẾP TỤC TRONG ÍT PHÚT</h2></div>`;return}if(['stage_summary','finished','score_result'].includes(s.status)){let heading=s.status==='finished'?'KẾT QUẢ CHUNG CUỘC':(s.status==='score_result'?'CÔNG BỐ ĐIỂM':'HOÀN THÀNH PHẦN THI');main.innerHTML=`<div class="summary"><div class="stage">${esc(s.stage||'Kết quả')}</div><h1>${heading}</h1>${rankingHtml(s.rankings)}</div>`;return}main.innerHTML=`<div class="question"><div class="stage">${esc(s.stage)} · ${Number(s.points||0)} ĐIỂM</div><div class="qtext">${esc(s.question)}</div><div class="timer" id="clock">${Number(s.seconds||0)}</div><div class="answer" id="ans">ĐÁP ÁN: ${esc(s.answer)}</div></div>`;if(s.status==='answer')document.getElementById('ans').style.display='block';if(s.timer_ends_at){let tick=()=>{let left=Math.max(0,Math.ceil((Number(s.timer_ends_at)-Date.now())/1000)),el=document.getElementById('clock');if(el)el.textContent=left||'HẾT'};tick();timer=setInterval(tick,200)}}async function poll(){if(pollBusy)return;pollBusy=true;try{let r=await fetch(endpoint+'&_='+Date.now(),{cache:'no-store'}),d=await r.json();if(d.ok){draw(d.state);conn.textContent='Đồng bộ · '+(d.controlled_by||'Giáo viên')}else conn.textContent=d.message}catch(e){conn.textContent='Mất kết nối, đang thử lại…'}finally{pollBusy=false}}document.addEventListener('click',()=>{if(music.src&&music.paused)music.play().catch(()=>{})},{once:true});welcome();poll();setInterval(poll,300);
</script></body></html>
