<?php
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/noitru_store.php';
require_login();
require_perm('nt.ravao');
$user=current_user()?:[];$isAdmin=($user['role']??'')==='admin';
function ntxc_norm($v){$v=preg_replace('/\s+/u',' ',trim((string)$v))??trim((string)$v);return function_exists('mb_strtolower')?mb_strtolower($v,'UTF-8'):strtolower($v);}
function ntxc_can_check(){global $isAdmin,$user;if($isAdmin)return true;$want=ntxc_norm($user['teacher_name']??$user['name']??'');if($want==='')return false;$today=date('Y-m-d');foreach(noitru_duty_all() as $r)if(($r['date']??'')===$today&&ntxc_norm($r['teacher_name']??'')===$want)return true;$m=noitru_duty_manager_for_date($today)??[];foreach((array)($m['teacher_names']??[]) as $n)if(ntxc_norm($n)===$want)return true;return false;}
$canCheck=ntxc_can_check();
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Kiểm tra ra vào KTX</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>body{background:#f4f7fb}.wrap{max-width:760px;margin:auto;padding:12px}.card{border:0;border-radius:18px;box-shadow:0 8px 30px #173b5d15}.video{width:100%;aspect-ratio:4/3;object-fit:cover;background:#111;border-radius:16px}.status{border-radius:14px;padding:1rem}.approved{background:#eaf8ef;border:1px solid #b8e5c5}.approved_early,.approved_late,.pending{background:#fff7df;border:1px solid #f0c85a}.used{background:#eef2f7;border:1px solid #cbd5e1}.rejected,.none{background:#fff0f0;border:1px solid #f2bbbb}.big{font-size:1.05rem;font-weight:800}.scanline{position:relative}.scanline:after{content:'';position:absolute;left:8%;right:8%;top:50%;height:2px;background:#22c55e;box-shadow:0 0 12px #22c55e}.toolbar{position:sticky;top:0;z-index:4;background:#f4f7fb;padding:4px 0 10px}.time-warning{font-weight:800;color:#9a6700}</style></head><body><div class="wrap"><div class="toolbar d-flex justify-content-between align-items-center"><a class="btn btn-light border" href="noitru_exit_manager.php?view=check"><i class="bi bi-arrow-left"></i> Ra/vào KTX</a><strong>Kiểm tra QR</strong><button class="btn btn-outline-primary" id="restart"><i class="bi bi-camera"></i> Quét lại</button></div><section class="card"><div class="card-body"><div class="mb-2 text-muted small">Camera sẽ tự bật. Đưa mã QR trên thẻ học sinh vào giữa khung.</div><?php if(!$canCheck):?><div class="alert alert-warning mb-0">Chỉ giáo viên trực ngày <?=date('d/m/Y')?> hoặc quản trị được xác nhận ra/vào.</div><?php else:?><div class="scanline"><video id="video" class="video" playsinline muted></video></div><div id="cameraMsg" class="small text-muted mt-2">Đang mở camera…</div><form id="manual" class="input-group mt-3"><input id="qr" class="form-control" placeholder="Hoặc nhập/dán mã QR"><button class="btn btn-dark">Kiểm tra</button></form><div id="result" class="mt-3"></div><?php endif;?></div></section></div>
<script>
const video=document.getElementById('video'),msg=document.getElementById('cameraMsg'),result=document.getElementById('result'),qr=document.getElementById('qr'),manual=document.getElementById('manual'),restart=document.getElementById('restart');let stream=null,timer=null,busy=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function stop(){if(timer)clearInterval(timer);timer=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function render(d){const s=d.student||{},r=d.request||{};let html='<div class="status '+esc(d.state)+'"><div class="big">'+esc(d.message)+'</div><div class="mt-2"><strong>'+esc(s.name)+'</strong> · '+esc(s.class_name)+'</div>';
 if(r.from_date)html+='<div class="small mt-1">Đăng ký: '+esc(r.from_date)+' → '+esc(r.to_date)+'</div>';
 if(r.reason)html+='<div class="mt-1">Lý do: '+esc(r.reason)+'</div>';
 if(d.state==='approved_early'||d.state==='approved_late')html+='<div class="time-warning mt-2"><i class="bi bi-exclamation-triangle-fill"></i> Lệch thời gian: '+esc(d.time_delta_text||'')+'</div>';
 if(d.state==='used')html+='<div class="mt-2 small"><strong>Đã ra:</strong> '+esc(r.actual_exit_at||'')+'<br><strong>Đã vào:</strong> '+esc(r.actual_return_at||'')+'</div>';
 if((d.state==='approved'||d.state==='approved_early'||d.state==='approved_late')&&d.can_confirm)html+='<a class="btn '+(d.state==='approved'?'btn-success':'btn-warning')+' w-100 mt-3" href="'+esc(d.found_url)+'"><i class="bi bi-check2-circle"></i> '+(d.state==='approved'?'Xem và xác nhận ra/vào':'ĐÃ KIỂM TRA CẢNH BÁO – TIẾP TỤC XÁC NHẬN')+'</a>';
 if(d.public_file_url)html+='<a class="btn btn-outline-secondary w-100 mt-2" target="_blank" href="'+esc(d.public_file_url)+'"><i class="bi bi-file-earmark-text"></i> Xem đơn</a>';
 if(d.state==='used')html+='<div class="alert alert-secondary mt-3 mb-0"><i class="bi bi-lock-fill"></i> Không thể xác nhận thêm bằng đơn này.</div>';
 html+='</div>';result.innerHTML=html;}
async function check(value){if(busy||!value)return;busy=true;await stop();msg.textContent='Đang kiểm tra đăng ký…';try{const fd=new FormData();fd.append('qr',value);const res=await fetch('noitru_exit_check_api.php',{method:'POST',body:fd});const d=await res.json();render(d);msg.textContent=d.state==='approved'?'Đơn hợp lệ trong đúng thời gian.':d.message;}catch(e){result.innerHTML='<div class="alert alert-danger">Không kiểm tra được mã. Hãy thử lại.</div>';msg.textContent='Lỗi kiểm tra.';}busy=false;}
async function start(){await stop();result.innerHTML='';busy=false;if(!video)return;if(!('BarcodeDetector' in window)){msg.textContent='Trình duyệt chưa hỗ trợ quét QR tự động. Hãy dùng Chrome/Edge mới hoặc nhập mã bên dưới.';return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.srcObject=stream;await video.play();msg.textContent='Camera đã sẵn sàng – đang quét…';const det=new BarcodeDetector({formats:['qr_code']});timer=setInterval(async()=>{if(busy)return;try{const codes=await det.detect(video);if(codes.length)check(codes[0].rawValue)}catch(e){}},350);}catch(e){msg.textContent='Không mở được camera. Hãy cho phép quyền Camera cho website.';}}
if(manual)manual.addEventListener('submit',e=>{e.preventDefault();check(qr.value.trim())});if(restart)restart.onclick=start;window.addEventListener('load',()=>setTimeout(start,250));window.addEventListener('beforeunload',stop);
</script></body></html>
