<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/csdl_store.php';
require_once __DIR__ . '/includes/noitru_assignment_store.php';
require_login();
require_module('thidua', 'view');

$user=current_user()??[];$userName=trim((string)($user['name']??$user['teacher_name']??$user['username']??''));
$permissions=['input'=>'td.student_room_input','stats'=>'td.student_room_stats','settings'=>'td.student_room_settings'];
$allowedTabs=[];foreach($permissions as $key=>$code)if(can_perm_level($code,'view'))$allowedTabs[]=$key;
if(!$allowedTabs){http_response_code(403);exit('Tài khoản chưa được cấp quyền cho Phòng nội trú.');}
$tab=(string)($_GET['tab']??$allowedTabs[0]);if(!in_array($tab,$allowedTabs,true)){http_response_code(403);exit('Tài khoản chưa được cấp quyền cho tab này.');}
$canEdit=can_perm_level($permissions[$tab],'edit');$canDelete=can_perm_level($permissions[$tab],'delete');

$dataFile=DATA_PATH.'/thidua_rooms.json';
$data=load_json($dataFile,[]);$data=array_merge(['settings'=>[],'criteria'=>[],'entries'=>[]],is_array($data)?$data:[]);
$data['settings']=array_merge(['weekly_max'=>100,'excellent'=>90,'good'=>80,'pass'=>65],is_array($data['settings']??null)?$data['settings']:[]);
$data['criteria']=array_values(is_array($data['criteria']??null)?$data['criteria']:[]);$data['entries']=array_values(is_array($data['entries']??null)?$data['entries']:[]);
if(!$data['criteria'])$data['criteria']=[
 ['id'=>'rc_clean','name'=>'Vệ sinh phòng bẩn','points'=>5,'active'=>true],
 ['id'=>'rc_bed','name'=>'Chăn, màn, đồ dùng sắp xếp chưa gọn','points'=>3,'active'=>true],
 ['id'=>'rc_discipline','name'=>'Vi phạm giờ giấc, nội quy phòng ở','points'=>5,'active'=>true],
];

$assignment=noitru_assignments_data();$rooms=array_values(array_unique(array_filter(array_map('strval',(array)($assignment['room_names']??[])))));
foreach((array)($assignment['rooms']??[]) as $room){$room=trim((string)$room);if($room!==''&&!in_array($room,$rooms,true))$rooms[]=$room;}
sort($rooms,SORT_NATURAL|SORT_FLAG_CASE);

function td_room_redirect(string $tab,array $extra=[]): void {$query=http_build_query(['tab'=>$tab]+$extra);header('Location: '.BASE_URL.'thidua_phongnoitru.php?'.$query);exit;}
function td_room_week(string $date): array {$shared=csdl_week_for_date($date);if($shared)return $shared;$time=strtotime($date)?:time();$start=date('Y-m-d',strtotime('monday this week',$time));return ['start'=>$start,'end'=>date('Y-m-d',strtotime($start.' +6 days')),'label'=>date('d/m',strtotime($start)).' - '.date('d/m/Y',strtotime($start.' +6 days'))];}
function td_room_rating(float $score,float $max,array $settings): string {$percent=$max>0?$score*100/$max:0;if($percent>=(float)$settings['excellent'])return 'Tốt';if($percent>=(float)$settings['good'])return 'Khá';if($percent>=(float)$settings['pass'])return 'Đạt';return 'Chưa đạt';}
function td_room_entry_key(array $entry): string {return (string)($entry['week_start']??'').'|'.(string)($entry['room']??'');}

if(empty($_SESSION['td_room_csrf']))$_SESSION['td_room_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['td_room_csrf'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Phiên làm việc không hợp lệ.');}
 $action=(string)($_POST['action']??'');$actionTab=['entry_save'=>'input','entry_delete'=>'input','settings_save'=>'settings'][$action]??'';
 if($actionTab===''||!in_array($actionTab,$allowedTabs,true)){http_response_code(403);exit('Không có quyền thực hiện thao tác này.');}
 $needed=$action==='entry_delete'?'delete':'edit';if(!can_perm_level($permissions[$actionTab],$needed)){http_response_code(403);exit('Tài khoản chưa có quyền '.$needed.' tại tab này.');}
 if($action==='settings_save'){
   $weeklyMax=max(1,(float)($_POST['weekly_max']??100));$excellent=max(0,min(100,(float)($_POST['excellent']??90)));$good=max(0,min($excellent,(float)($_POST['good']??80)));$pass=max(0,min($good,(float)($_POST['pass']??65)));
   $ids=(array)($_POST['criterion_id']??[]);$names=(array)($_POST['criterion_name']??[]);$points=(array)($_POST['criterion_points']??[]);$active=(array)($_POST['criterion_active']??[]);$criteria=[];
   foreach($names as $index=>$name){$name=trim((string)$name);if($name==='')continue;$id=preg_replace('/[^a-zA-Z0-9_-]/','',(string)($ids[$index]??''));if($id==='')$id='rc_'.bin2hex(random_bytes(5));$criteria[]=['id'=>$id,'name'=>$name,'points'=>max(.01,(float)($points[$index]??1)),'active'=>(string)($active[$index]??'1')==='1'];}
   if(!$criteria){flash('Cần ít nhất một mục điểm trừ.','danger');td_room_redirect('settings');}
   $data['settings']=['weekly_max'=>$weeklyMax,'excellent'=>$excellent,'good'=>$good,'pass'=>$pass];$data['criteria']=$criteria;save_json($dataFile,$data);flash('Đã lưu tổng điểm, ngưỡng xếp loại và các mục điểm trừ.','success');td_room_redirect('settings');
 }
 if($action==='entry_save'){
   $room=trim((string)($_POST['room']??''));if(!in_array($room,$rooms,true)){flash('Phòng ở không có trong danh sách nội trú.','danger');td_room_redirect('input');}
   $date=trim((string)($_POST['date']??date('Y-m-d')));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date=date('Y-m-d');$week=td_room_week($date);
   $criterionMap=[];foreach($data['criteria'] as $criterion)if(!empty($criterion['active']))$criterionMap[(string)$criterion['id']]=$criterion;
   $selected=(array)($_POST['criterion']??[]);$quantities=(array)($_POST['quantity']??[]);$notes=(array)($_POST['item_note']??[]);$aggregated=[];
   foreach($selected as $index=>$criterionId){$criterionId=(string)$criterionId;if(!isset($criterionMap[$criterionId]))continue;$qty=max(1,(int)($quantities[$index]??1));if(!isset($aggregated[$criterionId]))$aggregated[$criterionId]=['criterion_id'=>$criterionId,'name'=>(string)$criterionMap[$criterionId]['name'],'points'=>(float)$criterionMap[$criterionId]['points'],'quantity'=>0,'note'=>''];$aggregated[$criterionId]['quantity']+=$qty;$note=trim((string)($notes[$index]??''));if($note!=='')$aggregated[$criterionId]['note']=trim($aggregated[$criterionId]['note'].'; '.$note,'; ');}
   $items=array_values($aggregated);$deduction=0;foreach($items as $item)$deduction+=(float)$item['points']*(int)$item['quantity'];$max=(float)$data['settings']['weekly_max'];$score=max(0,$max-$deduction);
   $row=['id'=>'tre_'.bin2hex(random_bytes(7)),'room'=>$room,'date'=>$date,'week_start'=>$week['start'],'week_end'=>$week['end'],'week_label'=>$week['label']??'','items'=>$items,'deduction'=>round($deduction,2),'max_score'=>$max,'score'=>round($score,2),'rating'=>td_room_rating($score,$max,$data['settings']),'general_note'=>trim((string)($_POST['general_note']??'')),'created_by'=>$userName,'created_at'=>date('c'),'updated_by'=>$userName,'updated_at'=>date('c')];
   $found=false;foreach($data['entries'] as &$entry)if(td_room_entry_key($entry)===$week['start'].'|'.$room){$row['id']=$entry['id']??$row['id'];$row['created_by']=$entry['created_by']??$userName;$row['created_at']=$entry['created_at']??date('c');$entry=$row;$found=true;break;}unset($entry);if(!$found)$data['entries'][]=$row;
   save_json($dataFile,$data);flash(($found?'Đã cập nhật':'Đã lưu').' điểm phòng '.$room.'; còn '.$score.'/'.$max.' điểm.','success');td_room_redirect('input',['week'=>$week['start']]);
 }
 if($action==='entry_delete'){$id=trim((string)($_POST['id']??''));$before=count($data['entries']);$data['entries']=array_values(array_filter($data['entries'],fn($row)=>(string)($row['id']??'')!==$id));if(count($data['entries'])===$before){flash('Không tìm thấy dữ liệu cần xóa.','warning');}else{save_json($dataFile,$data);flash('Đã xóa dữ liệu chấm điểm phòng.','warning');}td_room_redirect('input',['week'=>(string)($_POST['week']??'')]);}
}

$weekRequest=(string)($_GET['week']??date('Y-m-d'));$inputWeek=td_room_week($weekRequest);$inputMap=[];foreach($data['entries'] as $entry)if(($entry['week_start']??'')===$inputWeek['start'])$inputMap[(string)($entry['room']??'')]=$entry;
$statsMode=($_GET['mode']??'week')==='range'?'range':'week';$statsAnchor=(string)($_GET['anchor']??date('Y-m-d'));$statsWeek=td_room_week($statsAnchor);$from=$statsMode==='week'?$statsWeek['start']:(string)($_GET['from']??date('Y-m-01'));$to=$statsMode==='week'?$statsWeek['end']:(string)($_GET['to']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from))$from=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||$to<$from)$to=$from;
$summary=[];foreach($rooms as $room)$summary[$room]=['room'=>$room,'weeks'=>0,'total'=>0.0,'average'=>0.0,'deduction'=>0.0,'latest_rating'=>'','details'=>[]];foreach($data['entries'] as $entry){$date=(string)($entry['date']??$entry['week_start']??'');$room=(string)($entry['room']??'');if($date<$from||$date>$to||!isset($summary[$room]))continue;$summary[$room]['weeks']++;$summary[$room]['total']+=(float)($entry['score']??0);$summary[$room]['deduction']+=(float)($entry['deduction']??0);$summary[$room]['latest_rating']=(string)($entry['rating']??'');$summary[$room]['details'][]=$entry;}foreach($summary as &$row)if($row['weeks']){$row['average']=round($row['total']/$row['weeks'],2);$row['rating']=td_room_rating($row['average'],(float)$data['settings']['weekly_max'],$data['settings']);}unset($row);uasort($summary,function($a,$b){if(!$a['weeks']&&!$b['weeks'])return strnatcasecmp($a['room'],$b['room']);if(!$a['weeks'])return 1;if(!$b['weeks'])return -1;return ($b['average']<=>$a['average'])?:strnatcasecmp($a['room'],$b['room']);});
$activeCriteria=array_values(array_filter($data['criteria'],fn($row)=>!empty($row['active'])));
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Thi đua phòng nội trú – CDS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>
:root{--gold:#d99a00;--nav:#503700;--soft:#fff8df;--ink:#172033}*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:var(--ink);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.shell{display:grid;grid-template-columns:245px minmax(0,1fr);min-height:100vh}.side{position:sticky;top:0;height:100vh;padding:1rem;background:linear-gradient(180deg,#704d00,#3d2a00);color:#fff}.brand{display:flex;gap:.7rem;align-items:center;color:#fff;text-decoration:none;padding:.4rem .35rem 1.1rem}.brand i{font-size:1.4rem;background:#ffffff22;border-radius:12px;padding:.65rem}.brand small{display:block;opacity:.7}.side-title{margin:1rem .7rem .35rem;font-size:.7rem;text-transform:uppercase;opacity:.55;font-weight:800}.side a.nav-link{display:flex;align-items:center;gap:.6rem;color:#ffffffd5;border-radius:11px;padding:.72rem}.side a.nav-link.active,.side a.nav-link:hover{background:#fff;color:#674700}.main{min-width:0;padding:1.2rem}.head{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:1rem}.head h2{font-weight:850;margin:0}.cardx{background:#fff;border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 4px 16px #0f172a0a}.toolbar{display:flex;gap:.7rem;align-items:end;flex-wrap:wrap;padding:1rem;margin-bottom:1rem}.room-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:.8rem}.room-card{overflow:hidden}.room-head{display:flex;justify-content:space-between;align-items:center;padding:.85rem 1rem;background:var(--soft);border-bottom:1px solid #f4dda0}.room-body{padding:1rem}.criterion-row{display:grid;grid-template-columns:minmax(0,1fr) 75px minmax(100px,.7fr) 42px;gap:.45rem;margin-bottom:.45rem}.form-control,.form-select,.btn{min-height:42px;border-radius:10px}.badge-score{font-size:1rem;background:#fff;color:#805b00;border:1px solid #e8c963}.table th{background:var(--soft);color:#654600;white-space:nowrap}.rank{display:inline-grid;place-items:center;width:32px;height:32px;border-radius:50%;background:#edf2f7;font-weight:800}.rank.first{background:#ffd95d}.setting-row{display:grid;grid-template-columns:90px minmax(0,1fr) 150px 90px 42px;gap:.55rem;align-items:center;margin-bottom:.55rem}.empty{padding:2rem;text-align:center;color:#64748b}@media(max-width:800px){.shell{display:block}.side{position:relative;height:auto}.main{padding:.75rem}.room-grid{grid-template-columns:1fr}.criterion-row{grid-template-columns:1fr 72px}.criterion-row .note{grid-column:1/-1}.setting-row{grid-template-columns:1fr 110px 80px 42px}.setting-row .criterion-id{display:none}}@media print{.side,.no-print{display:none!important}.shell{display:block}.main{padding:0}.cardx{box-shadow:none}.table{font-size:11pt}}
</style></head><body><div class="shell"><aside class="side"><a class="brand" href="<?=BASE_URL?>thidua.php?section=student_score"><i class="bi bi-door-closed"></i><div><strong>PHÒNG NỘI TRÚ</strong><small>Thi đua học sinh</small></div></a><div class="side-title">Chức năng</div><?php if(in_array('input',$allowedTabs,true)):?><a class="nav-link <?=$tab==='input'?'active':''?>" href="?tab=input"><i class="bi bi-pencil-square"></i> Nhập liệu</a><?php endif;?><?php if(in_array('stats',$allowedTabs,true)):?><a class="nav-link <?=$tab==='stats'?'active':''?>" href="?tab=stats"><i class="bi bi-bar-chart-line"></i> Thống kê - Xếp loại</a><?php endif;?><?php if(in_array('settings',$allowedTabs,true)):?><a class="nav-link <?=$tab==='settings'?'active':''?>" href="?tab=settings"><i class="bi bi-gear"></i> Cài đặt</a><?php endif;?><a class="nav-link mt-4" href="<?=BASE_URL?>thidua.php?section=student_score"><i class="bi bi-arrow-left"></i> Nề nếp - Học tập</a></aside><main class="main"><?php show_flash();?><header class="head"><div><h2><i class="bi bi-door-closed text-warning"></i> Phòng nội trú</h2><div class="text-muted">Chấm điểm, tổng hợp và xếp loại phòng ở</div></div><span class="badge text-bg-warning p-2"><?=e($userName)?></span></header>

<?php if($tab==='input'):?>
<form class="cardx toolbar no-print" method="get"><input type="hidden" name="tab" value="input"><div><label class="form-label">Chọn ngày thuộc tuần</label><input class="form-control" type="date" name="week" value="<?=e($inputWeek['start'])?>"></div><button class="btn btn-warning"><i class="bi bi-calendar-week"></i> Tải danh sách phòng</button><div class="ms-auto"><strong>Tuần: <?=e($inputWeek['label']??($inputWeek['start'].' - '.$inputWeek['end']))?></strong><div class="small text-muted">Điểm chuẩn: <?=number_format((float)$data['settings']['weekly_max'],1,',','.')?> điểm/phòng</div></div></form>
<?php if(!$rooms):?><div class="cardx empty">Chưa có danh sách phòng. Hãy tạo hoặc đồng bộ phòng trong Quản lý nội trú → Chia phòng.</div><?php else:?><div class="room-grid"><?php foreach($rooms as $room):$saved=$inputMap[$room]??null;$savedItems=(array)($saved['items']??[]);?><section class="cardx room-card"><div class="room-head"><div><strong><?=e($room)?></strong><small class="d-block text-muted"><?=$saved?'Đã nhập '.date('d/m/Y',strtotime((string)$saved['date'])):'Chưa nhập tuần này'?></small></div><span class="badge badge-score"><?=$saved?number_format((float)$saved['score'],1,',','.').'/'.number_format((float)$saved['max_score'],1,',','.'):'—'?></span></div><div class="room-body"><form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="entry_save"><input type="hidden" name="room" value="<?=e($room)?>"><label class="form-label">Ngày chấm</label><input class="form-control mb-3" type="date" name="date" value="<?=e($saved['date']??$inputWeek['start'])?>" required><div class="criterion-host"><?php foreach($savedItems?:[['criterion_id'=>'','quantity'=>1,'note'=>'']] as $item):?><div class="criterion-row"><select class="form-select" name="criterion[]"><option value="">Không có lỗi / Chọn mục trừ</option><?php foreach($activeCriteria as $criterion):?><option value="<?=e($criterion['id'])?>" <?=($item['criterion_id']??'')===$criterion['id']?'selected':''?>>−<?=number_format((float)$criterion['points'],1,',','.')?> · <?=e($criterion['name'])?></option><?php endforeach;?></select><input class="form-control" type="number" min="1" name="quantity[]" value="<?=max(1,(int)($item['quantity']??1))?>" title="Số lần"><input class="form-control note" name="item_note[]" value="<?=e($item['note']??'')?>" placeholder="Ghi chú"><button class="btn btn-outline-danger" type="button" onclick="this.closest('.criterion-row').remove()"><i class="bi bi-x"></i></button></div><?php endforeach;?></div><button class="btn btn-sm btn-outline-secondary mb-3" type="button" onclick="addCriterion(this)"><i class="bi bi-plus"></i> Thêm lỗi vi phạm</button><textarea class="form-control mb-3" name="general_note" rows="2" placeholder="Nhận xét chung (không bắt buộc)"><?=e($saved['general_note']??'')?></textarea><button class="btn btn-warning w-100" <?=$canEdit?'':'disabled'?>><i class="bi bi-floppy"></i> <?=$saved?'Cập nhật':'Lưu điểm phòng'?></button></form><?php if($saved&&$canDelete):?><form method="post" class="mt-2" onsubmit="return confirm('Xóa dữ liệu chấm điểm của <?=e($room)?> trong tuần này?')"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="entry_delete"><input type="hidden" name="id" value="<?=e($saved['id'])?>"><input type="hidden" name="week" value="<?=e($inputWeek['start'])?>"><button class="btn btn-sm btn-outline-danger w-100"><i class="bi bi-trash"></i> Xóa dữ liệu tuần</button></form><?php endif;?></div></section><?php endforeach;?></div><?php endif;?>

<?php elseif($tab==='stats'):?>
<form class="cardx toolbar no-print" method="get"><input type="hidden" name="tab" value="stats"><div><label class="form-label">Kiểu thống kê</label><select class="form-select" name="mode" onchange="this.form.submit()"><option value="week" <?=$statsMode==='week'?'selected':''?>>Theo tuần</option><option value="range" <?=$statsMode==='range'?'selected':''?>>Giai đoạn bất kỳ</option></select></div><?php if($statsMode==='week'):?><div><label class="form-label">Ngày thuộc tuần</label><input class="form-control" type="date" name="anchor" value="<?=e($statsAnchor)?>"></div><?php else:?><div><label class="form-label">Từ ngày</label><input class="form-control" type="date" name="from" value="<?=e($from)?>"></div><div><label class="form-label">Đến ngày</label><input class="form-control" type="date" name="to" value="<?=e($to)?>"></div><?php endif;?><button class="btn btn-warning"><i class="bi bi-filter"></i> Xem kết quả</button><button class="btn btn-outline-secondary" type="button" onclick="window.print()"><i class="bi bi-printer"></i> In</button></form><section class="cardx p-3"><div class="d-flex justify-content-between gap-2 flex-wrap mb-3"><div><h5 class="fw-bold mb-1">Xếp loại phòng ở</h5><span class="text-muted">Từ <?=date('d/m/Y',strtotime($from))?> đến <?=date('d/m/Y',strtotime($to))?></span></div><div class="small text-muted">Xếp theo điểm trung bình giảm dần · Chỉ tính tuần đã nhập</div></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Thứ hạng</th><th>Phòng</th><th>Số tuần đã nhập</th><th>Tổng điểm trừ</th><th>Tổng điểm</th><th>Điểm trung bình</th><th>Xếp loại</th></tr></thead><tbody><?php $rank=0;foreach($summary as $row):?><tr><td><?php if($row['weeks']):$rank++;?><span class="rank <?=$rank===1?'first':''?>"><?=$rank?></span><?php else:?>—<?php endif;?></td><td><strong><?=e($row['room'])?></strong></td><td><?=e($row['weeks'])?></td><td><?=$row['weeks']?number_format($row['deduction'],1,',','.'):'—'?></td><td><?=$row['weeks']?number_format($row['total'],1,',','.'):'—'?></td><td><?=$row['weeks']?'<strong>'.number_format($row['average'],2,',','.').'</strong>':'<span class="text-muted">Chưa nhập</span>'?></td><td><?=$row['weeks']?'<span class="badge '.($row['rating']==='Tốt'?'text-bg-success':($row['rating']==='Chưa đạt'?'text-bg-danger':'text-bg-warning')).'">'.e($row['rating']).'</span>':'—'?></td></tr><?php endforeach;if(!$rooms):?><tr><td colspan="7" class="empty">Chưa có danh sách phòng.</td></tr><?php endif;?></tbody></table></div></section>

<?php else:?>
<form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="settings_save"><section class="cardx p-3 mb-3"><h5 class="fw-bold">Quy định điểm và xếp loại</h5><div class="row g-3"><div class="col-md-3"><label class="form-label">Tổng điểm một phòng/tuần</label><input class="form-control" type="number" min="1" step=".1" name="weekly_max" value="<?=e($data['settings']['weekly_max'])?>" required></div><div class="col-md-3"><label class="form-label">Tốt từ (%)</label><input class="form-control" type="number" min="0" max="100" step=".1" name="excellent" value="<?=e($data['settings']['excellent'])?>"></div><div class="col-md-3"><label class="form-label">Khá từ (%)</label><input class="form-control" type="number" min="0" max="100" step=".1" name="good" value="<?=e($data['settings']['good'])?>"></div><div class="col-md-3"><label class="form-label">Đạt từ (%)</label><input class="form-control" type="number" min="0" max="100" step=".1" name="pass" value="<?=e($data['settings']['pass'])?>"></div></div><div class="form-text mt-2">Mặc định: Tốt ≥90%, Khá ≥80%, Đạt ≥65%, dưới 65% là Chưa đạt. Có thể thay đổi tại đây.</div></section><section class="cardx p-3"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="fw-bold mb-1">Các mục điểm trừ</h5><span class="text-muted small">Chỉ các mục chọn “Hiển thị” mới xuất hiện trong danh sách xổ xuống ở tab Nhập liệu.</span></div><button class="btn btn-outline-warning" type="button" onclick="addSettingRow()"><i class="bi bi-plus"></i> Thêm mục</button></div><div id="settingRows"><?php foreach($data['criteria'] as $criterion):?><div class="setting-row"><input class="form-control criterion-id" name="criterion_id[]" value="<?=e($criterion['id'])?>" readonly><input class="form-control" name="criterion_name[]" value="<?=e($criterion['name'])?>" placeholder="Nội dung vi phạm" required><input class="form-control" type="number" min=".01" step=".01" name="criterion_points[]" value="<?=e($criterion['points'])?>" title="Điểm trừ" required><select class="form-select" name="criterion_active[]"><option value="1" <?=!empty($criterion['active'])?'selected':''?>>Hiển thị</option><option value="0" <?=empty($criterion['active'])?'selected':''?>>Ẩn</option></select><button class="btn btn-outline-danger" type="button" onclick="this.closest('.setting-row').remove()"><i class="bi bi-trash"></i></button></div><?php endforeach;?></div><div class="text-end mt-3"><button class="btn btn-warning px-4" <?=$canEdit?'':'disabled'?>><i class="bi bi-floppy"></i> Lưu cài đặt</button></div></section></form>
<?php endif;?></main></div><template id="criterionTemplate"><div class="criterion-row"><select class="form-select" name="criterion[]"><option value="">Không có lỗi / Chọn mục trừ</option><?php foreach($activeCriteria as $criterion):?><option value="<?=e($criterion['id'])?>">−<?=number_format((float)$criterion['points'],1,',','.')?> · <?=e($criterion['name'])?></option><?php endforeach;?></select><input class="form-control" type="number" min="1" name="quantity[]" value="1" title="Số lần"><input class="form-control note" name="item_note[]" placeholder="Ghi chú"><button class="btn btn-outline-danger" type="button" onclick="this.closest('.criterion-row').remove()"><i class="bi bi-x"></i></button></div></template><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>
function addCriterion(button){var host=button.closest('form').querySelector('.criterion-host'),template=document.getElementById('criterionTemplate');host.appendChild(template.content.cloneNode(true))}
function addSettingRow(){var host=document.getElementById('settingRows'),row=document.createElement('div');row.className='setting-row';row.innerHTML='<input class="form-control criterion-id" name="criterion_id[]" readonly placeholder="Tự tạo"><input class="form-control" name="criterion_name[]" placeholder="Nội dung vi phạm" required><input class="form-control" type="number" min=".01" step=".01" name="criterion_points[]" value="1" required><select class="form-select" name="criterion_active[]"><option value="1">Hiển thị</option><option value="0">Ẩn</option></select><button class="btn btn-outline-danger" type="button" onclick="this.closest(\'.setting-row\').remove()"><i class="bi bi-trash"></i></button>';host.appendChild(row)}
</script></body></html>
