<?php
require_once __DIR__ . '/includes/auth.php';
require_login();
$batch=trim((string)($_GET['batch']??''));$data=load_json(DATA_PATH.'/library_equipment.json',['equipment_loans'=>[]]);$rows=array_values(array_filter((array)($data['equipment_loans']??[]),fn($row)=>($row['batch_id']??'')===$batch));
if(!$rows){http_response_code(404);exit('Không tìm thấy phiếu mượn thiết bị.');}
$user=current_user()??[];$name=trim((string)($user['teacher_name']??$user['name']??''));$first=$rows[0];$isAdmin=($user['role']??'')==='admin';if(!$isAdmin&&!cds_can_feature('hl.thietbi','view')&&($first['created_by']??'')!==$name){http_response_code(403);exit('Không có quyền xem phiếu.');}
$year=(string)($first['school_year']??SCHOOL_YEAR);$borrower=(string)($first['borrower']??'');$subject=(string)($first['subject']??'');$group=(string)($first['teacher_group']??'');
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Phiếu mượn thiết bị – <?=htmlspecialchars($borrower)?></title><style>
@page{size:A4 portrait;margin:17mm}*{box-sizing:border-box}body{font-family:"Times New Roman",serif;font-size:13.5pt;color:#000;margin:0}.toolbar{position:fixed;top:10px;right:12px}.toolbar button,.toolbar a{font:14px Arial;padding:8px 14px;margin-left:6px;text-decoration:none;border:1px solid #555;border-radius:5px;background:#fff;color:#111}.title{text-align:center;margin-bottom:30px}.title h1{font-size:17pt;margin:0;text-transform:uppercase}.title h2{font-size:15pt;margin:4px 0}.info{margin:10px 0}.dots{display:inline-block;min-width:290px;border-bottom:1px dotted #000;padding:0 6px 2px}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12.5pt}th,td{border:1px solid #000;padding:7px 5px;text-align:center;height:34px}td:nth-child(2){text-align:left}.notes{margin-top:8px;font-size:12.5pt}.notes p{margin:7px 0}.sign{text-align:center;width:40%;margin:35px 0 0 auto}.sign .space{height:75px}@media print{.toolbar{display:none}}</style></head><body>
<div class="toolbar"><a href="<?=BASE_URL?>thuvien.php?tab=equipment_loans">Quay lại</a><button onclick="window.print()">In / Lưu PDF</button></div>
<div class="title"><h1>PHIẾU ĐĂNG KÝ MƯỢN THIẾT BỊ – ĐỒ DÙNG DẠY HỌC</h1><h2>NĂM HỌC: <?=htmlspecialchars($year)?></h2></div>
<div class="info">Họ và tên GV: <span class="dots"><?=htmlspecialchars($borrower)?></span></div>
<div class="info">Môn dạy: <span class="dots" style="min-width:190px"><?=htmlspecialchars($subject)?></span> Tổ chuyên môn: <span class="dots" style="min-width:180px"><?=htmlspecialchars($group)?></span></div>
<table><thead><tr><th style="width:13%">Ngày/Tháng</th><th>Tên thiết bị</th><th style="width:10%">Số lượng</th><th style="width:13%">Dạy tiết (PPCT)</th><th style="width:12%">Khối/lớp</th><th style="width:16%">Ghi chú</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=htmlspecialchars(date('d/m/Y',strtotime((string)$row['borrowed_at'])))?></td><td><?=htmlspecialchars((string)$row['equipment_name'])?></td><td><?=(int)$row['quantity']?></td><td><?=htmlspecialchars((string)($row['lesson_period']??''))?></td><td><?=htmlspecialchars((string)($row['teaching_grade']??''))?></td><td><?=htmlspecialchars((string)($row['note']??''))?></td></tr><?php endforeach;for($i=count($rows);$i<10;$i++):?><tr><td></td><td></td><td></td><td></td><td></td><td></td></tr><?php endfor;?></tbody></table>
<div class="notes"><strong>Phụ chú:</strong><p>– Thiết bị của trường không có cùng ghi rõ.</p><p>– Thiết bị dạy học tự làm của giáo viên.</p></div>
<div class="sign"><strong>GIÁO VIÊN</strong><div>(Ký và ghi họ tên)</div><div class="space"></div><strong><?=htmlspecialchars($borrower)?></strong></div>
</body></html>