<?php
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/timetable_store.php';
require_login();require_module('chuyenmon','view');
$user=current_user()??[];$isAdmin=($user['role']??'')==='admin';$canManage=$isAdmin||can_edit_perm('cm.nhaplieu');
if(empty($_SESSION['tt_csrf']))$_SESSION['tt_csrf']=bin2hex(random_bytes(24));$csrf=$_SESSION['tt_csrf'];
function tt_redirect(string $tab='mine'): never {header('Location: '.BASE_URL.'thoikhoabieu.php?tab='.$tab);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals((string)$csrf,(string)($_POST['csrf']??''))){flash('Phiên làm việc không hợp lệ.','danger');tt_redirect();}
    if(!$canManage){flash('Bạn không có quyền quản lý thời khóa biểu.','danger');tt_redirect();}
    $action=(string)($_POST['action']??'');
    try{
        if($action==='upload'){
            $upload=$_FILES['timetable_file']??[];if(($upload['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Hãy chọn file Excel .xlsx.');if(strtolower(pathinfo((string)($upload['name']??''),PATHINFO_EXTENSION))!=='xlsx')throw new RuntimeException('Chỉ chấp nhận file .xlsx.');
            $parsed=tt_parse_xlsx((string)$upload['tmp_name']);if(empty($parsed['ok']))throw new RuntimeException($parsed['message']??'Không đọc được file.');$from=(string)($_POST['week_from']??'');$to=(string)($_POST['week_to']??'');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||$to<$from)throw new RuntimeException('Khoảng tuần không hợp lệ.');
            $versions=tt_versions();foreach($versions as &$old)$old['published']=false;unset($old);$now=date('c');$show=!empty($_POST['dashboard_visible']);$versions[]=['id'=>'tt_'.bin2hex(random_bytes(7)),'name'=>trim((string)($_POST['name']??''))?:'Tuần '.date('d/m',strtotime($from)).'–'.date('d/m',strtotime($to)),'week_from'=>$from,'week_to'=>$to,'entries'=>$parsed['entries'],'raw_values'=>$parsed['raw_values'],'published'=>true,'dashboard_visible'=>$show,'dashboard_from'=>$show?$now:'','dashboard_to'=>$show?date('c',time()+2*86400):'','source_name'=>basename((string)$upload['name']),'created_by'=>$user['name']??'','created_at'=>$now];tt_save(CDS_TIMETABLE_VERSIONS,$versions);flash($parsed['message'].' Đã công bố thời khóa biểu.','success');tt_redirect('history');
        }
        if($action==='mapping_save'){
            $type=(string)($_POST['mapping_type']??'');$raw=trim((string)($_POST['raw']??''));$targetId=(string)($_POST['target_id']??'');if(!in_array($type,['teacher','class','subject'],true)||$raw===''||$targetId==='')throw new RuntimeException('Dữ liệu đối chiếu chưa đầy đủ.');$catalogs=tt_catalogs();$target=null;foreach($catalogs[$type]??[] as $row)if((string)($row['id']??'')===$targetId){$target=$row;break;}if(!$target)throw new RuntimeException('Không tìm thấy dữ liệu CSDL đã chọn.');$maps=tt_mappings();$maps[$type][tt_mapping_key($raw)]=['raw'=>$raw,'id'=>$targetId,'name'=>$target['name']??$raw,'updated_at'=>date('c')];tt_save(CDS_TIMETABLE_MAPPINGS,$maps);flash('Đã lưu đối chiếu “'.$raw.'”.','success');tt_redirect('settings');
        }
        if($action==='publish'){$id=(string)($_POST['id']??'');$versions=tt_versions();foreach($versions as &$v)$v['published']=(($v['id']??'')===$id);unset($v);tt_save(CDS_TIMETABLE_VERSIONS,$versions);flash('Đã chuyển phiên bản thời khóa biểu đang áp dụng.','success');tt_redirect('history');}
        if($action==='delete'){$id=(string)($_POST['id']??'');$versions=array_values(array_filter(tt_versions(),fn($v)=>($v['id']??'')!==$id));tt_save(CDS_TIMETABLE_VERSIONS,$versions);flash('Đã xóa phiên bản thời khóa biểu.','success');tt_redirect('history');}
    }catch(Throwable $e){flash($e->getMessage(),'danger');tt_redirect($action==='upload'?'upload':'settings');}
}
$tab=(string)($_GET['tab']??'mine');if(!in_array($tab,['mine','class','upload','history','settings'],true))$tab='mine';if(!$canManage&&in_array($tab,['upload','history','settings'],true))$tab='mine';
$versions=tt_versions();$selected=tt_active_version(isset($_GET['version'])?(string)$_GET['version']:null)??tt_active_version();$resolved=$selected?tt_resolve_version($selected):['entries'=>[],'unmatched'=>[]];$entries=$resolved['entries'];$catalogs=tt_catalogs();$teacher=tt_teacher_for_user($user);$teacherName=(string)($teacher['name']??$user['teacher_name']??$user['name']??'');
$viewTeacherId=$canManage?(string)($_GET['teacher_id']??($teacher['id']??$catalogs['teacher'][0]['id']??'')):(string)($teacher['id']??'');$viewTeacherName=$teacherName;foreach($catalogs['teacher'] as $candidate)if((string)($candidate['id']??'')===$viewTeacherId){$viewTeacherName=(string)($candidate['name']??'');break;}
$classId=(string)($_GET['class_id']??'');if($classId===''){foreach($catalogs['class'] as $c)if(($c['homeroom_teacher_id']??'')===($teacher['id']??'')||tt_norm($c['homeroom_teacher_name']??'')===tt_norm($teacherName)){$classId=(string)$c['id'];break;}}if($classId==='')$classId=(string)($catalogs['class'][0]['id']??'');
$className='';foreach($catalogs['class'] as $c)if((string)($c['id']??'')===$classId){$className=(string)$c['name'];break;}
if($tab==='mine')$display=array_values(array_filter($entries,fn($e)=>($e['teacher_id']??'')===$viewTeacherId||tt_norm($e['teacher_name']??$e['teacher_raw']??'')===tt_norm($viewTeacherName)));
else $display=array_values(array_filter($entries,fn($e)=>$tab!=='class'||($e['class_id']??'')===$classId||tt_norm($e['class_name']??$e['class_raw']??'')===tt_norm($className)));
$grid=[];foreach($display as $e)$grid[(int)$e['day']][tt_norm($e['session']??'sáng')][(int)$e['period']]=$e;
$rawAll=['teacher'=>[],'class'=>[],'subject'=>[]];foreach($versions as $v)foreach($rawAll as $type=>$_)foreach((array)($v['raw_values'][$type]??[]) as $raw)$rawAll[$type][$raw]=true;$maps=tt_mappings();
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Thời khóa biểu – CDS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>
:root{--p:#1f4e79;--bg:#eef3f8}body{background:var(--bg);color:#172033;font-family:Segoe UI,system-ui,sans-serif}.top{background:linear-gradient(120deg,#173f67,#2877b3);color:#fff}.wrap{max-width:1500px}.tabs{display:flex;gap:.45rem;overflow:auto;padding:.45rem;background:#fff;border-radius:16px;box-shadow:0 4px 18px #173f6712}.tabs a{padding:.7rem 1rem;border-radius:11px;color:#526579;text-decoration:none;font-weight:750;white-space:nowrap}.tabs a.active{background:var(--p);color:#fff}.card{border:1px solid #dce5ed;border-radius:17px;box-shadow:0 5px 18px #173f670b}.tt-grid{display:grid;grid-template-columns:repeat(6,minmax(190px,1fr));gap:.7rem;min-width:1180px}.day{background:#fff;border:1px solid #dbe5ed;border-radius:15px;overflow:hidden}.day h5{margin:0;padding:.7rem;text-align:center;background:#e9f2fb;color:var(--p)}.session{padding:.45rem .65rem;background:#f8fafc;color:#64748b;font-size:.75rem;font-weight:850;text-transform:uppercase}.lesson{display:grid;grid-template-columns:30px 1fr;gap:.45rem;min-height:70px;padding:.6rem;border-top:1px solid #edf1f5}.lesson .period{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#dbeafe;color:#1d4ed8;font-weight:800}.lesson strong,.lesson small{display:block}.lesson small{margin-top:.15rem;color:#64748b}.empty{padding:3rem;text-align:center;color:#718096}.map-row{display:grid;grid-template-columns:minmax(150px,.8fr) minmax(230px,1.4fr) auto;gap:.6rem;align-items:center;padding:.65rem 0;border-bottom:1px solid #edf1f5}.map-ok{color:#15803d;font-size:.8rem}.badge-new{background:#dbeafe;color:#1d4ed8}@media(max-width:760px){.wrap{padding-left:.7rem!important;padding-right:.7rem!important}.top .container{padding:.8rem!important}.tt-grid{display:block;min-width:0}.day{margin-bottom:.75rem}.map-row{grid-template-columns:1fr}.desktop-help{display:none}}
</style></head><body><header class="top"><div class="container-fluid wrap py-3 d-flex justify-content-between align-items-center gap-3"><div><h3 class="mb-0"><i class="bi bi-calendar3"></i> Thời khóa biểu</h3><small><?=e(SCHOOL_NAME)?></small></div><div class="d-flex gap-2"><a class="btn btn-light btn-sm" href="<?=BASE_URL?>admin.php"><i class="bi bi-house"></i> Tổng quan</a><a class="btn btn-outline-light btn-sm" href="<?=BASE_URL?>chuyenmon/"><i class="bi bi-journal-bookmark"></i> Chuyên môn</a></div></div></header><main class="container-fluid wrap py-3"><?php show_flash();?><nav class="tabs mb-3"><a class="<?=$tab==='mine'?'active':''?>" href="?tab=mine"><i class="bi bi-person"></i> TKB của tôi</a><a class="<?=$tab==='class'?'active':''?>" href="?tab=class"><i class="bi bi-people"></i> Theo lớp</a><?php if($canManage):?><a class="<?=$tab==='upload'?'active':''?>" href="?tab=upload"><i class="bi bi-cloud-arrow-up"></i> Cập nhật tuần</a><a class="<?=$tab==='history'?'active':''?>" href="?tab=history"><i class="bi bi-clock-history"></i> Lịch sử</a><a class="<?=$tab==='settings'?'active':''?>" href="?tab=settings"><i class="bi bi-sliders"></i> Cài đặt & đối chiếu</a><?php endif;?></nav>
<?php if(in_array($tab,['mine','class'],true)):?><section class="card p-3 mb-3"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3"><div><span class="text-muted small">Phiên bản đang xem</span><h4 class="mb-0"><?=e($selected['name']??'Chưa có thời khóa biểu')?></h4><?php if($selected):?><small><?=date('d/m/Y',strtotime($selected['week_from']))?> – <?=date('d/m/Y',strtotime($selected['week_to']))?></small><?php endif;?></div><div class="d-flex gap-2 flex-wrap"><?php if($tab==='class'):?><form><input type="hidden" name="tab" value="class"><select class="form-select" name="class_id" onchange="this.form.submit()"><?php foreach($catalogs['class'] as $c):?><option value="<?=e($c['id'])?>" <?=($c['id']??'')===$classId?'selected':''?>>Lớp <?=e($c['name'])?></option><?php endforeach;?></select></form><?php else:?><span class="badge text-bg-primary p-2"><i class="bi bi-person-check"></i> <?=e($teacherName?:'Tài khoản chưa ghép giáo viên')?></span><?php endif;?><select class="form-select" onchange="location.href='?tab=<?=e($tab)?>&version='+encodeURIComponent(this.value)<?php if($tab==='class'):?>+'&class_id=<?=e($classId)?>'<?php endif;?>"><option value="">Tuần đang áp dụng</option><?php foreach($versions as $v):?><option value="<?=e($v['id'])?>" <?=($selected['id']??'')===($v['id']??'')?'selected':''?>><?=e($v['name'])?></option><?php endforeach;?></select></div></div></section><div class="overflow-auto"><div class="tt-grid"><?php for($day=2;$day<=7;$day++):?><section class="day"><h5>Thứ <?=$day?></h5><?php foreach(['sang'=>'Sáng','chieu'=>'Chiều'] as $sessionKey=>$sessionLabel):?><div class="session"><?=$sessionLabel?></div><?php for($period=1;$period<=4;$period++):$e=$grid[$day][$sessionKey][$period]??null;?><div class="lesson"><span class="period"><?=$period?></span><div><?php if($e):?><strong><?=e($e['subject_name']??$e['subject_raw']??'')?></strong><small><?=$tab==='mine'?'Lớp '.e($e['class_name']??$e['class_raw']??''):e($e['teacher_name']??$e['teacher_raw']??'')?></small><?php else:?><span class="text-muted">—</span><?php endif;?></div></div><?php endfor;endforeach;?></section><?php endfor;?></div></div><?php if(!$selected):?><div class="empty"><i class="bi bi-calendar-x fs-1"></i><h5>Chưa có thời khóa biểu</h5><p>Quản trị cần tải và công bố file Excel tuần.</p></div><?php endif;?>
<?php elseif($tab==='upload'):?><section class="card p-4"><h4><i class="bi bi-file-earmark-excel text-success"></i> Tải thời khóa biểu tuần</h4><p class="text-muted">Hệ thống đọc mẫu có ba cột Lớp – Buổi – Tiết; mỗi Thứ gồm cột Môn và Giáo viên.</p><form method="post" enctype="multipart/form-data" class="row g-3"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="upload"><div class="col-md-4"><label class="form-label">Tên phiên bản</label><input class="form-control" name="name" placeholder="Ví dụ: TKB tuần 3"></div><div class="col-md-4"><label class="form-label">Từ ngày *</label><input class="form-control" type="date" name="week_from" required></div><div class="col-md-4"><label class="form-label">Đến ngày *</label><input class="form-control" type="date" name="week_to" required></div><div class="col-12"><label class="form-label">File Excel .xlsx *</label><input class="form-control" type="file" name="timetable_file" accept=".xlsx" required></div><div class="col-12"><label class="form-check p-3 border rounded-3 bg-light"><input class="form-check-input" type="checkbox" name="dashboard_visible" value="1" checked> <span class="form-check-label"><strong>Hiện thông báo tại admin.php</strong><br><small class="text-muted">Mặc định hiển thị 2 ngày kể từ lúc công bố và được đồng bộ tới chuông điện thoại.</small></span></label></div><div class="col-12"><button class="btn btn-primary"><i class="bi bi-cloud-arrow-up"></i> Kiểm tra, tải lên và công bố</button></div></form></section>
<?php elseif($tab==='history'):?><section class="card overflow-hidden"><div class="p-3 border-bottom"><h4 class="mb-0">Lịch sử phiên bản</h4></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Phiên bản</th><th>Tuần áp dụng</th><th>Số tiết</th><th>Người tải</th><th>Trạng thái</th><th></th></tr></thead><tbody><?php foreach($versions as $v):?><tr><td><strong><?=e($v['name'])?></strong><small class="d-block text-muted"><?=e($v['source_name']??'')?></small></td><td><?=date('d/m/Y',strtotime($v['week_from']))?>–<?=date('d/m/Y',strtotime($v['week_to']))?></td><td><?=count($v['entries']??[])?></td><td><?=e($v['created_by']??'')?></td><td><?=$v['published']?'<span class="badge text-bg-success">Đang áp dụng</span>':'<span class="badge text-bg-secondary">Lịch sử</span>'?> <?=!empty($v['dashboard_visible'])?'<span class="badge badge-new">Có thông báo</span>':''?></td><td><div class="d-flex gap-1"><?php if(empty($v['published'])):?><form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="publish"><input type="hidden" name="id" value="<?=e($v['id'])?>"><button class="btn btn-sm btn-outline-success">Áp dụng</button></form><?php endif;?><a class="btn btn-sm btn-outline-primary" href="?tab=class&version=<?=e($v['id'])?>">Xem</a><form method="post" onsubmit="return confirm('Xóa phiên bản thời khóa biểu này?')"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=e($v['id'])?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></td></tr><?php endforeach;if(!$versions):?><tr><td colspan="6" class="empty">Chưa có phiên bản.</td></tr><?php endif;?></tbody></table></div></section>
<?php else:?><section class="card p-3 mb-3"><h4>Cài đặt và đối chiếu CSDL</h4><p class="text-muted mb-0">Danh sách đích lấy trực tiếp từ CSDL. Tên viết tắt trong Excel chỉ cần ghép một lần và được ghi nhớ cho các tuần sau.</p></section><?php foreach(['teacher'=>'Giáo viên','class'=>'Lớp','subject'=>'Môn học'] as $type=>$label):?><section class="card p-3 mb-3"><h5><?=$label?></h5><?php foreach(array_keys($rawAll[$type]) as $raw):$mapped=tt_map_value($type,$raw,$maps)?:tt_auto_target($type,$raw,$catalogs);?><form method="post" class="map-row"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="mapping_save"><input type="hidden" name="mapping_type" value="<?=$type?>"><input type="hidden" name="raw" value="<?=e($raw)?>"><div><strong><?=e($raw)?></strong><?php if($mapped):?><div class="map-ok"><i class="bi bi-check-circle"></i> <?=e($mapped['name'])?></div><?php endif;?></div><select class="form-select" name="target_id" required><option value="">Chọn từ CSDL…</option><?php foreach($catalogs[$type] as $target):?><option value="<?=e($target['id'])?>" <?=($mapped['id']??'')===($target['id']??'')?'selected':''?>><?=e($target['name'])?></option><?php endforeach;?></select><button class="btn btn-outline-primary">Lưu ghép</button></form><?php endforeach;if(!$rawAll[$type]):?><div class="text-muted">Chưa có dữ liệu từ file Excel.</div><?php endif;?></section><?php endforeach;endif;?></main></body></html>
