<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/csdl_store.php';
require_login();

$user = current_user() ?? [];
$role = (string)($user['role'] ?? '');
$isAdmin = $role === 'admin';
$canLibraryManage = $isAdmin || cds_can_feature('hl.thuvien', 'edit');
$canLibraryDelete = $isAdmin || cds_can_feature('hl.thuvien', 'delete');
$canEquipmentManage = $isAdmin || cds_can_feature('hl.thietbi', 'edit');
$canEquipmentDelete = $isAdmin || cds_can_feature('hl.thietbi', 'delete');
$canEquipmentBorrow = true; // Mọi tài khoản đã đăng nhập được lập phiếu mượn thiết bị.
$canManage = $canLibraryManage || $canEquipmentManage;
$userName = trim((string)($user['teacher_name'] ?? $user['name'] ?? $user['username'] ?? ''));
$dataFile = DATA_PATH . '/library_equipment.json';
$data = load_json($dataFile, ['books'=>[], 'loans'=>[], 'equipment'=>[], 'equipment_loans'=>[], 'maintenance'=>[]]);
foreach (['books','loans','equipment','equipment_loans','maintenance'] as $key) $data[$key] = is_array($data[$key] ?? null) ? array_values($data[$key]) : [];

if (empty($_SESSION['library_csrf'])) $_SESSION['library_csrf'] = bin2hex(random_bytes(24));
$csrf = (string)$_SESSION['library_csrf'];

function lib_redirect(string $tab='dashboard'): void { header('Location: '.BASE_URL.'thuvien.php?tab='.urlencode($tab)); exit; }
function lib_index(array $rows,string $id): int { foreach($rows as $i=>$row)if(($row['id']??'')===$id)return $i;return -1; }
function lib_date(string $value): string { $time=strtotime($value);return $time?date('d/m/Y',$time):'—'; }
function lib_book_available(array $book,array $loans): int {
    $borrowed=0;foreach($loans as $loan)if(($loan['book_id']??'')===($book['id']??'')&&empty($loan['returned_at']))$borrowed+=(int)($loan['quantity']??0);
    return max(0,(int)($book['quantity']??0)-$borrowed);
}
function lib_norm(string $value): string { return function_exists('mb_strtolower')?mb_strtolower(trim($value),'UTF-8'):strtolower(trim($value)); }

$teachers = function_exists('csdl_teachers_all') ? csdl_teachers_all() : [];
$students = function_exists('csdl_students_all') ? csdl_students_all() : [];
$classes = function_exists('csdl_classes_all') ? csdl_classes_all() : [];
$classMap=[];foreach($classes as $class)$classMap[(string)($class['id']??'')]=(string)($class['name']??'');

if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (!hash_equals($csrf,(string)($_POST['csrf']??''))) { http_response_code(403);exit('Phiên làm việc không hợp lệ.'); }
    $action=(string)($_POST['action']??'');$tab=(string)($_POST['tab']??'library_books');
    $libraryActions=['save_book','delete_book','save_loan','return_loan','delete_loan'];
    $equipmentManageActions=['save_equipment','delete_equipment','save_maintenance','delete_maintenance'];
    $equipmentBorrowActions=['save_equipment_loan','return_equipment_loan','delete_equipment_loan'];
    if(in_array($action,$libraryActions,true)&&!$canLibraryManage){http_response_code(403);exit('Tài khoản chưa có quyền quản lý thư viện.');}
    if(in_array($action,$equipmentManageActions,true)&&!$canEquipmentManage){http_response_code(403);exit('Tài khoản chưa có quyền quản lý thiết bị.');}
    if(in_array($action,$equipmentBorrowActions,true)&&!$canEquipmentBorrow){http_response_code(403);exit('Tài khoản chưa có quyền lập phiếu thiết bị.');}

    if ($action==='save_book') {
        $id=trim((string)($_POST['id']??''));$title=trim((string)($_POST['title']??''));$quantity=max(0,(int)($_POST['quantity']??0));
        if($title===''||$quantity<1){flash('Tên sách và số lượng phải hợp lệ.','danger');lib_redirect('library_books');}
        $row=['id'=>$id?:'book_'.bin2hex(random_bytes(7)),'title'=>$title,'code'=>trim((string)($_POST['code']??'')),'barcode'=>trim((string)($_POST['barcode']??'')),'category'=>trim((string)($_POST['category']??'')),'subject'=>trim((string)($_POST['subject']??'')),'grade'=>trim((string)($_POST['grade']??'')),'quantity'=>$quantity,'import_date'=>trim((string)($_POST['import_date']??date('Y-m-d'))),'source'=>trim((string)($_POST['source']??'')),'shelf'=>trim((string)($_POST['shelf']??'')),'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c')];
        $index=lib_index($data['books'],$id);
        if($index>=0){$row['created_at']=$data['books'][$index]['created_at']??date('c');$data['books'][$index]=$row;}else{$row['created_at']=date('c');$data['books'][]=$row;}
        save_json($dataFile,$data);flash('Đã lưu thông tin sách.','success');lib_redirect('library_books');
    }
    if ($action==='delete_book') {
        $id=trim((string)($_POST['id']??''));$active=false;foreach($data['loans'] as $loan)if(($loan['book_id']??'')===$id&&empty($loan['returned_at'])){$active=true;break;}
        if($active){flash('Không thể xóa sách đang có lượt mượn chưa trả.','danger');lib_redirect('library_books');}
        $index=lib_index($data['books'],$id);if($index>=0)array_splice($data['books'],$index,1);
        save_json($dataFile,$data);flash('Đã xóa sách.','warning');lib_redirect('library_books');
    }
    if ($action==='save_loan') {
        $bookIds=array_values((array)($_POST['book_id']??[]));$quantities=array_values((array)($_POST['quantity']??[]));
        $name=trim((string)($_POST['borrower_name']??''));$borrowerType=in_array($_POST['borrower_type']??'', ['student','teacher','manual'],true)?(string)$_POST['borrower_type']:'manual';
        if($name===''){flash('Vui lòng nhập người mượn.','danger');lib_redirect('library_loans');}
        $borrowedAt=trim((string)($_POST['borrowed_at']??date('Y-m-d')));$dueAt=trim((string)($_POST['due_at']??''));$batch='batch_'.bin2hex(random_bytes(6));$added=0;
        foreach($bookIds as $line=>$bookId){$bookId=trim((string)$bookId);if($bookId==='')continue;$bookIndex=lib_index($data['books'],$bookId);$qty=max(1,(int)($quantities[$line]??1));if($bookIndex<0)continue;$available=lib_book_available($data['books'][$bookIndex],$data['loans']);if($qty>$available){flash('Sách “'.$data['books'][$bookIndex]['title'].'” chỉ còn '.$available.' cuốn.','danger');lib_redirect('library_loans');}
        $data['loans'][]=['id'=>'loan_'.bin2hex(random_bytes(8)),'batch_id'=>$batch,'book_id'=>$bookId,'book_title'=>(string)$data['books'][$bookIndex]['title'],'book_category'=>(string)($data['books'][$bookIndex]['category']??''),'borrower_type'=>$borrowerType,'borrower_id'=>trim((string)($_POST['borrower_id']??'')),'borrower_name'=>$name,'class_name'=>trim((string)($_POST['class_name']??'')),'quantity'=>$qty,'borrowed_at'=>$borrowedAt,'due_at'=>$dueAt,'condition_out'=>trim((string)($_POST['condition_out']??'')),'note'=>trim((string)($_POST['note']??'')),'returned_at'=>'','return_condition'=>'','created_by'=>$userName,'created_at'=>date('c')];$added++;}
        if(!$added){flash('Vui lòng thêm ít nhất một sách vào phiếu mượn.','danger');lib_redirect('library_loans');}
        save_json($dataFile,$data);flash('Đã ghi nhận phiếu mượn gồm '.$added.' đầu sách.','success');lib_redirect('library_loans');
    }
    if ($action==='return_loan') {
        $index=lib_index($data['loans'],trim((string)($_POST['id']??'')));if($index<0){flash('Không tìm thấy phiếu mượn.','danger');lib_redirect('library_loans');}
        $data['loans'][$index]['returned_at']=trim((string)($_POST['returned_at']??date('Y-m-d')));
        $data['loans'][$index]['return_condition']=trim((string)($_POST['return_condition']??''));
        $extra=trim((string)($_POST['return_note']??''));if($extra!=='')$data['loans'][$index]['note']=trim((string)($data['loans'][$index]['note']??'')."\nTrả sách: ".$extra);
        $data['loans'][$index]['returned_by']=$userName;$data['loans'][$index]['updated_at']=date('c');
        save_json($dataFile,$data);flash('Đã xác nhận trả sách.','success');lib_redirect('library_loans');
    }
    if ($action==='delete_loan') {
        $index=lib_index($data['loans'],trim((string)($_POST['id']??'')));if($index>=0)array_splice($data['loans'],$index,1);
        save_json($dataFile,$data);flash('Đã xóa phiếu mượn.','warning');lib_redirect('library_loans');
    }
    if ($action==='save_equipment') {
        $id=trim((string)($_POST['id']??''));$name=trim((string)($_POST['name']??''));if($name===''){flash('Vui lòng nhập tên thiết bị.','danger');lib_redirect('equipment');}
        $row=['id'=>$id?:'eq_'.bin2hex(random_bytes(7)),'name'=>$name,'code'=>trim((string)($_POST['code']??'')),'category'=>trim((string)($_POST['category']??'')),'quantity'=>max(0,(int)($_POST['quantity']??0)),'good_quantity'=>max(0,(int)($_POST['good_quantity']??0)),'location'=>trim((string)($_POST['location']??'')),'import_date'=>trim((string)($_POST['import_date']??date('Y-m-d'))),'source'=>trim((string)($_POST['source']??'')),'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c')];
        $index=lib_index($data['equipment'],$id);if($index>=0){$row['created_at']=$data['equipment'][$index]['created_at']??date('c');$data['equipment'][$index]=$row;}else{$row['created_at']=date('c');$data['equipment'][]=$row;}
        save_json($dataFile,$data);flash('Đã lưu thiết bị.','success');lib_redirect('equipment');
    }
    if ($action==='delete_equipment') {
        $index=lib_index($data['equipment'],trim((string)($_POST['id']??'')));if($index>=0)array_splice($data['equipment'],$index,1);
        save_json($dataFile,$data);flash('Đã xóa thiết bị.','warning');lib_redirect('equipment_catalog');
    }
    if($action==='save_equipment_loan'){
        $ids=array_values((array)($_POST['equipment_id']??[]));$quantities=array_values((array)($_POST['equipment_quantity']??[]));$borrower=trim((string)($_POST['equipment_borrower']??$userName));$batch='eqbatch_'.bin2hex(random_bytes(6));$added=0;
        foreach($ids as $line=>$equipmentId){$equipmentId=trim((string)$equipmentId);if($equipmentId==='')continue;$index=lib_index($data['equipment'],$equipmentId);if($index<0)continue;$qty=max(1,(int)($quantities[$line]??1));$active=0;foreach($data['equipment_loans'] as $loan)if(($loan['equipment_id']??'')===$equipmentId&&empty($loan['returned_at']))$active+=(int)($loan['quantity']??0);$available=max(0,(int)($data['equipment'][$index]['good_quantity']??0)-$active);if($qty>$available){flash('Thiết bị “'.$data['equipment'][$index]['name'].'” chỉ còn '.$available.' sản phẩm có thể mượn.','danger');lib_redirect('equipment_loans');}
        $data['equipment_loans'][]=['id'=>'eql_'.bin2hex(random_bytes(7)),'batch_id'=>$batch,'equipment_id'=>$equipmentId,'equipment_name'=>(string)$data['equipment'][$index]['name'],'equipment_code'=>(string)($data['equipment'][$index]['code']??''),'borrower'=>$borrower,'quantity'=>$qty,'borrowed_at'=>trim((string)($_POST['equipment_borrowed_at']??date('Y-m-d'))),'due_at'=>trim((string)($_POST['equipment_due_at']??'')),'purpose'=>trim((string)($_POST['purpose']??'')),'note'=>trim((string)($_POST['equipment_note']??'')),'returned_at'=>'','return_condition'=>'','created_by'=>$userName,'created_at'=>date('c')];$added++;}
        if(!$added){flash('Vui lòng thêm ít nhất một thiết bị.','danger');lib_redirect('equipment_loans');}save_json($dataFile,$data);flash('Đã lập phiếu mượn '.$added.' loại thiết bị.','success');lib_redirect('equipment_loans');
    }
    if($action==='return_equipment_loan'){
        $index=lib_index($data['equipment_loans'],trim((string)($_POST['id']??'')));if($index>=0){$data['equipment_loans'][$index]['returned_at']=trim((string)($_POST['returned_at']??date('Y-m-d')));$data['equipment_loans'][$index]['return_condition']=trim((string)($_POST['return_condition']??''));$data['equipment_loans'][$index]['updated_at']=date('c');save_json($dataFile,$data);flash('Đã xác nhận trả thiết bị.','success');}lib_redirect('equipment_loans');
    }
    if($action==='delete_equipment_loan'){
        if(!$canEquipmentDelete){http_response_code(403);exit('Không có quyền xóa phiếu thiết bị.');}$index=lib_index($data['equipment_loans'],trim((string)($_POST['id']??'')));if($index>=0)array_splice($data['equipment_loans'],$index,1);save_json($dataFile,$data);flash('Đã xóa phiếu thiết bị.','warning');lib_redirect('equipment_loans');
    }
    if($action==='save_maintenance'){
        $equipmentId=trim((string)($_POST['equipment_id']??''));$index=lib_index($data['equipment'],$equipmentId);if($index<0){flash('Thiết bị không hợp lệ.','danger');lib_redirect('maintenance');}
        $data['maintenance'][]=['id'=>'mt_'.bin2hex(random_bytes(7)),'equipment_id'=>$equipmentId,'equipment_name'=>(string)$data['equipment'][$index]['name'],'type'=>trim((string)($_POST['maintenance_type']??'Bảo dưỡng')),'scheduled_at'=>trim((string)($_POST['scheduled_at']??date('Y-m-d'))),'completed_at'=>trim((string)($_POST['completed_at']??'')),'status'=>trim((string)($_POST['maintenance_status']??'Đã lên lịch')),'cost'=>max(0,(float)($_POST['cost']??0)),'provider'=>trim((string)($_POST['provider']??'')),'note'=>trim((string)($_POST['maintenance_note']??'')),'created_at'=>date('c')];save_json($dataFile,$data);flash('Đã lưu lịch bảo dưỡng/sửa chữa.','success');lib_redirect('maintenance');
    }
    if($action==='delete_maintenance'){
        if(!$canEquipmentDelete){http_response_code(403);exit('Không có quyền xóa lịch bảo dưỡng.');}$index=lib_index($data['maintenance'],trim((string)($_POST['id']??'')));if($index>=0)array_splice($data['maintenance'],$index,1);save_json($dataFile,$data);flash('Đã xóa lịch bảo dưỡng.','warning');lib_redirect('maintenance');
    }
}

$tabAliases=['books'=>'library_books','loans'=>'library_loans','statistics'=>'library_statistics','equipment'=>'equipment_catalog'];$tab=(string)($_GET['tab']??'dashboard');$tab=$tabAliases[$tab]??$tab;$allowedTabs=['dashboard','library_books','library_loans','library_statistics','equipment_catalog','equipment_identity','equipment_loans','maintenance','inventory'];if(!in_array($tab,$allowedTabs,true))$tab='dashboard';
$totalTitles=count($data['books']);$totalBooks=array_sum(array_map(fn($r)=>(int)($r['quantity']??0),$data['books']));
$activeLoans=array_values(array_filter($data['loans'],fn($r)=>empty($r['returned_at'])));
$borrowedBooks=array_sum(array_map(fn($r)=>(int)($r['quantity']??0),$activeLoans));
$overdueCount=count(array_filter($activeLoans,fn($r)=>!empty($r['due_at'])&&$r['due_at']<date('Y-m-d')));
$totalEquipment=array_sum(array_map(fn($r)=>(int)($r['quantity']??0),$data['equipment']));
$goodEquipment=array_sum(array_map(fn($r)=>(int)($r['good_quantity']??0),$data['equipment']));
$activeEquipmentLoans=array_values(array_filter($data['equipment_loans'],fn($r)=>empty($r['returned_at'])));
$maintenanceWarnings=array_values(array_filter($data['maintenance'],fn($r)=>($r['status']??'')!=='Hoàn thành'&&!empty($r['scheduled_at'])&&$r['scheduled_at']<=date('Y-m-d',strtotime('+30 days'))));

$q=trim((string)($_GET['q']??''));$categoryFilter=trim((string)($_GET['category']??''));$borrowerFilter=trim((string)($_GET['borrower_type']??''));$classFilter=trim((string)($_GET['class_name']??''));
$bookList=array_values(array_filter($data['books'],function($row)use($q,$categoryFilter){if($categoryFilter!==''&&($row['category']??'')!==$categoryFilter)return false;if($q!==''&&!str_contains(lib_norm(implode(' ',[$row['title']??'',$row['code']??'',$row['barcode']??'',$row['subject']??'',$row['source']??'',$row['shelf']??''])),lib_norm($q)))return false;return true;}));
$loanList=array_values(array_filter($data['loans'],function($row)use($q,$categoryFilter,$borrowerFilter,$classFilter){if($categoryFilter!==''&&($row['book_category']??'')!==$categoryFilter)return false;if($borrowerFilter!==''&&($row['borrower_type']??'')!==$borrowerFilter)return false;if($classFilter!==''&&($row['class_name']??'')!==$classFilter)return false;if($q!==''&&!str_contains(lib_norm(implode(' ',[$row['borrower_name']??'',$row['book_title']??'',$row['class_name']??''])),lib_norm($q)))return false;return true;}));
usort($loanList,fn($a,$b)=>strcmp((string)($b['borrowed_at']??''),(string)($a['borrowed_at']??'')));

$from=trim((string)($_GET['from']??date('Y-m-01')));$to=trim((string)($_GET['to']??date('Y-m-d')));
$periodLoans=array_values(array_filter($data['loans'],fn($r)=>($r['borrowed_at']??'')>=$from&&($r['borrowed_at']??'')<=$to));
$categoryStats=[];$sourceStats=[];foreach($data['books'] as $book){$cat=(string)($book['category']??'Chưa phân loại');$src=(string)($book['source']??'Chưa rõ nguồn');$categoryStats[$cat]=($categoryStats[$cat]??0)+(int)($book['quantity']??0);$sourceStats[$src]=($sourceStats[$src]??0)+(int)($book['quantity']??0);}
$loanStats=[];foreach($periodLoans as $loan){$cat=(string)($loan['book_category']??'Chưa phân loại');$loanStats[$cat]=($loanStats[$cat]??0)+(int)($loan['quantity']??0);}
$classNames=array_values(array_unique(array_filter(array_map(fn($r)=>(string)($r['class_name']??''),$data['loans']))));sort($classNames,SORT_NATURAL);
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Thư viện – Thiết bị</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<style>:root{--primary:#6246a5;--primary2:#8468c8;--bg:#f3f1f8}body{background:var(--bg);font-family:Segoe UI,system-ui,sans-serif;color:#252332}.topbar{background:linear-gradient(120deg,#443078,#7457b5);color:#fff}.brand{font-size:1.25rem;font-weight:800}.nav-pills{flex-wrap:nowrap;overflow:auto}.nav-pills .nav-link{color:#eee7ff;font-weight:650;white-space:nowrap;border-radius:10px}.nav-pills .nav-link.active,.nav-pills .nav-link:hover{background:#fff;color:var(--primary)}.card{border:0;border-radius:15px;box-shadow:0 5px 18px rgba(55,38,100,.08)}.stat{position:relative;overflow:hidden}.stat strong{font-size:1.9rem;color:var(--primary)}.stat>i{position:absolute;right:14px;bottom:0;font-size:3.3rem;opacity:.1}.table thead th{background:#eae4f6;color:#443078;white-space:nowrap}.overdue{background:#ffe1e3!important;color:#9b1c2c}.badge-soft{background:#ece6f8;color:#563b8c}.modal-header{background:var(--primary);color:#fff}.modal-header .btn-close{filter:invert(1)}.qr-video{width:100%;max-height:360px;background:#111;border-radius:12px}@media print{.no-print,.topbar,.btn,form{display:none!important}body{background:#fff}.card{box-shadow:none;border:1px solid #ddd}.container{max-width:none}}</style></head><body>
<header class="topbar shadow-sm no-print"><div class="container py-3"><div class="d-flex flex-wrap align-items-center justify-content-between gap-3"><a class="brand text-white text-decoration-none" href="<?= BASE_URL ?>thuvien.php"><i class="bi bi-book-half me-2"></i>THƯ VIỆN – THIẾT BỊ</a><ul class="nav nav-pills gap-1"><li><a class="nav-link <?=$tab==='dashboard'?'active':''?>" href="?tab=dashboard"><i class="bi bi-grid"></i> Tổng quan</a></li><li><a class="nav-link <?=$tab==='books'?'active':''?>" href="?tab=books"><i class="bi bi-bookshelf"></i> Thư viện</a></li><li><a class="nav-link <?=$tab==='loans'?'active':''?>" href="?tab=loans"><i class="bi bi-arrow-left-right"></i> Mượn – trả</a></li><li><a class="nav-link <?=$tab==='statistics'?'active':''?>" href="?tab=statistics"><i class="bi bi-bar-chart"></i> Thống kê</a></li><li><a class="nav-link <?=$tab==='equipment'?'active':''?>" href="?tab=equipment"><i class="bi bi-tools"></i> Thiết bị</a></li></ul><a class="btn btn-sm btn-outline-light" href="<?=BASE_URL?>"><i class="bi bi-diagram-3"></i> Hệ sinh thái</a></div></div></header>
<main class="container py-4"><?php show_flash();?>
<?php if($tab==='dashboard'):?>
<div class="mb-4"><h2 class="fw-bold">Tổng quan Thư viện – Thiết bị</h2><p class="text-muted">Số liệu tài sản, sách và tình hình lưu thông hiện tại.</p></div><div class="row g-3 mb-4"><?php foreach([[$totalTitles,'Đầu sách','bi-journals'],[$totalBooks,'Tổng số cuốn','bi-book'],[$borrowedBooks,'Đang được mượn','bi-arrow-up-right-circle'],[$overdueCount,'Phiếu quá hạn','bi-exclamation-triangle'],[$totalEquipment,'Tổng thiết bị','bi-tools'],[$goodEquipment,'Thiết bị sử dụng tốt','bi-check2-circle']] as $stat):?><div class="col-6 col-lg-4"><div class="card stat p-3"><strong><?=$stat[0]?></strong><div class="text-muted"><?=$stat[1]?></div><i class="bi <?=$stat[2]?>"></i></div></div><?php endforeach;?></div>
<div class="row g-3"><div class="col-lg-7"><div class="card"><div class="card-header bg-white fw-bold py-3">Sách đang mượn gần đây</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Người mượn</th><th>Sách</th><th>Hẹn trả</th></tr></thead><tbody><?php foreach(array_slice($activeLoans,0,6) as $loan):$late=!empty($loan['due_at'])&&$loan['due_at']<date('Y-m-d');?><tr class="<?=$late?'overdue':''?>"><td><?=e($loan['borrower_name'])?></td><td><?=e($loan['book_title'])?></td><td><?=lib_date((string)$loan['due_at'])?></td></tr><?php endforeach;if(!$activeLoans):?><tr><td colspan="3" class="text-center text-muted py-4">Không có sách đang mượn.</td></tr><?php endif;?></tbody></table></div></div></div><div class="col-lg-5"><div class="card p-4"><h5 class="fw-bold">Tình trạng kho</h5><div class="d-flex justify-content-between py-2 border-bottom"><span>Sách có sẵn</span><strong><?=max(0,$totalBooks-$borrowedBooks)?></strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span>Sách đang mượn</span><strong><?=$borrowedBooks?></strong></div><div class="d-flex justify-content-between py-2"><span>Thiết bị hỏng/chờ xử lý</span><strong><?=max(0,$totalEquipment-$goodEquipment)?></strong></div></div></div></div>

<?php elseif($tab==='books'):?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h2 class="fw-bold mb-1">Danh mục sách và tài liệu</h2><p class="text-muted mb-0">Quản lý số lượng, mã vạch, nguồn nhập và vị trí kệ.</p></div><?php if($canManage):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#bookModal" onclick="resetBook()"><i class="bi bi-plus-circle"></i> Thêm sách</button><?php endif;?></div>
<form class="card p-3 mb-3 no-print"><input type="hidden" name="tab" value="books"><div class="row g-2"><div class="col-md-7"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Tên sách, mã, mã vạch, nguồn hoặc kệ"></div><div class="col-md-3"><select class="form-select" name="category"><option value="">Tất cả loại</option><?php foreach(['Sách giáo khoa','Sách tham khảo','Sách truyện','Báo','Tạp chí','Tài liệu số'] as $cat):?><option <?=$categoryFilter===$cat?'selected':''?>><?=$cat?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="bi bi-search"></i> Lọc</button></div></div></form>
<div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>STT</th><th>Mã/Mã vạch</th><th>Tên sách</th><th>Phân loại</th><th>Kho</th><th>Ngày nhập</th><th>Nguồn</th><th>Kệ</th><th></th></tr></thead><tbody><?php foreach($bookList as $i=>$book):$available=lib_book_available($book,$data['loans']);?><tr><td><?=$i+1?></td><td><strong><?=e($book['code'])?></strong><br><small><?=e($book['barcode'])?></small></td><td><strong><?=e($book['title'])?></strong><br><small class="text-muted"><?=e(trim(($book['subject']??'').' · Khối '.($book['grade']??''),' ·'))?></small></td><td><span class="badge badge-soft"><?=e($book['category'])?></span></td><td><?=$available?> / <?=e($book['quantity'])?></td><td><?=lib_date((string)$book['import_date'])?></td><td><?=e($book['source'])?></td><td><?=e($book['shelf'])?></td><td class="text-nowrap"><?php if($canManage):?><button class="btn btn-sm btn-outline-primary" data-book="<?=e(base64_encode(json_encode($book,JSON_UNESCAPED_UNICODE)))?>" onclick="editBook(this)"><i class="bi bi-pencil"></i></button><form class="d-inline" method="post" onsubmit="return confirm('Xóa đầu sách này?')"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete_book"><input type="hidden" name="id" value="<?=e($book['id'])?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form><?php endif;?></td></tr><?php endforeach;if(!$bookList):?><tr><td colspan="9" class="text-center text-muted py-4">Chưa có sách.</td></tr><?php endif;?></tbody></table></div></div>
<?php if($canManage):?><div class="modal fade" id="bookModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title" id="bookTitle">Thêm sách</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_book"><input type="hidden" name="id"><div class="row g-3"><div class="col-md-8"><label class="form-label">Tên sách/tài liệu</label><input class="form-control" name="title" required></div><div class="col-md-4"><label class="form-label">Loại</label><select class="form-select" name="category" required><?php foreach(['Sách giáo khoa','Sách tham khảo','Sách truyện','Báo','Tạp chí','Tài liệu số'] as $cat):?><option><?=$cat?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Mã sách</label><input class="form-control" name="code"></div><div class="col-md-4"><label class="form-label">Mã vạch</label><input class="form-control" name="barcode"></div><div class="col-md-4"><label class="form-label">Số lượng</label><input class="form-control" type="number" min="1" name="quantity" value="1" required></div><div class="col-md-4"><label class="form-label">Môn/chủ đề</label><input class="form-control" name="subject"></div><div class="col-md-4"><label class="form-label">Khối</label><input class="form-control" name="grade"></div><div class="col-md-4"><label class="form-label">Vị trí kệ</label><input class="form-control" name="shelf"></div><div class="col-md-4"><label class="form-label">Ngày nhập</label><input class="form-control" type="date" name="import_date" value="<?=date('Y-m-d')?>"></div><div class="col-md-8"><label class="form-label">Nguồn sách</label><input class="form-control" name="source" placeholder="Ngân sách, tài trợ, cấp phát…"></div><div class="col-12"><label class="form-label">Ghi chú</label><textarea class="form-control" name="note"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Lưu sách</button></div></form></div></div></div><?php endif;?>

<?php elseif($tab==='loans'):?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h2 class="fw-bold mb-1">Quản lý mượn – trả sách</h2><p class="text-muted mb-0">Các phiếu quá hạn được đánh dấu màu đỏ.</p></div><?php if($canManage):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loanModal"><i class="bi bi-plus-circle"></i> Mượn sách</button><?php endif;?></div>
<form class="card p-3 mb-3 no-print"><input type="hidden" name="tab" value="loans"><div class="row g-2"><div class="col-lg-4"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Người mượn hoặc tên sách"></div><div class="col-lg-3"><select class="form-select" name="category"><option value="">Tất cả loại sách</option><?php foreach(['Sách giáo khoa','Sách tham khảo','Sách truyện','Báo','Tạp chí','Tài liệu số'] as $cat):?><option <?=$categoryFilter===$cat?'selected':''?>><?=$cat?></option><?php endforeach;?></select></div><div class="col-lg-2"><select class="form-select" name="borrower_type"><option value="">GV và học sinh</option><option value="teacher" <?=$borrowerFilter==='teacher'?'selected':''?>>Giáo viên</option><option value="student" <?=$borrowerFilter==='student'?'selected':''?>>Học sinh</option><option value="manual" <?=$borrowerFilter==='manual'?'selected':''?>>Nhập tay</option></select></div><div class="col-lg-2"><select class="form-select" name="class_name"><option value="">Tất cả lớp</option><?php foreach($classNames as $name):?><option <?=$classFilter===$name?'selected':''?>><?=e($name)?></option><?php endforeach;?></select></div><div class="col-lg-1"><button class="btn btn-primary w-100"><i class="bi bi-filter"></i></button></div></div></form>
<div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Người mượn</th><th>Đối tượng/Lớp</th><th>Sách</th><th>SL</th><th>Ngày mượn</th><th>Hẹn trả</th><th>Ngày trả</th><th>Tình trạng</th><th></th></tr></thead><tbody><?php foreach($loanList as $loan):$late=empty($loan['returned_at'])&&!empty($loan['due_at'])&&$loan['due_at']<date('Y-m-d');?><tr class="<?=$late?'overdue':''?>"><td><strong><?=e($loan['borrower_name'])?></strong></td><td><?=['student'=>'Học sinh','teacher'=>'Giáo viên','manual'=>'Nhập tay'][$loan['borrower_type']??'manual']?><?=!empty($loan['class_name'])?'<br><small>'.e($loan['class_name']).'</small>':''?></td><td><?=e($loan['book_title'])?><br><small><?=e($loan['book_category'])?></small></td><td><?=e($loan['quantity'])?></td><td><?=lib_date((string)$loan['borrowed_at'])?></td><td><?=lib_date((string)$loan['due_at'])?><?=$late?'<br><strong>QUÁ HẠN</strong>':''?></td><td><?=lib_date((string)$loan['returned_at'])?></td><td><small>Mượn: <?=e($loan['condition_out'])?><br>Trả: <?=e($loan['return_condition'])?></small></td><td class="text-nowrap"><?php if($canManage&&empty($loan['returned_at'])):?><button class="btn btn-sm btn-success" data-loan="<?=e(base64_encode(json_encode($loan,JSON_UNESCAPED_UNICODE)))?>" onclick="openReturn(this)"><i class="bi bi-box-arrow-in-left"></i> Trả</button><?php endif;if($canManage):?><form class="d-inline" method="post" onsubmit="return confirm('Xóa phiếu này?')"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete_loan"><input type="hidden" name="id" value="<?=e($loan['id'])?>"><input type="hidden" name="tab" value="loans"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form><?php endif;?></td></tr><?php endforeach;if(!$loanList):?><tr><td colspan="9" class="text-center text-muted py-4">Chưa có phiếu mượn.</td></tr><?php endif;?></tbody></table></div></div>
<?php if($canManage):?><div class="modal fade" id="loanModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title">Lập phiếu mượn sách</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_loan"><input type="hidden" name="borrower_id" id="borrowerId"><input type="hidden" name="borrower_type" id="borrowerType" value="manual"><input type="hidden" name="class_name" id="borrowerClass"><div class="row g-3"><div class="col-md-8"><label class="form-label">Người mượn</label><input class="form-control" name="borrower_name" id="borrowerName" list="borrowerList" placeholder="Gõ tên, mã học sinh/GV hoặc quét QR" required><datalist id="borrowerList"><?php foreach($students as $s):?><option value="<?=e($s['name']??'')?>" data-id="<?=e($s['id']??'')?>" data-code="<?=e($s['code']??'')?>" data-type="student" data-class="<?=e($classMap[(string)($s['class_id']??'')]??'')?>"><?=e(($s['code']??'').' · '.($classMap[(string)($s['class_id']??'')]??''))?></option><?php endforeach;foreach($teachers as $t):?><option value="<?=e($t['name']??'')?>" data-id="<?=e($t['id']??'')?>" data-code="<?=e($t['code']??'')?>" data-type="teacher" data-class="">Giáo viên · <?=e($t['code']??'')?></option><?php endforeach;?></datalist></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-outline-primary w-100" type="button" onclick="openQr()"><i class="bi bi-qr-code-scan"></i> Quét QR thẻ</button></div><div class="col-md-8"><label class="form-label">Sách</label><select class="form-select" name="book_id" required><option value="">Chọn sách</option><?php foreach($data['books'] as $book):$av=lib_book_available($book,$data['loans']);?><option value="<?=e($book['id'])?>" <?=$av<1?'disabled':''?>><?=e($book['title'])?> — <?=e($book['category'])?> (còn <?=$av?>)</option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Số lượng</label><input class="form-control" type="number" min="1" name="quantity" value="1"></div><div class="col-md-4"><label class="form-label">Ngày mượn</label><input class="form-control" type="date" name="borrowed_at" value="<?=date('Y-m-d')?>"></div><div class="col-md-4"><label class="form-label">Ngày hẹn trả</label><input class="form-control" type="date" name="due_at" value="<?=date('Y-m-d',strtotime('+14 days'))?>"></div><div class="col-md-4"><label class="form-label">Tình trạng sách</label><select class="form-select" name="condition_out"><option>Tốt</option><option>Cũ</option><option>Rách nhẹ</option><option>Khác</option></select></div><div class="col-12"><label class="form-label">Ghi chú</label><textarea class="form-control" name="note"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Lưu phiếu mượn</button></div></form></div></div></div>
<div class="modal fade" id="returnModal"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title">Xác nhận trả sách</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="return_loan"><input type="hidden" name="id" id="returnId"><p id="returnInfo" class="fw-semibold"></p><label class="form-label">Ngày trả</label><input class="form-control mb-3" type="date" name="returned_at" value="<?=date('Y-m-d')?>"><label class="form-label">Tình trạng sách khi trả</label><select class="form-select mb-3" name="return_condition"><option>Tốt</option><option>Cũ</option><option>Rách nhẹ</option><option>Hư hỏng</option><option>Mất sách</option></select><label class="form-label">Ghi chú</label><textarea class="form-control" name="return_note"></textarea></div><div class="modal-footer"><button class="btn btn-success">Lưu trả sách</button></div></form></div></div></div>
<div class="modal fade" id="qrModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Quét QR thẻ học sinh</h5><button class="btn-close" type="button" data-bs-dismiss="modal" onclick="stopQr()"></button></div><div class="modal-body"><video id="qrVideo" class="qr-video" playsinline></video><div class="small text-muted mt-2" id="qrMessage">Đưa mã QR trên thẻ vào giữa camera.</div></div></div></div></div><?php endif;?>

<?php elseif($tab==='statistics'):?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="fw-bold mb-1">Thống kê thư viện</h2><p class="text-muted mb-0">Số lượng kho, nguồn sách và mượn–trả theo giai đoạn.</p></div><button class="btn btn-outline-primary no-print" onclick="window.print()"><i class="bi bi-printer"></i> In biên bản</button></div><form class="card p-3 mb-3 no-print"><input type="hidden" name="tab" value="statistics"><div class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">Từ ngày</label><input class="form-control" type="date" name="from" value="<?=e($from)?>"></div><div class="col-md-4"><label class="form-label">Đến ngày</label><input class="form-control" type="date" name="to" value="<?=e($to)?>"></div><div class="col-md-4"><button class="btn btn-primary w-100">Xem thống kê</button></div></div></form>
<div class="text-center mb-4 d-none d-print-block"><h3>BIÊN BẢN THỐNG KÊ MƯỢN SÁCH GIÁO KHOA</h3><p>Từ ngày <?=lib_date($from)?> đến ngày <?=lib_date($to)?></p></div><div class="row g-3"><div class="col-lg-6"><div class="card p-3"><h5 class="fw-bold">Số lượng sách hiện có theo loại</h5><table class="table"><thead><tr><th>Loại</th><th class="text-end">Số lượng</th></tr></thead><tbody><?php foreach($categoryStats as $name=>$count):?><tr><td><?=e($name)?></td><td class="text-end"><?=$count?></td></tr><?php endforeach;?></tbody></table></div></div><div class="col-lg-6"><div class="card p-3"><h5 class="fw-bold">Lượt nhận sách theo nguồn</h5><table class="table"><thead><tr><th>Nguồn</th><th class="text-end">Số lượng</th></tr></thead><tbody><?php foreach($sourceStats as $name=>$count):?><tr><td><?=e($name)?></td><td class="text-end"><?=$count?></td></tr><?php endforeach;?></tbody></table></div></div><div class="col-12"><div class="card p-3"><h5 class="fw-bold">Mượn sách từ <?=lib_date($from)?> đến <?=lib_date($to)?></h5><div class="row g-3"><?php foreach($loanStats as $name=>$count):?><div class="col-md-4"><div class="border rounded p-3"><strong class="fs-4 text-primary"><?=$count?></strong><div><?=e($name)?></div></div></div><?php endforeach;if(!$loanStats):?><p class="text-muted">Không có lượt mượn trong giai đoạn này.</p><?php endif;?></div><hr><h6>Chi tiết sách giáo khoa</h6><div class="table-responsive"><table class="table"><thead><tr><th>Người mượn</th><th>Lớp</th><th>Sách</th><th>SL</th><th>Mượn</th><th>Trả</th></tr></thead><tbody><?php foreach($periodLoans as $loan): if(($loan['book_category']??'')==='Sách giáo khoa'): ?><tr><td><?=e($loan['borrower_name'])?></td><td><?=e($loan['class_name'])?></td><td><?=e($loan['book_title'])?></td><td><?=e($loan['quantity'])?></td><td><?=lib_date((string)$loan['borrowed_at'])?></td><td><?=lib_date((string)$loan['returned_at'])?></td></tr><?php endif; endforeach;?></tbody></table></div><div class="row mt-5 d-none d-print-flex"><div class="col-6 text-center"><strong>NGƯỜI LẬP BIÊN BẢN</strong><div class="mt-5"><?=$userName?></div></div><div class="col-6 text-center"><strong>XÁC NHẬN CỦA NHÀ TRƯỜNG</strong></div></div></div></div></div>

<?php else:?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h2 class="fw-bold mb-1">Danh mục thiết bị</h2><p class="text-muted mb-0">Theo dõi số lượng, tình trạng và vị trí thiết bị.</p></div><?php if($canManage):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#equipmentModal" onclick="resetEquipment()"><i class="bi bi-plus-circle"></i> Thêm thiết bị</button><?php endif;?></div><div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Mã</th><th>Tên thiết bị</th><th>Loại</th><th>Tổng</th><th>Sử dụng tốt</th><th>Hỏng</th><th>Vị trí</th><th>Nguồn</th><th></th></tr></thead><tbody><?php foreach($data['equipment'] as $eq):?><tr><td><?=e($eq['code'])?></td><td><strong><?=e($eq['name'])?></strong></td><td><?=e($eq['category'])?></td><td><?=e($eq['quantity'])?></td><td><?=e($eq['good_quantity'])?></td><td><?=max(0,(int)$eq['quantity']-(int)$eq['good_quantity'])?></td><td><?=e($eq['location'])?></td><td><?=e($eq['source'])?></td><td><?php if($canManage):?><button class="btn btn-sm btn-outline-primary" data-equipment="<?=e(base64_encode(json_encode($eq,JSON_UNESCAPED_UNICODE)))?>" onclick="editEquipment(this)"><i class="bi bi-pencil"></i></button><form class="d-inline" method="post" onsubmit="return confirm('Xóa thiết bị này?')"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete_equipment"><input type="hidden" name="id" value="<?=e($eq['id'])?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form><?php endif;?></td></tr><?php endforeach;if(!$data['equipment']):?><tr><td colspan="9" class="text-center text-muted py-4">Chưa có thiết bị.</td></tr><?php endif;?></tbody></table></div></div>
<?php if($canManage):?><div class="modal fade" id="equipmentModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title" id="equipmentTitle">Thêm thiết bị</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_equipment"><input type="hidden" name="id"><div class="row g-3"><div class="col-md-8"><label class="form-label">Tên thiết bị</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Mã thiết bị</label><input class="form-control" name="code"></div><div class="col-md-4"><label class="form-label">Loại</label><input class="form-control" name="category"></div><div class="col-md-4"><label class="form-label">Tổng số</label><input class="form-control" type="number" min="0" name="quantity"></div><div class="col-md-4"><label class="form-label">Sử dụng tốt</label><input class="form-control" type="number" min="0" name="good_quantity"></div><div class="col-md-4"><label class="form-label">Vị trí</label><input class="form-control" name="location"></div><div class="col-md-4"><label class="form-label">Ngày nhập</label><input class="form-control" type="date" name="import_date" value="<?=date('Y-m-d')?>"></div><div class="col-md-4"><label class="form-label">Nguồn</label><input class="form-control" name="source"></div><div class="col-12"><label class="form-label">Ghi chú</label><textarea class="form-control" name="note"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Lưu thiết bị</button></div></form></div></div></div><?php endif;?>
<?php endif;?></main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>
function decodeData(value){return JSON.parse(decodeURIComponent(escape(atob(value||''))))}
function fillForm(form,row){Object.keys(row).forEach(function(key){var input=form.querySelector('[name="'+key+'"]');if(input)input.value=row[key]??''})}
function resetBook(){var f=document.querySelector('#bookModal form');f.reset();f.querySelector('[name="id"]').value='';f.querySelector('[name="import_date"]').value='<?=date('Y-m-d')?>';document.getElementById('bookTitle').textContent='Thêm sách'}
function editBook(button){var row=decodeData(button.dataset.book),f=document.querySelector('#bookModal form');fillForm(f,row);document.getElementById('bookTitle').textContent='Sửa sách';bootstrap.Modal.getOrCreateInstance(document.getElementById('bookModal')).show()}
function resetEquipment(){var f=document.querySelector('#equipmentModal form');f.reset();f.querySelector('[name="id"]').value='';f.querySelector('[name="import_date"]').value='<?=date('Y-m-d')?>';document.getElementById('equipmentTitle').textContent='Thêm thiết bị'}
function editEquipment(button){var row=decodeData(button.dataset.equipment),f=document.querySelector('#equipmentModal form');fillForm(f,row);document.getElementById('equipmentTitle').textContent='Sửa thiết bị';bootstrap.Modal.getOrCreateInstance(document.getElementById('equipmentModal')).show()}
function openReturn(button){var row=decodeData(button.dataset.loan);document.getElementById('returnId').value=row.id;document.getElementById('returnInfo').textContent=row.borrower_name+' — '+row.book_title+' ('+row.quantity+' cuốn)';bootstrap.Modal.getOrCreateInstance(document.getElementById('returnModal')).show()}
var borrower=document.getElementById('borrowerName');if(borrower)borrower.addEventListener('change',function(){var options=Array.from(document.querySelectorAll('#borrowerList option')),needle=this.value.trim().toLowerCase(),match=options.find(function(o){return o.value.trim().toLowerCase()===needle||o.dataset.code.toLowerCase()===needle});document.getElementById('borrowerId').value=match?match.dataset.id:'';document.getElementById('borrowerType').value=match?match.dataset.type:'manual';document.getElementById('borrowerClass').value=match?match.dataset.class:''});
var qrStream=null,qrTimer=null;
function resolveQr(text){var raw=String(text||''),code=raw;try{var u=new URL(raw);code=u.searchParams.get('code')||u.searchParams.get('id')||u.pathname.split('/').filter(Boolean).pop()||raw}catch(e){}var options=Array.from(document.querySelectorAll('#borrowerList option')),needle=String(code).trim().toLowerCase(),match=options.find(function(o){return o.dataset.code.toLowerCase()===needle||o.dataset.id.toLowerCase()===needle});if(!match)return false;borrower.value=match.value;borrower.dispatchEvent(new Event('change'));stopQr();bootstrap.Modal.getInstance(document.getElementById('qrModal')).hide();return true}
async function openQr(){var modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('qrModal'));modal.show();var msg=document.getElementById('qrMessage');if(!('BarcodeDetector'in window)){msg.textContent='Trình duyệt chưa hỗ trợ quét QR trực tiếp. Hãy nhập mã học sinh vào ô Người mượn.';return}try{qrStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});var video=document.getElementById('qrVideo');video.srcObject=qrStream;await video.play();var detector=new BarcodeDetector({formats:['qr_code']});qrTimer=setInterval(async function(){try{var codes=await detector.detect(video);if(codes.length&&!resolveQr(codes[0].rawValue))msg.textContent='Đã đọc QR nhưng chưa tìm thấy học sinh trong CSDL.'}catch(e){}},500)}catch(e){msg.textContent='Không mở được camera. Vui lòng cấp quyền camera hoặc nhập mã thủ công.'}}
function stopQr(){if(qrTimer)clearInterval(qrTimer);qrTimer=null;if(qrStream)qrStream.getTracks().forEach(function(t){t.stop()});qrStream=null}
</script></body></html>