const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');let values=[],seed=987654321;
const env={crypto:{getRandomValues(a){a[0]=values.length?values.shift():(seed=(Math.imul(seed,1664525)+1013904223)>>>0);}},Uint32Array};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/cds-ball-engine.js'),'utf8'),env);const e=env.CDSBallEngine;
values=[4294967295,6];assert.equal(e.randomIndex(10),6);assert.throws(()=>e.randomIndex(0));assert.throws(()=>e.plan([]));
const students=Array.from({length:30},(_,i)=>({id:'s'+i,name:i<2?'Nguyễn Văn An':'Học sinh '+i})),selected=new Set(students.map(s=>s.id)),called=new Set(['s0']);assert.equal(e.pool(students,selected,called,true).length,29);assert(e.pool(students,selected,called,true).some(s=>s.id==='s1'));assert.equal(e.pool(students,selected,called,false).length,30);selected.delete('s3');assert(!e.pool(students,selected,called,false).some(s=>s.id==='s3'));
assert.equal(e.pegs.length,113);assert.equal(e.ballRadius,9);assert.equal(e.pegRadius,6);
function check(p){assert.equal(p.candidates[p.slot].id,p.winner.id);assert.equal(new Set(p.candidates.map(s=>s.id)).size,p.candidates.length);const width=780/p.candidates.length,end=e.position(p,1);assert.equal(end.y,520);assert(end.x>=60+p.slot*width+12&&end.x<=60+(p.slot+1)*width-12);assert.equal(Math.min(p.candidates.length-1,Math.floor((end.x-60)/width)),p.slot);assert(end.index>=3,'Must hit several pegs');assert.equal(end.hidden,false);let prior=p.frames[0];for(const f of p.frames){assert(Number.isFinite(f.x)&&Number.isFinite(f.y));assert(f.x>=69&&f.x<=831&&f.y>=30&&f.y<=520);assert(Math.hypot(f.x-prior.x,f.y-prior.y)<12,'No teleport between physics frames');for(const peg of e.pegs)assert(Math.hypot(f.x-peg.x,f.y-peg.y)>=e.ballRadius+e.pegRadius-.001,'Ball penetrates a peg');prior=f;}const mid=e.position(p,.54321);assert(Number.isFinite(mid.x)&&Number.isFinite(mid.y));assert.equal(e.position(p,-1).y,p.frames[0].y);assert.equal(e.position(p,2).y,520);}
for(let i=0;i<students.length;i++){values=[i];const p=e.plan(students);assert.equal(p.winner.id,'s'+i);assert.equal(p.candidates.length,8);check(p);const before=JSON.stringify(p.candidates);const frame=e.namesFrame(students,p.candidates.length);assert.equal(new Set(frame.map(s=>s.id)).size,p.candidates.length);assert.equal(JSON.stringify(p.candidates),before);}
for(const limit of [1,2,4,8])for(let i=0;i<50;i++)check(e.plan(students,limit));const one=e.plan([students[0]]);assert.equal(one.slot,0);assert.equal(one.candidates.length,1);check(one);assert.throws(()=>e.plan(students,9));assert.equal(students.length,30);
console.log('PASS: uniform student selection, identity/exclusions, 231 peg simulations, no penetration or teleport, 1/2/4/8 bins and exact result-bin match');
