// node tests/cds_clock_timer_test.cjs — deterministic sound/timer regression checks.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
let now=Date.parse('2026-10-06T12:00:00Z'),notes=0;const gains=[],nodes={},classes=new Set();
function node(id){return nodes[id]||(nodes[id]={value:'',checked:false,style:{},dataset:{},textContent:'',addEventListener(type,fn){this[type]=fn;},setAttribute(){},set innerHTML(html){for(const m of html.matchAll(/id="([^"]+)"[^>]*>/g))node(m[1]).value=/value="([^"]*)"/.exec(m[0])?.[1]||'';}});}
class Clock extends Date{static now(){return now;}}
class Audio{constructor(){this.state='running';this.currentTime=0;}resume(){return Promise.resolve();}createOscillator(){return {frequency:{},connect(){},start(){notes++;},stop(){},disconnect(){}};}createGain(){return {gain:{setValueAtTime(v){gains.push(v);},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}}
node('soundVolume').value='55';node('soundMode').value='chime';node('warningSound').checked=true;
const env={Date:Clock,Intl,performance:{now:()=>now},setInterval(){},setTimeout(){},location:{hash:''},window:{AudioContext:Audio,addEventListener(){}},document:{getElementById:node,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},body:{dataset:{},classList:{add:c=>classes.add(c),remove:c=>classes.delete(c),toggle(c,on){on?classes.add(c):classes.delete(c);}}}}};
const source=fs.readFileSync(path.join(__dirname,'../assets/cds-clock.js'),'utf8').replace('})();','window.test={render,tick,beep,initSound};})();');vm.runInNewContext(source,env);const t=env.window.test;
function start(seconds){t.render('timer');node('minutes').value='0';node('seconds').value=String(seconds);node('setTimer').click();node('startTimer').click();}
function advance(ms){now+=ms;t.tick();}
start(20);advance(4000);assert.equal(notes,0);assert(!classes.has('timer-urgent'));advance(1000);assert.equal(notes,2);assert(classes.has('timer-urgent'));t.tick();t.tick();assert.equal(notes,2);advance(1000);assert.equal(notes,4);node('pauseTimer').click();advance(5000);assert.equal(notes,4);assert(!classes.has('timer-urgent'));node('startTimer').click();let baseline=notes;t.render('clock'); // Warning continues while a different panel is selected.
advance(1000);assert.equal(notes,baseline+2);node('warningSound').checked=false;baseline=notes;advance(1000);assert.equal(notes,baseline);advance(20000);assert.equal(notes,baseline+3);assert.equal(node('notification').hidden,false);assert(classes.has('celebrating'));const finishGain=gains.at(-1);assert(finishGain>.55*.27);baseline=notes;advance(1900);assert.equal(notes,baseline+3);node('stopSound').click();assert.equal(node('notification').hidden,true);assert(!classes.has('celebrating'));baseline=notes;advance(2000);assert.equal(notes,baseline);
node('warningSound').checked=true;node('soundMuted').checked=true;start(5);advance(6000);assert.equal(notes,baseline);assert.equal(node('notification').hidden,false);node('stopSound').click();node('soundMuted').checked=false;node('soundVolume').value='0';start(5);advance(6000);assert.equal(notes,baseline);node('stopSound').click();node('soundVolume').value='55';start(5);assert.equal(notes,baseline+2);node('resetTimer').click();assert(!classes.has('timer-urgent'));baseline=notes;advance(6000);assert.equal(notes,baseline);
console.log('PASS: warning at 15s, no duplicate notes, pause/resume, opt-out, louder repeating expiry, mute/zero volume, short timer and reset');
