<?php
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/lesson_book_store.php';
require_login();
$week=lb_week((string)($_GET['week']??''));if(!$week){http_response_code(404);exit('Không tìm thấy tuần học.');}
$class=trim((string)($_GET['class']??''));
if($class===''){http_response_code(422);exit('Hãy chọn một lớp trước khi xuất Sổ đầu bài.');}
$allSlots=lb_slots($week);$canSeeClass=false;foreach($allSlots as$r)if(($r['class']??'')===$class&&lb_can_view($r)){$canSeeClass=true;break;}
if(!$canSeeClass){http_response_code(403);exit('Tài khoản không được xem hoặc xuất Sổ đầu bài của lớp này.');}
$rows=array_values(array_filter($allSlots,fn($r)=>lb_can_view($r)&&($r['class']??'')===$class));
function lb_x($v){return htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');}
$title='SỔ ĐẦU BÀI - LỚP '.$class.' - '.($week['label']??'');
$sheetName=trim((string)preg_replace('/[\\\/?*\[\]:]+/u',' ','Lớp '.$class));if(function_exists('mb_substr'))$sheetName=mb_substr($sheetName,0,31,'UTF-8');else$sheetName=substr($sheetName,0,31);if($sheetName==='')$sheetName='So dau bai';
$xml='<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?>';
$xml.='<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">';
$xml.='<Styles><Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Center"/><Font ss:FontName="Times New Roman" ss:Size="11"/></Style><Style ss:ID="title"><Alignment ss:Horizontal="Center"/><Font ss:FontName="Times New Roman" ss:Size="16" ss:Bold="1"/></Style><Style ss:ID="head"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="Times New Roman" ss:Size="10" ss:Bold="1"/><Interior ss:Color="#D9EAF7" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/></Borders></Style><Style ss:ID="cell"><Alignment ss:Vertical="Center" ss:WrapText="1"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/></Borders></Style><Style ss:ID="center"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/></Borders></Style></Styles>';
$xml.='<Worksheet ss:Name="'.lb_x($sheetName).'"><Table><Column ss:Width="70"/><Column ss:Width="45"/><Column ss:Width="44"/><Column ss:Width="50"/><Column ss:Width="75"/><Column ss:Width="46"/><Column ss:Width="150"/><Column ss:Width="115"/><Column ss:Width="125"/><Column ss:Width="65"/><Column ss:Width="58"/><Column ss:Width="85"/><Column ss:Width="78"/>';
$xml.='<Row ss:Height="28"><Cell ss:MergeAcross="12" ss:StyleID="title"><Data ss:Type="String">'.lb_x($title).'</Data></Cell></Row><Row><Cell ss:MergeAcross="12"><Data ss:Type="String">Từ ngày '.date('d/m/Y',strtotime($week['start'])).' đến ngày '.date('d/m/Y',strtotime($week['end'])).'</Data></Cell></Row>';
$heads=['Thứ, ngày/tháng','Buổi','Tiết','Lớp','Môn học','Tiết PPCT','Đầu bài / nội dung công việc','Học sinh vắng trong tiết','Nhận xét của giáo viên','Xếp loại tiết học','Trạng thái','Giáo viên thực tế','Ký tên'];$xml.='<Row ss:Height="35">';foreach($heads as$h)$xml.='<Cell ss:StyleID="head"><Data ss:Type="String">'.lb_x($h).'</Data></Cell>';$xml.='</Row>';
$days=[1=>'Thứ Hai',2=>'Thứ Ba',3=>'Thứ Tư',4=>'Thứ Năm',5=>'Thứ Sáu',6=>'Thứ Bảy',7=>'Chủ nhật'];$labels=['pending'=>'Chưa hoàn thành','taught'=>'Đã dạy','substitute'=>'Dạy thay','makeup'=>'Dạy bù','online'=>'Trực tuyến','holiday'=>'Nghỉ lễ','teacher_absent'=>'GV nghỉ','class_absent'=>'Lớp nghỉ','postponed'=>'Hoãn','cancelled'=>'Hủy'];
foreach($rows as$r){$vals=[($days[(int)date('N',strtotime($r['date']))]??'').' '.date('d/m/Y',strtotime($r['date'])),$r['session'],$r['period'],$r['class'],$r['subject'],$r['ppct_period']??'',$r['lesson_title']??'',$r['absent_names']??'',$r['teacher_comment']??'',$r['rating']??'',$labels[$r['status']??'pending']??($r['status']??''),$r['actual_teacher']??'',!empty($r['signed_at'])?('Đã ký - '.($r['signed_by']??'')):''];$xml.='<Row ss:Height="42">';foreach($vals as$i=>$v)$xml.='<Cell ss:StyleID="'.(in_array($i,[0,1,2,3,5,9,10,12],true)?'center':'cell').'"><Data ss:Type="String">'.lb_x($v).'</Data></Cell>';$xml.='</Row>';}
$xml.='</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><PageSetup><Layout x:Orientation="Landscape"/><Header x:Margin="0.2"/><Footer x:Margin="0.2"/><PageMargins x:Bottom="0.45" x:Left="0.35" x:Right="0.35" x:Top="0.45"/></PageSetup><FitToPage/><Print><FitWidth>1</FitWidth><FitHeight>0</FitHeight><PaperSizeIndex>8</PaperSizeIndex><ValidPrinterInfo/></Print><FreezePanes/><FrozenNoSplit/><SplitHorizontal>3</SplitHorizontal><TopRowBottomPane>3</TopRowBottomPane></WorksheetOptions></Worksheet></Workbook>';
$filename='So-dau-bai-Lop-'.preg_replace('/[^A-Za-z0-9_-]+/','-',$class.'-'.($week['label']??'tuan')).'.xls';
if(!empty($_GET['save_drive'])){$res=cds_drive_save_generated($xml,$filename,'application/vnd.ms-excel','education_plans');flash(!empty($res['ok'])?'Đã lưu bản Excel lên Google Drive.':('Không lưu được Drive: '.($res['message']??'Lỗi không xác định')),!empty($res['ok'])?'success':'danger');header('Location: '.BASE_URL.'sodaubai.php?tab=week&week='.urlencode((string)$week['key']).'&class='.urlencode($class));exit;}
header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Cache-Control: no-store');echo $xml;
