<?php
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/lesson_book_store.php';
require_login();
$scope=in_array((string)($_GET['scope']??''),['class','teacher'],true)?(string)$_GET['scope']:'class';
$target=trim((string)($_GET[$scope]??''));
if($target===''){http_response_code(422);exit($scope==='class'?'Chưa chọn lớp cần xuất.':'Chưa chọn giáo viên cần xuất.');}
$paper=in_array((string)($_GET['paper']??''),['a4_pair','a3'],true)?(string)$_GET['paper']:'a4_pair';
$session=(string)($_GET['session']??'all');$onlyFilled=!empty($_GET['only_filled']);$includeCover=!empty($_GET['include_cover']);
$weeks=lb_weeks();$from=(string)($_GET['from_week']??'');$to=(string)($_GET['to_week']??$from);$selected=[];$active=false;
foreach($weeks as$w){if((string)$w['key']===$from)$active=true;if($active)$selected[]=$w;if((string)$w['key']===$to&&$active)break;}
if(!$selected&&($w=lb_week($from)))$selected=[$w];if(!$selected){http_response_code(422);exit('Không tìm thấy tuần học cần xuất.');}
$bundles=[];$allRows=[];
foreach($selected as$w){$rows=array_values(array_filter(lb_slots($w),function($r)use($scope,$target,$session,$onlyFilled){if(!lb_can_view($r))return false;if($scope==='class'&&!lb_same($target,(string)($r['class']??'')))return false;if($scope==='teacher'&&!lb_same($target,(string)($r['scheduled_teacher']??''))&&!lb_same($target,(string)($r['actual_teacher']??'')))return false;$s=lb_norm((string)($r['session']??''));if($session==='morning'&&strpos($s,'sang')===false)return false;if($session==='afternoon'&&strpos($s,'chieu')===false)return false;if($onlyFilled&&trim((string)($r['lesson_title']??''))===''&&trim((string)($r['teacher_comment']??''))===''&&(string)($r['status']??'pending')==='pending')return false;return true;}));
 foreach(['Sáng','Chiều']as$part){$partRows=array_values(array_filter($rows,fn($r)=>lb_same($part,(string)($r['session']??''))));if($partRows)$bundles[]=['week'=>$w,'session'=>$part,'rows'=>$partRows];}$allRows=array_merge($allRows,$rows);
}
$validation=lb_print_validation($allRows);$settings=lb_settings();$ps=$settings['print'];
function lbp_sig(array $r): string {$p=(string)($r['signature_path']??'');if($p===''||!is_file($p))return'';$raw=@file_get_contents($p);return$raw===false?'':'data:image/png;base64,'.base64_encode($raw);}
function lbp_day(array $r): string {$n=(int)date('N',strtotime((string)$r['date']))+1;return'Thứ '.$n.'<br>'.date('d/m/Y',strtotime((string)$r['date']));}
function lbp_scores(array $r): array {$rating=(string)($r['rating']??'');$sum=['Tốt'=>10,'Khá'=>8,'Trung bình'=>6,'Yếu'=>4][$rating]??'';return[$sum,$rating];}
function lbp_group_counts(array $rows): array {$c=[];foreach($rows as$r){$k=(string)$r['date'];$c[$k]=($c[$k]??0)+1;}return$c;}
$title=$scope==='class'?'LỚP '.$target:'GIÁO VIÊN '.$target;
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sổ đầu bài - <?=e($target)?></title><style>
@page{size:<?=$paper==='a3'?'A3 landscape':'A4 portrait'?>;margin:0}
*{box-sizing:border-box}body{font-family:"Times New Roman",serif;margin:0;background:#edf1f5;color:#111}.toolbar{position:sticky;top:0;z-index:9;background:#fff;border-bottom:1px solid #ccd5df;padding:12px 18px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.toolbar button,.toolbar a{font:600 15px Arial;padding:9px 15px;border-radius:7px;border:0;text-decoration:none}.primary{background:#1769aa;color:#fff}.secondary{background:#e6edf4;color:#17324d}.check{font:14px Arial;margin-left:auto;display:flex;gap:12px;flex-wrap:wrap}.ok{color:#16733a}.warn{color:#a02626}.page{background:#fff;width:210mm;min-height:297mm;margin:12px auto;padding:10mm 9mm;box-shadow:0 2px 14px #0002;page-break-after:always;overflow:hidden}.page.even.mirror{padding-left:14mm;padding-right:7mm}.page.odd.mirror{padding-left:7mm;padding-right:14mm}.cover{display:flex;flex-direction:column;justify-content:center;text-align:center}.cover h1{font-size:25pt;margin:20mm 0 8mm}.head{text-align:center;font-weight:bold;margin-bottom:4mm}.head .week{font-size:15pt}.spread-note{font-size:9pt;font-style:italic;text-align:right}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:7.5pt}th,td{border:1px solid #111;padding:1.1mm .8mm;text-align:center;vertical-align:middle;height:7.2mm}th{font-weight:bold}.left .c-day{width:16%}.left .c-period{width:7%}.left .c-subject{width:14%}.left .c-ppct{width:9%}.left .c-absent{width:18%}.left .c-title{width:36%}.right .c-comment{width:43%}.right .score{width:6%}.right .c-rating{width:10%}.right .c-sign{width:17%}.text-left{text-align:left}.sig{max-width:28mm;max-height:7mm;object-fit:contain}.footer-box{margin-top:4mm;border:1px solid #111;min-height:23mm;padding:3mm;font-size:9pt}.signatures{display:flex;justify-content:space-around;text-align:center;margin-top:7mm;font-weight:bold}.a3{width:420mm;min-height:297mm}.a3 table{font-size:7pt}.a3 th,.a3 td{height:6.5mm}@page{size:A4 portrait;margin:0}@media print{body{background:#fff}.toolbar{display:none}.page{margin:0;box-shadow:none}.a3{width:420mm;min-height:297mm}@page{size:A4 portrait;margin:0}body.a3-mode .page{@page{size:A3 landscape}}}
</style></head><body class="<?=$paper==='a3'?'a3-mode':''?>"><div class="toolbar"><a class="secondary" href="<?=BASE_URL?>sodaubai.php?tab=print">← Cài đặt in</a><button class="primary" onclick="window.print()">In / Lưu PDF</button><span class="check"><b>Kiểm tra:</b><span class="ok"><?=$validation['filled']?> tiết có dữ liệu</span><span class="<?=$validation['missing_content']?'warn':'ok'?>"><?=$validation['missing_content']?> thiếu đầu bài</span><span class="<?=$validation['pending']?'warn':'ok'?>"><?=$validation['pending']?> chưa hoàn thành</span><span class="<?=$validation['missing_signature']?'warn':'ok'?>"><?=$validation['missing_signature']?> chưa ký</span></span></div>
<?php $pageNo=0;if($includeCover):$pageNo++;?><section class="page cover <?=!empty($ps['mirrored_margins'])?'mirror':''?>"><div>TRƯỜNG <?=e(defined('SCHOOL_NAME')?SCHOOL_NAME:'')?></div><h1>SỔ GHI ĐẦU BÀI</h1><h2><?=e($title)?></h2><p>Từ <?=date('d/m/Y',strtotime($selected[0]['start']))?> đến <?=date('d/m/Y',strtotime($selected[count($selected)-1]['end']))?></p><p>Năm học <?=e(date('Y',strtotime($selected[0]['start'])).' – '.date('Y',strtotime($selected[count($selected)-1]['end'])))?></p></section><?php endif;?>
<?php foreach($bundles as$b):$counts=lbp_group_counts($b['rows']);$seen=[];$w=$b['week'];if($paper==='a3'):$pageNo++;?><section class="page a3 <?=($pageNo%2?'odd':'even')?> <?=!empty($ps['mirrored_margins'])?'mirror':''?>"><div class="head"><div>SỔ GHI ĐẦU BÀI · <?=e($title)?></div><div class="week"><?=e($w['label'])?> · BUỔI <?=mb_strtoupper($b['session'],'UTF-8')?> (<?=date('d/m/Y',strtotime($w['start']))?>–<?=date('d/m/Y',strtotime($w['end']))?>)</div></div><table><thead><tr><th>Thứ ngày/tháng</th><th>Tiết</th><?php if($scope==='teacher'):?><th>Lớp</th><?php endif;?><th>Môn học</th><th>Tiết PPCT</th><th>Tên HS nghỉ tiết</th><th>Đầu bài / nội dung</th><th>Nhận xét GV</th><th>Cộng</th><th>XL</th><th>Ký tên</th></tr></thead><tbody><?php foreach($b['rows']as$r):[$sum,$rating]=lbp_scores($r);?><tr><?php if(empty($seen[$r['date']])):$seen[$r['date']]=true;?><td rowspan="<?=$counts[$r['date']]?>"><?=lbp_day($r)?></td><?php endif;?><td><?=e($r['period'])?></td><?php if($scope==='teacher'):?><td><?=e($r['class'])?></td><?php endif;?><td><?=e($r['subject'])?></td><td><?=e($r['ppct_period']??'')?></td><td><?=e($r['absent_names']??'')?></td><td class="text-left"><?=e($r['lesson_title']??'')?></td><td class="text-left"><?=e($r['teacher_comment']??'')?></td><td><?=e($sum)?></td><td><?=e($rating)?></td><td><?php if($src=lbp_sig($r)):?><img class="sig" src="<?=$src?>"><?php endif;?></td></tr><?php endforeach;?></tbody></table><div class="signatures"><div>GIÁO VIÊN CHỦ NHIỆM<br><br><br><?=e($ps['homeroom_name'])?></div><div>BAN GIÁM HIỆU<br><br><br><?=e($ps['leader_name'])?></div></div></section>
<?php else:$pageNo++;$seen=[];?><section class="page odd <?=!empty($ps['mirrored_margins'])?'mirror':''?>"><div class="head"><div>SỔ GHI ĐẦU BÀI · <?=e($title)?></div><div class="week"><?=e($w['label'])?> · BUỔI <?=mb_strtoupper($b['session'],'UTF-8')?></div></div><div class="spread-note">Trang trái – Nội dung tiết học</div><table class="left"><thead><tr><th class="c-day">Thứ ngày/tháng</th><th class="c-period">Tiết</th><th class="c-subject"><?=$scope==='teacher'?'Lớp / Môn':'Môn học'?></th><th class="c-ppct">Tiết PPCT</th><th class="c-absent">Tên HS nghỉ tiết</th><th class="c-title">Đầu bài hay nội dung công việc</th></tr></thead><tbody><?php foreach($b['rows']as$r):?><tr><?php if(empty($seen[$r['date']])):$seen[$r['date']]=true;?><td rowspan="<?=$counts[$r['date']]?>"><?=lbp_day($r)?></td><?php endif;?><td><?=e($r['period'])?></td><td><?=e(($scope==='teacher'?$r['class'].' / ':'').$r['subject'])?></td><td><?=e($r['ppct_period']??'')?></td><td><?=e($r['absent_names']??'')?></td><td class="text-left"><?=e($r['lesson_title']??'')?></td></tr><?php endforeach;?></tbody></table><div class="footer-box">Tổng số tiết đã dạy: <?=$validation['filled']?> · Số tiết chưa hoàn thành: <?=$validation['pending']?></div></section>
<?php $pageNo++;?><section class="page even <?=!empty($ps['mirrored_margins'])?'mirror':''?>"><div class="head"><div>SỔ GHI ĐẦU BÀI · <?=e($title)?></div><div class="week"><?=e($w['label'])?> · BUỔI <?=mb_strtoupper($b['session'],'UTF-8')?></div></div><div class="spread-note">Trang phải – Nhận xét, xếp loại và chữ ký</div><table class="right"><thead><tr><th class="c-comment">Nhận xét của giáo viên</th><th class="score">HT<br>4</th><th class="score">KL<br>3</th><th class="score">VS<br>2</th><th class="score">CC<br>1</th><th class="score">Cộng<br>10</th><th class="c-rating">XL</th><th class="c-sign">Ký tên</th></tr></thead><tbody><?php foreach($b['rows']as$r):[$sum,$rating]=lbp_scores($r);?><tr><td class="text-left"><?=e($r['teacher_comment']??'')?></td><td></td><td></td><td></td><td></td><td><?=e($sum)?></td><td><?=e($rating)?></td><td><?php if($src=lbp_sig($r)):?><img class="sig" src="<?=$src?>"><?php elseif(!empty($r['signed_at'])):?><small>Đã ký</small><?php endif;?></td></tr><?php endforeach;?></tbody></table><div class="footer-box"><b>Nhận xét của giáo viên chủ nhiệm / Ban giám hiệu:</b></div><div class="signatures"><div>GIÁO VIÊN CHỦ NHIỆM<br><br><br><?=e($ps['homeroom_name'])?></div><div>BAN GIÁM HIỆU<br><br><br><?=e($ps['leader_name'])?></div></div></section><?php endif;endforeach;?>
<?php if(!$bundles):?><section class="page"><h2>Không có dữ liệu thuộc phạm vi tài khoản</h2><p>Kiểm tra lớp/giáo viên, tuần học, buổi học hoặc bỏ chọn “Chỉ tiết có dữ liệu”.</p></section><?php endif;?></body></html>
