<?php
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/lesson_book_store.php';
require_login();
$page_title='Sổ đầu bài';
if(empty($_SESSION['lb_csrf']))$_SESSION['lb_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['lb_csrf'];
$weekKey=(string)($_REQUEST['week']??'');$week=lb_week($weekKey);if(!$week){http_response_code(503);exit('Chưa cài đặt tuần học trong CSDL.');}$weekKey=(string)$week['key'];
$tab=(string)($_GET['tab']??'daily');$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrf,(string)($_POST['csrf']??'')))$result=['ok'=>false,'message'=>'Phiên thao tác hết hạn, vui lòng tải lại trang.'];
 else{
  $action=(string)($_POST['action']??'');
  if($action==='save_record')$result=lb_save_record($week,$_POST);
  elseif($action==='sign_record')$result=lb_sign($week,(string)($_POST['slot_id']??''));
  elseif($action==='upload_signature')$result=lb_upload_signature($_FILES['signature']??[]);
  elseif($action==='save_curriculum')$result=lb_save_curriculum($_POST);
  elseif($action==='import_curriculum')$result=lb_import_curriculum($_FILES['curriculum_file']??[]);
  elseif($action==='save_settings'&&lb_is_admin()){$settings=lb_settings();$settings['auto_lock']=!empty($_POST['auto_lock']);$settings['grace_days']=max(0,(int)($_POST['grace_days']??1));$settings['lock_time']=preg_match('/^\d{2}:\d{2}$/',(string)($_POST['lock_time']??''))?$_POST['lock_time']:'23:59';save_json(LB_SETTINGS_FILE,$settings);$result=['ok'=>true,'message'=>'Đã lưu cài đặt khóa sổ.'];}
  elseif(in_array($action,['lock','unlock'],true))$result=lb_set_lock($week,(array)($_POST['classes']??[]),$action==='lock',trim((string)($_POST['reason']??'')));
 }
 if($result)flash($result['message'],$result['ok']?'success':'danger');header('Location: '.BASE_URL.'sodaubai.php?'.http_build_query(['tab'=>$tab,'week'=>$weekKey,'date'=>$_POST['date_filter']??($_GET['date']??'')]));exit;
}
$slots=lb_slots($week);$me=lb_teacher_name();$date=(string)($_GET['date']??date('Y-m-d'));$classFilter=trim((string)($_GET['class']??''));
$classes=[];foreach($slots as$r)if(lb_can_view($r))$classes[(string)$r['class']]=true;$classes=array_keys($classes);sort($classes,SORT_NATURAL);
$visible=array_values(array_filter($slots,function($r)use($date,$classFilter){if($date!==''&&($r['date']??'')!==$date)return false;if($classFilter!==''&&($r['class']??'')!==$classFilter)return false;return lb_can_view($r);}));
$statusLabels=['pending'=>'Chưa hoàn thành','taught'=>'Đã dạy','substitute'=>'Dạy thay','makeup'=>'Dạy bù','online'=>'Trực tuyến','holiday'=>'Nghỉ lễ','teacher_absent'=>'GV nghỉ','class_absent'=>'Lớp nghỉ','postponed'=>'Hoãn','cancelled'=>'Hủy'];
require_once __DIR__ . '/includes/header.php';
?>
<style>
.lb-shell{max-width:1600px;margin:auto}.lb-hero{background:linear-gradient(135deg,#153f69,#287bb6);color:#fff;border-radius:18px;padding:20px 24px;margin-bottom:16px}.lb-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.lb-tabs a{padding:9px 14px;background:#fff;border:1px solid #cbd8e6;border-radius:10px;text-decoration:none;color:#1f4e79;font-weight:700}.lb-tabs a.active{background:#1f4e79;color:#fff}.lb-filter{background:#fff;border-radius:14px;padding:14px;box-shadow:0 4px 18px #183b5b12;margin-bottom:15px}.lb-table{min-width:1200px}.lb-table td{vertical-align:middle}.lb-table input,.lb-table select{min-width:74px}.lb-table .lesson{min-width:230px}.lb-table .absence{min-width:180px}.lb-sticky{position:sticky;right:0;background:#fff;z-index:2}.lb-note{font-size:.84rem;color:#65758a}.lb-sign{max-width:150px;max-height:48px;object-fit:contain}.lb-empty{padding:44px;text-align:center;color:#718096}.lb-card{background:#fff;border-radius:14px;padding:18px;box-shadow:0 4px 18px #183b5b12;margin-bottom:16px}.lb-lock{font-size:.75rem;padding:4px 8px;border-radius:999px}.lb-lock.y{background:#fee2e2;color:#991b1b}.lb-lock.n{background:#dcfce7;color:#166534}@media(max-width:700px){.lb-hero{padding:16px}.lb-filter .row>*{margin-bottom:8px}.lb-tabs a{flex:1;text-align:center}.lb-table{font-size:.86rem}}
@media print{nav,.lb-tabs,.lb-filter,.no-print,footer{display:none!important}.lb-shell{max-width:none}.lb-card{box-shadow:none;padding:0}.table-responsive{overflow:visible}.lb-table{min-width:0;font-size:10pt}}
</style>
<main class="container-fluid px-3 px-lg-4 pb-5 lb-shell">
 <section class="lb-hero d-flex justify-content-between align-items-center flex-wrap gap-3"><div><div class="text-uppercase small opacity-75 fw-bold">Chuyên môn · dữ liệu theo TKB</div><h1 class="h2 mb-1"><i class="bi bi-journal-check"></i> Sổ đầu bài</h1><div><?=e($week['label'])?> · <?=e(date('d/m/Y',strtotime($week['start'])))?>–<?=e(date('d/m/Y',strtotime($week['end'])))?></div></div><form class="d-flex flex-wrap gap-2 align-items-end" method="get" action="<?=BASE_URL?>sodaubai_export.php"><input type="hidden" name="week" value="<?=e($weekKey)?>"><div><label class="form-label small mb-1 text-white">Xuất Excel theo lớp</label><select class="form-select" name="class" required><option value="">Chọn lớp</option><?php foreach($classes as$c):?><option value="<?=e($c)?>" <?=$classFilter===$c?'selected':''?>>Lớp <?=e($c)?></option><?php endforeach;?></select></div><button class="btn btn-light" type="submit"><i class="bi bi-file-earmark-excel"></i> Tải Excel A3</button><button class="btn btn-outline-light" type="submit" name="save_drive" value="1"><i class="bi bi-google"></i> Lưu Drive</button></form></section>
 <?php show_flash(); ?>
 <nav class="lb-tabs">
  <?php foreach(['daily'=>'Ghi sổ hằng ngày','week'=>'Theo lớp / tuần','progress'=>'Tiến độ & thống kê','curriculum'=>'PPCT','signature'=>'Chữ ký','settings'=>'Cài đặt & khóa']as$k=>$v):if(!lb_is_admin()&&in_array($k,['curriculum','settings'],true))continue;?><a class="<?=$tab===$k?'active':''?>" href="<?=BASE_URL?>sodaubai.php?tab=<?=$k?>&week=<?=urlencode($weekKey)?>"><?=e($v)?></a><?php endforeach;?>
 </nav>

 <?php if(in_array($tab,['daily','week'],true)):?>
 <form class="lb-filter" method="get"><input type="hidden" name="tab" value="<?=$tab?>"><div class="row g-2 align-items-end"><div class="col-lg-3"><label class="form-label fw-bold">Tuần học</label><select class="form-select" name="week" onchange="this.form.submit()"><?php foreach(lb_weeks()as$w):?><option value="<?=e($w['key'])?>" <?=$weekKey===$w['key']?'selected':''?>><?=e($w['label'])?> (<?=date('d/m',strtotime($w['start']))?>–<?=date('d/m/Y',strtotime($w['end']))?>)</option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label fw-bold">Ngày</label><input class="form-control" type="date" name="date" value="<?=e($date)?>"></div><div class="col-lg-2"><label class="form-label fw-bold">Lớp</label><select class="form-select" name="class"><option value="">Tất cả lớp</option><?php foreach($classes as$c):?><option <?=$classFilter===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div><div class="col-lg-2"><button class="btn btn-primary"><i class="bi bi-funnel"></i> Xem</button></div><div class="col-lg-3 lb-note">Vắng học chỉ lưu riêng trong tiết này, không đồng bộ sang điểm danh hoặc tiết khác.</div></div></form>
 <section class="lb-card"><div class="d-flex justify-content-between mb-3"><h2 class="h5 mb-0">Các tiết được phân công</h2><span class="badge text-bg-primary"><?=count($visible)?> tiết</span></div><div class="table-responsive"><table class="table table-bordered table-hover lb-table"><thead><tr><th>Ngày</th><th>Buổi / tiết</th><th>Lớp</th><th>Môn</th><th>GV theo TKB</th><th>GV thực tế</th><th>Tiết PPCT</th><th>Đầu bài / nội dung</th><th>HS vắng trong tiết</th><th>Nhận xét</th><th>Xếp loại</th><th>Trạng thái</th><th class="lb-sticky">Lưu / ký</th></tr></thead><tbody>
 <?php foreach($visible as$r):$locked=lb_locked($week,$r);$disabled=$locked||!lb_can_edit($r);$formId='f'.substr($r['slot_id'],0,10);?>
 <tr><td><?=date('d/m/Y',strtotime($r['date']))?><div><span class="lb-lock <?=$locked?'y':'n'?>"><?=$locked?'Đã khóa':'Đang mở'?></span></div></td><td><?=e($r['session'])?> · <?=e($r['period'])?></td><td class="fw-bold"><?=e($r['class'])?></td><td><?=e($r['subject'])?></td><td><?=e($r['scheduled_teacher'])?></td>
 <td><input form="<?=$formId?>" class="form-control" name="actual_teacher" value="<?=e($r['actual_teacher'])?>" <?=$disabled?'disabled':''?>></td><td><input form="<?=$formId?>" class="form-control text-center" type="number" min="0" name="ppct_period" value="<?=e($r['ppct_period']??'')?>" <?=$disabled?'disabled':''?>></td><td><input form="<?=$formId?>" class="form-control lesson" name="lesson_title" value="<?=e($r['lesson_title']??'')?>" placeholder="Tự lấy theo PPCT hoặc nhập" <?=$disabled?'disabled':''?>></td><td><input form="<?=$formId?>" class="form-control absence" name="absent_names" value="<?=e($r['absent_names']??'')?>" placeholder="Nhập tên, cách nhau dấu phẩy" <?=$disabled?'disabled':''?>></td><td><input form="<?=$formId?>" class="form-control" name="teacher_comment" value="<?=e($r['teacher_comment']??'')?>" <?=$disabled?'disabled':''?>></td><td><select form="<?=$formId?>" class="form-select" name="rating" <?=$disabled?'disabled':''?>><option value="">—</option><?php foreach(['Tốt','Khá','Trung bình','Yếu']as$x):?><option <?=$x===($r['rating']??'')?'selected':''?>><?=$x?></option><?php endforeach;?></select></td><td><select form="<?=$formId?>" class="form-select" name="status" <?=$disabled?'disabled':''?>><?php foreach($statusLabels as$k=>$v):?><option value="<?=$k?>" <?=$k===($r['status']??'pending')?'selected':''?>><?=$v?></option><?php endforeach;?></select></td><td class="lb-sticky"><form id="<?=$formId?>" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="week" value="<?=e($weekKey)?>"><input type="hidden" name="date_filter" value="<?=e($date)?>"><input type="hidden" name="slot_id" value="<?=e($r['slot_id'])?>"><input type="hidden" name="action" value="save_record"><input type="hidden" name="actual_periods" value="1"><button class="btn btn-sm btn-primary" <?=$disabled?'disabled':''?> title="Lưu"><i class="bi bi-floppy"></i></button></form><?php if(!empty($r['signed_at'])):?><div class="text-success small mt-1"><i class="bi bi-patch-check-fill"></i> Đã ký<br><?=e($r['signed_by']??'')?></div><?php else:?><form method="post" class="mt-1"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="week" value="<?=e($weekKey)?>"><input type="hidden" name="date_filter" value="<?=e($date)?>"><input type="hidden" name="action" value="sign_record"><input type="hidden" name="slot_id" value="<?=e($r['slot_id'])?>"><button class="btn btn-sm btn-outline-success" <?=$disabled?'disabled':''?> onclick="return confirm('Xác nhận ký tiết học này?')"><i class="bi bi-pen"></i> Ký</button></form><?php endif;?></td></tr>
 <?php endforeach;if(!$visible):?><tr><td colspan="13" class="lb-empty">Không có tiết nào thuộc phạm vi tài khoản trong ngày đã chọn. Kiểm tra TKB và phần ghép tên giáo viên.</td></tr><?php endif;?></tbody></table></div></section>
 <?php elseif($tab==='curriculum'&&lb_is_admin()):?>
 <section class="lb-card"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h2 class="h5 mb-1">Nhập PPCT hàng loạt từ Excel</h2><p class="lb-note mb-0">Khóa đối chiếu là <b>Môn + Khối + Tiết PPCT</b>. Dòng đã có sẽ được cập nhật; dòng mới được bổ sung. Nếu có dòng sai, hệ thống không nhập tệp để tránh dữ liệu dở dang.</p></div><a class="btn btn-outline-success align-self-start" href="<?=BASE_URL?>sodaubai_ppct_template.php"><i class="bi bi-download"></i> Tải mẫu Excel</a></div><form method="post" enctype="multipart/form-data" class="row g-2 align-items-end mt-2"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="import_curriculum"><div class="col-lg-9"><label class="form-label fw-bold">Tệp PPCT (.xlsx)</label><input class="form-control" type="file" name="curriculum_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></div><div class="col-lg-3"><button class="btn btn-success w-100" onclick="return confirm('Nhập và cập nhật PPCT từ tệp Excel đã chọn?')"><i class="bi bi-file-earmark-arrow-up"></i> Kiểm tra và nhập</button></div></form></section>
 <section class="lb-card"><h2 class="h5">Nhập hoặc sửa một dòng PPCT</h2><p class="lb-note">Tên bài sẽ tự điền khi giáo viên nhập đúng môn, khối và tiết PPCT.</p><form method="post" class="row g-2 align-items-end"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="save_curriculum"><div class="col-md-3"><label class="form-label">Môn</label><input class="form-control" name="subject" required></div><div class="col-md-2"><label class="form-label">Khối</label><input class="form-control" name="grade" required></div><div class="col-md-2"><label class="form-label">Tiết PPCT</label><input class="form-control" type="number" min="1" name="period" required></div><div class="col-md-4"><label class="form-label">Tên bài / nội dung</label><input class="form-control" name="title" required></div><div class="col-md-1"><button class="btn btn-primary">Lưu</button></div></form></section><section class="lb-card"><div class="d-flex justify-content-between"><h2 class="h5">Danh mục PPCT</h2><span class="badge text-bg-primary"><?=count(lb_curriculum())?> dòng</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Môn</th><th>Khối</th><th>Tiết</th><th>Tên bài</th><th>Ghi chú</th></tr></thead><tbody><?php $cur=lb_curriculum();usort($cur,fn($a,$b)=>strcmp(($a['subject'].'|'.$a['grade'].'|'.sprintf('%04d',$a['period'])),($b['subject'].'|'.$b['grade'].'|'.sprintf('%04d',$b['period']))));foreach($cur as$r):?><tr><td><?=e($r['subject'])?></td><td><?=e($r['grade'])?></td><td class="text-center"><?=e($r['period'])?></td><td><?=e($r['title'])?></td><td><?=e($r['note']??'')?></td></tr><?php endforeach;?></tbody></table></div></section>
 <?php elseif($tab==='signature'):?>
 <section class="lb-card"><h2 class="h5">Ảnh chữ ký giáo viên</h2><p>Ảnh được tự động cắt khoảng trắng, giữ đúng tỷ lệ và đặt trong khung PNG trong suốt 480 × 160 px. Mỗi lần ký sẽ lưu đúng phiên bản ảnh tại thời điểm đó.</p><?php if($sig=lb_signature_meta()):?><div class="alert alert-success">Đã có chữ ký phiên bản <?=e($sig['version'])?>, tạo lúc <?=e($sig['created_at'])?>.</div><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="upload_signature"><div class="input-group"><input class="form-control" type="file" name="signature" accept="image/png,image/jpeg" required><button class="btn btn-primary"><i class="bi bi-crop"></i> Chuẩn hóa và lưu</button></div></form></section>
 <?php elseif($tab==='settings'&&lb_is_admin()):$settings=lb_settings();?>
 <section class="lb-card"><h2 class="h5">Khóa sổ tự động</h2><form method="post" class="row g-3 align-items-end"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="save_settings"><div class="col-md-3 form-check ms-3"><input class="form-check-input" type="checkbox" name="auto_lock" id="autolock" <?=$settings['auto_lock']?'checked':''?>><label class="form-check-label" for="autolock">Tự khóa sau khi hết tuần</label></div><div class="col-md-2"><label class="form-label">Số ngày gia hạn</label><input class="form-control" type="number" min="0" name="grace_days" value="<?=e($settings['grace_days'])?>"></div><div class="col-md-2"><label class="form-label">Giờ khóa</label><input class="form-control" type="time" name="lock_time" value="<?=e($settings['lock_time'])?>"></div><div class="col-md-2"><button class="btn btn-primary">Lưu cài đặt</button></div></form></section><section class="lb-card"><h2 class="h5">Khóa / mở theo lớp</h2><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><div class="d-flex flex-wrap gap-2 mb-3"><?php foreach($classes as$c):$li=lb_lock_info($week,$c);?><label class="border rounded p-2"><input type="checkbox" name="classes[]" value="<?=e($c)?>"> <b><?=e($c)?></b> <span class="lb-lock <?=!empty($li['locked'])?'y':'n'?>"><?=!empty($li['locked'])?'Đã khóa':'Đang mở'?></span></label><?php endforeach;?></div><input class="form-control mb-2" name="reason" placeholder="Lý do khóa hoặc mở khóa (được lưu nhật ký)"><button class="btn btn-danger" name="action" value="lock"><i class="bi bi-lock"></i> Khóa đã chọn</button> <button class="btn btn-success" name="action" value="unlock"><i class="bi bi-unlock"></i> Mở khóa đã chọn</button></form></section>
 <?php else:?>
 <?php $statsFrom=(string)($_GET['stats_from']??$week['start']);$statsTo=(string)($_GET['stats_to']??$week['end']);$statsTeacher=trim((string)($_GET['stats_teacher']??''));$statsSubject=trim((string)($_GET['stats_subject']??''));$statsClass=trim((string)($_GET['stats_class']??''));$allAccessible=lb_stat_rows($statsFrom,$statsTo);$teachers=[];$subjects=[];$statClasses=[];foreach($allAccessible as$r){if(trim((string)($r['actual_teacher']??''))!=='')$teachers[(string)$r['actual_teacher']]=true;if(trim((string)($r['subject']??''))!=='')$subjects[(string)$r['subject']]=true;if(trim((string)($r['class']??''))!=='')$statClasses[(string)$r['class']]=true;}$teachers=array_keys($teachers);$subjects=array_keys($subjects);$statClasses=array_keys($statClasses);sort($teachers,SORT_NATURAL);sort($subjects,SORT_NATURAL);sort($statClasses,SORT_NATURAL);$statRows=lb_stat_rows($statsFrom,$statsTo,$statsTeacher,$statsSubject,$statsClass);$actual=array_sum(array_map(fn($r)=>in_array($r['status']??'',['taught','substitute','makeup','online'],true)?(float)($r['actual_periods']??1):0,$statRows));$signed=count(array_filter($statRows,fn($r)=>!empty($r['signed_at'])));$teacherStats=lb_stat_group($statRows,'actual_teacher');$subjectStats=lb_stat_group($statRows,'subject');$classStats=lb_stat_group($statRows,'class');?>
 <form class="lb-filter" method="get"><input type="hidden" name="tab" value="progress"><input type="hidden" name="week" value="<?=e($weekKey)?>"><div class="row g-2 align-items-end"><div class="col-lg-2"><label class="form-label fw-bold">Từ ngày</label><input class="form-control" type="date" name="stats_from" value="<?=e($statsFrom)?>" required></div><div class="col-lg-2"><label class="form-label fw-bold">Đến ngày</label><input class="form-control" type="date" name="stats_to" value="<?=e($statsTo)?>" required></div><div class="col-lg-2"><label class="form-label fw-bold">Giáo viên</label><select class="form-select" name="stats_teacher"><option value="">Tất cả</option><?php foreach($teachers as$x):?><option <?=$x===$statsTeacher?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label fw-bold">Môn</label><select class="form-select" name="stats_subject"><option value="">Tất cả</option><?php foreach($subjects as$x):?><option <?=$x===$statsSubject?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label fw-bold">Lớp</label><select class="form-select" name="stats_class"><option value="">Tất cả</option><?php foreach($statClasses as$x):?><option <?=$x===$statsClass?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-lg-2"><button class="btn btn-primary w-100"><i class="bi bi-bar-chart"></i> Thống kê</button></div></div></form>
 <div class="row g-3"><div class="col-md-3"><div class="lb-card"><div class="text-muted">Dòng đã cập nhật</div><div class="display-6 fw-bold"><?=count($statRows)?></div></div></div><div class="col-md-3"><div class="lb-card"><div class="text-muted">Tiết dạy thực tế</div><div class="display-6 fw-bold"><?=number_format($actual,1,',','.')?></div></div></div><div class="col-md-3"><div class="lb-card"><div class="text-muted">Đã ký</div><div class="display-6 fw-bold"><?=$signed?></div></div></div><div class="col-md-3"><div class="lb-card"><div class="text-muted">Tỷ lệ ký</div><div class="display-6 fw-bold"><?=count($statRows)?number_format($signed*100/count($statRows),1,',','.'):0?>%</div></div></div></div>
 <?php foreach([['Theo giáo viên',$teacherStats],['Theo môn học',$subjectStats],['Theo lớp',$classStats]]as[$heading,$groupRows]):?><section class="lb-card"><h2 class="h5"><?=e($heading)?></h2><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Tên</th><th class="text-center">Dòng cập nhật</th><th class="text-center">Đã hoàn thành</th><th class="text-center">Tiết thực tế</th><th class="text-center">Dạy thay</th><th class="text-center">Nghỉ/hoãn/hủy</th><th class="text-center">Đã ký</th></tr></thead><tbody><?php foreach($groupRows as$g):?><tr><td class="fw-bold"><?=e($g['name'])?></td><td class="text-center"><?=$g['records']?></td><td class="text-center"><?=$g['completed']?></td><td class="text-center fw-bold"><?=number_format($g['actual'],1,',','.')?></td><td class="text-center"><?=$g['substitute']?></td><td class="text-center"><?=$g['cancelled']?></td><td class="text-center"><?=$g['signed']?></td></tr><?php endforeach;if(!$groupRows):?><tr><td colspan="7" class="lb-empty">Chưa có dữ liệu trong phạm vi đã chọn.</td></tr><?php endif;?></tbody></table></div></section><?php endforeach;?>
 <section class="lb-card"><h2 class="h5">Nguyên tắc thống kê</h2><ul><li>Chỉ Đã dạy, Dạy thay, Dạy bù và Trực tuyến được tính vào số tiết dạy thực tế.</li><li>Giáo viên theo TKB và giáo viên thực tế lưu riêng; thống kê giáo viên dùng người thực tế đứng lớp.</li><li>Nghỉ, hoãn, hủy không tính tiết thực tế nhưng vẫn được kê riêng để đối chiếu.</li></ul></section>
 <?php endif;?>
</main>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
