<?php
$page_title='Thời khóa biểu';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/timetable_store.php';
$user=cds_user();
if(!$user){$next=$_SERVER['REQUEST_URI']??(BASE_URL.'thoikhoabieu.php');header('Location: /login.php?next='.urlencode($next));exit;}
if(!cds_can_feature('cm.tracuu','view')){http_response_code(403);exit('Bạn chưa có quyền xem Thời khóa biểu.');}
$canSub=cds_can_feature('cm.pccm','edit');
$canSettings=cds_can_feature('cm.nhaplieu','edit');
$tab=(string)($_GET['tab']??'lookup');if(!in_array($tab,['lookup','substitution','settings'],true))$tab='lookup';if($tab==='substitution'&&!$canSub)$tab='lookup';if($tab==='settings'&&!$canSettings)$tab='lookup';
if(empty($_SESSION['tkb_csrf']))$_SESSION['tkb_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['tkb_csrf'];
$teachers=array_values(array_filter(array_map('strval',(array)load_json(TEACHERS_FILE,[]))));sort($teachers,SORT_NATURAL|SORT_FLAG_CASE);
$classes=array_values(array_filter(array_map('strval',(array)load_json(CLASSES_FILE,[]))));sort($classes,SORT_NATURAL|SORT_FLAG_CASE);
function tkb_redirect(string $tab): never {header('Location: '.BASE_URL.'thoikhoabieu.php?tab='.$tab);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))){flash('Phiên làm việc không hợp lệ.','danger');tkb_redirect($tab);}
    $action=(string)($_POST['action']??'');
    if($action==='upload'&&$canSettings){$upload=$_FILES['tkb_file']??null;$start=trim((string)($_POST['start_date']??''));$label=trim((string)($_POST['week_label']??''));if(!$upload||($upload['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK){flash('Hãy chọn file Excel thời khóa biểu.','danger');tkb_redirect('settings');}if(strtolower(pathinfo((string)($upload['name']??''),PATHINFO_EXTENSION))!=='xlsx'){flash('Chỉ hỗ trợ file .xlsx.','danger');tkb_redirect('settings');}if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)){flash('Hãy chọn ngày bắt đầu tuần.','danger');tkb_redirect('settings');}$result=tkb_import_week((string)$upload['tmp_name'],$label,$start,$teachers,$classes,(string)($user['name']??''));flash($result['message']??(!empty($result['ok'])?'Đã cập nhật thời khóa biểu tuần mới.':'Không nhập được thời khóa biểu.'),!empty($result['ok'])?'success':'danger');tkb_redirect('settings');}
    if($action==='mapping'&&$canSettings){$teacherMap=[];$classMap=[];foreach((array)($_POST['teacher_raw']??[]) as $i=>$raw)$teacherMap[(string)$raw]=(string)($_POST['teacher_value'][$i]??'');foreach((array)($_POST['class_raw']??[]) as $i=>$raw)$classMap[(string)$raw]=(string)($_POST['class_value'][$i]??'');tkb_save_mapping($teacherMap,$classMap);flash('Đã lưu bảng ghép tên giáo viên và lớp.','success');tkb_redirect('settings');}
    if($action==='substitution'&&$canSub){$week=tkb_week_by_id((string)($_POST['week_id']??''))?:tkb_active_week();$date=(string)($_POST['date']??'');$slotKey=(string)($_POST['slot_key']??'');$sub=trim((string)($_POST['substitute_teacher']??''));if(!$week||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$slotKey===''||$sub===''){flash('Thiếu dữ liệu dạy thay.','danger');tkb_redirect('substitution');}$target=null;foreach(tkb_resolved_slots($week) as $slot)if(tkb_slot_key($slot)===$slotKey){$target=$slot;break;}if(!$target){flash('Không tìm thấy tiết học cần dạy thay.','danger');tkb_redirect('substitution');}if(tkb_teacher_busy($week,$sub,(int)$target['day'],(string)$target['session'],(int)$target['period'],$date)){flash($sub.' đang có lịch ở tiết này, không thể xếp dạy thay.','danger');tkb_redirect('substitution');}$row=['id'=>'sub_'.bin2hex(random_bytes(6)),'date'=>$date,'week_id'=>$week['id'],'slot_key'=>$slotKey,'day'=>(int)$target['day'],'session'=>(string)$target['session'],'period'=>(int)$target['period'],'class'=>(string)($target['class']?:$target['class_raw']),'subject'=>(string)$target['subject'],'absent_teacher'=>(string)($target['teacher']?:$target['teacher_raw']),'substitute_teacher'=>$sub,'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c'),'updated_by'=>(string)($user['name']??'')];tkb_save_substitution($row);flash('Đã lưu lịch dạy thay.','success');tkb_redirect('substitution');}
}
$weeks=tkb_weeks();$weekId=(string)($_GET['week_id']??'');$week=$weekId!==''?tkb_week_by_id($weekId):tkb_active_week();$slots=$week?tkb_resolved_slots($week):[];$mapping=tkb_mapping();
$lookupMode=(string)($_GET['mode']??'school');if(!in_array($lookupMode,['school','teacher','class'],true))$lookupMode='school';$teacherFilter=trim((string)($_GET['teacher']??''));$classFilter=trim((string)($_GET['class']??''));
$visibleSlots=array_values(array_filter($slots,function($s)use($lookupMode,$teacherFilter,$classFilter){if($lookupMode==='teacher')return $teacherFilter!==''&&($s['teacher']??'')===$teacherFilter;if($lookupMode==='class')return $classFilter!==''&&(($s['class']??'')===$classFilter||($s['class_raw']??'')===$classFilter);return true;}));
usort($visibleSlots,fn($a,$b)=>[(int)$a['day'],($a['session']==='Chiều'?1:0),(int)$a['period'],(string)($a['class']?:$a['class_raw'])]<=>[(int)$b['day'],($b['session']==='Chiều'?1:0),(int)$b['period'],(string)($b['class']?:$b['class_raw'])]);
$subDate=(string)($_GET['date']??date('Y-m-d'));$absentTeacher=trim((string)($_GET['absent_teacher']??''));$subDay=(int)date('N',strtotime($subDate))+1;$absentSlots=array_values(array_filter($slots,fn($s)=>$absentTeacher!==''&&($s['teacher']??'')===$absentTeacher&&(int)$s['day']===$subDay));$subRows=array_values(array_filter(tkb_substitutions(),fn($r)=>($r['date']??'')===$subDate));
require_once __DIR__.'/includes/header.php';
?>
<style>
.tkb-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;flex-wrap:wrap;margin-bottom:1rem}.tkb-head h2{color:#173f65;font-weight:800}.tkb-tabs{display:flex;gap:.4rem;flex-wrap:wrap;padding:.35rem;border:1px solid #dce6ef;border-radius:14px;background:#fff}.tkb-tabs a{display:flex;align-items:center;gap:.4rem;padding:.6rem .85rem;border-radius:10px;color:#315b7d;text-decoration:none;font-weight:750}.tkb-tabs a.active{background:#1f5d8d;color:#fff}.tkb-card{border:1px solid #dfe8f0;border-radius:16px;background:#fff;box-shadow:0 4px 18px rgba(15,23,42,.05)}.tkb-filter{padding:1rem;margin-bottom:1rem}.tkb-radio{display:flex;gap:1rem;flex-wrap:wrap}.tkb-radio label{font-weight:700}.tkb-table th{background:#eaf3fb;color:#173f65;white-space:nowrap}.tkb-table td{vertical-align:middle}.teacher-name{color:#d6335c;font-weight:700}.tkb-day{font-weight:800;color:#174b73}.mapping-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.mapping-list{max-height:520px;overflow:auto}.mapping-row{display:grid;grid-template-columns:minmax(130px,1fr) minmax(180px,1.3fr);gap:.55rem;align-items:center;padding:.45rem 0;border-bottom:1px solid #edf2f7}.warning-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#dc3545;margin-right:.35rem}.ok-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#198754;margin-right:.35rem}@media(max-width:767px){.tkb-tabs{width:100%;overflow:auto;flex-wrap:nowrap}.tkb-tabs a{white-space:nowrap}.mapping-grid{grid-template-columns:1fr}.tkb-filter .row>*{margin-bottom:.4rem}}
</style>
<div class="tkb-head"><div><h2 class="mb-1"><i class="bi bi-calendar3"></i> Thời khóa biểu</h2><div class="text-muted">Tra cứu toàn trường · quản lý dạy thay · cập nhật Excel theo tuần</div></div><nav class="tkb-tabs"><a class="<?=$tab==='lookup'?'active':''?>" href="?tab=lookup"><i class="bi bi-search"></i>Tra cứu TKB</a><?php if($canSub):?><a class="<?=$tab==='substitution'?'active':''?>" href="?tab=substitution"><i class="bi bi-person-check"></i>Lịch dạy thay</a><?php endif;?><?php if($canSettings):?><a class="<?=$tab==='settings'?'active':''?>" href="?tab=settings"><i class="bi bi-gear"></i>Cài đặt</a><?php endif;?></nav></div>
<?php show_flash(); ?>
<?php if(!$week):?><div class="alert alert-warning"><i class="bi bi-exclamation-triangle"></i> Chưa có dữ liệu thời khóa biểu. Người có quyền hãy vào tab <strong>Cài đặt</strong> để tải file Excel tuần đầu tiên.</div><?php endif;?>
<?php if($tab==='lookup'):?>
<form class="tkb-card tkb-filter" method="get"><input type="hidden" name="tab" value="lookup"><div class="row g-3 align-items-end"><div class="col-lg-4"><label class="form-label fw-bold">Phạm vi xem</label><div class="tkb-radio"><label><input type="radio" name="mode" value="school" <?=$lookupMode==='school'?'checked':''?> onchange="this.form.submit()"> Toàn trường</label><label><input type="radio" name="mode" value="teacher" <?=$lookupMode==='teacher'?'checked':''?> onchange="this.form.submit()"> Theo giáo viên</label><label><input type="radio" name="mode" value="class" <?=$lookupMode==='class'?'checked':''?> onchange="this.form.submit()"> Theo lớp</label></div></div><div class="col-lg-3"><label class="form-label">Tuần</label><select class="form-select" name="week_id" onchange="this.form.submit()"><?php foreach(array_reverse($weeks) as $w):?><option value="<?=e($w['id'])?>" <?=($week['id']??'')===$w['id']?'selected':''?>><?=e($w['label'])?> · <?=e(date('d/m',strtotime($w['start_date'])))?>–<?=e(date('d/m/Y',strtotime($w['end_date'])))?></option><?php endforeach;?></select></div><?php if($lookupMode==='teacher'):?><div class="col-lg-3"><label class="form-label">Giáo viên</label><select class="form-select" name="teacher" onchange="this.form.submit()"><option value="">Chọn giáo viên...</option><?php foreach($teachers as $t):?><option <?= $teacherFilter===$t?'selected':'' ?>><?=e($t)?></option><?php endforeach;?></select></div><?php elseif($lookupMode==='class'):?><div class="col-lg-3"><label class="form-label">Lớp</label><select class="form-select" name="class" onchange="this.form.submit()"><option value="">Chọn lớp...</option><?php foreach($classes as $c):?><option <?= $classFilter===$c?'selected':'' ?>><?=e($c)?></option><?php endforeach;?></select></div><?php endif;?><div class="col-lg-2"><button class="btn btn-primary w-100"><i class="bi bi-funnel"></i> Xem</button></div></div></form>
<div class="tkb-card table-responsive"><table class="table table-hover tkb-table mb-0"><thead><tr><th>Thứ</th><th>Buổi</th><th>Tiết</th><th>Lớp</th><th>Môn</th><th>Giáo viên</th></tr></thead><tbody><?php foreach($visibleSlots as $s):?><tr><td class="tkb-day">Thứ <?=e($s['day'])?></td><td><?=e($s['session'])?></td><td class="text-center fw-bold"><?=e($s['period'])?></td><td><strong><?=e($s['class']?:$s['class_raw'])?></strong><?php if(empty($s['class'])):?><br><small class="text-danger">chưa ghép danh mục</small><?php endif;?></td><td><?=e($s['subject'])?></td><td class="teacher-name"><?=e($s['teacher']?:$s['teacher_raw'])?><?php if(empty($s['teacher'])&&$s['teacher_raw']!==''):?><br><small class="text-danger">chưa ghép danh mục</small><?php endif;?></td></tr><?php endforeach;if(!$visibleSlots):?><tr><td colspan="6" class="text-center text-muted py-5">Chưa có tiết học phù hợp lựa chọn.</td></tr><?php endif;?></tbody></table></div>
<?php elseif($tab==='substitution'&&$canSub):?>
<form class="tkb-card tkb-filter" method="get"><input type="hidden" name="tab" value="substitution"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label fw-bold">Ngày nghỉ</label><input class="form-control" type="date" name="date" value="<?=e($subDate)?>"></div><div class="col-md-5"><label class="form-label fw-bold">Giáo viên nghỉ</label><select class="form-select" name="absent_teacher"><option value="">Chọn giáo viên...</option><?php foreach($teachers as $t):?><option <?= $absentTeacher===$t?'selected':'' ?>><?=e($t)?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="bi bi-arrow-repeat"></i> Lấy tiết nghỉ</button></div></div></form>
<?php if($absentTeacher&&$week):?><div class="tkb-card table-responsive mb-3"><table class="table tkb-table mb-0"><thead><tr><th>Buổi</th><th>Tiết</th><th>Lớp</th><th>Môn</th><th>GV nghỉ</th><th style="min-width:240px">Giáo viên dạy thay</th></tr></thead><tbody><?php foreach($absentSlots as $s):$saved=null;foreach($subRows as $r)if(($r['slot_key']??'')===tkb_slot_key($s)){$saved=$r;break;}?><tr><td><?=e($s['session'])?></td><td class="text-center fw-bold"><?=e($s['period'])?></td><td><?=e($s['class']?:$s['class_raw'])?></td><td><?=e($s['subject'])?></td><td class="teacher-name"><?=e($absentTeacher)?></td><td><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="substitution"><input type="hidden" name="week_id" value="<?=e($week['id'])?>"><input type="hidden" name="date" value="<?=e($subDate)?>"><input type="hidden" name="slot_key" value="<?=e(tkb_slot_key($s))?>"><select class="form-select form-select-sm" name="substitute_teacher" required><option value="">Chọn GV...</option><?php foreach($teachers as $t):$busy=tkb_teacher_busy($week,$t,(int)$s['day'],(string)$s['session'],(int)$s['period'],$subDate);?><option value="<?=e($t)?>" <?=($saved['substitute_teacher']??'')===$t?'selected':''?> <?=$busy?'disabled':''?>><?=e($t)?><?=$busy?' · bận':''?></option><?php endforeach;?></select><button class="btn btn-sm btn-success"><i class="bi bi-check2"></i></button></form><?php if($saved):?><small class="text-success">Đã xếp: <?=e($saved['substitute_teacher'])?></small><?php endif;?></td></tr><?php endforeach;if(!$absentSlots):?><tr><td colspan="6" class="text-center text-muted py-4">Giáo viên này không có tiết trong ngày đã chọn.</td></tr><?php endif;?></tbody></table></div><?php endif;?>
<?php if($subRows):?><div class="tkb-card p-3"><h5 class="mb-3"><i class="bi bi-list-check"></i> Lịch dạy thay ngày <?=e(date('d/m/Y',strtotime($subDate)))?></h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tiết</th><th>Lớp</th><th>Môn</th><th>GV nghỉ</th><th>GV dạy thay</th></tr></thead><tbody><?php foreach($subRows as $r):?><tr><td><?=e($r['session'])?> · <?=e($r['period'])?></td><td><?=e($r['class'])?></td><td><?=e($r['subject'])?></td><td><?=e($r['absent_teacher'])?></td><td><strong class="text-success"><?=e($r['substitute_teacher'])?></strong></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<?php elseif($tab==='settings'&&$canSettings):?>
<div class="row g-3 mb-3"><div class="col-lg-5"><section class="tkb-card p-4 h-100"><h5><i class="bi bi-file-earmark-excel text-success"></i> Cập nhật TKB tuần</h5><p class="text-muted small">File Excel dùng cấu trúc như mẫu: Lớp · Buổi · Tiết, sau đó mỗi Thứ gồm 2 cột Môn và Giáo viên.</p><form method="post" enctype="multipart/form-data" class="vstack gap-3"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="upload"><div><label class="form-label fw-bold">Tên tuần</label><input class="form-control" name="week_label" placeholder="Ví dụ: Tuần 3"></div><div><label class="form-label fw-bold">Ngày Thứ 2 bắt đầu tuần</label><input class="form-control" type="date" name="start_date" required></div><div><label class="form-label fw-bold">File Excel (.xlsx)</label><input class="form-control" type="file" name="tkb_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></div><button class="btn btn-success"><i class="bi bi-cloud-arrow-up"></i> Tải lên và dùng làm TKB hiện hành</button></form></section></div><div class="col-lg-7"><section class="tkb-card p-4 h-100"><h5><i class="bi bi-clock-history"></i> Các tuần đã cập nhật</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tuần</th><th>Áp dụng</th><th>Số tiết</th><th>Trạng thái</th></tr></thead><tbody><?php foreach(array_reverse($weeks) as $w):?><tr><td><strong><?=e($w['label'])?></strong><br><small><?=e($w['uploaded_by']??'')?></small></td><td><?=e(date('d/m/Y',strtotime($w['start_date'])))?> – <?=e(date('d/m/Y',strtotime($w['end_date'])))?></td><td><?=count((array)($w['slots']??[]))?></td><td><?=$w['active']?'<span class="badge text-bg-success">Hiện hành</span>':'<span class="badge text-bg-secondary">Lưu trữ</span>'?></td></tr><?php endforeach;if(!$weeks):?><tr><td colspan="4" class="text-muted">Chưa có dữ liệu.</td></tr><?php endif;?></tbody></table></div></section></div></div>
<?php if($week):$teacherAliases=tkb_aliases($week,'teacher_raw');$classAliases=tkb_aliases($week,'class_raw');?><form method="post" class="tkb-card p-4"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="mapping"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h5 class="mb-1"><i class="bi bi-link-45deg"></i> Ghép dữ liệu Excel với danh mục CDS</h5><div class="small text-muted">Tên đã ghép sẽ được ghi nhớ và tự dùng cho các tuần sau.</div></div><button class="btn btn-primary"><i class="bi bi-floppy"></i> Lưu bảng ghép</button></div><div class="mapping-grid"><div><h6>Giáo viên trong Excel</h6><div class="mapping-list"><?php foreach($teacherAliases as $raw):$value=(string)($mapping['teachers'][$raw]??'');?><div class="mapping-row"><div><?= $value?'<span class="ok-dot"></span>':'<span class="warning-dot"></span>' ?><strong><?=e($raw)?></strong><input type="hidden" name="teacher_raw[]" value="<?=e($raw)?>"></div><select class="form-select form-select-sm" name="teacher_value[]"><option value="">— Chưa ghép —</option><?php foreach($teachers as $t):?><option value="<?=e($t)?>" <?=$value===$t?'selected':''?>><?=e($t)?></option><?php endforeach;?></select></div><?php endforeach;?></div></div><div><h6>Lớp trong Excel</h6><div class="mapping-list"><?php foreach($classAliases as $raw):$value=(string)($mapping['classes'][$raw]??'');?><div class="mapping-row"><div><?= $value?'<span class="ok-dot"></span>':'<span class="warning-dot"></span>' ?><strong><?=e($raw)?></strong><input type="hidden" name="class_raw[]" value="<?=e($raw)?>"></div><select class="form-select form-select-sm" name="class_value[]"><option value="">— Chưa ghép —</option><?php foreach($classes as $c):?><option value="<?=e($c)?>" <?=$value===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div><?php endforeach;?></div></div></div></form><?php endif;?>
<?php endif;?>
<?php require_once __DIR__.'/includes/footer.php'; ?>
