<?php
$page_title='Thời khóa biểu';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/timetable_store.php';
$user=cds_user();
if(!$user){$next=$_SERVER['REQUEST_URI']??(BASE_URL.'thoikhoabieu.php');header('Location: /login.php?next='.urlencode($next));exit;}
$isAdmin=(($user['role']??'')==='admin');
if(!cds_can_feature('cm.tracuu','view')&&!$isAdmin){http_response_code(403);exit('Bạn chưa có quyền xem Thời khóa biểu.');}
$canSub=$isAdmin||cds_can_feature('cm.pccm','edit');
$canSettings=$isAdmin||cds_can_feature('cm.nhaplieu','edit');
$tab=(string)($_GET['tab']??'lookup');if(!in_array($tab,['lookup','substitution','settings'],true))$tab='lookup';if($tab==='substitution'&&!$canSub)$tab='lookup';if($tab==='settings'&&!$canSettings)$tab='lookup';
if(empty($_SESSION['tkb_csrf']))$_SESSION['tkb_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['tkb_csrf'];
$teachers=array_values(array_filter(array_map('strval',(array)load_json(TEACHERS_FILE,[]))));$teachers=sort_teachers_by_ten($teachers);
$classes=array_values(array_filter(array_map('strval',(array)load_json(CLASSES_FILE,[]))));sort($classes,SORT_NATURAL|SORT_FLAG_CASE);
function tkb_redirect(string $tab): never {header('Location: '.BASE_URL.'thoikhoabieu.php?tab='.$tab);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))){flash('Phiên làm việc không hợp lệ.','danger');tkb_redirect($tab);}
    $action=(string)($_POST['action']??'');
    if($action==='upload'&&$canSettings){
        $upload=$_FILES['tkb_file']??null;$start=trim((string)($_POST['start_date']??''));$label=trim((string)($_POST['week_label']??''));
        if(!$upload||($upload['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK){flash('Hãy chọn file Excel thời khóa biểu.','danger');tkb_redirect('settings');}
        if(strtolower(pathinfo((string)($upload['name']??''),PATHINFO_EXTENSION))!=='xlsx'){flash('Chỉ hỗ trợ file .xlsx.','danger');tkb_redirect('settings');}
        if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)){flash('Hãy chọn ngày bắt đầu tuần.','danger');tkb_redirect('settings');}
        $result=tkb_import_week((string)$upload['tmp_name'],$label,$start,$teachers,$classes,(string)($user['name']??''));
        flash($result['message']??(!empty($result['ok'])?'Đã cập nhật thời khóa biểu tuần mới.':'Không nhập được thời khóa biểu.'),!empty($result['ok'])?'success':'danger');tkb_redirect('settings');
    }
    if($action==='mapping'&&$canSettings){$teacherMap=[];$classMap=[];foreach((array)($_POST['teacher_raw']??[]) as $i=>$raw)$teacherMap[(string)$raw]=(string)($_POST['teacher_value'][$i]??'');foreach((array)($_POST['class_raw']??[]) as $i=>$raw)$classMap[(string)$raw]=(string)($_POST['class_value'][$i]??'');tkb_save_mapping($teacherMap,$classMap);flash('Đã lưu bảng ghép tên giáo viên và lớp.','success');tkb_redirect('settings');}
    if($action==='substitution'&&$canSub){
        $week=tkb_week_by_id((string)($_POST['week_id']??''))?:tkb_active_week();$date=(string)($_POST['date']??'');$slotKey=(string)($_POST['slot_key']??'');$sub=trim((string)($_POST['substitute_teacher']??''));
        if(!$week||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$slotKey===''||$sub===''){flash('Thiếu dữ liệu dạy thay.','danger');tkb_redirect('substitution');}
        $target=null;foreach(tkb_resolved_slots($week) as $slot)if(tkb_slot_key($slot)===$slotKey){$target=$slot;break;}
        if(!$target){flash('Không tìm thấy tiết học cần dạy thay.','danger');tkb_redirect('substitution');}
        if(tkb_teacher_busy($week,$sub,(int)$target['day'],(string)$target['session'],(int)$target['period'],$date)){flash($sub.' đang có lịch ở tiết này, không thể xếp dạy thay.','danger');tkb_redirect('substitution');}
        $fit=tkb_teacher_fit($sub,$target,$week,$date);
        $row=['id'=>'sub_'.bin2hex(random_bytes(6)),'date'=>$date,'week_id'=>$week['id'],'slot_key'=>$slotKey,'day'=>(int)$target['day'],'session'=>(string)$target['session'],'period'=>(int)$target['period'],'class'=>(string)($target['class']?:$target['class_raw']),'class_raw'=>(string)($target['class_raw']??''),'subject'=>(string)$target['subject'],'absent_teacher'=>(string)($target['teacher']?:$target['teacher_raw']),'substitute_teacher'=>$sub,'fit_labels'=>$fit['labels'],'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c'),'updated_by'=>(string)($user['name']??'')];
        tkb_save_substitution($row);flash('Đã xác nhận '.$sub.' dạy thay. Thông tin đã được đánh dấu trên thời khóa biểu.','success');tkb_redirect('substitution');
    }
}
$weeks=tkb_weeks();$weekId=(string)($_GET['week_id']??'');$week=$weekId!==''?tkb_week_by_id($weekId):tkb_active_week();$slots=$week?tkb_resolved_slots($week):[];$mapping=tkb_mapping();
$lookupMode=(string)($_GET['mode']??'school');if(!in_array($lookupMode,['school','teacher','class'],true))$lookupMode='school';$teacherFilter=trim((string)($_GET['teacher']??''));$classFilter=trim((string)($_GET['class']??''));
$subDate=(string)($_GET['date']??date('Y-m-d'));$absentTeacher=trim((string)($_GET['absent_teacher']??''));$subDay=(int)date('N',strtotime($subDate))+1;$absentSlots=array_values(array_filter($slots,fn($s)=>$absentTeacher!==''&&($s['teacher']??'')===$absentTeacher&&(int)$s['day']===$subDay));$subRows=array_values(array_filter(tkb_substitutions(),fn($r)=>($r['date']??'')===$subDate));

function tkb_lookup_slots(array $week,array $slots,string $mode,string $teacher,string $class): array {
    $out=[];
    foreach($slots as $s){
        $resolvedClass=(string)($s['class']?:$s['class_raw']);$include=$mode==='school'||($mode==='class'&&$class!==''&&$resolvedClass===$class)||($mode==='teacher'&&$teacher!==''&&($s['teacher']??'')===$teacher);
        if(!$include)continue;$s['_sub']=tkb_substitution_for_slot($week,$s);$s['_sub_role']='';if($mode==='teacher'&&$s['_sub']&&($s['_sub']['absent_teacher']??'')===$teacher)$s['_sub_role']='absent';$out[]=$s;
    }
    if($mode==='teacher'&&$teacher!=='')foreach(tkb_week_substitutions($week) as $r)if(($r['substitute_teacher']??'')===$teacher){
        $synthetic=['day'=>(int)$r['day'],'session'=>(string)$r['session'],'period'=>(int)$r['period'],'class'=>(string)$r['class'],'class_raw'=>(string)($r['class_raw']??$r['class']),'subject'=>(string)$r['subject'],'teacher'=>$teacher,'teacher_raw'=>$teacher,'_sub'=>$r,'_sub_role'=>'substitute'];$out[]=$synthetic;
    }
    return $out;
}
function tkb_matrix(array $slots): array {$grid=[];$max=['Sáng'=>4,'Chiều'=>4];foreach($slots as $s){$session=mb_stripos((string)$s['session'],'chiều',0,'UTF-8')!==false?'Chiều':'Sáng';$period=(int)$s['period'];$max[$session]=max($max[$session]??0,$period);$grid[$session][$period][(int)$s['day']][]=$s;}return [$grid,$max];}
function tkb_cell_html(array $items,string $mode): string {
    if(!$items)return '';$parts=[];foreach($items as $s){$class=(string)($s['class']?:$s['class_raw']);$teacher=(string)($s['teacher']?:$s['teacher_raw']);$main=e((string)$s['subject']);$small=[];
        if($mode==='teacher')$small[]='<span class="tkb-class-mini">'.e($class).'</span>';elseif($mode!=='school')$small[]='<span class="tkb-teacher-mini">'.e($teacher).'</span>';
        $sub=$s['_sub']??null;$role=$s['_sub_role']??'';if($sub){if($role==='substitute')$small[]='<span class="tkb-sub-note"><i class="bi bi-arrow-repeat"></i> Dạy thay cho '.e((string)$sub['absent_teacher']).'</span>';elseif($role==='absent')$small[]='<span class="tkb-sub-note"><i class="bi bi-person-dash"></i> Nghỉ · '.e((string)$sub['substitute_teacher']).' dạy thay</span>';else $small[]='<span class="tkb-sub-note"><i class="bi bi-arrow-repeat"></i> Dạy thay: '.e((string)$sub['substitute_teacher']).'</span>';}
        if($mode==='school')$small[]='<span class="tkb-class-mini">'.e($class).' · '.e($teacher).'</span>';$parts[]='<div class="tkb-cell-item"><div class="tkb-subject">'.$main.'</div>'.implode('',$small).'</div>';}
    return implode('<div class="tkb-cell-sep"></div>',$parts);
}
function tkb_render_matrix(array $slots,string $mode,string $title=''): void {[$grid,$max]=tkb_matrix($slots);if($title!=='')echo '<h5 class="tkb-matrix-title">'.e($title).'</h5>';echo '<div class="tkb-matrix-wrap"><table class="tkb-matrix"><thead><tr><th class="session-col">Buổi</th><th class="period-col">Tiết</th>';for($d=2;$d<=7;$d++)echo '<th>Thứ '.$d.'</th>';echo '</tr></thead><tbody>';foreach(['Sáng','Chiều'] as $session){$count=max(1,(int)($max[$session]??4));for($p=1;$p<=$count;$p++){echo '<tr>';if($p===1)echo '<th class="session-name" rowspan="'.$count.'">'.($session==='Sáng'?'S':'C').'</th>';echo '<th class="period-no">'.$p.'</th>';for($d=2;$d<=7;$d++){echo '<td>'.tkb_cell_html((array)($grid[$session][$p][$d]??[]),$mode).'</td>';}echo '</tr>';}}echo '</tbody></table></div>';}
$lookupSlots=$week?tkb_lookup_slots($week,$slots,$lookupMode,$teacherFilter,$classFilter):[];
require_once __DIR__.'/includes/header.php';
?>
<style>
.tkb-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;flex-wrap:wrap;margin-bottom:1rem}.tkb-head h2{color:#173f65;font-weight:800}.tkb-tabs{display:flex;gap:.4rem;flex-wrap:wrap;padding:.35rem;border:1px solid #dce6ef;border-radius:14px;background:#fff}.tkb-tabs a{display:flex;align-items:center;gap:.4rem;padding:.6rem .85rem;border-radius:10px;color:#315b7d;text-decoration:none;font-weight:750}.tkb-tabs a.active{background:#1f5d8d;color:#fff}.tkb-card{border:1px solid #dfe8f0;border-radius:16px;background:#fff;box-shadow:0 4px 18px rgba(15,23,42,.05)}.tkb-filter{padding:1rem;margin-bottom:1rem}.tkb-radio{display:flex;gap:1rem;flex-wrap:wrap}.tkb-radio label{font-weight:700}.mapping-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.mapping-list{max-height:520px;overflow:auto}.mapping-row{display:grid;grid-template-columns:minmax(130px,1fr) minmax(180px,1.3fr);gap:.55rem;align-items:center;padding:.45rem 0;border-bottom:1px solid #edf2f7}.warning-dot,.ok-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:.35rem}.warning-dot{background:#dc3545}.ok-dot{background:#198754}
.tkb-matrix-title{margin:1.2rem 0 .55rem;color:#173f65;font-weight:800}.tkb-matrix-wrap{overflow:auto;background:#fff;border-radius:14px;border:1px solid #cfd8e1;margin-bottom:1rem}.tkb-matrix{border-collapse:collapse;width:100%;min-width:930px;table-layout:fixed}.tkb-matrix th,.tkb-matrix td{border:1px solid #6c757d;text-align:center;vertical-align:middle}.tkb-matrix thead th{height:50px;background:#f2f4f6;font-weight:800;color:#111}.tkb-matrix td{height:62px;padding:.35rem .4rem;background:#fff}.tkb-matrix tbody tr:nth-child(even) td{background:#fafafa}.session-col{width:62px}.period-col{width:58px}.session-name{font-size:1.15rem;background:#fff!important}.period-no{font-size:1rem;background:#fff!important}.tkb-subject{font-weight:750;color:#161616;line-height:1.15}.tkb-teacher-mini,.tkb-class-mini,.tkb-sub-note{display:block;margin-top:.18rem;font-size:.69rem;line-height:1.15}.tkb-teacher-mini{color:#d6335c}.tkb-class-mini{color:#52606d;font-weight:700}.tkb-sub-note{color:#b45309;font-weight:800}.tkb-cell-sep{border-top:1px dashed #cbd5e1;margin:.28rem 0}.fit-badges{display:flex;flex-wrap:wrap;gap:.25rem;margin-top:.25rem}.fit-badge{font-size:.66rem;padding:.18rem .38rem;border-radius:999px;background:#e8f4ff;color:#175985;font-weight:750}.sub-choice-note{font-size:.72rem;color:#64748b;margin-top:.25rem}.tkb-table th{background:#eaf3fb;color:#173f65;white-space:nowrap}.tkb-table td{vertical-align:middle}
@media(max-width:767px){.tkb-tabs{width:100%;overflow:auto;flex-wrap:nowrap}.tkb-tabs a{white-space:nowrap}.mapping-grid{grid-template-columns:1fr}.tkb-filter .row>*{margin-bottom:.4rem}.tkb-matrix{min-width:820px}.tkb-matrix td{height:56px;padding:.25rem}.tkb-subject{font-size:.82rem}}
@media print{.cm-desktop-sidebar,.cm-mobile-bottom,.tkb-head,.tkb-filter{display:none!important}body{padding:0!important}.tkb-matrix-wrap{overflow:visible;border:0}.tkb-matrix{min-width:0;font-size:10px}.tkb-matrix th,.tkb-matrix td{height:auto;padding:3px}}
</style>
<div class="tkb-head"><div><h2 class="mb-1"><i class="bi bi-calendar3"></i> Thời khóa biểu</h2><div class="text-muted">Tra cứu theo ma trận · quản lý dạy thay · cập nhật Excel theo tuần</div></div><nav class="tkb-tabs"><a class="<?=$tab==='lookup'?'active':''?>" href="<?=BASE_URL?>thoikhoabieu.php?tab=lookup"><i class="bi bi-search"></i>Tra cứu TKB</a><?php if($canSub):?><a class="<?=$tab==='substitution'?'active':''?>" href="<?=BASE_URL?>thoikhoabieu.php?tab=substitution"><i class="bi bi-person-check"></i>Lịch dạy thay</a><?php endif;?><?php if($canSettings):?><a class="<?=$tab==='settings'?'active':''?>" href="<?=BASE_URL?>thoikhoabieu.php?tab=settings"><i class="bi bi-gear"></i>Cài đặt</a><?php endif;?></nav></div>
<?php show_flash(); ?>
<?php if(!$week):?><div class="alert alert-warning"><i class="bi bi-exclamation-triangle"></i> Chưa có dữ liệu thời khóa biểu. Người có quyền hãy vào tab <strong>Cài đặt</strong> để tải file Excel tuần đầu tiên.</div><?php endif;?>

<?php if($tab==='lookup'):?>
<form class="tkb-card tkb-filter" method="get" action="<?=BASE_URL?>thoikhoabieu.php"><input type="hidden" name="tab" value="lookup"><div class="row g-3 align-items-end"><div class="col-lg-4"><label class="form-label fw-bold">Phạm vi xem</label><div class="tkb-radio"><label><input type="radio" name="mode" value="school" <?=$lookupMode==='school'?'checked':''?> onchange="this.form.submit()"> Toàn trường</label><label><input type="radio" name="mode" value="teacher" <?=$lookupMode==='teacher'?'checked':''?> onchange="this.form.submit()"> Theo giáo viên</label><label><input type="radio" name="mode" value="class" <?=$lookupMode==='class'?'checked':''?> onchange="this.form.submit()"> Theo lớp</label></div></div><div class="col-lg-3"><label class="form-label">Chọn TKB</label><select class="form-select" name="week_id" onchange="this.form.submit()"><?php foreach(array_reverse($weeks) as $w):?><option value="<?=e($w['id'])?>" <?=($week['id']??'')===$w['id']?'selected':''?>><?=e($w['label'])?> · <?=e(date('d/m',strtotime($w['start_date'])))?>–<?=e(date('d/m/Y',strtotime($w['end_date'])))?></option><?php endforeach;?></select></div><?php if($lookupMode==='teacher'):?><div class="col-lg-3"><label class="form-label">Chọn giáo viên</label><select class="form-select" name="teacher" onchange="this.form.submit()"><option value="">Chọn giáo viên...</option><?php foreach($teachers as $t):?><option value="<?=e($t)?>" <?=$teacherFilter===$t?'selected':''?>><?=e($t)?></option><?php endforeach;?></select></div><?php elseif($lookupMode==='class'):?><div class="col-lg-3"><label class="form-label">Chọn lớp</label><select class="form-select" name="class" onchange="this.form.submit()"><option value="">Chọn lớp...</option><?php foreach($classes as $c):?><option value="<?=e($c)?>" <?=$classFilter===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div><?php endif;?><div class="col-lg-2"><button type="button" class="btn btn-outline-primary w-100" onclick="window.print()"><i class="bi bi-printer"></i> In TKB</button></div></div></form>
<?php if($week):?>
    <?php if($lookupMode==='teacher'&&$teacherFilter!==''): tkb_render_matrix($lookupSlots,'teacher','Thời khóa biểu giáo viên '.$teacherFilter); ?>
    <?php elseif($lookupMode==='class'&&$classFilter!==''): tkb_render_matrix($lookupSlots,'class','Thời khóa biểu lớp '.$classFilter); ?>
    <?php elseif($lookupMode==='school'): foreach($classes as $c){$classSlots=tkb_lookup_slots($week,$slots,'class','',$c);if($classSlots)tkb_render_matrix($classSlots,'class','Lớp '.$c);} ?>
    <?php else:?><div class="alert alert-info">Hãy chọn <?= $lookupMode==='teacher'?'giáo viên':'lớp' ?> để xem thời khóa biểu.</div><?php endif;?>
<?php endif;?>

<?php elseif($tab==='substitution'&&$canSub):?>
<form class="tkb-card tkb-filter" method="get" action="<?=BASE_URL?>thoikhoabieu.php"><input type="hidden" name="tab" value="substitution"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label fw-bold">Ngày nghỉ</label><input class="form-control" type="date" name="date" value="<?=e($subDate)?>"></div><div class="col-md-5"><label class="form-label fw-bold">Giáo viên nghỉ</label><select class="form-select" name="absent_teacher"><option value="">Chọn giáo viên...</option><?php foreach($teachers as $t):?><option value="<?=e($t)?>" <?=$absentTeacher===$t?'selected':''?>><?=e($t)?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="bi bi-arrow-repeat"></i> Lấy tiết nghỉ</button></div></div></form>
<?php if($absentTeacher&&$week):?><div class="tkb-card table-responsive mb-3"><table class="table tkb-table mb-0"><thead><tr><th>Buổi</th><th>Tiết</th><th>Lớp</th><th>Môn</th><th>GV nghỉ</th><th style="min-width:360px">Chọn giáo viên dạy thay</th></tr></thead><tbody>
<?php foreach($absentSlots as $s):$saved=null;foreach($subRows as $r)if(($r['slot_key']??'')===tkb_slot_key($s)){$saved=$r;break;}$candidates=tkb_substitute_candidates($teachers,$s,$week,$subDate,$absentTeacher);?>
<tr><td><?=e($s['session'])?></td><td class="text-center fw-bold"><?=e($s['period'])?></td><td><strong><?=e($s['class']?:$s['class_raw'])?></strong></td><td><?=e($s['subject'])?></td><td class="text-danger fw-bold"><?=e($absentTeacher)?></td><td><form method="post" action="<?=BASE_URL?>thoikhoabieu.php?tab=substitution" class="d-flex gap-2 align-items-start"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="substitution"><input type="hidden" name="week_id" value="<?=e($week['id'])?>"><input type="hidden" name="date" value="<?=e($subDate)?>"><input type="hidden" name="slot_key" value="<?=e(tkb_slot_key($s))?>"><div class="flex-grow-1"><select class="form-select form-select-sm" name="substitute_teacher" required><option value="">Chọn GV phù hợp...</option><?php foreach($candidates as $c):$label=$c['teacher'];if($c['labels'])$label.=' — '.implode(' · ',$c['labels']);if($c['busy'])$label.=' — ĐANG BẬN';?><option value="<?=e($c['teacher'])?>" <?=($saved['substitute_teacher']??'')===$c['teacher']?'selected':''?> <?=$c['busy']?'disabled':''?>><?=e($label)?></option><?php endforeach;?></select><div class="sub-choice-note">Ưu tiên tự động: <strong>cùng chuyên môn</strong> → đã dạy lớp này → cùng khối. Giáo viên đang bận sẽ không chọn được.</div><?php if($saved):?><div class="fit-badges"><span class="fit-badge">Đã xếp: <?=e($saved['substitute_teacher'])?></span><?php foreach((array)($saved['fit_labels']??[]) as $lb):?><span class="fit-badge"><?=e($lb)?></span><?php endforeach;?></div><?php endif;?></div><button class="btn btn-sm btn-success"><i class="bi bi-check2"></i> Xác nhận</button></form></td></tr>
<?php endforeach;if(!$absentSlots):?><tr><td colspan="6" class="text-center text-muted py-4">Giáo viên này không có tiết trong ngày đã chọn.</td></tr><?php endif;?></tbody></table></div><?php endif;?>
<?php if($subRows):?><div class="tkb-card p-3"><h5 class="mb-3"><i class="bi bi-list-check"></i> Lịch dạy thay ngày <?=e(date('d/m/Y',strtotime($subDate)))?></h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tiết</th><th>Lớp</th><th>Môn</th><th>GV nghỉ</th><th>GV dạy thay</th><th>Mức phù hợp</th></tr></thead><tbody><?php foreach($subRows as $r):?><tr><td><?=e($r['session'])?> · <?=e($r['period'])?></td><td><?=e($r['class'])?></td><td><?=e($r['subject'])?></td><td><?=e($r['absent_teacher'])?></td><td><strong class="text-success"><?=e($r['substitute_teacher'])?></strong></td><td><?php foreach((array)($r['fit_labels']??[]) as $lb):?><span class="fit-badge"><?=e($lb)?></span> <?php endforeach;?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>

<?php elseif($tab==='settings'&&$canSettings):?>
<div class="row g-3 mb-3"><div class="col-lg-5"><section class="tkb-card p-4 h-100"><h5><i class="bi bi-file-earmark-excel text-success"></i> Cập nhật TKB tuần</h5><p class="text-muted small">File Excel dùng cấu trúc như mẫu: Lớp · Buổi · Tiết, sau đó mỗi Thứ gồm 2 cột Môn và Giáo viên.</p><form method="post" action="<?=BASE_URL?>thoikhoabieu.php?tab=settings" enctype="multipart/form-data" class="vstack gap-3"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="upload"><div><label class="form-label fw-bold">Tên tuần</label><input class="form-control" name="week_label" placeholder="Ví dụ: Tuần 3"></div><div><label class="form-label fw-bold">Ngày Thứ 2 bắt đầu tuần</label><input class="form-control" type="date" name="start_date" required></div><div><label class="form-label fw-bold">File Excel (.xlsx)</label><input class="form-control" type="file" name="tkb_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></div><button class="btn btn-success"><i class="bi bi-cloud-arrow-up"></i> Tải lên và dùng làm TKB hiện hành</button></form></section></div><div class="col-lg-7"><section class="tkb-card p-4 h-100"><h5><i class="bi bi-clock-history"></i> Các tuần đã cập nhật</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tuần</th><th>Áp dụng</th><th>Số tiết</th><th>Trạng thái</th></tr></thead><tbody><?php foreach(array_reverse($weeks) as $w):?><tr><td><strong><?=e($w['label'])?></strong><br><small><?=e($w['uploaded_by']??'')?></small></td><td><?=e(date('d/m/Y',strtotime($w['start_date'])))?> – <?=e(date('d/m/Y',strtotime($w['end_date'])))?></td><td><?=count((array)($w['slots']??[]))?></td><td><?=$w['active']?'<span class="badge text-bg-success">Hiện hành</span>':'<span class="badge text-bg-secondary">Lưu trữ</span>'?></td></tr><?php endforeach;if(!$weeks):?><tr><td colspan="4" class="text-muted">Chưa có dữ liệu.</td></tr><?php endif;?></tbody></table></div></section></div></div>
<?php if($week):$teacherAliases=tkb_aliases($week,'teacher_raw');$classAliases=tkb_aliases($week,'class_raw');?><form method="post" action="<?=BASE_URL?>thoikhoabieu.php?tab=settings" class="tkb-card p-4"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="mapping"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h5 class="mb-1"><i class="bi bi-link-45deg"></i> Ghép dữ liệu Excel với danh mục CDS</h5><div class="small text-muted">Tên đã ghép sẽ được ghi nhớ và tự dùng cho các tuần sau.</div></div><button class="btn btn-primary"><i class="bi bi-floppy"></i> Lưu bảng ghép</button></div><div class="mapping-grid"><div><h6>Giáo viên trong Excel</h6><div class="mapping-list"><?php foreach($teacherAliases as $raw):$value=(string)($mapping['teachers'][$raw]??'');?><div class="mapping-row"><div><?= $value?'<span class="ok-dot"></span>':'<span class="warning-dot"></span>' ?><strong><?=e($raw)?></strong><input type="hidden" name="teacher_raw[]" value="<?=e($raw)?>"></div><select class="form-select form-select-sm" name="teacher_value[]"><option value="">— Chưa ghép —</option><?php foreach($teachers as $t):?><option value="<?=e($t)?>" <?=$value===$t?'selected':''?>><?=e($t)?></option><?php endforeach;?></select></div><?php endforeach;?></div></div><div><h6>Lớp trong Excel</h6><div class="mapping-list"><?php foreach($classAliases as $raw):$value=(string)($mapping['classes'][$raw]??'');?><div class="mapping-row"><div><?= $value?'<span class="ok-dot"></span>':'<span class="warning-dot"></span>' ?><strong><?=e($raw)?></strong><input type="hidden" name="class_raw[]" value="<?=e($raw)?>"></div><select class="form-select form-select-sm" name="class_value[]"><option value="">— Chưa ghép —</option><?php foreach($classes as $c):?><option value="<?=e($c)?>" <?=$value===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div><?php endforeach;?></div></div></div></form><?php endif;?>
<?php endif;?>
<?php require_once __DIR__.'/includes/footer.php'; ?>
