<?php
$page_title='In và xuất phương án TKB';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/timetable_store.php';
require_once dirname(__DIR__).'/includes/timetable_builder.php';
$user=cds_user();if(!$user){header('Location: /login.php?next='.urlencode($_SERVER['REQUEST_URI']??''));exit;}
$canManage=(($user['role']??'')==='admin')||cds_can_feature('cm.nhaplieu','edit');if(!$canManage){http_response_code(403);exit('Bạn chưa có quyền in phương án TKB.');}
$data=ttb_data();$plan=ttb_plan($data,(string)($data['active_plan']??''));$assignments=ttb_assignments();$classes=array_values(array_unique(array_column($assignments,'class')));sort($classes,SORT_NATURAL|SORT_FLAG_CASE);$teachers=array_values(array_unique(array_column($assignments,'teacher')));natcasesort($teachers);$mode=(string)($_GET['mode']??'class');if(!in_array($mode,['class','teacher','school'],true))$mode='class';$class=(string)($_GET['class']??($classes[0]??''));$teacher=(string)($_GET['teacher']??($teachers?reset($teachers):''));
$entries=(array)($plan['entries']??[]);$filtered=array_values(array_filter($entries,function($e)use($mode,$class,$teacher){return$mode==='school'||($mode==='teacher'&&($e['teacher']??'')===$teacher)||($mode==='class'&&in_array($class,(array)($e['classes']??[]),true));}));
if(($_GET['download']??'')==='excel'){header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="phuong-an-tkb-'.date('Ymd-His').'.xls"');echo"\xEF\xBB\xBF";echo'<table border="1"><tr><th>Thứ</th><th>Buổi</th><th>Tiết</th><th>Lớp</th><th>Môn</th><th>Giáo viên</th></tr>';foreach($filtered as$e)echo'<tr><td>'.e($e['day']).'</td><td>'.e($e['session']).'</td><td>'.e($e['period']).'</td><td>'.e(implode(' + ',$e['classes'])).'</td><td>'.e($e['subject']).'</td><td>'.e($e['teacher']).'</td></tr>';echo'</table>';exit;}
function tkbp_matrix(array$entries,array$settings,string$title):void{$grid=[];foreach($entries as$e)$grid[$e['session']][$e['period']][$e['day']][]=$e;echo'<h5 class="print-title">'.e($title).'</h5><table class="print-grid"><thead><tr><th>Buổi</th><th>Tiết</th>';foreach($settings['days']as$d)echo'<th>Thứ '.e($d).'</th>';echo'</tr></thead><tbody>';foreach(['Sáng'=>(int)$settings['morning_periods'],'Chiều'=>(int)$settings['afternoon_periods']]as$session=>$max)for($p=1;$p<=$max;$p++){echo'<tr>';if($p===1)echo'<th rowspan="'.$max.'">'.e($session).'</th>';echo'<th>'.$p.'</th>';foreach($settings['days']as$d){echo'<td>';foreach((array)($grid[$session][$p][$d]??[])as$e)echo'<strong>'.e($e['subject']).'</strong><small>'.e(implode(' + ',$e['classes'])).' · '.e($e['teacher']).'</small>';echo'</td>';}echo'</tr>';}echo'</tbody></table>';}
require_once __DIR__.'/includes/header.php';
?>
<style>.print-toolbar,.print-sheet{background:#fff;border:1px solid #dbe5ed;border-radius:14px}.print-grid{width:100%;border-collapse:collapse;table-layout:fixed;font-size:.78rem}.print-grid th,.print-grid td{border:1px solid #7f8b96;text-align:center;vertical-align:middle;padding:.22rem}.print-grid th{background:#edf4f9}.print-grid td{height:48px}.print-grid strong,.print-grid small{display:block;line-height:1.12}.print-grid small{color:#596b7c}.print-title{text-align:center;color:#173f65;font-weight:800;margin:1rem 0 .5rem}@media print{.cm-desktop-sidebar,.cm-mobile-bottom,.print-toolbar,.page-head{display:none!important}.print-sheet{border:0}.print-grid{font-size:9px}.print-grid td{height:auto}@page{size:A4 landscape;margin:10mm}}</style>
<div class="page-head d-flex justify-content-between align-items-center mb-3"><div><h2 class="mb-0 text-primary"><i class="bi bi-printer"></i> In và xuất phương án TKB</h2><small class="text-muted">Xem trước trước khi in, lưu PDF hoặc tải Excel.</small></div><a class="btn btn-outline-secondary" href="/tkb_xep.php?tab=plan">Quay lại xem & chỉnh</a></div>
<?php if(!$plan):?><div class="alert alert-warning">Chưa có phương án đang làm việc.</div><?php else:?><form class="print-toolbar p-3 mb-3 d-flex gap-2 flex-wrap align-items-end"><div><label class="form-label">Phạm vi</label><select class="form-select" name="mode" onchange="this.form.submit()"><option value="class" <?=$mode==='class'?'selected':''?>>Theo lớp</option><option value="teacher" <?=$mode==='teacher'?'selected':''?>>Theo giáo viên</option><option value="school" <?=$mode==='school'?'selected':''?>>Toàn trường</option></select></div><?php if($mode==='class'):?><div><label class="form-label">Lớp</label><select class="form-select" name="class" onchange="this.form.submit()"><?php foreach($classes as$c):?><option <?=$class===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div><?php elseif($mode==='teacher'):?><div><label class="form-label">Giáo viên</label><select class="form-select" name="teacher" onchange="this.form.submit()"><?php foreach($teachers as$t):?><option <?=$teacher===$t?'selected':''?>><?=e($t)?></option><?php endforeach;?></select></div><?php endif;?><button type="button" class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer"></i> In / Lưu PDF</button><a class="btn btn-success" href="?<?=e(http_build_query(array_merge($_GET,['download'=>'excel'])))?>"><i class="bi bi-file-earmark-excel"></i> Xuất Excel</a></form><section class="print-sheet p-3"><?php if($mode==='school'):foreach($classes as$c){$rows=array_values(array_filter($entries,fn($e)=>in_array($c,(array)$e['classes'],true)));tkbp_matrix($rows,$data['settings'],'THỜI KHÓA BIỂU LỚP '.$c);}elseif($mode==='teacher'):tkbp_matrix($filtered,$data['settings'],'THỜI KHÓA BIỂU GIÁO VIÊN '.$teacher);else:tkbp_matrix($filtered,$data['settings'],'THỜI KHÓA BIỂU LỚP '.$class);endif;?></section><?php endif;?>
<?php require_once __DIR__.'/includes/footer.php';?>
