<?php
$page_title='Xuất thời khóa biểu toàn trường';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/timetable_store.php';
$user=cds_user();
if(!$user){header('Location: /login.php?next='.urlencode($_SERVER['REQUEST_URI']??''));exit;}
$isAdmin=(($user['role']??'')==='admin');
if(!cds_can_feature('cm.tracuu','view')&&!$isAdmin){http_response_code(403);exit('Bạn chưa có quyền xem Thời khóa biểu.');}
$weekId=trim((string)($_GET['week_id']??''));
$week=$weekId!==''?tkb_week_by_id($weekId):tkb_active_week();
if(!$week){http_response_code(404);exit('Chưa có dữ liệu thời khóa biểu.');}
$slots=tkb_resolved_slots($week);
$classes=array_values(array_filter(array_map('strval',(array)load_json(CLASSES_FILE,[]))));sort($classes,SORT_NATURAL|SORT_FLAG_CASE);
$grid=[];$max=['Sáng'=>4,'Chiều'=>4];
foreach($slots as $s){
 $class=trim((string)($s['class']?:$s['class_raw']));if($class==='')continue;
 $session=mb_stripos((string)($s['session']??''),'chiều',0,'UTF-8')!==false?'Chiều':'Sáng';
 $p=(int)($s['period']??0);$d=(int)($s['day']??0);if($p<1||$d<2||$d>7)continue;
 $max[$session]=max($max[$session]??4,$p);$grid[$d][$session][$p][$class][]=$s;
}
function sx_short_teacher($name){$name=trim((string)$name);$parts=preg_split('/\s+/u',$name);if(count($parts)<2)return$name;$last=array_pop($parts);$ini='';foreach($parts as$p)$ini.=mb_strtoupper(mb_substr($p,0,1,'UTF-8'),'UTF-8').'.';return$ini.$last;}
function sx_cell($items){if(!$items)return'';$out=[];foreach($items as$s){$sub=tkb_substitution_for_slot($GLOBALS['week'],$s);$teacher=(string)($s['teacher']?:$s['teacher_raw']);if(is_array($sub)&&($sub['status']??'')==='approved'&&trim((string)($sub['substitute_teacher']??''))!=='')$teacher=(string)$sub['substitute_teacher'];$out[]='<strong>'.e((string)($s['subject']??'')).'</strong><small>'.e(sx_short_teacher($teacher)).'</small>';}return implode('<hr>',$out);}
$school=defined('SCHOOL_NAME')?SCHOOL_NAME:'Trường PTDTNT THCS&THPT Xín Mần';
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($page_title)?></title><script src="https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js"></script><style>
*{box-sizing:border-box}body{margin:0;background:#eef3f8;font-family:Arial,"Segoe UI",sans-serif;color:#172033}.toolbar{position:sticky;top:0;z-index:20;background:#fff;border-bottom:1px solid #d8e1ea;padding:10px 18px;display:flex;gap:8px;justify-content:center}.toolbar button,.toolbar a{border:1px solid #1f5d8d;background:#fff;color:#1f5d8d;border-radius:8px;padding:9px 15px;font-weight:700;text-decoration:none;cursor:pointer}.toolbar .primary{background:#1f5d8d;color:#fff}.sheet{width:calc(100% - 24px);max-width:1800px;margin:12px auto;background:#fff;padding:18px;box-shadow:0 2px 14px #0001}.head{text-align:center;margin-bottom:14px}.head .school{font-size:17px;color:#526579}.head h1{font-size:27px;color:#173f65;margin:5px 0}.head .week{font-size:15px}.day{break-inside:avoid;margin:15px 0 20px}.day h2{text-align:center;font-size:18px;color:#173f65;margin:0 0 6px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}th,td{border:1px solid #8797a8;text-align:center;vertical-align:middle;padding:4px 3px;overflow-wrap:anywhere}thead th{background:#dceeff;color:#123f64;font-weight:800}.session{width:42px;font-weight:900}.period{width:38px;font-weight:800;background:#f5f8fb}.morning{background:#fff2b8}.afternoon{background:#dcfce7}td{height:44px}td strong{display:block;font-size:11px;line-height:1.1}td small{display:block;margin-top:2px;color:#d6335c;font-size:9px;line-height:1.05}td hr{border:0;border-top:1px dashed #cbd5e1;margin:3px 0}.foot{text-align:right;color:#64748b;font-size:10px;margin-top:8px}
@page{size:A3 landscape;margin:8mm}@media print{body{background:#fff}.toolbar{display:none}.sheet{width:100%;max-width:none;margin:0;padding:0;box-shadow:none}.day{page-break-inside:avoid}table{font-size:8.5px}td{height:35px;padding:2px}td strong{font-size:8.5px}td small{font-size:7px}.head h1{font-size:20px}.day h2{font-size:14px}}
</style></head><body><div class="toolbar"><a href="thoikhoabieu.php?tab=lookup&mode=school&week_id=<?=urlencode((string)$week['id'])?>">← Quay lại</a><button class="primary" onclick="window.print()">In / Lưu PDF</button><button onclick="saveImage()">Tải ảnh PNG</button></div><main class="sheet" id="schoolSheet"><header class="head"><div class="school"><?=e($school)?></div><h1>THỜI KHÓA BIỂU TOÀN TRƯỜNG</h1><div class="week"><?=e((string)($week['label']??''))?> · <?=e(date('d/m/Y',strtotime((string)$week['start_date'])))?> – <?=e(date('d/m/Y',strtotime((string)$week['end_date'])))?></div></header><?php for($d=2;$d<=7;$d++):?><section class="day"><h2>THỨ <?=$d?></h2><div class="table-wrap"><table><thead><tr><th class="session">Buổi</th><th class="period">Tiết</th><?php foreach($classes as$c):?><th><?=e($c)?></th><?php endforeach;?></tr></thead><tbody><?php foreach(['Sáng','Chiều']as$session):$cnt=max(1,(int)($max[$session]??4));for($p=1;$p<=$cnt;$p++):?><tr><?php if($p===1):?><th class="session <?=$session==='Sáng'?'morning':'afternoon'?>" rowspan="<?=$cnt?>"><?=$session==='Sáng'?'S':'C'?></th><?php endif;?><th class="period"><?=$p?></th><?php foreach($classes as$c):?><td><?=sx_cell((array)($grid[$d][$session][$p][$c]??[]))?></td><?php endforeach;?></tr><?php endfor;endforeach;?></tbody></table></div></section><?php endfor;?><div class="foot">HỆ SINH THÁI QUẢN LÝ NHÀ TRƯỜNG - Chuyên môn</div></main><script>
async function saveImage(){var el=document.getElementById('schoolSheet'),btn=event.currentTarget;btn.disabled=true;var old=btn.textContent;btn.textContent='Đang tạo ảnh...';try{var canvas=await html2canvas(el,{scale:2,backgroundColor:'#ffffff',useCORS:true});var a=document.createElement('a');a.download='TKB-toan-truong-<?=e(date('dmY',strtotime((string)$week['start_date'])))?>.png';a.href=canvas.toDataURL('image/png',1);a.click();}catch(e){alert('Không tạo được ảnh. Vui lòng dùng In / Lưu PDF.');}finally{btn.disabled=false;btn.textContent=old;}}
</script></body></html>