<?php
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/timetable_store.php';
header('Content-Type: application/json; charset=utf-8');
$user=cds_user();if(!$user){http_response_code(401);echo json_encode(['ok'=>false,'message'=>'Chưa đăng nhập.'],JSON_UNESCAPED_UNICODE);exit;}
if(!hash_equals((string)($_SESSION['tkb_range_csrf']??''),(string)($_POST['csrf']??''))){http_response_code(403);echo json_encode(['ok'=>false,'message'=>'Phiên làm việc không hợp lệ.'],JSON_UNESCAPED_UNICODE);exit;}
$isAdmin=(($user['role']??'')==='admin');$canApprove=$isAdmin||cds_can_feature('cm.pccm','edit');
$teachers=array_values(array_filter(array_map('strval',(array)load_json(TEACHERS_FILE,[]))));$selfTeacher=trim((string)($user['teacher_name']??$user['name']??''));if($selfTeacher!==''&&!in_array($selfTeacher,$teachers,true))foreach($teachers as$t)if(tkb_key($t)===tkb_key($selfTeacher)){$selfTeacher=$t;break;}
$date=trim((string)($_POST['date']??''));$week=tkb_week_by_id(trim((string)($_POST['week_id']??'')));$slotKey=trim((string)($_POST['slot_key']??''));$sub=trim((string)($_POST['substitute_teacher']??''));$absent=trim((string)($_POST['absent_teacher']??''));if(!$canApprove&&$selfTeacher!=='')$absent=$selfTeacher;
if(!$week||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$slotKey===''||$sub===''||$absent===''){echo json_encode(['ok'=>false,'message'=>'Thiếu dữ liệu đăng ký dạy thay.'],JSON_UNESCAPED_UNICODE);exit;}
$target=null;foreach(tkb_resolved_slots($week)as$slot)if(tkb_slot_key($slot)===$slotKey&&($slot['teacher']??'')===$absent){$target=$slot;break;}if(!$target){echo json_encode(['ok'=>false,'message'=>'Không tìm thấy tiết cần dạy thay.'],JSON_UNESCAPED_UNICODE);exit;}
if(tkb_teacher_busy($week,$sub,(int)$target['day'],(string)$target['session'],(int)$target['period'],$date)){echo json_encode(['ok'=>false,'message'=>$sub.' đang có lịch ở tiết này.'],JSON_UNESCAPED_UNICODE);exit;}
$fit=tkb_teacher_fit($sub,$target,$week,$date);$status=$canApprove?'approved':'pending';$className=(string)($target['class']?:$target['class_raw']);$row=['date'=>$date,'start_date'=>$date,'end_date'=>$date,'week_id'=>$week['id'],'slot_key'=>$slotKey,'day'=>(int)$target['day'],'session'=>(string)$target['session'],'period'=>(int)$target['period'],'class'=>$className,'class_raw'=>(string)($target['class_raw']??''),'subject'=>(string)$target['subject'],'absent_teacher'=>$absent,'substitute_teacher'=>$sub,'assigned_to'=>$sub,'fit_labels'=>$fit['labels'],'status'=>$status,'kind'=>'task','title'=>'Dạy thay '.(string)$target['subject'].' lớp '.$className.' · '.$sub,'url'=>BASE_URL.'thoikhoabieu.php?tab=substitution&date='.rawurlencode($date),'active'=>false,'publish_dashboard'=>false,'requested_at'=>date('c'),'requested_by'=>(string)($user['name']??$selfTeacher),'updated_at'=>date('c'),'updated_by'=>(string)($user['name']??'')];if($status==='approved'){$row['approved_at']=date('c');$row['approved_by']=(string)($user['name']??'');}
if(!tkb_save_substitution($row)){http_response_code(500);echo json_encode(['ok'=>false,'message'=>'Không lưu được lịch dạy thay.'],JSON_UNESCAPED_UNICODE);exit;}
echo json_encode(['ok'=>true,'status'=>$status,'message'=>$status==='approved'?'Đã xác nhận lịch dạy thay.':'Đã gửi đăng ký, chờ Tổ trưởng chuyên môn hoặc Quản trị duyệt.'],JSON_UNESCAPED_UNICODE);
