<?php
require_once __DIR__.'/periodic_report.php';
require_once __DIR__.'/periodic_report_docx.php';
require_once __DIR__.'/observation_form.php';
$prPageUser=cds_user()??[];$prPageDefaultPlace=pr_default_place($prPageUser);$prPageScope=pr_scope($prPageUser,get_teachers_sorted());$prPageCsrf=cds_drive_csrf_token();
$prPageAllReports=array_merge(cm_docs_by_section('bc_dinhky'),cm_docs_by_section('bc_thang'));
$prPageVisibleReports=array_values(array_filter($prPageAllReports,fn($prPageR)=>pr_visible($prPageR,$prPageScope)));
$prPageId=trim((string)($_POST['id']??$_GET['id']??''));$prPageExisting=null;
foreach($prPageAllReports as$prPageRow)if(($prPageRow['id']??'')===$prPageId){$prPageExisting=$prPageRow;break;}
if($prPageId!==''&&(!$prPageExisting||!pr_visible($prPageExisting,$prPageScope))){http_response_code(404);exit('Không tìm thấy báo cáo trong phạm vi tổ của tài khoản.');}
$prPageGroup=$prPageScope['wide']?trim((string)($_POST['report_group']??$_GET['group']??$prPageExisting['report_group']??$prPageScope['own'])):$prPageScope['own'];
if(!in_array($prPageGroup,$prPageScope['groups'],true))$prPageGroup=$prPageScope['groups'][0]??'';
$prPageMonth=trim((string)($_GET['month']??$prPageExisting['month']??date('Y-m')));if(!pr_month($prPageMonth))$prPageMonth=date('Y-m');
$prPageError='';$prPageSubmitted=null;$prPageView=(string)($_GET['view']??'');
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!hash_equals($prPageCsrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Phiên làm việc hết hiệu lực. Vui lòng tải lại trang.');}
    if(!$prPageScope['write']){http_response_code(403);exit('Chỉ TTCM của tổ, BGH và quản trị có quyền soạn báo cáo.');}
    $prPageAction=(string)($_POST['action']??'');
    try {
        if($prPageAction==='periodic_save'){
            if($prPageScope['wide']&&!in_array(trim((string)($_POST['report_group']??'')),$prPageScope['groups'],true))throw new RuntimeException('Tổ chuyên môn không hợp lệ.');
            if($prPageGroup==='')throw new RuntimeException('Chưa gán tổ chuyên môn. Vui lòng cập nhật tổ của giáo viên trong Phân công – Danh mục.');
            if($prPageExisting&&(string)($_POST['revision']??'')!==(string)($prPageExisting['report_revision']??$prPageExisting['updated_at']??$prPageExisting['created_at']??''))throw new RuntimeException('Báo cáo đã được cập nhật ở phiên khác. Nội dung vừa nhập vẫn ở dưới; hãy mở bản mới trong tab khác để đối chiếu trước khi lưu lại.');
            $prPageMonth=trim((string)($_POST['month']??''));$prPageNext=trim((string)($_POST['next_month']??''));$prPageDate=trim((string)($_POST['date']??''));
            if(!pr_month($prPageMonth)||!pr_month($prPageNext)||!pr_date($prPageDate))throw new RuntimeException('Tháng báo cáo, tháng kế hoạch hoặc ngày lập không hợp lệ.');
            $prPageReport=['id'=>$prPageId,'section'=>'bc_dinhky','kind'=>'report','report_version'=>1,'report_group'=>$prPageGroup,'month'=>$prPageMonth,'next_month'=>$prPageNext,'date'=>$prPageDate,'report_sections'=>[],'report_revision'=>bin2hex(random_bytes(12)),'by'=>$prPageScope['name']];
            foreach(['school','place','number','recipient','signer']as$prPageKey){$prPageReport[$prPageKey]=trim((string)($_POST[$prPageKey]??''));if(strlen($prPageReport[$prPageKey])>1000)throw new RuntimeException('Thông tin đầu báo cáo quá dài.');}
            if($prPageReport['school']===''||$prPageReport['place']===''||$prPageReport['recipient']===''||$prPageReport['signer']==='')throw new RuntimeException('Vui lòng nhập trường, địa danh, nơi nhận và người ký.');
            foreach(pr_sections()as$prPageKey=>$prPageLabel)$prPageReport['report_sections'][$prPageKey]=pr_clean((string)($_POST['report_sections'][$prPageKey]??''));
            $prPageReport['title']='Báo cáo chuyên môn tháng '.substr($prPageMonth,5,2).'/'.substr($prPageMonth,0,4).' — '.$prPageGroup;
            $prPageReport['content']=trim(strip_tags(implode("\n",$prPageReport['report_sections'])));
            $prPageSameSnapshot=$prPageExisting&&($prPageExisting['month']??'')===$prPageMonth&&($prPageExisting['report_group']??'')===$prPageGroup&&!empty($prPageExisting['snapshot']);
            $prPageReport['snapshot']=$prPageSameSnapshot&&empty($_POST['refresh_snapshot'])?$prPageExisting['snapshot']:pr_snapshot($prPageGroup,$prPageMonth,get_teachers_sorted());
            // Mỗi bản Drive gắn đúng nội dung đã lưu; bản cũ không bị ghi đè hay xóa.
            $prPageReport['drive_path']='';$prPageReport['drive_saved_at']='';
            $prPageSavedId=pr_store($prPageReport,$prPageExisting?(string)($_POST['revision']??''):null);if(!empty($_POST['default_place'])&&!pr_save_default_place($prPageUser,$prPageReport['place']))flash('Báo cáo đã lưu, nhưng chưa lưu được địa danh mặc định.','warning');else flash('Đã lưu báo cáo và phụ lục của '.$prPageGroup.'.');
            header('Location: '.BASE_URL.'baocao.php?tab=dinhky&id='.rawurlencode($prPageSavedId).'&view=preview');exit;
        }
        if($prPageAction==='periodic_drive'){
            if(!$prPageExisting||empty($prPageExisting['report_version']))throw new RuntimeException('Hãy lưu bản báo cáo hoàn chỉnh trước.');
            if((string)($_POST['revision']??'')!==(string)($prPageExisting['report_revision']??''))throw new RuntimeException('Báo cáo đã thay đổi. Hãy tải lại trang trước khi lưu lên Drive.');
            $prPageBytes=pr_docx($prPageExisting);$prPageType=cds_drive_type_for_action(cds_drive_page_action(),'plans');
            $prPageResult=cds_drive_upload_bytes($prPageBytes,$prPageExisting['title'].'.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',$prPageType);
            if(empty($prPageResult['ok']))throw new RuntimeException((string)($prPageResult['message']??'Không lưu được lên Drive.'));
            pr_store(['id'=>$prPageId,'drive_path'=>(string)$prPageResult['path'],'drive_saved_at'=>date('c')],(string)$prPageExisting['report_revision']);flash('Đã lưu bản Word hoàn chỉnh vào Google Drive.');header('Location: '.BASE_URL.'baocao.php?tab=dinhky&id='.rawurlencode($prPageId).'&view=preview');exit;
        }
        if($prPageAction==='periodic_delete'){
            if(!$prPageScope['wide']||!cds_can_feature('cm.baocao.dinhky','delete')){http_response_code(403);exit('Chỉ BGH hoặc quản trị có quyền xóa báo cáo.');}
            if(!$prPageExisting)throw new RuntimeException('Báo cáo không tồn tại.');cm_doc_delete($prPageId);flash('Đã xóa báo cáo khỏi CDS. Tệp trên Drive được giữ nguyên.','warning');header('Location: '.BASE_URL.'baocao.php?tab=dinhky');exit;
        }
        throw new RuntimeException('Thao tác không hợp lệ.');
    }catch(Throwable $prPageE){$prPageError=$prPageE->getMessage();$prPageView='';if($prPageAction==='periodic_save'){
            if($prPageScope['wide']&&!in_array(trim((string)($_POST['report_group']??'')),$prPageScope['groups'],true))throw new RuntimeException('Tổ chuyên môn không hợp lệ.');$prPageSubmitted=$_POST;$prPageSubmitted['report_sections']=[];foreach(pr_sections()as$prPageKey=>$prPageLabel){try{$prPageSubmitted['report_sections'][$prPageKey]=pr_clean((string)($_POST['report_sections'][$prPageKey]??''));}catch(Throwable $prPageIgnored){$prPageSubmitted['report_sections'][$prPageKey]='';}}}else $prPageView='preview';}
}
if(in_array($prPageView,['print','embed','download'],true)){
    if(!$prPageExisting||empty($prPageExisting['report_version'])){http_response_code(400);exit('Hãy chuyển báo cáo cũ sang mẫu mới và lưu trước khi xuất.');}
    if($prPageView==='print'||$prPageView==='embed'){echo pr_html($prPageExisting,$prPageView==='print');exit;}
    try{$prPageBytes=pr_docx($prPageExisting);header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');header('Content-Disposition: attachment; filename="bao-cao-'.$prPageExisting['month'].'.docx"; filename*=UTF-8\'\''.rawurlencode($prPageExisting['title'].'.docx'));header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');echo $prPageBytes;exit;}catch(Throwable $prPageE){$prPageError=$prPageE->getMessage();$prPageView='preview';}
}
$prPageReport=$prPageSubmitted??$prPageExisting??['id'=>'','report_group'=>$prPageGroup,'month'=>$prPageMonth,'next_month'=>date('Y-m',strtotime($prPageMonth.'-01 +1 month')),'date'=>date('Y-m-d'),'school'=>SCHOOL_NAME,'place'=>$prPageDefaultPlace!==''?$prPageDefaultPlace:(function_exists('school_place')?school_place():'Xín Mần'),'number'=>'','recipient'=>'Ban Giám hiệu nhà trường','signer'=>$prPageScope['name'],'report_sections'=>[]];
if(empty($prPageReport['report_version'])&&$prPageExisting){$prPageReport=array_merge(['next_month'=>date('Y-m',strtotime($prPageMonth.'-01 +1 month')),'school'=>SCHOOL_NAME,'place'=>$prPageDefaultPlace!==''?$prPageDefaultPlace:'Xín Mần','number'=>'','recipient'=>'Ban Giám hiệu nhà trường','signer'=>$prPageScope['name']],$prPageReport);$prPageReport['month']=$prPageMonth;$prPageReport['report_sections']=$prPageSubmitted['report_sections']??['results'=>'<p>'.nl2br(pr_escape($prPageExisting['content']??'')).'</p>'];}
$prPageReport['report_group']=$prPageGroup;
require __DIR__.'/header.php';
?>
<link rel="stylesheet" href="<?=BASE_URL?>assets/periodic-report.css?v=20261007-1">
<div class="pr-heading"><div><h3><i class="bi bi-journal-richtext"></i> Báo cáo định kỳ</h3><p><?=pr_escape($prPageGroup?:'Chưa gán tổ chuyên môn')?> · Soạn nội dung, chốt số liệu, xuất báo cáo</p></div><a class="btn btn-outline-primary" href="<?=BASE_URL?>baocao.php?tab=dinhky&group=<?=rawurlencode($prPageGroup)?>"><i class="bi bi-plus-lg"></i> Báo cáo mới</a></div>
<?php if($prPageError):?><div class="alert alert-danger" role="alert"><?=pr_escape($prPageError)?></div><?php endif;?>
<?php if(!$prPageGroup):?><div class="alert alert-warning">Tài khoản chưa được gán tổ chuyên môn. Vui lòng cập nhật tổ trong Phân công – Danh mục.</div><?php endif;?>
<div class="pr-workspace"><main>
<?php if($prPageView==='preview'&&$prPageExisting):?>
<section class="card"><div class="card-header pr-actions"><strong><i class="bi bi-file-earmark-check"></i> Bản báo cáo đã lưu</strong><div><a class="btn btn-sm btn-light" href="<?=BASE_URL?>baocao.php?tab=dinhky&id=<?=rawurlencode($prPageId)?>">Chỉnh sửa</a><?php if(!empty($prPageExisting['report_version'])):?><a class="btn btn-sm btn-light" href="<?=BASE_URL?>baocao.php?tab=dinhky&id=<?=rawurlencode($prPageId)?>&view=download">Tải Word</a><a class="btn btn-sm btn-light" target="_blank" rel="noopener" href="<?=BASE_URL?>baocao.php?tab=dinhky&id=<?=rawurlencode($prPageId)?>&view=print">In / PDF</a><?php endif;?></div></div><div class="card-body">
<?php if(!empty($prPageExisting['report_version'])):?>
<div class="pr-drive-row"><?php if($prPageScope['write']):?><form method="post"><input type="hidden" name="csrf" value="<?=pr_escape($prPageCsrf)?>"><input type="hidden" name="id" value="<?=pr_escape($prPageId)?>"><input type="hidden" name="revision" value="<?=pr_escape($prPageExisting['report_revision']??'')?>"><button class="btn btn-success btn-sm" name="action" value="periodic_drive"><i class="bi bi-google"></i> Lưu vào Google Drive</button></form><?php endif;?><?php if(!empty($prPageExisting['drive_path'])):?><a class="btn btn-outline-success btn-sm" href="<?=pr_escape(cds_storage_file_url($prPageExisting['drive_path']))?>" target="_blank" rel="noopener">Mở bản đã lưu trên Drive</a><?php endif;?><small>Tệp Word dùng kho “Kế hoạch và báo cáo” trong cấu hình Drive.</small></div>
<iframe class="pr-preview" title="Bản báo cáo hoàn chỉnh" sandbox="allow-same-origin" src="<?=BASE_URL?>baocao.php?tab=dinhky&id=<?=rawurlencode($prPageId)?>&view=embed"></iframe>
<?php else:?><p class="text-muted">Báo cáo cũ được giữ nguyên. Chọn Chỉnh sửa để chuyển nội dung sang mẫu mới.</p><h4><?=pr_escape($prPageExisting['title']??'')?></h4><div style="white-space:pre-wrap"><?=pr_escape($prPageExisting['content']??'')?></div><?php if(!empty($prPageExisting['file_path'])):?><a href="<?=pr_escape(cds_storage_file_url($prPageExisting['file_path']))?>" target="_blank" rel="noopener">Mở tệp đính kèm cũ</a><?php endif;?><?php endif;?>
</div></section>
<?php else:?>
<form method="post" id="pr-form" class="card"><div class="card-header"><i class="bi bi-pencil-square"></i> Soạn báo cáo · <?=pr_escape($prPageGroup)?></div><div class="card-body">
<input type="hidden" name="action" value="periodic_save"><input type="hidden" name="csrf" value="<?=pr_escape($prPageCsrf)?>"><input type="hidden" name="id" value="<?=pr_escape($prPageId)?>"><input type="hidden" name="revision" value="<?=pr_escape($prPageSubmitted['revision']??$prPageExisting['report_revision']??$prPageExisting['updated_at']??$prPageExisting['created_at']??'')?>">
<fieldset <?=$prPageScope['write']?'':'disabled'?>>
<div class="pr-fields">
<div><label for="pr-group">Tổ chuyên môn</label><?php if($prPageScope['wide']):?><select id="pr-group" class="form-select" name="report_group"><?php foreach($prPageScope['groups']as$prPageG):?><option <?= $prPageG===$prPageGroup?'selected':''?> value="<?=pr_escape($prPageG)?>"><?=pr_escape($prPageG)?></option><?php endforeach;?></select><?php else:?><input id="pr-group" class="form-control" value="<?=pr_escape($prPageGroup)?>" readonly><input type="hidden" name="report_group" value="<?=pr_escape($prPageGroup)?>"><?php endif;?><small>Tự nhận theo tổ của TTCM.</small></div>
<?php foreach(['month'=>['Tháng báo cáo','month'],'next_month'=>['Tháng kế hoạch','month'],'school'=>['Tên trường','text'],'place'=>['Địa danh','text'],'date'=>['Ngày lập','date'],'number'=>['Số, ký hiệu','text'],'signer'=>['Tổ trưởng ký báo cáo','text'],'recipient'=>['Nơi nhận','text']]as$prPageKey=>$prPageMeta):?><div class="<?=$prPageKey==='school'?'pr-wide':($prPageKey==='recipient'?'pr-full':'')?>"><label for="pr-<?=$prPageKey?>"><?=$prPageMeta[0]?></label><input id="pr-<?=$prPageKey?>" class="form-control" type="<?=$prPageMeta[1]?>" name="<?=$prPageKey?>" value="<?=pr_escape($prPageReport[$prPageKey]??'')?>" <?=$prPageKey==='number'?'placeholder="…/BC-TCM"':'required'?>><?php if($prPageKey==='place'):?><label class="d-flex align-items-center gap-2 mt-2 fw-normal"><input type="checkbox" name="default_place" value="1" <?=!empty($prPageSubmitted['default_place'])?'checked':''?>> Lưu địa danh này làm mặc định</label><?php if($prPageDefaultPlace!==''):?><small>Mặc định: <?=pr_escape($prPageDefaultPlace)?></small><?php endif;?><?php endif;?></div><?php endforeach;?>
</div>
<p class="pr-format-note"><i class="bi bi-file-earmark-word"></i> Quốc hiệu, tiêu ngữ, tiêu đề, nơi nhận và phần ký được ghép tự động. Bản Word: A4, Times New Roman, cỡ 14; lề trái 30, phải 15, trên/dưới 20 mm.</p>
<?php foreach(pr_sections()as$prPageKey=>$prPageLabel):?><section class="pr-editor-section"><h4><?=$prPageKey==='results'?'<span>II. Kết quả thực hiện nhiệm vụ tháng báo cáo</span>':''?><?=pr_escape($prPageLabel)?></h4><p class="pr-help"><?=['implementation'=>'Nêu kế hoạch, văn bản chỉ đạo và cách triển khai trong tháng.','results'=>'Nêu nhiệm vụ đã thực hiện, kết quả và minh chứng.','issues'=>'Nêu tồn tại, nguyên nhân và giải pháp khắc phục.','next_plan'=>'Nêu nhiệm vụ, thời gian, người thực hiện và kết quả dự kiến.','manual_appendix'=>'Chèn bảng để bổ sung các biểu chưa có trong hồ sơ số.'][$prPageKey]?></p><div class="pr-rich" data-rich>
<div class="pr-toolbar" role="toolbar" aria-label="Công cụ soạn thảo <?=pr_escape($prPageLabel)?>">
<?php foreach(['bold'=>['B','Đậm'],'italic'=>['I','Nghiêng'],'underline'=>['U','Gạch chân'],'strikeThrough'=>['S','Gạch ngang'],'superscript'=>['x²','Chỉ số trên'],'subscript'=>['x₂','Chỉ số dưới'],'justifyLeft'=>['≡','Căn trái'],'justifyCenter'=>['☰','Căn giữa'],'justifyRight'=>['≡→','Căn phải'],'justifyFull'=>['▤','Căn đều'],'insertUnorderedList'=>['•','Danh sách dấu chấm'],'insertOrderedList'=>['1.','Danh sách số'],'outdent'=>['←','Giảm thụt lề'],'indent'=>['→','Tăng thụt lề'],'undo'=>['↶','Hoàn tác'],'redo'=>['↷','Làm lại'],'removeFormat'=>['Tx','Xóa định dạng']]as$prPageCmd=>$prPageMeta):?><button type="button" data-cmd="<?=$prPageCmd?>" title="<?=$prPageMeta[1]?>" aria-label="<?=$prPageMeta[1]?>"><?=$prPageMeta[0]?></button><?php endforeach;?>
<select data-size aria-label="Cỡ chữ"><option value="3">12 pt</option><option value="4" selected>14 pt</option><option value="5">16 pt</option><option value="6">18 pt</option></select><label title="Màu chữ" class="pr-color">A<input type="color" data-color value="#000000" aria-label="Màu chữ"></label><button type="button" data-link title="Chèn liên kết">🔗</button><button type="button" data-table title="Chèn bảng">▦ Bảng</button><button type="button" data-row title="Thêm hàng vào bảng">+ Hàng</button><button type="button" data-delete-row title="Xóa hàng trong bảng">− Hàng</button></div>
<div class="pr-editable" contenteditable="<?=$prPageScope['write']?'true':'false'?>" role="textbox" aria-multiline="true" aria-label="<?=pr_escape($prPageLabel)?>"><?=pr_clean((string)($prPageReport['report_sections'][$prPageKey]??''))?></div><textarea name="report_sections[<?=$prPageKey?>]" hidden><?=pr_escape($prPageReport['report_sections'][$prPageKey]??'')?></textarea>
</div></section><?php endforeach;?>
<div class="pr-snapshot"><strong><i class="bi bi-table"></i> Phụ lục tự động theo tổ và tháng</strong><p>Sổ đầu bài · Dự giờ · Chấm công · Kiểm tra hồ sơ. Lấy số liệu khi lưu lần đầu. Bản ghi ngoài tổ và ngoài tháng không đưa vào báo cáo.</p><?php if(!empty($prPageExisting['snapshot'])):?><small>Đã chốt: <?=pr_escape(date('d/m/Y H:i',strtotime($prPageExisting['snapshot']['at'])))?></small><label><input type="checkbox" name="refresh_snapshot" value="1"> Cập nhật phụ lục từ hồ sơ hiện tại khi lưu lại</label><?php else:?><small>Phụ lục sẽ được chốt khi bấm Lưu và xem báo cáo.</small><?php endif;?></div>
<div class="pr-save"><button class="btn btn-primary" type="submit" <?=$prPageGroup?'':'disabled'?>><i class="bi bi-save"></i> Lưu và xem báo cáo</button><span id="pr-save-note">Sau khi lưu có thể tải Word, in / lưu PDF hoặc lưu vào Drive.</span></div>
</fieldset><?php if(!$prPageScope['write']):?><p class="text-muted mt-3">Tài khoản có quyền xem báo cáo của tổ. TTCM, BGH hoặc quản trị được soạn và lưu.</p><?php endif;?></div></form>
<?php endif;?></main>
<aside class="card pr-archive"><div class="card-header"><i class="bi bi-clock-history"></i> Báo cáo đã lưu</div><div class="card-body"><form method="get" class="pr-filter"><input type="hidden" name="tab" value="dinhky"><?php if($prPageScope['wide']):?><select class="form-select form-select-sm" name="group"><option value="">Tất cả tổ</option><?php foreach($prPageScope['groups']as$prPageG):?><option value="<?=pr_escape($prPageG)?>" <?=($_GET['group']??'')===$prPageG?'selected':''?>><?=pr_escape($prPageG)?></option><?php endforeach;?></select><?php endif;?><input class="form-control form-control-sm" type="month" name="filter_month" aria-label="Lọc tháng" value="<?=pr_escape($_GET['filter_month']??'')?>"><button class="btn btn-sm btn-outline-primary">Lọc</button></form>
<?php $prPageCount=0;usort($prPageVisibleReports,fn($prPageA,$prPageB)=>strcmp($prPageB['month']??$prPageB['date']??'',$prPageA['month']??$prPageA['date']??''));foreach($prPageVisibleReports as$prPageR){if(!empty($_GET['group'])&&($prPageR['report_group']??'')!==$_GET['group'])continue;if(!empty($_GET['filter_month'])&&($prPageR['month']??'')!==$_GET['filter_month'])continue;$prPageCount++;?>
<article class="pr-archive-item <?=$prPageId===($prPageR['id']??'')?'selected':''?>"><a href="<?=BASE_URL?>baocao.php?tab=dinhky&id=<?=rawurlencode($prPageR['id'])?>&view=preview"><strong><?=pr_escape($prPageR['title']??'Báo cáo')?></strong><small><?=pr_escape($prPageR['report_group']??'Báo cáo cũ')?> · <?=pr_escape($prPageR['date']??'')?></small></a><?php if($prPageScope['wide']&&cds_can_feature('cm.baocao.dinhky','delete')):?><form method="post" onsubmit="return confirm('Xóa báo cáo này khỏi CDS? Tệp Drive vẫn được giữ.');"><input type="hidden" name="csrf" value="<?=pr_escape($prPageCsrf)?>"><input type="hidden" name="id" value="<?=pr_escape($prPageR['id'])?>"><button class="btn btn-sm btn-outline-danger" name="action" value="periodic_delete" title="Xóa báo cáo"><i class="bi bi-trash"></i></button></form><?php endif;?></article>
<?php }if(!$prPageCount):?><p class="text-muted small mt-3">Chưa có báo cáo phù hợp.</p><?php endif;?></div></aside></div>
<script src="<?=BASE_URL?>assets/periodic-report.js?v=20261007-1" defer></script>
<?php require __DIR__.'/footer.php'; ?>
