<?php
$statsRange=in_array((string)($_GET['stats_range']??'week'),['total','week','custom'],true)?(string)$_GET['stats_range']:'week';
$statsWeekKey=(string)($_GET['stats_week']??$weekKey);$statsWeek=lb_week($statsWeekKey)?:$week;
$allWeeks=lb_weeks();$firstWeek=$allWeeks[0]??$week;$lastWeek=$allWeeks?end($allWeeks):$week;
if($statsRange==='total'){$statsFrom=(string)($firstWeek['start']??$week['start']);$statsTo=(string)($lastWeek['end']??$week['end']);}
elseif($statsRange==='week'){$statsFrom=(string)$statsWeek['start'];$statsTo=(string)$statsWeek['end'];}
else{$statsFrom=(string)($_GET['stats_from']??$week['start']);$statsTo=(string)($_GET['stats_to']??$week['end']);}
if($statsTo<$statsFrom){$swap=$statsFrom;$statsFrom=$statsTo;$statsTo=$swap;}
$statsTeacher=trim((string)($_GET['stats_teacher']??''));$statsSubject=trim((string)($_GET['stats_subject']??''));$statsClass=trim((string)($_GET['stats_class']??''));
$statsCompletion=in_array((string)($_GET['stats_completion']??'all'),['all','completed','incomplete','saved_unsigned','not_saved'],true)?(string)$_GET['stats_completion']:'all';
$allAccessible=lb_stat_rows($statsFrom,$statsTo);$teachers=[];$subjects=[];$statClasses=[];
foreach($allAccessible as$r){$teacherName=trim((string)($r['actual_teacher']??$r['scheduled_teacher']??''));if($teacherName!=='')$teachers[$teacherName]=true;if(trim((string)($r['subject']??''))!=='')$subjects[(string)$r['subject']]=true;if(trim((string)($r['class']??''))!=='')$statClasses[(string)$r['class']]=true;}
$teachers=array_keys($teachers);$subjects=array_keys($subjects);$statClasses=array_keys($statClasses);sort($teachers,SORT_NATURAL);sort($subjects,SORT_NATURAL);sort($statClasses,SORT_NATURAL);
$statRows=lb_stat_rows($statsFrom,$statsTo,$statsTeacher,$statsSubject,$statsClass,$statsCompletion);
$scheduled=count($statRows);$saved=count(array_filter($statRows,fn($r)=>!empty($r['_saved'])));$completed=count(array_filter($statRows,fn($r)=>!empty($r['signed_at'])));$incomplete=$scheduled-$completed;$savedUnsigned=count(array_filter($statRows,fn($r)=>!empty($r['_saved'])&&empty($r['signed_at'])));
$teacherStats=lb_stat_group($statRows,'actual_teacher');$subjectStats=lb_stat_group($statRows,'subject');$classStats=lb_stat_group($statRows,'class');$weekStats=lb_stat_group($statRows,'week_label');
$exportQuery=$_GET;$exportQuery['stats_from']=$statsFrom;$exportQuery['stats_to']=$statsTo;$exportQuery['stats_teacher']=$statsTeacher;$exportQuery['stats_subject']=$statsSubject;$exportQuery['stats_class']=$statsClass;$exportQuery['stats_completion']=$statsCompletion;unset($exportQuery['tab'],$exportQuery['week']);
?>
<style>
.lb-progress-summary .lb-card{padding:14px 16px;margin-bottom:0}.lb-progress-summary .metric{font-size:1.75rem;font-weight:800;line-height:1.1;color:#173f67}.lb-stat-switch{display:flex;gap:7px;flex-wrap:wrap}.lb-stat-switch button{border:1px solid #cbd8e6;background:#fff;color:#1f4e79;border-radius:9px;padding:7px 12px;font-weight:700}.lb-stat-switch button.active{background:#1f4e79;color:#fff}.lb-stat-panel{display:none}.lb-stat-panel.active{display:block}.lb-stat-table{font-size:.92rem}.lb-stat-table th{white-space:nowrap}.lb-progress-filter .advanced{border-top:1px solid #e6edf4;margin-top:12px;padding-top:12px}
</style>
<form class="lb-filter lb-progress-filter" method="get"><input type="hidden" name="tab" value="progress"><input type="hidden" name="week" value="<?=e($weekKey)?>">
 <div class="row g-2 align-items-end">
  <div class="col-lg-2"><label class="form-label fw-bold">Phạm vi</label><select class="form-select" name="stats_range" id="lbStatsRange"><option value="total" <?=$statsRange==='total'?'selected':''?>>Tổng năm học</option><option value="week" <?=$statsRange==='week'?'selected':''?>>Theo tuần</option><option value="custom" <?=$statsRange==='custom'?'selected':''?>>Khoảng ngày</option></select></div>
  <div class="col-lg-3 stats-range-week"><label class="form-label fw-bold">Tuần học</label><select class="form-select" name="stats_week"><?php foreach($allWeeks as$w):?><option value="<?=e($w['key'])?>" <?=$statsWeekKey===(string)$w['key']?'selected':''?>><?=e($w['label'])?> · <?=date('d/m',strtotime($w['start']))?>–<?=date('d/m/Y',strtotime($w['end']))?></option><?php endforeach;?></select></div>
  <div class="col-lg-2 stats-range-custom"><label class="form-label fw-bold">Từ ngày</label><input class="form-control" type="date" name="stats_from" value="<?=e($statsFrom)?>"></div>
  <div class="col-lg-2 stats-range-custom"><label class="form-label fw-bold">Đến ngày</label><input class="form-control" type="date" name="stats_to" value="<?=e($statsTo)?>"></div>
  <div class="col-lg-3"><label class="form-label fw-bold">Trạng thái hoàn thành</label><select class="form-select" name="stats_completion"><option value="all" <?=$statsCompletion==='all'?'selected':''?>>Tất cả tiết TKB</option><option value="completed" <?=$statsCompletion==='completed'?'selected':''?>>Đã hoàn thành (đã ký)</option><option value="incomplete" <?=$statsCompletion==='incomplete'?'selected':''?>>Chưa hoàn thành</option><option value="saved_unsigned" <?=$statsCompletion==='saved_unsigned'?'selected':''?>>Đã lưu, chưa ký</option><option value="not_saved" <?=$statsCompletion==='not_saved'?'selected':''?>>Chưa lưu sổ</option></select></div>
  <div class="col-lg-2"><button class="btn btn-primary w-100"><i class="bi bi-funnel"></i> Áp dụng</button></div>
 </div>
 <div class="row g-2 align-items-end advanced">
  <div class="col-lg-3"><label class="form-label small fw-bold">Giáo viên</label><select class="form-select form-select-sm" name="stats_teacher"><option value="">Tất cả giáo viên</option><?php foreach($teachers as$x):?><option <?=$x===$statsTeacher?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div>
  <div class="col-lg-3"><label class="form-label small fw-bold">Môn</label><select class="form-select form-select-sm" name="stats_subject"><option value="">Tất cả môn</option><?php foreach($subjects as$x):?><option <?=$x===$statsSubject?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div>
  <div class="col-lg-2"><label class="form-label small fw-bold">Lớp</label><select class="form-select form-select-sm" name="stats_class"><option value="">Tất cả lớp</option><?php foreach($statClasses as$x):?><option <?=$x===$statsClass?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div>
  <div class="col-lg-2"><a class="btn btn-sm btn-outline-secondary w-100" href="<?=BASE_URL?>sodaubai.php?tab=progress&week=<?=urlencode($weekKey)?>">Đặt lại</a></div>
  <div class="col-lg-2"><a class="btn btn-sm btn-success w-100" href="<?=BASE_URL?>sodaubai_stats_export.php?<?=e(http_build_query($exportQuery))?>"><i class="bi bi-file-earmark-excel"></i> Xuất Excel</a></div>
 </div>
</form>
<div class="row g-2 lb-progress-summary mb-3">
 <?php foreach([['Tiết được xếp TKB',$scheduled,'primary'],['Đã lưu sổ',$saved,'info'],['Hoàn thành · đã ký',$completed,'success'],['Chưa hoàn thành',$incomplete,'danger'],['Đã lưu, chưa ký',$savedUnsigned,'warning']]as[$label,$value,$tone]):?><div class="col-6 col-lg"><div class="lb-card border-start border-4 border-<?=$tone?>"><div class="text-muted small"><?=e($label)?></div><div class="metric"><?=number_format($value,0,',','.')?></div></div></div><?php endforeach;?>
</div>
<section class="lb-card">
 <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">Bảng kiểm soát tiến độ</h2><p class="lb-note mb-0">Chỉ tiết đã ký mới được tính hoàn thành. Tiết đã lưu nhưng chưa ký vẫn nằm trong nhóm chưa hoàn thành.</p></div><div class="lb-stat-switch" role="tablist"><?php foreach(['week'=>'Theo tuần','teacher'=>'Giáo viên','subject'=>'Môn học','class'=>'Lớp']as$k=>$label):?><button type="button" data-stat-panel="<?=$k?>" class="<?=$k==='week'?'active':''?>"><?=e($label)?></button><?php endforeach;?></div></div>
 <?php foreach(['week'=>$weekStats,'teacher'=>$teacherStats,'subject'=>$subjectStats,'class'=>$classStats]as$panel=>$groupRows):?><div class="lb-stat-panel <?=$panel==='week'?'active':''?>" data-stat-content="<?=$panel?>"><div class="table-responsive"><table class="table table-sm table-hover align-middle lb-stat-table"><thead><tr><th><?=e(['week'=>'Tuần','teacher'=>'Giáo viên','subject'=>'Môn học','class'=>'Lớp'][$panel])?></th><th class="text-center">Tiết TKB</th><th class="text-center">Đã lưu</th><th class="text-center text-success">Hoàn thành</th><th class="text-center text-danger">Chưa hoàn thành</th><th class="text-center">Tỷ lệ</th><th class="text-center">Tiết thực tế</th><th class="text-center">Nghỉ/hoãn/hủy</th></tr></thead><tbody><?php foreach($groupRows as$g):$rate=$g['scheduled']?($g['completed']*100/$g['scheduled']):0;?><tr><td class="fw-bold"><?=e($g['name'])?></td><td class="text-center"><?=$g['scheduled']?></td><td class="text-center"><?=$g['saved']?></td><td class="text-center text-success fw-bold"><?=$g['completed']?></td><td class="text-center text-danger fw-bold"><?=$g['incomplete']?></td><td class="text-center"><span class="badge <?=$rate>=100?'text-bg-success':($rate>=80?'text-bg-warning':'text-bg-light')?>"><?=number_format($rate,1,',','.')?>%</span></td><td class="text-center"><?=number_format($g['actual'],1,',','.')?></td><td class="text-center"><?=$g['cancelled']?></td></tr><?php endforeach;if(!$groupRows):?><tr><td colspan="8" class="lb-empty">Không có tiết TKB phù hợp với bộ lọc.</td></tr><?php endif;?></tbody></table></div></div><?php endforeach;?>
</section>
<section class="lb-card"><h2 class="h5">Nguyên tắc tính</h2><ul class="mb-0"><li><b>Tiết được xếp TKB</b>: toàn bộ tiết trong TKB thuộc phạm vi và bộ lọc.</li><li><b>Hoàn thành</b>: tiết đã có chữ ký giáo viên; lưu nội dung hoặc chọn “Đã dạy” nhưng chưa ký vẫn chưa hoàn thành.</li><li>Bản ghi chưa ký được giáo viên tiếp tục sửa cho đến khi sổ bị khóa tự động hoặc khóa thủ công.</li><li>Sau khi ký, nội dung được giữ cố định; quản trị chỉ xử lý bằng xóa có lý do và nhập lại khi thật sự cần.</li></ul></section>
<script>(function(){const range=document.getElementById('lbStatsRange');function syncRange(){document.querySelectorAll('.stats-range-week').forEach(x=>x.style.display=range.value==='week'?'':'none');document.querySelectorAll('.stats-range-custom').forEach(x=>x.style.display=range.value==='custom'?'':'none')}if(range){range.addEventListener('change',syncRange);syncRange()}document.querySelectorAll('[data-stat-panel]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-stat-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-stat-content]').forEach(x=>x.classList.toggle('active',x.dataset.statContent===b.dataset.statPanel))}))})()</script>
