<?php
$profileUser=current_user();
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!cds_account_csrf_valid((string)($_POST['csrf']??''))) flash('Phiên làm việc không hợp lệ, vui lòng thử lại.','danger');
    elseif(($_POST['profile_action']??'')==='save_profile'){$result=cds_account_update_profile((string)($profileUser['id']??''),$_POST);flash($result['message'],!empty($result['ok'])?'success':'danger');}
    elseif(($_POST['profile_action']??'')==='upload_photo'){$result=cds_account_upload_teacher_photo((string)($profileUser['id']??''),(array)($_FILES['teacher_photo']??[]));flash($result['message'],!empty($result['ok'])?'success':'danger');}
    elseif(($_POST['profile_action']??'')==='change_password'){$result=cds_account_change_password((string)($profileUser['id']??''),(string)($_POST['current_password']??''),(string)($_POST['new_password']??''),(string)($_POST['confirm_password']??''));flash($result['message'],!empty($result['ok'])?'success':'danger');}
    header('Location: '.BASE_URL.'admin.php?view=profile');exit;
}
$profileUser=find_user_by_id((string)($profileUser['id']??''))?:$profileUser;$profile=cds_account_profile($profileUser);$profileTeacher=cds_account_teacher_for_user($profileUser);$profileHasPhoto=$profileTeacher?staff_card_has_photo((string)$profileTeacher['id']):false;
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Thông tin cá nhân – CDS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>
body{background:#f3f6fb;color:#172033}.profile-shell{max-width:1050px}.profile-hero{background:linear-gradient(135deg,#174d7b,#2472b7);color:#fff;border-radius:22px}.profile-avatar{width:70px;height:70px;border-radius:20px;background:#ffffff25;display:grid;place-items:center;font-size:2rem;overflow:hidden}.profile-avatar img{width:100%;height:100%;object-fit:cover}.card{border:0;border-radius:20px}.form-label{font-weight:650}.security-note{background:#f0f7ff;border-radius:14px;color:#315a7c}.photo-preview,.photo-placeholder{width:105px;height:140px;border-radius:12px}.photo-preview{object-fit:cover;border:1px solid #dbe4ee}.photo-placeholder{display:grid;place-items:center;background:#eef4fa;color:#718096;font-size:2rem}@media(max-width:767px){.profile-shell{padding:12px!important}.profile-hero{border-radius:16px}.profile-avatar{width:54px;height:54px}}
</style></head><body><main class="container profile-shell py-4">
<section class="profile-hero p-4 mb-3 d-flex flex-wrap align-items-center justify-content-between gap-3"><div class="d-flex align-items-center gap-3"><span class="profile-avatar"><?php if($profileHasPhoto):?><img src="<?=e(BASE_URL.'staff_photo.php?id='.rawurlencode((string)$profileTeacher['id']).'&v='.time())?>" alt="Ảnh thẻ"><?php else:?><i class="bi bi-person-vcard"></i><?php endif?></span><div><h2 class="mb-1">Thông tin cá nhân</h2><div class="opacity-75"><?=e($profileUser['username']??'')?> · Dữ liệu tài khoản CDS</div></div></div><a class="btn btn-light" href="admin.php"><i class="bi bi-arrow-left"></i> Về trang tổng quan</a></section>
<?php show_flash();?><div class="row g-3"><div class="col-lg-7">
<section class="card shadow-sm mb-3"><div class="card-body p-4"><h5 class="mb-3"><i class="bi bi-person-bounding-box text-primary"></i> Ảnh thẻ giáo viên</h5><?php if(!$profileTeacher):?><div class="alert alert-warning mb-0">Tài khoản chưa liên kết với hồ sơ giáo viên trong CSDL. Vui lòng liên hệ quản trị để ghép đúng hồ sơ.</div><?php else:?><form method="post" enctype="multipart/form-data" class="d-flex flex-wrap gap-3 align-items-center"><input type="hidden" name="csrf" value="<?=e(cds_account_csrf_token())?>"><input type="hidden" name="profile_action" value="upload_photo"><div><?php if($profileHasPhoto):?><img class="photo-preview" id="photoPreview" src="<?=e(BASE_URL.'staff_photo.php?id='.rawurlencode((string)$profileTeacher['id']).'&v='.time())?>" alt="Ảnh thẻ hiện tại"><?php else:?><div class="photo-placeholder" id="photoPlaceholder"><i class="bi bi-person"></i></div><img class="photo-preview d-none" id="photoPreview" alt="Ảnh xem trước"><?php endif?></div><div class="flex-grow-1"><label class="form-label">Chọn ảnh gốc JPG, PNG hoặc WebP</label><input class="form-control" id="teacherPhoto" type="file" name="teacher_photo" accept="image/jpeg,image/png,image/webp" required><div class="form-text">Giữ nguyên tệp và chất lượng gốc; tối thiểu 300 × 400 px, tối đa 20 MB. Ảnh được lưu vào MySQL, Google Drive và dùng chung khi in thẻ CBGV.</div><button class="btn btn-primary mt-3"><i class="bi bi-cloud-arrow-up"></i> Tải ảnh và đồng bộ</button></div></form><?php endif?></div></section>
<section class="card shadow-sm"><div class="card-body p-4"><h5 class="mb-3"><i class="bi bi-pencil-square text-primary"></i> Chỉnh sửa hồ sơ</h5><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=e(cds_account_csrf_token())?>"><input type="hidden" name="profile_action" value="save_profile"><div class="col-md-7"><label class="form-label">Họ và tên *</label><input class="form-control" name="name" required value="<?=e($profile['name'])?>"></div><div class="col-md-5"><label class="form-label">Tên đăng nhập</label><input class="form-control" value="<?=e($profileUser['username']??'')?>" readonly></div><div class="col-md-4"><label class="form-label">Ngày sinh</label><input type="date" class="form-control" name="dob" value="<?=e($profile['dob'])?>"></div><div class="col-md-4"><label class="form-label">Giới tính</label><select class="form-select" name="gender"><option value="">Chưa khai báo</option><?php foreach(['Nam','Nữ','Khác'] as $gender):?><option <?=$profile['gender']===$gender?'selected':''?>><?=e($gender)?></option><?php endforeach?></select></div><div class="col-md-4"><label class="form-label">Số điện thoại</label><input class="form-control" name="phone" value="<?=e($profile['phone'])?>"></div><div class="col-12"><label class="form-label">Email</label><input type="email" class="form-control" name="email" value="<?=e($profile['email'])?>"></div><div class="col-md-6"><label class="form-label">Quê quán</label><input class="form-control" name="hometown" value="<?=e($profile['hometown'])?>"></div><div class="col-md-6"><label class="form-label">Địa chỉ hiện tại</label><input class="form-control" name="address" value="<?=e($profile['address'])?>"></div><div class="col-12"><button class="btn btn-primary px-4"><i class="bi bi-cloud-check"></i> Lưu vào CSDL</button></div></form></div></section></div>
<div class="col-lg-5"><section class="card shadow-sm"><div class="card-body p-4"><h5 class="mb-3"><i class="bi bi-shield-lock text-success"></i> Đổi mật khẩu</h5><div class="security-note p-3 small mb-3">Mật khẩu mới có tối thiểu 8 ký tự. Không chia sẻ mật khẩu với người khác.</div><form method="post" class="vstack gap-3"><input type="hidden" name="csrf" value="<?=e(cds_account_csrf_token())?>"><input type="hidden" name="profile_action" value="change_password"><div><label class="form-label">Mật khẩu hiện tại</label><input type="password" class="form-control" name="current_password" required autocomplete="current-password"></div><div><label class="form-label">Mật khẩu mới</label><input type="password" class="form-control" name="new_password" required minlength="8" autocomplete="new-password"></div><div><label class="form-label">Nhập lại mật khẩu mới</label><input type="password" class="form-control" name="confirm_password" required minlength="8" autocomplete="new-password"></div><button class="btn btn-success"><i class="bi bi-key"></i> Đổi mật khẩu</button></form></div></section></div></div></main>
<script>const input=document.getElementById('teacherPhoto');if(input)input.addEventListener('change',()=>{const file=input.files&&input.files[0],img=document.getElementById('photoPreview'),placeholder=document.getElementById('photoPlaceholder');if(!file)return;img.src=URL.createObjectURL(file);img.classList.remove('d-none');if(placeholder)placeholder.classList.add('d-none')});</script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
