<?php
if(defined('CDS_CM_SWITCHER_RENDERED'))return;define('CDS_CM_SWITCHER_RENDERED',true);
$cdsUser=$_SESSION['cds_user']??null;if(!$cdsUser)return;$isAdmin=($cdsUser['role']??'')==='admin';
$links=[['Tổng quan CDS','/admin.php','bi-speedometer2','#2563eb'],['Chuyên môn','/chuyenmon/','bi-journal-bookmark-fill','#198754'],['Cơ sở dữ liệu','/csdl.php','bi-database','#20c997'],['Quản lý nội trú','/noitru.php','bi-building','#d63384'],['Thi đua','/thidua.php','bi-trophy','#ca8a04']];
?>
<style>
.cds-cm-switch{position:fixed;z-index:2500;right:0;top:50%;transform:translate(68%,-50%);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;transition:transform .18s ease}.cds-cm-switch:hover,.cds-cm-switch:focus-within,.cds-cm-switch.open{transform:translate(0,-50%)}
.cds-cm-switch>button{display:grid;place-items:center;width:42px;height:48px;padding:0;border:1px solid rgba(255,255,255,.82);border-right:0;border-radius:14px 0 0 14px;background:#1f5d8d;color:#fff;box-shadow:0 7px 20px rgba(15,23,42,.2);cursor:pointer}.cds-cm-switch>button:hover{background:#174b73}.cds-cm-switch>button span,.cds-cm-switch>button .bi-chevron-down{display:none}.cds-cm-switch>button>.bi-grid-3x3-gap-fill{font-size:17px}
.cds-cm-menu{position:absolute;display:none;right:52px;top:50%;transform:translateY(-50%);width:min(310px,calc(100vw - 72px));max-height:68vh;overflow:auto;padding:9px;border:1px solid #e2e8f0;border-radius:15px;background:#fff;color:#1e293b;box-shadow:0 18px 45px rgba(15,23,42,.22)}.cds-cm-switch.open .cds-cm-menu{display:block;animation:cmSwitchIn .16s ease-out}.cds-cm-title{padding:6px 8px 9px;color:#64748b;font-size:11px;font-weight:800;text-transform:uppercase}.cds-cm-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.cds-cm-grid a{display:flex;align-items:center;gap:8px;padding:9px;border-radius:10px;color:#1e293b;text-decoration:none;font-size:13px;font-weight:700}.cds-cm-grid a:hover,.cds-cm-grid a.active{background:#eff6ff;color:#1d4ed8}.cds-cm-grid i{display:grid;place-items:center;width:32px;height:32px;border-radius:9px;background:#f1f5f9;color:var(--cmc);font-size:16px}@keyframes cmSwitchIn{from{opacity:0;transform:translate(8px,-50%)}to{opacity:1;transform:translate(0,-50%)}}
@media(max-width:767px){.cds-cm-switch{top:43%}.cds-cm-menu{right:48px;width:min(300px,calc(100vw - 62px));max-height:64vh}.cds-cm-grid{grid-template-columns:1fr}.cds-cm-switch>button{width:39px;height:46px}.cds-cm-switch>button>.bi-grid-3x3-gap-fill{font-size:16px}}
</style>
<div class="cds-cm-switch" id="cdsCmSwitcher"><button type="button" aria-expanded="false" aria-label="Mở menu chuyển nhanh" title="Chuyển nhanh"><i class="bi bi-grid-3x3-gap-fill"></i><span>Chuyển module</span><i class="bi bi-chevron-down"></i></button><div class="cds-cm-menu"><div class="cds-cm-title">Đi đến nhanh · <?= htmlspecialchars($cdsUser['name']??'',ENT_QUOTES,'UTF-8') ?></div><div class="cds-cm-grid"><?php foreach($links as $link):?><a class="<?= $link[1]==='/chuyenmon/'?'active':'' ?>" href="<?= htmlspecialchars($link[1],ENT_QUOTES,'UTF-8') ?>" style="--cmc:<?= $link[3] ?>"><i class="bi <?= $link[2] ?>"></i><span><?= htmlspecialchars($link[0],ENT_QUOTES,'UTF-8') ?></span></a><?php endforeach;?><?php if($isAdmin):?><a href="/users.php" style="--cmc:#2563eb"><i class="bi bi-people"></i><span>Phân quyền</span></a><a href="/activity.php" style="--cmc:#7c3aed"><i class="bi bi-activity"></i><span>Nhật ký</span></a><?php endif;?></div></div></div>
<script>(function(){var b=document.getElementById('cdsCmSwitcher');if(!b)return;var btn=b.querySelector('button');function close(){b.classList.remove('open');btn.setAttribute('aria-expanded','false')}btn.onclick=function(e){e.stopPropagation();var open=b.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')};document.addEventListener('click',function(e){if(!b.contains(e.target))close()});document.addEventListener('keydown',function(e){if(e.key==='Escape')close()})})();</script>
