<?php
if(defined('CDS_CM_SWITCHER_RENDERED'))return;define('CDS_CM_SWITCHER_RENDERED',true);
$cdsUser=$_SESSION['cds_user']??null;if(!$cdsUser)return;$isAdmin=($cdsUser['role']??'')==='admin';
$links=[['Tổng quan CDS','/admin.php','bi-speedometer2','#2563eb'],['Chuyên môn','/chuyenmon/','bi-journal-bookmark-fill','#198754'],['Cơ sở dữ liệu','/csdl.php','bi-database','#20c997'],['Quản lý nội trú','/noitru.php','bi-building','#d63384'],['Thi đua','/thidua.php','bi-trophy','#ca8a04']];
?>
<style>
.cds-cm-switch{position:fixed;z-index:2500;right:10px;bottom:18px;font-family:var(--cds-font,system-ui,-apple-system,"Segoe UI",sans-serif);transition:transform .22s ease,opacity .22s ease}.cds-cm-switch:not(.open).idle{transform:translateX(24px);opacity:.62}.cds-cm-switch:not(.open).idle:hover,.cds-cm-switch:not(.open).idle:focus-within{transform:none;opacity:1}
.cds-cm-switch>button{display:grid;place-items:center;width:46px;height:46px;padding:0;border:1px solid rgba(255,255,255,.8);border-radius:50%;background:#1d5f91;color:#fff;box-shadow:0 8px 24px rgba(15,23,42,.2);cursor:pointer}.cds-cm-switch>button:hover{background:#174d78;transform:translateY(-1px)}.cds-cm-switch>button span,.cds-cm-switch>button .bi-chevron-down{display:none}
.cds-cm-menu{position:absolute;display:none;right:0;bottom:56px;width:min(310px,calc(100vw - 24px));max-height:65vh;overflow:auto;padding:9px;border:1px solid #e2e8f0;border-radius:16px;background:#fff;box-shadow:0 18px 45px rgba(15,23,42,.22)}.cds-cm-switch.open .cds-cm-menu{display:block;animation:cmSwitchIn .16s ease-out}.cds-cm-title{padding:6px 8px 9px;color:#64748b;font-size:11px;font-weight:800;text-transform:uppercase}.cds-cm-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.cds-cm-grid a{display:flex;align-items:center;gap:8px;padding:10px;border-radius:11px;color:#1e293b;text-decoration:none;font-size:13px;font-weight:700}.cds-cm-grid a:hover,.cds-cm-grid a.active{background:#eff6ff;color:#1d4ed8}.cds-cm-grid i{display:grid;place-items:center;width:32px;height:32px;border-radius:9px;background:#f1f5f9;color:var(--cmc)}@keyframes cmSwitchIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
@media(max-width:767px){.cds-cm-switch{right:10px;bottom:calc(76px + env(safe-area-inset-bottom))}.cds-cm-switch:not(.open).idle{transform:translateX(22px)}.cds-cm-grid{grid-template-columns:1fr}}
</style>
<div class="cds-cm-switch" id="cdsCmSwitcher"><button type="button" aria-expanded="false" aria-label="Mở menu chuyển nhanh" title="Chuyển nhanh"><i class="bi bi-grid-3x3-gap-fill"></i><span>Chuyển module</span><i class="bi bi-chevron-down"></i></button><div class="cds-cm-menu"><div class="cds-cm-title">Đi đến nhanh · <?= htmlspecialchars($cdsUser['name']??'',ENT_QUOTES,'UTF-8') ?></div><div class="cds-cm-grid"><?php foreach($links as $link):?><a class="<?= $link[1]==='/chuyenmon/'?'active':'' ?>" href="<?= htmlspecialchars($link[1],ENT_QUOTES,'UTF-8') ?>" style="--cmc:<?= $link[3] ?>"><i class="bi <?= $link[2] ?>"></i><span><?= htmlspecialchars($link[0],ENT_QUOTES,'UTF-8') ?></span></a><?php endforeach;?><?php if($isAdmin):?><a href="/users.php" style="--cmc:#2563eb"><i class="bi bi-people"></i><span>Phân quyền</span></a><a href="/activity.php" style="--cmc:#7c3aed"><i class="bi bi-activity"></i><span>Nhật ký</span></a><?php endif;?></div></div></div>
<script>(function(){var b=document.getElementById('cdsCmSwitcher');if(!b)return;var btn=b.querySelector('button'),timer;function idle(){clearTimeout(timer);timer=setTimeout(function(){if(!b.classList.contains('open'))b.classList.add('idle')},2600)}function close(){b.classList.remove('open');btn.setAttribute('aria-expanded','false');idle()}btn.onclick=function(e){e.stopPropagation();b.classList.remove('idle');var open=b.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false');if(!open)idle()};b.addEventListener('mouseenter',function(){b.classList.remove('idle');clearTimeout(timer)});b.addEventListener('mouseleave',idle);document.addEventListener('click',function(e){if(!b.contains(e.target))close()});document.addEventListener('keydown',function(e){if(e.key==='Escape')close()});idle()})();</script>
