<?php
require_once __DIR__ . '/csdl_store.php';

function cds_dashboard_scope_data(array $user): array {
    $classes=csdl_classes_all();$students=csdl_students_all();$teachers=csdl_teachers_all();$allowed=allowed_classes();$classIds=[];
    foreach($classes as $class)if($allowed===null||in_array((string)($class['name']??''),$allowed,true))$classIds[]=(string)($class['id']??'');
    $scopeStudents=array_values(array_filter($students,fn($s)=>!empty($s['active'])&&in_array((string)($s['class_id']??''),$classIds,true)));
    $scopeClasses=array_values(array_filter($classes,fn($c)=>!empty($c['active'])&&in_array((string)($c['id']??''),$classIds,true)));
    $noitru=['boarders'=>0,'present'=>0,'absent'=>0,'attendance_date'=>'','pending_exits'=>0,'health_today'=>0,'low_medicine'=>0];
    if(can_module('noitru','view')){require_once __DIR__.'/noitru_store.php';$boarders=array_values(array_filter(noitru_boarders_live(),fn($s)=>$allowed===null||in_array((string)($s['class_name']??''),$allowed,true)));$boarderIds=array_fill_keys(array_column($boarders,'id'),true);$today=date('Y-m-d');$attRows=array_values(array_filter(noitru_att_all(),fn($r)=>isset($boarderIds[$r['student_id']??''])));$latestDate='';$latestShift='';foreach($attRows as $r){$d=$r['date']??'';if($d>$latestDate&&$d<=$today){$latestDate=$d;$latestShift=$r['shift']??'';}elseif($d===$latestDate)$latestShift=$r['shift']??$latestShift;}$attendance=['present'=>0,'absent'=>0,'late'=>0,'excused'=>0];foreach($attRows as $r)if(($r['date']??'')===$latestDate&&($r['shift']??'')===$latestShift){$st=$r['status']??'present';if(isset($attendance[$st]))$attendance[$st]++;}$noitru=['boarders'=>count($boarders),'present'=>$attendance['present']+$attendance['late'],'absent'=>$attendance['absent']+$attendance['excused'],'attendance_date'=>$latestDate,'pending_exits'=>count(array_filter(noitru_exits_all(),fn($r)=>($r['status']??'')==='pending'&&isset($boarderIds[$r['student_id']??'']))),'health_today'=>count(array_filter(noitru_health_all(),fn($r)=>($r['date']??'')===$today&&isset($boarderIds[$r['student_id']??'']))),'low_medicine'=>count(array_filter(noitru_medicines_all(),fn($m)=>(int)($m['quantity']??0)<=(int)($m['low_stock']??10)))];}
    $thidua=['absence_month'=>0,'scored_classes'=>0,'leader'=>'Chưa có','leader_score'=>0];if(can_module('thidua','view')){$td=load_json(DATA_PATH.'/thidua.json',['records'=>[],'weekly_scores'=>[]]);$month=date('Y-m');$week=date('Y-m-d',strtotime('monday this week'));$weekScores=array_values(array_filter($td['weekly_scores']??[],fn($r)=>($r['week_start']??'')===$week));usort($weekScores,fn($a,$b)=>(float)($b['final_score']??0)<=>(float)($a['final_score']??0));$thidua=['absence_month'=>count(array_filter($td['records']??[],fn($r)=>($r['type']??'')==='teacher_attendance'&&str_starts_with((string)($r['date']??''),$month))),'scored_classes'=>count($weekScores),'leader'=>$weekScores[0]['class_name']??'Chưa có','leader_score'=>$weekScores[0]['final_score']??0];}
    return ['csdl'=>['teachers'=>count(array_filter($teachers,fn($t)=>!empty($t['active']))),'students'=>count($scopeStudents),'classes'=>count($scopeClasses)],'noitru'=>$noitru,'thidua'=>$thidua];
}

function cds_dashboard_quick_actions(array $user): array {
    $items=[];$add=function($permission,$url,$label,$icon,$color)use(&$items){if(can_perm($permission))$items[]=compact('url','label','icon','color');};
    $add('csdl.view','csdl.php?tab=students','Danh sách học sinh','bi-people','#0f766e');$add('cm.tracuu','chuyenmon/','Tra cứu chuyên môn','bi-search','#16a34a');$add('nt.diemdanh','noitru.php?tab=attendance','Điểm danh nội trú','bi-person-check','#db2777');$add('nt.baoan','noitru.php?tab=meals','Báo ăn','bi-egg-fried','#ea580c');$add('nt.ravao','noitru.php?tab=exits','Xin ra/vào KTX','bi-door-open','#9333ea');$add('nt.yte','noitru.php?tab=health','Ghi nhận y tế','bi-heart-pulse','#dc2626');$add('nt.thucdon','noitru.php?tab=menu','Thực đơn tuần','bi-journal-text','#0891b2');$add('td.capnhat','thidua.php?section=teacher_attendance','Chấm công','bi-calendar-check','#ca8a04');$add('td.xem','thidua.php?section=student_score','Bảng thi đua','bi-trophy','#ca8a04');
    if(($user['role']??'')==='admin'){$items[]=['url'=>'users.php','label'=>'Phân quyền','icon'=>'bi-shield-lock','color'=>'#2563eb'];$items[]=['url'=>'activity.php','label'=>'Nhật ký cán bộ','icon'=>'bi-activity','color'=>'#7c3aed'];}return $items;
}
