<?php

function lib_excel_norm_header($value): string {
    $value=mb_strtolower(trim((string)$value),'UTF-8');$value=preg_replace('/\s+/u',' ',$value);
    if(class_exists('Transliterator')){$tr=Transliterator::create('NFD; [:Nonspacing Mark:] Remove; NFC');if($tr)$value=$tr->transliterate($value);}return $value;
}
function lib_excel_dom($raw): ?DOMDocument {$dom=new DOMDocument();$old=libxml_use_internal_errors(true);$ok=$dom->loadXML((string)$raw,LIBXML_NONET|LIBXML_NOBLANKS);libxml_clear_errors();libxml_use_internal_errors($old);return $ok?$dom:null;}
function lib_excel_cell_value(DOMElement $cell,DOMXPath $xpath,array $shared): string {$type=$cell->getAttribute('t');$text='';foreach($xpath->query('.//main:t',$cell)?:[] as $part)$text.=$part->textContent;if($type==='inlineStr'||$text!=='')return trim($text);$node=$xpath->query('./main:v',$cell)->item(0);$raw=$node?$node->textContent:'';return trim($type==='s'?(string)($shared[(int)$raw]??''):$raw);}
function lib_excel_parse_xlsx(string $path): array {
    if(!class_exists('ZipArchive'))return ['ok'=>false,'message'=>'Hosting chưa bật PHP ZipArchive nên chưa đọc được file XLSX.'];if(!class_exists('DOMDocument'))return ['ok'=>false,'message'=>'Hosting chưa bật PHP DOM nên chưa đọc được file XLSX.'];
    $zip=new ZipArchive();if($zip->open($path)!==true)return ['ok'=>false,'message'=>'Không mở được file Excel.'];$workbookRaw=$zip->getFromName('xl/workbook.xml');$relsRaw=$zip->getFromName('xl/_rels/workbook.xml.rels');if($workbookRaw===false||$relsRaw===false){$zip->close();return ['ok'=>false,'message'=>'File không đúng định dạng XLSX.'];}
    $shared=[];$sharedRaw=$zip->getFromName('xl/sharedStrings.xml');if($sharedRaw!==false&&($dom=lib_excel_dom($sharedRaw))){$xp=new DOMXPath($dom);$xp->registerNamespace('main','http://schemas.openxmlformats.org/spreadsheetml/2006/main');foreach($xp->query('//main:si') as $si){$s='';foreach($xp->query('.//main:t',$si) as $part)$s.=$part->textContent;$shared[]=$s;}}
    $rels=[];$relsDom=lib_excel_dom($relsRaw);$relsXp=new DOMXPath($relsDom);$relsXp->registerNamespace('pkg','http://schemas.openxmlformats.org/package/2006/relationships');foreach($relsXp->query('//pkg:Relationship') as $rel)$rels[$rel->getAttribute('Id')]=$rel->getAttribute('Target');
    $wb=lib_excel_dom($workbookRaw);$wbXp=new DOMXPath($wb);$wbXp->registerNamespace('main','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$sheet=$wbXp->query('//main:sheets/main:sheet')->item(0);if(!$sheet){$zip->close();return ['ok'=>false,'message'=>'File Excel không có trang dữ liệu.'];}
    $rid=$sheet->getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');$target=ltrim(str_replace('\\','/',$rels[$rid]??''),'/');$sheetPath=str_starts_with($target,'xl/')?$target:'xl/'.$target;$raw=$zip->getFromName($sheetPath);$zip->close();if($raw===false||!($dom=lib_excel_dom($raw)))return ['ok'=>false,'message'=>'Không đọc được trang dữ liệu đầu tiên.'];
    $xp=new DOMXPath($dom);$xp->registerNamespace('main','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$rows=[];foreach($xp->query('//main:sheetData/main:row') as $row){$number=(int)$row->getAttribute('r');$values=[];foreach($xp->query('./main:c',$row) as $cell){if(!preg_match('/^([A-Z]+)/',$cell->getAttribute('r'),$m))continue;$col=0;foreach(str_split($m[1]) as $char)$col=$col*26+ord($char)-64;$values[$col]=lib_excel_cell_value($cell,$xp,$shared);}$rows[$number]=$values;}if(!$rows)return ['ok'=>false,'message'=>'File Excel chưa có dữ liệu.'];
    $aliases=['title'=>['ten sach','tên sách','ten sach/tai lieu','tên sách/tài liệu'],'code'=>['ma sach','mã sách'],'barcode'=>['ma vach/isbn','mã vạch/isbn','isbn','ma vach','mã vạch'],'category'=>['loai sach','loại sách','loai','loại'],'subject'=>['mon/chu de','môn/chủ đề','mon','môn','chu de','chủ đề'],'grade'=>['khoi','khối'],'publisher'=>['nha xuat ban','nhà xuất bản','nxb'],'publication_year'=>['nam xuat ban','năm xuất bản','nam xb','năm xb'],'price'=>['gia tien','giá tiền','gia','giá'],'quantity'=>['so luong','số lượng','sl'],'import_date'=>['ngay nhap','ngày nhập'],'source'=>['nguon sach','nguồn sách','nguon','nguồn'],'shelf'=>['vi tri ke','vị trí kệ','ke','kệ'],'note'=>['ghi chu','ghi chú']];
    $headerRow=null;$headerMap=[];foreach($rows as $candidateRow=>$candidateValues){$candidateMap=[];foreach($candidateValues as $col=>$header){$norm=lib_excel_norm_header($header);foreach($aliases as $key=>$names)if(in_array($norm,$names,true)){$candidateMap[$key]=$col;break;}}if(isset($candidateMap['title'])){$headerRow=$candidateRow;$headerMap=$candidateMap;break;}}if($headerRow===null)return ['ok'=>false,'message'=>'Không tìm thấy cột “Tên sách”. Hãy dùng đúng file mẫu.'];
    $items=[];$errors=[];foreach($rows as $number=>$values){if($number===$headerRow)continue;$get=fn($key)=>trim((string)($values[$headerMap[$key]??0]??''));$title=$get('title');$barcode=preg_replace('/\.0$/','',$get('barcode'));$code=$get('code');if($title===''&&$barcode===''&&$code==='')continue;if($title===''){$errors[]='Dòng '.$number.': thiếu Tên sách.';continue;}$quantity=max(1,(int)$get('quantity'));$price=max(0,(float)preg_replace('/[^0-9.-]/','',$get('price')));$date=$get('import_date');if(is_numeric($date)&&(float)$date>1000)$date=gmdate('Y-m-d',(int)round(((float)$date-25569)*86400));elseif(preg_match('/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})$/',$date,$m))$date=sprintf('%04d-%02d-%02d',$m[3],$m[2],$m[1]);if($date===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date=date('Y-m-d');$items[]=['row'=>$number,'title'=>$title,'code'=>$code,'barcode'=>$barcode,'category'=>$get('category')?:'Sách tham khảo','subject'=>$get('subject'),'grade'=>$get('grade'),'publisher'=>$get('publisher'),'publication_year'=>preg_replace('/\.0$/','',$get('publication_year')),'price'=>$price,'quantity'=>$quantity,'import_date'=>$date,'source'=>$get('source'),'shelf'=>$get('shelf'),'note'=>$get('note')];}
    return ['ok'=>true,'items'=>$items,'errors'=>$errors];
}
function lib_excel_import_books(array $parsed,array &$books): array {
    $byBarcode=[];$byCode=[];foreach($books as $i=>$book){$barcode=preg_replace('/\D/','',(string)($book['barcode']??''));$code=lib_excel_norm_header($book['code']??'');if($barcode!=='')$byBarcode[$barcode]=$i;if($code!=='')$byCode[$code]=$i;}$added=0;$updated=0;$now=date('c');
    foreach($parsed['items']??[] as $item){$barcode=preg_replace('/\D/','',(string)$item['barcode']);$code=lib_excel_norm_header($item['code']);$index=$barcode!==''?($byBarcode[$barcode]??null):null;if($index===null&&$code!=='')$index=$byCode[$code]??null;$row=$item;unset($row['row']);$row['updated_at']=$now;if($index!==null){$old=$books[$index];$row['id']=$old['id'];$row['created_at']=$old['created_at']??$now;$row['quantity']=(int)($old['quantity']??0)+(int)$row['quantity'];foreach($row as $key=>$value)if($value===''&&isset($old[$key]))$row[$key]=$old[$key];$books[$index]=$row;$updated++;}else{$row['id']='book_'.bin2hex(random_bytes(7));$row['created_at']=$now;$books[]=$row;$new=count($books)-1;if($barcode!=='')$byBarcode[$barcode]=$new;if($code!=='')$byCode[$code]=$new;$added++;}}
    return ['added'=>$added,'updated'=>$updated,'skipped'=>count($parsed['errors']??[]),'errors'=>$parsed['errors']??[]];
}
