<?php
if(defined('CDS_MODULE_SWITCHER_RENDERED')||!function_exists('is_logged_in')||!is_logged_in())return;
define('CDS_MODULE_SWITCHER_RENDERED',true);require_once __DIR__.'/modules.php';$switchUser=current_user();$switchModules=[];
foreach(get_ecosystem_modules() as $module){$id=$module['id']??'';if(($module['status']??'')==='soon')continue;if(($module['status']??'')==='link'||($switchUser['role']??'')==='admin'||can_module($id,'view'))$switchModules[]=$module;}
$switchPath=basename((string)parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH));
?>
<style>
.cds-switch{position:fixed;z-index:1999;right:0;top:50%;transform:translate(68%,-50%);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;transition:transform .18s ease}
.cds-switch:hover,.cds-switch:focus-within,.cds-switch.open{transform:translate(0,-50%)}
.cds-switch-btn{display:grid;place-items:center;width:42px;height:48px;padding:0;border:1px solid rgba(255,255,255,.82);border-right:0;border-radius:14px 0 0 14px;background:#1f5d8d;color:#fff;box-shadow:0 7px 20px rgba(15,23,42,.2);cursor:pointer}
.cds-switch-btn:hover{background:#174b73}.cds-switch-btn span,.cds-switch-btn .bi-chevron-down{display:none}.cds-switch-btn>.bi-grid-3x3-gap-fill{font-size:17px}
.cds-switch-menu{position:absolute;display:none;right:52px;top:50%;transform:translateY(-50%);width:min(330px,calc(100vw - 72px));max-height:min(72vh,560px);overflow:auto;padding:9px;border:1px solid #dce5ee;border-radius:15px;background:#fff;color:#1e293b;box-shadow:0 18px 45px rgba(15,23,42,.22)}
.cds-switch.open .cds-switch-menu{display:block;animation:cdsSwitchIn .16s ease-out}.cds-switch-title{display:flex;justify-content:space-between;align-items:center;padding:6px 8px 9px;color:#64748b;font-size:11px;font-weight:800;text-transform:uppercase}.cds-switch-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.cds-switch-link{display:flex;align-items:center;gap:9px;min-width:0;padding:9px;border-radius:10px;color:#1e293b;text-decoration:none;font-size:13px;font-weight:700}.cds-switch-link:hover{background:#f1f5f9;color:#174b73}.cds-switch-link.active{background:#eaf4ff;color:#174b73}.cds-switch-link i{display:grid;place-items:center;flex:0 0 32px;width:32px;height:32px;border-radius:9px;background:#f1f5f9;color:var(--sw-color,#2563eb);font-size:16px}.cds-switch-link span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cds-switch-sep{height:1px;margin:7px 5px;background:#e2e8f0}@keyframes cdsSwitchIn{from{opacity:0;transform:translate(8px,-50%)}to{opacity:1;transform:translate(0,-50%)}}
@media(max-width:767px){.cds-switch{top:43%}.cds-switch-menu{right:48px;width:min(300px,calc(100vw - 62px));max-height:64vh}.cds-switch-grid{grid-template-columns:1fr}.cds-switch-btn{width:39px;height:46px}.cds-switch-btn>.bi-grid-3x3-gap-fill{font-size:16px}}
</style>
<div class="cds-switch" id="cdsModuleSwitcher"><button class="cds-switch-btn" type="button" aria-expanded="false" aria-label="Mở menu chuyển nhanh" title="Chuyển nhanh"><i class="bi bi-grid-3x3-gap-fill"></i><span>Chuyển module</span><i class="bi bi-chevron-down"></i></button><div class="cds-switch-menu"><div class="cds-switch-title"><span>Đi đến nhanh</span><small><?= e($switchUser['name']??'') ?></small></div><div class="cds-switch-grid"><a class="cds-switch-link <?= $switchPath==='admin.php'?'active':'' ?>" href="<?= e(BASE_URL.'admin.php') ?>" style="--sw-color:#2563eb"><i class="bi bi-speedometer2"></i><span>Tổng quan</span></a><?php foreach($switchModules as $module):$modulePath=basename((string)parse_url($module['url']??'',PHP_URL_PATH));?><a class="cds-switch-link <?= $switchPath===$modulePath?'active':'' ?>" href="<?= e($module['url']) ?>" style="--sw-color:<?= e($module['color']??'#2563eb') ?>" <?= !empty($module['external'])?'target="_blank" rel="noopener"':'' ?>><i class="bi <?= e($module['icon']) ?>"></i><span><?= e($module['title']) ?></span></a><?php endforeach;?></div><?php if(($switchUser['role']??'')==='admin'):?><div class="cds-switch-sep"></div><div class="cds-switch-grid"><a class="cds-switch-link" href="<?= e(BASE_URL.'users.php') ?>"><i class="bi bi-people"></i><span>Tài khoản</span></a><a class="cds-switch-link" href="<?= e(BASE_URL.'activity.php') ?>"><i class="bi bi-activity"></i><span>Nhật ký</span></a></div><?php endif;?></div></div>
<script>(function(){var box=document.getElementById('cdsModuleSwitcher');if(!box)return;var btn=box.querySelector('.cds-switch-btn');function close(){box.classList.remove('open');btn.setAttribute('aria-expanded','false')}btn.addEventListener('click',function(e){e.stopPropagation();var open=box.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')});document.addEventListener('click',function(e){if(!box.contains(e.target))close()});document.addEventListener('keydown',function(e){if(e.key==='Escape')close()})})();</script>
