<?php
/** Xuất danh sách chia phòng/chia mâm: mỗi nhóm một trang A4 dọc. */
$yearLabel=(string)(csdl_year_current()['label']??SCHOOL_YEAR);
$preparedDate=trim((string)($_GET['prepared_date']??date('Y-m-d')));
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$preparedDate))$preparedDate=date('Y-m-d');
$preparedBy=trim((string)($_GET['prepared_by']??$by));
$approvedBy=trim((string)($_GET['approved_by']??''));
$groupTitle=$mode==='rooms'?'PHÒNG Ở':'MÂM ĂN';
$documentTitle=$mode==='rooms'?'DANH SÁCH HỌC SINH THEO PHÒNG Ở NỘI TRÚ':'DANH SÁCH HỌC SINH THEO MÂM ĂN NỘI TRÚ';
$groupEntries=[];
foreach($names as $name)$groupEntries[$name]=$grouped[$name]??[];
foreach($grouped as $name=>$students)if(!array_key_exists($name,$groupEntries))$groupEntries[$name]=$students;
uksort($groupEntries,static fn($left,$right)=>strnatcasecmp((string)$left,(string)$right));
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($documentTitle)?> – <?=e(SCHOOL_SHORT)?></title>
<style>
*{box-sizing:border-box}body{margin:0;background:#e5e7eb;color:#000;font-family:"Times New Roman",serif}.export-toolbar{position:sticky;top:0;z-index:10;padding:12px 18px;background:#173f65;color:#fff;font-family:Arial,sans-serif}.export-toolbar form{display:flex;align-items:end;justify-content:center;gap:10px;flex-wrap:wrap}.export-toolbar label{display:grid;gap:3px;font-size:12px}.export-toolbar input{min-height:36px;padding:6px 9px;border:1px solid #cbd5e1;border-radius:7px}.export-toolbar button,.export-toolbar a{min-height:36px;padding:8px 14px;border:0;border-radius:7px;background:#fff;color:#173f65;font-weight:700;text-decoration:none;cursor:pointer}.export-toolbar .print{background:#16a34a;color:#fff}.paper{width:210mm;min-height:297mm;margin:10mm auto;padding:20mm 15mm 20mm 20mm;background:#fff;font-size:13pt;line-height:1.25;page-break-after:always;break-after:page}.paper:last-child{page-break-after:auto;break-after:auto}.national{display:grid;grid-template-columns:40% 60%;gap:8mm;text-align:center;font-weight:700}.national p{margin:0}.national .underline{display:inline-block;border-bottom:1px solid #000;padding-bottom:2px}.place-date{margin:7mm 0 4mm;text-align:right;font-style:italic}.paper h1{margin:0;text-align:center;font-size:15pt}.school-year{text-align:center;font-weight:700;margin:1.5mm 0 5mm}.group-name{text-align:center;font-size:14pt;font-weight:700;margin-bottom:4mm}.summary{display:flex;justify-content:center;gap:8mm;margin-bottom:3mm;font-weight:700}.student-table{width:100%;border-collapse:collapse;table-layout:fixed}.student-table th,.student-table td{border:1px solid #000;padding:2mm 1.5mm}.student-table th{text-align:center}.student-table .stt{width:11mm;text-align:center}.student-table .class{width:22mm;text-align:center}.student-table .gender{width:22mm;text-align:center}.student-table .dob{width:28mm;text-align:center}.student-table tbody tr{height:10mm}.empty{text-align:center;font-style:italic}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:24mm;margin-top:7mm;text-align:center}.signature-title{font-weight:700;text-transform:uppercase}.signature-note{font-style:italic}.signature-name{margin-top:24mm;font-weight:700;min-height:7mm}@media(max-width:850px){.paper{margin:5mm 0;transform-origin:top left}}@media print{@page{size:A4 portrait;margin:20mm 15mm 20mm 20mm}body{background:#fff}.export-toolbar{display:none!important}.paper{width:auto;min-height:auto;margin:0;padding:0;box-shadow:none;font-size:13pt}.student-table thead{display:table-header-group}.student-table tr{break-inside:avoid}.signatures{break-inside:avoid}}
</style></head><body>
<div class="export-toolbar"><form method="get"><input type="hidden" name="mode" value="<?=e($mode)?>"><input type="hidden" name="export" value="a4"><label>Ngày lập<input type="date" name="prepared_date" value="<?=e($preparedDate)?>"></label><label>Người lập<input name="prepared_by" value="<?=e($preparedBy)?>" placeholder="Họ và tên"></label><label>Người duyệt<input name="approved_by" value="<?=e($approvedBy)?>" placeholder="Họ và tên"></label><button type="submit">Cập nhật bản in</button><button type="button" class="print" onclick="window.print()">In / Lưu PDF</button><button type="button" id="saveAssignmentDrive">Lưu lên Drive</button><a href="<?=e(BASE_URL.'noitru_assign.php?mode='.$mode)?>">Quay lại</a></form></div>
<?php if(!$groupEntries):?><section class="paper"><h1><?=e($documentTitle)?></h1><p class="empty">Chưa có dữ liệu <?=e($label)?> để xuất.</p></section><?php endif;?>
<?php foreach($groupEntries as $groupName=>$students):$summary=noitru_assignment_summary($students);?>
<section class="paper">
  <div class="national"><div><p>SỞ GD&amp;ĐT TUYÊN QUANG</p><p>TRƯỜNG PTDT NỘI TRÚ<br>THCS&amp;THPT XÍN MẦN</p></div><div><p>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</p><p><span class="underline">Độc lập - Tự do - Hạnh phúc</span></p></div></div>
  <div class="place-date">Pà Vầy Sủ, ngày <?= (int)date('d',strtotime($preparedDate)) ?> tháng <?= (int)date('m',strtotime($preparedDate)) ?> năm <?=e(date('Y',strtotime($preparedDate)))?></div>
  <h1><?=e($documentTitle)?></h1><div class="school-year">Năm học <?=e($yearLabel)?></div><div class="group-name"><?=e($groupTitle)?>: <?=e($groupName)?></div>
  <div class="summary"><span>Tổng số: <?=$summary['total']?> học sinh</span><span>Nam: <?=$summary['male']?></span><span>Nữ: <?=$summary['female']?></span><?php if($mode==='rooms'):?><span>Loại phòng: <?=e($roomGenders[$groupName]??'Linh hoạt')?></span><?php endif;?></div>
  <table class="student-table"><thead><tr><th class="stt">STT</th><th>Họ và tên</th><th class="class">Lớp</th><th class="gender">Giới tính</th><th class="dob">Ngày sinh</th></tr></thead><tbody><?php foreach($students as $index=>$student):?><tr><td class="stt"><?=$index+1?></td><td><?=e($student['name']??'')?></td><td class="class"><?=e($student['class_name']??'')?></td><td class="gender"><?=e(noitru_assignment_gender($student))?></td><td class="dob"><?php $dob=trim((string)($student['dob']??''));echo e($dob&&strtotime($dob)?date('d/m/Y',strtotime($dob)):$dob);?></td></tr><?php endforeach;?><?php if(!$students):?><tr><td colspan="5" class="empty">Chưa có học sinh được phân vào <?=e($label)?> này.</td></tr><?php endif;?></tbody></table>
  <div class="signatures"><div><div class="signature-title">Người lập danh sách</div><div class="signature-note">(Ký và ghi rõ họ tên)</div><div class="signature-name"><?=e($preparedBy)?></div></div><div><div class="signature-title">Người duyệt</div><div class="signature-note">(Ký và ghi rõ họ tên)</div><div class="signature-name"><?=e($approvedBy)?></div></div></div>
</section>
<?php endforeach;?>
<script>
document.getElementById('saveAssignmentDrive')?.addEventListener('click',async function(){
  const button=this,old=button.textContent,papers=[...document.querySelectorAll('.paper')].map(node=>node.outerHTML).join('');
  const html='<!doctype html><html lang="vi"><head><meta charset="utf-8"><title><?=e($documentTitle)?></title><style>'+document.querySelector('style').textContent+'</style></head><body>'+papers+'</body></html>';
  const data=new FormData();data.append('drive_api','save');data.append('csrf','<?=e(cds_drive_csrf_token())?>');data.append('source_action','<?=e(cds_drive_page_action())?>');data.append('type','room_meal_lists');data.append('name','<?=e($mode==='rooms'?'danh-sach-phong':'danh-sach-mam')?>-<?=e(date('Ymd',strtotime($preparedDate)))?>.html');data.append('file',new Blob([html],{type:'text/html'}),'document.html');
  button.disabled=true;button.textContent='Đang lưu…';try{const response=await fetch('<?=e(BASE_URL)?>admin.php',{method:'POST',body:data});const result=await response.json();alert(result.ok?'Đã lưu bản in lên Google Drive.':(result.message||'Không lưu được lên Drive.'));}catch(error){alert('Không kết nối được máy chủ để lưu Drive.');}finally{button.disabled=false;button.textContent=old;}
});
</script>
</body></html>
