<?php
$quizGuidePrompts=[
 'single'=>['Một đáp án A–D','Hãy soạn [20] câu hỏi củng cố môn [Vật lí], khối [10], chủ đề [Chương 1 – Mở đầu], theo sách [Kết nối tri thức]. Mỗi câu có đúng 1 đáp án đúng, 4 phương án A/B/C/D rõ ràng, không chồng nghĩa. Phân bố mức độ: 50% nhận biết, 30% thông hiểu, 20% vận dụng. Kiểm tra đáp án và phép tính. Không dùng dấu | trong nội dung. Chỉ xuất mỗi câu trên một dòng, không đánh số, không tiêu đề, đúng định dạng: Câu hỏi | Phương án A | Phương án B | Phương án C | Phương án D | Chữ cái đáp án đúng.'],
 'multi'=>['Nhiều đáp án','Hãy soạn [10] câu hỏi môn [môn], khối [khối], chủ đề [chủ đề], sách [sách]. Mỗi câu có 4 phương án A/B/C/D và 2 hoặc 3 phương án đúng. Ghi rõ trong câu hỏi: Chọn tất cả đáp án đúng. Tránh phương án chồng nghĩa. Với mỗi câu, trình bày riêng: Nội dung; A; B; C; D; Các chữ cái đúng; Giải thích ngắn; Thời gian suy nghĩ đề xuất 10–300 giây. Kiểm tra tính chính xác. Tôi sẽ nhập từng câu vào loại Nhiều đáp án, không dùng mục Nhập nhanh A–D.'],
 'paper_logic'=>['Hai mệnh đề – dùng được với thẻ giấy','Hãy soạn [10] câu hỏi môn [môn], khối [khối], chủ đề [chủ đề], sách [sách]. Mỗi câu gồm đúng 2 mệnh đề, đặt tên Mệnh đề A và Mệnh đề B, mỗi mệnh đề có giá trị đúng/sai xác định. Học sinh chọn một kết luận duy nhất: A = Chỉ mệnh đề A đúng; B = Chỉ mệnh đề B đúng; C = Cả hai mệnh đề đúng; D = Cả hai mệnh đề sai. Với mỗi câu, ghi: Nội dung gồm hai mệnh đề; Giá trị đúng/sai từng mệnh đề; Chữ cái kết luận đúng; Giải thích ngắn. Phân bố đều bốn kết luận. Tôi sẽ nhập từng câu vào loại Hai mệnh đề.'],
 'match'=>['Nối cặp','Hãy soạn [5] câu hỏi nối cặp môn [môn], khối [khối], chủ đề [chủ đề], sách [sách]. Mỗi câu có 4 cặp đúng, các vế phải phải khác nhau và không gây nhầm lẫn. Với mỗi câu, xuất: Nội dung yêu cầu; Các cặp đúng, mỗi dòng theo định dạng Vế trái | Vế phải; Giải thích ngắn; Thời gian đề xuất 10–300 giây. Không dùng dấu | bên trong một vế. Tôi sẽ dán các cặp vào ô Các cặp nối của từng câu, không nhập cả bộ vào Nhập nhanh A–D.'],
 'fill'=>['Điền đáp án','Hãy soạn [10] câu hỏi điền đáp án ngắn môn [môn], khối [khối], chủ đề [chủ đề], sách [sách]. Mỗi câu chỉ yêu cầu một kết quả rõ ràng. Với câu tính toán, nêu rõ đơn vị và cách làm tròn trong đề. Với mỗi câu, xuất: Nội dung; Các cách viết đáp án được chấp nhận, mỗi cách trên một dòng; Giải thích ngắn; Thời gian đề xuất 10–300 giây. Liệt kê biến thể có dấu/không dấu nếu muốn chấp nhận cả hai; không tự giả định hệ thống nhận mọi cách viết tương đương. Tôi sẽ nhập từng câu vào loại Điền đáp án.'],
 'order'=>['Sắp xếp','Hãy soạn [5] câu hỏi sắp xếp môn [môn], khối [khối], chủ đề [chủ đề], sách [sách]. Mỗi câu gồm 4–6 bước hoặc sự kiện khác nhau, có một thứ tự đúng xác định. Với mỗi câu, xuất: Nội dung yêu cầu; Danh sách theo đúng thứ tự, mỗi bước trên một dòng; Giải thích ngắn; Thời gian đề xuất 10–300 giây. Không đưa các bước có thể đổi chỗ mà vẫn đúng. Tôi sẽ dán thứ tự đúng vào loại Sắp xếp; hệ thống sẽ đảo thứ tự cho học sinh.']
];
?>
<style>
.quiz-guide{margin:20px auto;border:1px solid #d9d3fa;border-radius:20px;background:#fff;box-shadow:0 12px 35px #46358615;scroll-margin-top:16px;overflow:hidden}.quiz-guide>summary{cursor:pointer;display:flex;align-items:center;gap:12px;padding:20px;font-size:20px;font-weight:850;color:#342477;background:linear-gradient(110deg,#eee9ff,#eaf7ff);list-style:none}.quiz-guide>summary:after{content:'Mở hướng dẫn';margin-left:auto;font-size:13px;background:#6250dc;color:#fff;padding:8px 12px;border-radius:20px}.quiz-guide[open]>summary:after{content:'Thu gọn'}.guide-body{padding:22px;line-height:1.65}.guide-nav{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px}.guide-nav a{padding:8px 12px;background:#f0ecff;border-radius:10px;color:#49359b;font-weight:750}.guide-section{scroll-margin-top:20px;border-top:1px solid #e2e6f1;padding:20px 0}.guide-section h3{font-size:22px;color:#352979;margin:0 0 12px}.guide-flow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin:16px 0}.guide-step{padding:14px;background:linear-gradient(145deg,#f4efff,#eef8ff);border:1px solid #ded5fb;border-radius:14px;font-weight:750}.guide-step b{display:block;width:29px;height:29px;line-height:29px;text-align:center;background:#6651d8;color:#fff;border-radius:50%;margin-bottom:7px}.guide-table{overflow:auto}.guide-table table{width:100%;border-collapse:collapse;font-size:14px}.guide-table th,.guide-table td{padding:10px;border:1px solid #dce2ee;text-align:left}.guide-table th{background:#ece8ff}.guide-tip{background:#fff5db;border-left:4px solid #e7b52a;border-radius:8px;padding:12px 16px;margin:14px 0}.guide-prompt{border:1px solid #ddd7f4;border-radius:12px;padding:12px;margin:10px 0;background:#faf9ff}.guide-prompt summary{cursor:pointer;font-weight:800;color:#493499}.guide-prompt textarea{width:100%;min-height:160px;resize:vertical;margin:12px 0;font:14px/1.55 system-ui}.guide-copy{border:0;background:#6250dc;color:#fff;border-radius:9px;padding:10px 15px;cursor:pointer;font:inherit}.guide-body li{margin:8px 0}.guide-body code{background:#f1f3f9;padding:2px 5px;border-radius:4px;overflow-wrap:anywhere}@media(max-width:800px){.guide-flow{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:550px){.guide-body{padding:15px}.quiz-guide>summary{font-size:17px;padding:15px;flex-wrap:wrap}.quiz-guide>summary:after{margin-left:0}.guide-section h3{font-size:19px}}
</style>
<div class="shell"><details class="quiz-guide" id="quiz-help"><summary>📖 Hướng dẫn sử dụng Hỏi nhanh – Đáp gọn</summary><div class="guide-body">
<p>Chọn nội dung cần xem; có thể mở hướng dẫn trong khi soạn bộ hoặc tổ chức chơi.</p>
<nav class="guide-nav" aria-label="Nội dung hướng dẫn"><a href="#guide-author">✏️ Soạn bộ</a><a href="#guide-prompts">🤖 Mẫu lệnh ChatGPT</a><a href="#guide-computer">💻 Chơi trên máy</a><a href="#guide-paper">📷 Chơi bằng giấy</a><a href="#guide-settings">🎵 Cài đặt & xử lý lỗi</a></nav>
<section class="guide-section" id="guide-author"><h3>1. Soạn và quản lý bộ câu hỏi</h3>
<div class="guide-flow" aria-label="Sơ đồ soạn bộ"><div class="guide-step"><b>1</b>Tạo bộ mới</div><div class="guide-step"><b>2</b>Gõ tên · chọn môn, khối</div><div class="guide-step"><b>3</b>Chọn dạng câu hỏi</div><div class="guide-step"><b>4</b>Nhập nội dung · đáp án · lưu</div><div class="guide-step"><b>5</b>Kiểm tra · mở lượt chơi</div></div>
<ol><li>Trong <strong>Thư viện câu hỏi</strong>, bấm <strong>Tạo bộ câu hỏi mới</strong>. Gõ tên bộ; chọn <strong>Môn</strong>, <strong>Khối</strong>; viết giới thiệu và chọn Riêng tư/Công khai.</li><li>Vào <strong>Soạn câu hỏi</strong>, chọn một trong sáu dạng. Nhập đề và dữ liệu tương ứng theo bảng dưới.</li><li>Chọn <strong>thời gian suy nghĩ</strong>, mặc định 20 giây, từ 10 đến 300 giây. Thời gian riêng của câu được dùng trong chế độ chơi trên máy theo thời gian; chơi giấy do giáo viên quyết định khi dừng.</li><li>Có thể thêm ảnh bằng chức năng của trình soạn, hoặc điền liên kết ảnh, video, âm thanh hợp lệ. Viết giải thích để phục vụ công bố đáp án.</li><li>Bấm <strong>Lưu câu hỏi</strong>. Kiểm tra danh sách, đáp án đúng; dùng các nút sửa, sao chép, đổi thứ tự hoặc xóa câu. Một bộ tối đa 100 câu.</li><li><strong>Nhập nhanh nhiều câu A–D</strong> chỉ nhận câu Một đáp án, mỗi dòng sáu cột: <code>Câu hỏi | A | B | C | D | Chữ cái đúng</code>. Không thêm số thứ tự, tiêu đề hoặc dấu <code>|</code> trong nội dung từng cột. Các dạng khác nhập từng câu trong trình soạn.</li></ol>
<div class="guide-table"><table><thead><tr><th>Dạng</th><th>Cách nhập</th><th>Thẻ giấy</th></tr></thead><tbody>
<tr><td>Một đáp án</td><td>Nhập đủ A–D, chọn đúng một chữ cái.</td><td>✓ Có</td></tr>
<tr><td>Hai mệnh đề</td><td>Viết mệnh đề A và B trong đề. Chọn kết luận: A = Chỉ A đúng; B = Chỉ B đúng; C = Cả hai đúng; D = Cả hai sai.</td><td>✓ Có</td></tr>
<tr><td>Nhiều đáp án</td><td>Nhập A–D, tích các phương án đúng.</td><td>Không</td></tr>
<tr><td>Nối cặp</td><td>2–8 cặp, mỗi dòng <code>Vế trái | Vế phải</code>; các vế phải khác nhau.</td><td>Không</td></tr>
<tr><td>Điền đáp án</td><td>Mỗi dòng một cách viết chấp nhận. Hệ thống bỏ phân biệt hoa/thường và khoảng trắng thừa; không tự bỏ dấu hay đổi đơn vị.</td><td>Không</td></tr>
<tr><td>Sắp xếp</td><td>2–8 bước khác nhau theo đúng thứ tự, mỗi bước một dòng.</td><td>Không</td></tr>
</tbody></table></div>
<p>Thư viện lọc theo Môn, Khối và tên. Bộ công khai có thể được người khác chọn chơi hoặc sao chép; chỉ chủ bộ và quản trị sửa/xóa bộ gốc. Nút <strong>Xóa</strong> ngoài thư viện xóa cả lượt chơi và kết quả liên quan sau khi xác nhận.</p>
</section>
<section class="guide-section" id="guide-prompts"><h3>2. Mẫu lệnh tạo câu hỏi bằng ChatGPT</h3><p>Thay các phần trong <strong>[ngoặc vuông]</strong> bằng nội dung cần dạy, gửi lệnh cho ChatGPT rồi kiểm tra kiến thức và đáp án trước khi nhập CDS. Nếu cần bám sát một sách, cung cấp nội dung bài hoặc trang sách liên quan.</p>
<?php foreach($quizGuidePrompts as $key=>$prompt):?><details class="guide-prompt"><summary><?=e($prompt[0])?></summary><textarea id="guide-prompt-<?=e($key)?>" readonly aria-label="Mẫu lệnh <?=e($prompt[0])?>"><?=e($prompt[1])?></textarea><button type="button" class="guide-copy" data-guide-copy="guide-prompt-<?=e($key)?>">📋 Sao chép mẫu lệnh</button></details><?php endforeach?>
<div class="guide-tip">Chỉ mẫu <strong>Một đáp án A–D</strong> dùng trực tiếp với Nhập nhanh. Với các mẫu còn lại, lấy từng phần nội dung và dán vào đúng ô của trình soạn. ChatGPT không tự lưu câu hỏi vào CDS.</div>
</section>
<section class="guide-section" id="guide-computer"><h3>3. Tổ chức chơi trên máy tính/điện thoại học sinh</h3>
<div class="guide-flow" aria-label="Sơ đồ chơi trên máy"><div class="guide-step"><b>1</b>Chọn bộ & chế độ máy</div><div class="guide-step"><b>2</b>Chọn nhịp & 1–2 lớp</div><div class="guide-step"><b>3</b>Tạo lượt · gửi mã</div><div class="guide-step"><b>4</b>Học sinh vào chơi</div><div class="guide-step"><b>5</b>Công bố & xem kết quả</div></div>
<ol><li>Chọn bộ trong thư viện → <strong>Chọn cách chơi</strong> → <strong>Chơi trên máy</strong>.</li><li>Chọn <strong>Theo thời gian</strong> hoặc <strong>Theo nhịp giáo viên</strong>, rồi chọn một hoặc hai lớp và bấm <strong>Tạo lượt chơi</strong>. Lượt mở trong 24 giờ; hai lớp dùng chung mã.</li><li>Trong thẻ lượt chơi, mở <strong>Màn hình chiếu</strong> trên máy giáo viên nối máy chiếu/TV. Bấm Toàn màn hình và Bật âm thanh nếu dùng nhạc. Lượt mới có màn chào tên bộ, môn, khối.</li><li>Học sinh mở <a href="<?=BASE_URL?>vaochoi.php" target="_blank" rel="noopener"><?=e(BASE_URL)?>vaochoi.php</a>, nhập mã 8 chữ số, chọn đúng tên và bấm Bắt đầu. Học sinh cần thiết bị có mạng.</li><li><strong>Theo thời gian:</strong> học sinh bắt đầu trên thiết bị của mình; đồng hồ chạy theo từng câu. Sau khi trả lời hoặc hết giờ, học sinh tự bấm Câu tiếp. Các em có thể ở những câu khác nhau; màn chiếu không đại diện tiến độ của tất cả học sinh.</li><li><strong>Theo nhịp giáo viên:</strong> học sinh chờ giáo viên bấm Bắt đầu trên màn điều khiển; giáo viên dùng Câu trước/Câu tiếp để cả lớp cùng chuyển. Thời gian chờ do giáo viên quyết định.</li><li>Quay về <strong>Các lượt chơi</strong> để công bố đáp án, kết thúc lượt và mở <strong>Kết quả</strong>. Có thống kê từng câu và xuất CSV chi tiết. Tổ chức một lượt thử trước khi dùng với cả lớp.</li></ol>
</section>
<section class="guide-section" id="guide-paper"><h3>4. Tổ chức chơi bằng thẻ giấy A–D</h3>
<div class="guide-flow" aria-label="Sơ đồ chơi bằng giấy"><div class="guide-step"><b>1</b>Chuẩn bị bộ & thẻ</div><div class="guide-step"><b>2</b>Tạo lượt thẻ giấy</div><div class="guide-step"><b>3</b>Mở màn chiếu + máy quét</div><div class="guide-step"><b>4</b>Bắt đầu · quét đáp án</div><div class="guide-step"><b>5</b>Công bố · câu tiếp</div></div>
<ol><li>Bộ câu hỏi chỉ được chứa <strong>Một đáp án</strong> hoặc <strong>Hai mệnh đề</strong>. Nếu có Nhiều đáp án/Nối cặp/Điền/Sắp xếp, lựa chọn thẻ giấy bị khóa; tạo bộ riêng phù hợp.</li><li>Mở <a href="<?=BASE_URL?>hoclieu_quiz_cards.php">In thẻ trả lời A–D</a>. Chọn lớp hoặc Toàn trường, tìm tên và tích học sinh → Tạo trang in đã chọn → In thẻ đã chọn. A4 dọc, 100%, tắt đầu/chân trang; hai thẻ mỗi trang. Phát đúng thẻ cho từng em, có thể dùng lại mã cũ.</li><li>Chọn bộ → Chọn cách chơi → <strong>Quét thẻ giấy A–D</strong> → chọn một hoặc hai lớp → Tạo lượt chơi.</li><li>Trên máy nối máy chiếu, mở <strong>Màn hình chiếu</strong> của lượt đó. Trên điện thoại giáo viên, mở <strong>Máy quét</strong> cùng mã; đăng nhập tài khoản có quyền điều khiển. Không mở camera trên máy chiếu.</li><li>Màn chiếu ban đầu hiện màn chào. Bấm <strong>Bắt đầu · Camera</strong> trên điện thoại, cho phép camera: camera mở và màn chiếu hiện câu hỏi. Nếu trình duyệt hỏi quyền, chọn Cho phép.</li><li>Học sinh đọc đề, chọn một chữ cái rồi <strong>xoay thẻ để chữ A/B/C/D tương ứng nằm ở cạnh trên</strong>. Hướng mặt mã về camera, không che mã, giữ thẻ ổn định. Không cần điện thoại cá nhân.</li><li>Giáo viên lia camera qua lớp; nhìn tên đã quét và mục <strong>Học sinh chưa quét</strong>. Dùng zoom khi cần, bảo đảm đủ sáng và mã đủ rõ. Quét lại hoặc sửa thủ công nếu nhận sai; chỉ ghi nhận đáp án khi đang ở trạng thái quét.</li><li>Bấm Dừng quét rồi kiểm tra, hoặc <strong>Công bố</strong> để dừng và hiện kết quả/biểu đồ trên màn chiếu. Khi phát hiện sai, dùng các công cụ quét lại/sửa phù hợp trước khi chuyển.</li><li>Bấm <strong>Tiếp</strong> trên điện thoại để chuyển câu; sau chuyển câu bấm Bắt đầu/Camera để mở lượt quét cho câu mới. Với giấy, giáo viên quyết định thời gian suy nghĩ và lúc kết thúc quét, không dùng đồng hồ 20 giây của chế độ máy.</li><li>Ở câu cuối, dừng quét và công bố kết quả → <strong>Kết thúc & xếp hạng</strong> để hiện bảng vinh danh. Về trang quản lý lượt để xem báo cáo và xuất kết quả.</li></ol>
<div class="guide-tip"><strong>Quy ước Hai mệnh đề:</strong> chữ trên thẻ là lựa chọn kết luận: A = Chỉ mệnh đề A đúng; B = Chỉ mệnh đề B đúng; C = Cả hai đúng; D = Cả hai sai. Không dùng quy ước A = Đúng, B = Sai cho dạng này.</div>
</section>
<section class="guide-section" id="guide-settings"><h3>5. Âm thanh, quyền và xử lý lỗi thường gặp</h3>
<ul><li><strong>Nhạc chung:</strong> quản trị mở Âm thanh chung cho trò chơi ở trang thư viện. Có nhạc chào mừng, bắt đầu, nền, kết thúc thời gian, công bố đáp án và điểm. Dán URL HTTPS trực tiếp tới tệp MP3/OGG/WAV, để trống để tắt; liên kết trang chia sẻ chưa chắc là liên kết tệp phát được.</li><li><strong>Không có tiếng:</strong> trên màn chiếu bấm Bật âm thanh một lần, kiểm tra âm lượng máy/TV và đường dẫn nhạc. Trình duyệt có thể chặn tự phát trước thao tác người dùng.</li><li><strong>Camera không mở:</strong> dùng HTTPS trong Safari/Chrome, cho phép Camera ở quyền của trang; đóng ứng dụng khác đang dùng camera rồi thử lại. Thông báo lỗi hiện trên màn điện thoại.</li><li><strong>Không nhận thẻ:</strong> kiểm tra đúng mã lượt, đúng lớp/thẻ học sinh, đang mở lượt quét; ánh sáng đủ, không lóa, không che mã, không cắt mất góc mã. Đưa mã gần hơn hoặc điều chỉnh zoom.</li><li><strong>Không đồng bộ:</strong> hai thiết bị phải cùng mã lượt và có mạng. Giữ màn chiếu mở; nếu mất kết nối, chờ khôi phục và kiểm tra số học sinh đã ghi nhận trước khi chuyển câu.</li><li><strong>Không sửa được bộ công khai:</strong> tạo bản sao để sửa nếu không phải chủ bộ/quản trị. Không xóa bộ nếu còn cần kết quả của các lượt chơi.</li></ul>
</section>
</div></details></div>
<script>
document.querySelectorAll('[data-guide-copy]').forEach(button=>button.addEventListener('click',async()=>{const field=document.getElementById(button.dataset.guideCopy);try{await navigator.clipboard.writeText(field.value);button.textContent='✓ Đã sao chép';setTimeout(()=>button.textContent='📋 Sao chép mẫu lệnh',2000)}catch(error){field.focus();field.select();button.textContent='Đã chọn mẫu · nhấn Ctrl+C hoặc ⌘C để sao chép'}}));
document.addEventListener('click',event=>{const link=event.target.closest('a[href="#quiz-help"]');if(link){document.getElementById('quiz-help').open=true}});
</script>
