<?php
/** Bổ sung thẻ dọc 86x54 mm, niên khóa, mặt sau và in gấp đôi. */
if (defined('STUDENT_CARD_DUPLEX_UI')) return;
define('STUDENT_CARD_DUPLEX_UI', true);

function student_card_duplex_filter(string $html): string {
    $path = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?: '';
    if (!preg_match('~/csdl_student_cards\.php$~', $path) || stripos($html, '</body>') === false) return $html;
    $addon = <<<'HTML'
<style id="studentCardDuplexStyle">
#scDuplexPanel{background:#fff;border:1px solid #dbe5ee;border-radius:14px;padding:1rem;margin:0 0 1rem}.sc-themes{display:grid;grid-template-columns:repeat(4,1fr);gap:.45rem}.sc-theme{height:42px;border:2px solid transparent;border-radius:9px;cursor:pointer}.sc-theme.active{border-color:#111827;box-shadow:0 0 0 2px #fff inset}.sc-duplex-sheet{display:flex;align-items:stretch;justify-content:center;gap:0;break-inside:avoid;margin-bottom:10mm}.sc-face{width:54mm;height:86mm;position:relative;overflow:hidden;border:1px solid #94a3b8;background:#fff;color:#10243a}.sc-front{border-radius:3mm 0 0 3mm}.sc-back{border-radius:0 3mm 3mm 0}.sc-fold{width:0;border-left:1px dashed #6b7280;position:relative}.sc-fold:after{content:'ĐƯỜNG GẤP';position:absolute;top:4mm;left:-4mm;font-size:6pt;color:#6b7280;writing-mode:vertical-rl;background:#fff;padding:1mm 0}.sc-wave-top,.sc-wave-bottom{position:absolute;left:0;right:0;height:13mm;background:linear-gradient(135deg,var(--sc-main),var(--sc-second));z-index:0}.sc-wave-top{top:0;border-radius:0 0 60% 18%}.sc-wave-bottom{bottom:0;border-radius:55% 20% 0 0}.sc-face-content{position:relative;z-index:1;height:100%;padding:4mm 4mm 5mm;display:flex;flex-direction:column;align-items:center;text-align:center}.sc-logo-print{width:13mm;height:13mm;object-fit:contain;margin-top:1mm}.sc-agency{font-size:7.2pt;font-weight:700;margin-top:1mm}.sc-school-name{font-size:8.1pt;font-weight:900;line-height:1.15}.sc-card-title2{font-size:16pt;font-weight:900;color:var(--sc-main);margin:4mm 0 2mm}.sc-photo2{width:25mm;height:33.3mm;object-fit:cover;border:1px solid #94a3b8;border-radius:2mm;background:#eef2f7}.sc-student-name2{font-size:11pt;font-weight:900;color:var(--sc-main);text-transform:uppercase;margin-top:2mm;line-height:1.15}.sc-info2{font-size:8pt;line-height:1.45;margin-top:1.2mm}.sc-qr2{width:18mm;height:18mm;margin-top:auto;margin-bottom:5mm}.sc-qr2 img,.sc-qr2 canvas{width:18mm!important;height:18mm!important}.sc-rule-title{font-size:11pt;font-weight:900;color:#fff;background:var(--sc-main);border-radius:999px;padding:1.4mm 4mm;margin:2mm 0 3mm}.sc-rules{font-size:7.5pt;line-height:1.45;text-align:left;white-space:pre-line;width:100%}.sc-back-note{font-size:6.8pt;line-height:1.35;margin-top:1mm}.sc-face.hide-front .sc-face-content>*{display:none}.sc-face.hide-back .sc-face-content>*{display:none}.sc-only-front .sc-back,.sc-only-back .sc-front,.sc-only-front .sc-fold,.sc-only-back .sc-fold{display:none}.sc-only-front .sc-front,.sc-only-back .sc-back{border-radius:3mm}@media print{#scDuplexPanel,.sc-designer-ui,.no-print{display:none!important}.preview-area{display:block!important}.sc-duplex-sheet{margin:0 auto 8mm;page-break-inside:avoid}.sc-face{box-shadow:none}.student-card{display:none!important}@page{size:A4 portrait;margin:8mm}}
</style>
<script id="studentCardDuplexScript">
(function(){
if(typeof students==='undefined'||document.getElementById('scDuplexPanel'))return;
const preview=document.getElementById('preview');if(!preview)return;
const defaults={cohort:'2022 - 2025',front:true,back:true,frontLogo:true,frontAgency:true,frontSchool:true,frontTitle:true,frontPhoto:true,frontName:true,frontClass:true,frontYear:true,frontCohort:true,frontQr:false,backRules:true,backQr:true,backNote:true,agency:'SỞ GD&ĐT TUYÊN QUANG',school:'TRƯỜNG PTDTNT THCS&THPT XÍN MẦN',title:'THẺ HỌC SINH',rules:'1. Thẻ học sinh là tài sản của nhà trường, cấp cho học sinh để phục vụ học tập, rèn luyện và các hoạt động của nhà trường.\n2. Học sinh phải luôn mang theo thẻ khi đến trường và khi tham gia các hoạt động.\n3. Không cho người khác mượn thẻ.\n4. Không tẩy xóa, sửa chữa, làm hư hỏng thẻ.\n5. Khi mất thẻ, phải báo ngay cho giáo viên chủ nhiệm hoặc văn phòng nhà trường để được cấp lại.\n6. Thẻ chỉ có giá trị trong niên khóa của học sinh.',backNote:'Quét mã để xác minh thông tin học sinh hoặc sử dụng tại thư viện và các hệ thống của nhà trường.',theme:'blue'};
let cfg=Object.assign({},defaults,JSON.parse(localStorage.getItem('cdsStudentCardDuplexV1')||'{}'));
const themes={blue:['#0d47a1','#42a5f5','#f4b400'],green:['#166534','#22c55e','#facc15'],red:['#991b1b','#ef4444','#f59e0b'],purple:['#6b21a8','#c026d3','#f0abfc'],orange:['#c2410c','#fb923c','#fde047'],teal:['#0f766e','#14b8a6','#67e8f9'],navy:['#0f2f57','#2d6ca2','#f4b400'],rose:['#9f1239','#fb7185','#fda4af']};
const panel=document.createElement('div');panel.id='scDuplexPanel';panel.className='no-print';panel.innerHTML=`<div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h6 class="fw-bold mb-0"><i class="bi bi-layout-split"></i> Thẻ dọc 86 × 54 mm · In 2 mặt gấp đôi</h6><div class="small text-muted">Mỗi học sinh in mặt trước và mặt sau liền nhau, gấp theo đường kẻ để cài vào vỏ thẻ.</div></div><button id="scDuplexSave" class="btn btn-sm btn-success"><i class="bi bi-save"></i> Lưu tùy chọn</button></div><div class="row g-3"><div class="col-lg-4"><label class="form-label small">Niên khóa</label><input id="scCohort" class="form-control form-control-sm mb-2"><label class="form-label small">Dòng Sở GD&ĐT</label><input id="scAgency2" class="form-control form-control-sm mb-2"><label class="form-label small">Tên trường</label><input id="scSchool2" class="form-control form-control-sm mb-2"><label class="form-label small">Tiêu đề thẻ</label><input id="scTitle2" class="form-control form-control-sm"></div><div class="col-lg-4"><label class="form-label small">Mặt trước hiển thị</label><div id="scFrontOpts" class="row g-1"></div><label class="form-label small mt-2">Mặt sau hiển thị</label><div id="scBackOpts" class="row g-1"></div></div><div class="col-lg-4"><label class="form-label small">Mẫu màu phối</label><div id="scThemes" class="sc-themes mb-2"></div><label class="form-label small">Quy định sử dụng thẻ</label><textarea id="scRules" rows="7" class="form-control form-control-sm mb-2"></textarea><label class="form-label small">Ghi chú dưới QR</label><textarea id="scBackNote" rows="2" class="form-control form-control-sm"></textarea></div></div>`;
preview.parentElement.insertBefore(panel,preview);
const $=id=>document.getElementById(id);scCohort.value=cfg.cohort;scAgency2.value=cfg.agency;scSchool2.value=cfg.school;scTitle2.value=cfg.title;scRules.value=cfg.rules;scBackNote.value=cfg.backNote;
const front=[['front','In mặt trước'],['frontLogo','Logo'],['frontAgency','Sở GD&ĐT'],['frontSchool','Tên trường'],['frontTitle','Tiêu đề'],['frontPhoto','Ảnh'],['frontName','Tên HS'],['frontClass','Lớp'],['frontYear','Năm học'],['frontCohort','Niên khóa'],['frontQr','QR mặt trước']];
const back=[['back','In mặt sau'],['backRules','Quy định'],['backQr','QR mặt sau'],['backNote','Ghi chú QR']];
function opts(list){return list.map(x=>`<label class="col-6 form-check small"><input class="form-check-input sc-duplex-opt" data-key="${x[0]}" type="checkbox" ${cfg[x[0]]?'checked':''}><span class="form-check-label">${x[1]}</span></label>`).join('')};scFrontOpts.innerHTML=opts(front);scBackOpts.innerHTML=opts(back);
Object.entries(themes).forEach(([k,v])=>{let b=document.createElement('button');b.type='button';b.className='sc-theme'+(cfg.theme===k?' active':'');b.dataset.theme=k;b.style.background=`linear-gradient(135deg,${v[0]} 0 48%,${v[1]} 48% 75%,${v[2]} 75%)`;scThemes.appendChild(b)});
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function selected(){let ids=new Set([...document.querySelectorAll('.student-check:checked')].map(x=>x.value));return students.filter(s=>ids.has(String(s.id)))}
function qr(el,url){if(typeof QRCode!=='undefined')new QRCode(el,{text:new URL(url,location.origin).href,width:110,height:110,correctLevel:QRCode.CorrectLevel.M})}
function faceFront(s){let logo=localStorage.getItem('cdsCardLogo')||'';return `<section class="sc-face sc-front"><div class="sc-wave-top"></div><div class="sc-wave-bottom"></div><div class="sc-face-content">${cfg.frontLogo?(logo?`<img class="sc-logo-print" src="${logo}">`:''):''}${cfg.frontAgency?`<div class="sc-agency">${esc(cfg.agency)}</div>`:''}${cfg.frontSchool?`<div class="sc-school-name">${esc(cfg.school)}</div>`:''}${cfg.frontTitle?`<div class="sc-card-title2">${esc(cfg.title)}</div>`:''}${cfg.frontPhoto?`<img class="sc-photo2" src="${base}student_photo.php?id=${encodeURIComponent(s.id)}">`:''}${cfg.frontName?`<div class="sc-student-name2">${esc(s.name)}</div>`:''}<div class="sc-info2">${cfg.frontClass?`<div>Lớp: <b>${esc(s._class_name||'—')}</b></div>`:''}${cfg.frontYear?`<div>Năm học: <b>${esc(year)}</b></div>`:''}${cfg.frontCohort?`<div>Niên khóa: <b>${esc(cfg.cohort)}</b></div>`:''}</div>${cfg.frontQr?`<div class="sc-qr2" data-url="${esc(s._verify_url)}"></div>`:''}</div></section>`}
function faceBack(s){return `<section class="sc-face sc-back"><div class="sc-wave-top"></div><div class="sc-wave-bottom"></div><div class="sc-face-content">${cfg.backRules?`<div class="sc-rule-title">QUY ĐỊNH SỬ DỤNG THẺ</div><div class="sc-rules">${esc(cfg.rules)}</div>`:''}${cfg.backQr?`<div class="sc-qr2" data-url="${esc(s._verify_url)}"></div>`:''}${cfg.backNote?`<div class="sc-back-note">${esc(cfg.backNote)}</div>`:''}</div></section>`}
function draw(){let t=themes[cfg.theme]||themes.blue;document.documentElement.style.setProperty('--sc-main',t[0]);document.documentElement.style.setProperty('--sc-second',t[1]);let mode=cfg.front&&cfg.back?'':(cfg.front?'sc-only-front':'sc-only-back');preview.innerHTML=selected().map(s=>`<article class="sc-duplex-sheet ${mode}">${cfg.front?faceFront(s):''}${cfg.front&&cfg.back?'<div class="sc-fold"></div>':''}${cfg.back?faceBack(s):''}</article>`).join('');preview.querySelectorAll('.sc-qr2').forEach(el=>qr(el,el.dataset.url));if(window.selectedCount)selectedCount.textContent=selected().length}
function sync(){cfg.cohort=scCohort.value;cfg.agency=scAgency2.value;cfg.school=scSchool2.value;cfg.title=scTitle2.value;cfg.rules=scRules.value;cfg.backNote=scBackNote.value;document.querySelectorAll('.sc-duplex-opt').forEach(x=>cfg[x.dataset.key]=x.checked);draw()}
panel.addEventListener('input',sync);panel.addEventListener('change',sync);scThemes.addEventListener('click',e=>{let b=e.target.closest('.sc-theme');if(!b)return;cfg.theme=b.dataset.theme;scThemes.querySelectorAll('.sc-theme').forEach(x=>x.classList.toggle('active',x===b));draw()});scDuplexSave.onclick=()=>{sync();localStorage.setItem('cdsStudentCardDuplexV1',JSON.stringify(cfg));alert('Đã lưu tùy chọn thẻ dọc hai mặt trên trình duyệt này.')};document.addEventListener('change',e=>{if(e.target.matches('.student-check'))setTimeout(draw,0)});const oldRender=window.render;window.render=function(){if(oldRender)oldRender();setTimeout(draw,0)};draw();
})();
</script>
HTML;
    return preg_replace('/<\/body>/i', $addon . '</body>', $html, 1) ?? $html;
}
ob_start('student_card_duplex_filter');
