<?php
/** Trình thiết kế kéo thả cho trang tạo thẻ học sinh. */
if (defined('STUDENT_CARD_DESIGNER_UI')) return;
define('STUDENT_CARD_DESIGNER_UI', true);

function student_card_designer_filter(string $html): string {
    $path = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?: '';
    if (!preg_match('~/csdl_student_cards\.php$~', $path) || stripos($html, '</body>') === false) return $html;
    $addon = <<<'HTML'
<style id="studentCardDesignerStyle">
#scDesigner{background:#fff;border:1px solid #dbe5ee;border-radius:14px;padding:1rem;margin-bottom:1rem}.sc-grid{display:grid;grid-template-columns:290px minmax(0,1fr);gap:1rem}.sc-stage{overflow:auto;background:#dfe7ef;border-radius:12px;padding:14px}.sc-canvas{width:856px;height:540px;position:relative;overflow:hidden;border:2px solid #9fb0c0;border-radius:24px;background:linear-gradient(180deg,#1f4e79 0 118px,#fff 118px);transform-origin:top left}.sc-item{position:absolute;cursor:move;user-select:none;box-sizing:border-box;white-space:pre-line;line-height:1.15}.sc-item.active{outline:3px solid #0d6efd;outline-offset:2px}.sc-logo img,.sc-photo img{width:100%;height:100%;display:block;object-fit:contain}.sc-photo img{object-fit:cover;border:2px solid #aebdca;border-radius:8px}.sc-placeholder{width:100%;height:100%;display:flex;align-items:center;justify-content:center;border:2px dashed #9fb0c0;border-radius:8px;color:#718096;background:#f5f7fa}.sc-qr>div,.sc-qr img,.sc-qr canvas{width:100%!important;height:100%!important}.sc-props{display:grid;grid-template-columns:1fr 1fr;gap:.45rem}.sc-help{font-size:.78rem;color:#66788a}@media(max-width:1050px){.sc-grid{grid-template-columns:1fr}.sc-canvas{transform:scale(.7);margin-bottom:-162px;margin-right:-257px}.sc-stage{min-height:400px}}@media(max-width:600px){.sc-canvas{transform:scale(.42);margin-bottom:-313px;margin-right:-497px}.sc-stage{min-height:260px;padding:6px}.sc-props{grid-template-columns:1fr}}
</style>
<script id="studentCardDesignerScript">
(function(){
if(typeof students==='undefined'||typeof render!=='function'||document.getElementById('scDesigner'))return;
const D={logo:{n:'Logo trường',t:'logo',x:35,y:22,w:92,h:92,v:1},agency:{n:'Sở GD&ĐT',t:'text',x:140,y:25,w:630,h:34,f:25,c:'#fff',b:700,a:'center',v:1},school:{n:'Tên trường',t:'text',x:125,y:64,w:660,h:42,f:28,c:'#fff',b:900,a:'center',v:1},title:{n:'Tiêu đề',t:'text',x:215,y:132,w:430,h:54,f:38,c:'#1f4e79',b:900,a:'center',v:1},photo:{n:'Ảnh học sinh',t:'photo',x:55,y:198,w:190,h:253,v:1},name:{n:'Tên học sinh',t:'data',x:275,y:218,w:520,h:58,f:31,c:'#1f4e79',b:900,a:'center',v:1},classyear:{n:'Lớp, năm học',t:'data',x:275,y:300,w:350,h:70,f:23,c:'#10243a',b:700,a:'left',v:1},qr:{n:'Mã QR',t:'qr',x:650,y:292,w:145,h:145,v:1},qrcode:{n:'Mã thông tin',t:'data',x:600,y:446,w:230,h:30,f:16,c:'#10243a',b:700,a:'center',v:1}};
let d=JSON.parse(localStorage.getItem('cdsCardDesignerV1')||'null')||JSON.parse(JSON.stringify(D)),logo=localStorage.getItem('cdsCardLogo')||'',active='';
const oldOptions=document.querySelectorAll('.option-card')[1],preview=document.getElementById('preview');if(oldOptions)oldOptions.style.display='none';
const box=document.createElement('div');box.id='scDesigner';box.className='no-print';box.innerHTML=`<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h6 class="fw-bold mb-0"><i class="bi bi-arrows-move"></i> Tự thiết kế bố cục thẻ</h6><div class="sc-help">Kéo từng thành phần trên thẻ mẫu. Bố cục áp dụng cho toàn bộ thẻ khi in.</div></div><div class="d-flex gap-2"><button id="scSave" class="btn btn-sm btn-outline-success">Lưu bố cục</button><button id="scReset" class="btn btn-sm btn-outline-warning">Khôi phục mẫu</button></div></div><div class="sc-grid"><div><label class="form-label small mb-0">Dòng 1</label><input id="scAgency" class="form-control form-control-sm mb-2"><label class="form-label small mb-0">Dòng 2</label><input id="scSchool" class="form-control form-control-sm mb-2"><label class="form-label small mb-0">Tiêu đề</label><input id="scTitle" class="form-control form-control-sm mb-2"><label class="form-label small mb-0">Chèn logo</label><input id="scLogo" type="file" accept="image/png,image/jpeg,image/webp" class="form-control form-control-sm mb-2"><div id="scToggles" class="row g-1 mb-2"></div><div id="scProps" hidden><div id="scLabel" class="fw-semibold mb-1"></div><div class="sc-props"><input id="scFont" type="number" min="8" max="72" class="form-control form-control-sm" title="Cỡ chữ"><input id="scColor" type="color" class="form-control form-control-color w-100" title="Màu chữ"><input id="scWidth" type="number" min="20" max="856" class="form-control form-control-sm" title="Chiều rộng"><input id="scHeight" type="number" min="20" max="540" class="form-control form-control-sm" title="Chiều cao"><select id="scAlign" class="form-select form-select-sm"><option value="left">Căn trái</option><option value="center">Căn giữa</option><option value="right">Căn phải</option></select><select id="scWeight" class="form-select form-select-sm"><option value="400">Chữ thường</option><option value="700">Chữ đậm</option><option value="900">Rất đậm</option></select></div></div></div><div class="sc-stage"><div id="scCanvas" class="sc-canvas"></div></div></div>`;
const target=document.querySelector('.col-xl-9');if(target)target.insertBefore(box,target.firstChild);else document.querySelector('.container-fluid').prepend(box);
const $=id=>document.getElementById(id),txt=JSON.parse(localStorage.getItem('cdsCardTexts')||'null')||{agency:'SỞ GD&ĐT TUYÊN QUANG',school:'TRƯỜNG PTDTNT THCS&THPT XÍN MẦN',title:'THẺ HỌC SINH'};scAgency.value=txt.agency;scSchool.value=txt.school;scTitle.value=txt.title;
function E(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function content(k,s){if(k==='agency')return scAgency.value;if(k==='school')return scSchool.value;if(k==='title')return scTitle.value;if(k==='name')return s?String(s.name||'').toUpperCase():'NGUYỄN VĂN A';if(k==='classyear')return s?'Lớp: '+(s._class_name||'—')+'\nNăm học: '+year:'Lớp: 9A\nNăm học: '+year;if(k==='qrcode')return s?'Mã thông tin: '+s._public_code:'Mã thông tin: XM-HS001';return ''}
function sty(o,z=1){return `left:${o.x*z}px;top:${o.y*z}px;width:${o.w*z}px;height:${o.h*z}px;font-size:${(o.f||16)*z}px;color:${o.c||'#10243a'};font-weight:${o.b||400};text-align:${o.a||'left'}`}
function item(k,o,s,z=1){if(!o.v)return'';let x='';if(o.t==='text'||o.t==='data')x=E(content(k,s));if(o.t==='logo')x=logo?`<img src="${logo}">`:'<div class="sc-placeholder"><i class="bi bi-image fs-1"></i></div>';if(o.t==='photo')x=s?`<img src="${base}student_photo.php?id=${encodeURIComponent(s.id)}">`:'<div class="sc-placeholder"><i class="bi bi-person fs-1"></i></div>';if(o.t==='qr')x='<div></div>';return `<div class="sc-item sc-${o.t}" data-k="${k}" style="${sty(o,z)}">${x}</div>`}
function draw(){scCanvas.innerHTML=Object.entries(d).map(([k,o])=>item(k,o,null)).join('');scCanvas.querySelectorAll('.sc-item').forEach(el=>{el.classList.toggle('active',el.dataset.k===active);el.onpointerdown=drag});scToggles.innerHTML=Object.entries(d).map(([k,o])=>`<label class="col-6 form-check small"><input class="form-check-input sc-toggle" data-k="${k}" type="checkbox" ${o.v?'checked':''}><span class="form-check-label">${E(o.n)}</span></label>`).join('');props()}
function props(){let o=d[active];scProps.hidden=!o;if(!o)return;scLabel.textContent=o.n;scFont.value=o.f||16;scColor.value=o.c||'#10243a';scWidth.value=o.w;scHeight.value=o.h;scAlign.value=o.a||'left';scWeight.value=String(o.b||400)}
function drag(e){e.preventDefault();let el=e.currentTarget,k=el.dataset.k,o=d[k],r=scCanvas.getBoundingClientRect(),z=r.width/856,sx=e.clientX,sy=e.clientY,ox=o.x,oy=o.y;active=k;draw();el=scCanvas.querySelector(`[data-k="${k}"]`);el.setPointerCapture(e.pointerId);el.onpointermove=v=>{o.x=Math.max(0,Math.min(856-o.w,ox+(v.clientX-sx)/z));o.y=Math.max(0,Math.min(540-o.h,oy+(v.clientY-sy)/z));el.style.left=o.x+'px';el.style.top=o.y+'px'};el.onpointerup=()=>{draw();cards()}}
function cards(){let ids=new Set([...document.querySelectorAll('.student-check:checked')].map(x=>x.value)),list=students.filter(s=>ids.has(String(s.id)));preview.innerHTML=list.map(s=>`<article class="student-card" style="position:relative;background:linear-gradient(180deg,var(--card-main) 0 11.8mm,#fff 11.8mm)">${Object.entries(d).map(([k,o])=>item(k,o,s,.1)).join('')}</article>`).join('');selectedCount.textContent=list.length;preview.querySelectorAll('.sc-qr').forEach((el,i)=>new QRCode(el.firstElementChild,{text:new URL(list[i]._verify_url,location.origin).href,width:96,height:96,correctLevel:QRCode.CorrectLevel.M}))}
[scAgency,scSchool,scTitle].forEach(x=>x.oninput=()=>{draw();cards()});scLogo.onchange=function(){let f=this.files&&this.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{logo=r.result;localStorage.setItem('cdsCardLogo',logo);draw();cards()};r.readAsDataURL(f)};scToggles.onchange=e=>{if(!e.target.matches('.sc-toggle'))return;d[e.target.dataset.k].v=e.target.checked;draw();cards()};[scFont,scColor,scWidth,scHeight,scAlign,scWeight].forEach(x=>x.oninput=()=>{if(!active)return;let o=d[active];o.f=+scFont.value;o.c=scColor.value;o.w=+scWidth.value;o.h=+scHeight.value;o.a=scAlign.value;o.b=+scWeight.value;draw();cards()});scSave.onclick=()=>{localStorage.setItem('cdsCardDesignerV1',JSON.stringify(d));localStorage.setItem('cdsCardTexts',JSON.stringify({agency:scAgency.value,school:scSchool.value,title:scTitle.value}));alert('Đã lưu bố cục trên trình duyệt này.')};scReset.onclick=()=>{if(!confirm('Khôi phục mẫu mặc định?'))return;d=JSON.parse(JSON.stringify(D));active='';draw();cards()};
const oldRender=window.render;window.render=function(){oldRender();setTimeout(cards,0)};document.addEventListener('change',e=>{if(e.target.matches('.student-check'))cards()});draw();cards();
})();
</script>
HTML;
    return preg_replace('/<\/body>/i', $addon . '</body>', $html, 1) ?? $html;
}
ob_start('student_card_designer_filter');
