<?php
/** Chọn, kéo, đổi kích thước và định dạng từng thành phần thẻ học sinh. */
if (defined('STUDENT_CARD_ELEMENT_EDITOR')) return;
define('STUDENT_CARD_ELEMENT_EDITOR', true);
function student_card_element_editor_filter(string $html): string {
    $path = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?: '';
    if (!preg_match('~/csdl_student_cards\.php$~', $path) || stripos($html, '</body>') === false) return $html;
    $addon = <<<'HTML'
<style id="sceStyle">
#scElementEditor .form-label{margin-bottom:.15rem}.sce-grid{display:grid;grid-template-columns:1fr 1fr;gap:.5rem}.sce-actions{display:grid;grid-template-columns:1fr 1fr;gap:.5rem}.sce-target{cursor:pointer}.sce-target:hover{outline:1px dashed #0d6efd;outline-offset:1px}.sce-selected{outline:2px solid #0d6efd!important;outline-offset:2px;cursor:move!important;resize:both!important;overflow:hidden!important}.sce-help{font-size:.78rem;color:#64748b}.sce-nowrap{white-space:nowrap!important}.sce-target.student-info.sce-nowrap>div{white-space:nowrap!important}@media(max-width:480px){.sce-grid{grid-template-columns:1fr}}@media print{#scElementEditor{display:none!important}.sce-target,.sce-selected{outline:0!important;resize:none!important;cursor:default!important}}
</style>
<script id="sceScript">
(function(){
const preview=document.getElementById('samplePreview'),column=document.querySelector('#designStep .col-xl-4');
if(!preview||!column||document.getElementById('scElementEditor'))return;
const ITEMS={logo:['Logo trường','front','.logo',0],agency:['Dòng Sở GD&ĐT','front','.agency',1],school:['Tên trường','front','.school-name',1],title:['Tiêu đề THẺ HỌC SINH','front','.title',1],photo:['Ảnh học sinh','front','.photo',0],name:['Tên học sinh','front','.student-name',1],info:['Lớp, năm học, niên khóa','front','.student-info',1],frontQr:['QR mặt trước','front','.front-qr',0],ruleTitle:['Tiêu đề quy định','back','.rule-title',1],rules:['Nội dung quy định','back','.rules',1],backQr:['QR mặt sau','back','.back-qr',0],backNote:['Ghi chú dưới QR','back','.back-note',1]};
const KEY='cdsStudentCardElementLayoutV4';let store={vertical:{},horizontal:{}},chosen='title',busy=false,drag=false,ro=null,suppressResizeUntil=0;
try{store=Object.assign(store,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
const panel=document.createElement('div');panel.id='scElementEditor';panel.className='panel p-3 mb-3 no-print';panel.innerHTML=`<h6 class="fw-bold mb-1"><i class="bi bi-bounding-box-circles"></i> Chỉnh từng thành phần</h6><div class="sce-help mb-2">Bấm vào thành phần trên thẻ mẫu. Kéo để di chuyển; kéo góc dưới bên phải để thay đổi kích thước.</div><label class="form-label small">Thành phần</label><select id="sceItem" class="form-select form-select-sm mb-2"></select><div id="sceMissing" class="alert alert-warning py-2 small d-none">Thành phần đang bị tắt trong tùy chọn hiển thị.</div><div class="sce-grid"><label class="small">X (mm)<input id="sceX" type="number" step="0.1" class="form-control form-control-sm"></label><label class="small">Y (mm)<input id="sceY" type="number" step="0.1" class="form-control form-control-sm"></label><label class="small">Rộng (mm)<input id="sceW" type="number" min="2" step="0.1" class="form-control form-control-sm"></label><label class="small">Cao (mm)<input id="sceH" type="number" min="2" step="0.1" class="form-control form-control-sm"></label></div><div id="sceText" class="mt-2"><div class="sce-grid"><label class="small">Cỡ chữ (pt)<input id="sceFont" type="number" min="4" max="40" step="0.2" class="form-control form-control-sm"></label><label class="small">Màu chữ<input id="sceColor" type="color" class="form-control form-control-color w-100"></label><label class="small">Độ đậm<select id="sceWeight" class="form-select form-select-sm"><option value="300">Mảnh</option><option value="400">Thường</option><option value="500">Vừa</option><option value="600">Đậm vừa</option><option value="700">Đậm</option><option value="800">Rất đậm</option><option value="900">Đậm nhất</option></select></label><label class="small">Căn chữ<select id="sceAlign" class="form-select form-select-sm"><option value="left">Trái</option><option value="center">Giữa</option><option value="right">Phải</option></select></label></div><div class="d-flex flex-wrap gap-3 mt-2"><label class="form-check"><input id="sceItalic" class="form-check-input" type="checkbox"><span class="form-check-label small">Chữ nghiêng</span></label><label class="form-check"><input id="sceNowrap" class="form-check-input" type="checkbox"><span class="form-check-label small">Không xuống dòng</span></label></div><div class="sce-help mt-1">Khi bật “Không xuống dòng”, hãy tăng ô Rộng hoặc kéo rộng khối để sử dụng phần trống còn lại.</div></div><div class="sce-actions mt-3"><button id="sceReset" type="button" class="btn btn-sm btn-outline-warning">Đặt lại khối</button><button id="sceSave" type="button" class="btn btn-sm btn-success">Lưu bố cục</button></div>`;
const ps=column.querySelectorAll('.panel');(ps[1]||ps[0]).insertAdjacentElement('afterend',panel);
const $=id=>document.getElementById(id),sel=$('sceItem');Object.entries(ITEMS).forEach(([k,v])=>sel.add(new Option(v[0],k)));sel.value=chosen;
function cardType(){const active=document.querySelector('.type-card.active');if(active&&active.dataset.type)return active.dataset.type;return preview.querySelector('.card-face.horizontal')?'horizontal':'vertical'}
function size(){return cardType()==='horizontal'?{w:90,h:60}:{w:54,h:86}}
function face(k,root=preview){return root.querySelector('.card-face.'+ITEMS[k][1])}
function target(k,root=preview){const f=face(k,root);return f?f.querySelector(ITEMS[k][2]):null}
function cfg(){return store[cardType()]||(store[cardType()]={})}
function persist(){localStorage.setItem(KEY,JSON.stringify(store))}
function rgb(v){const m=String(v).match(/\d+/g);return m&&m.length>2?'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join(''):'#10243a'}
function defaultNowrap(k){return ['title','name','info','agency','school','ruleTitle'].includes(k)}
function capture(k){const el=target(k),f=face(k);if(!el||!f)return null;const a=el.getBoundingClientRect(),b=f.getBoundingClientRect(),d=size(),cs=getComputedStyle(el),c={x:(a.left-b.left)/b.width*d.w,y:(a.top-b.top)/b.height*d.h,w:a.width/b.width*d.w,h:a.height/b.height*d.h};if(ITEMS[k][3])Object.assign(c,{font:parseFloat(cs.fontSize)*.75,color:rgb(cs.color),weight:parseInt(cs.fontWeight)||400,italic:cs.fontStyle==='italic',align:cs.textAlign||'center',nowrap:defaultNowrap(k)||cs.whiteSpace==='nowrap'});return c}
function get(k){return cfg()[k]||(cfg()[k]=capture(k)||{x:2,y:2,w:20,h:8,font:8,color:'#10243a',weight:400,italic:false,align:'center',nowrap:defaultNowrap(k)})}
function pct(mm,axis){const d=size();return mm/(axis==='x'?d.w:d.h)*100}
function style(el,k,c){if(!el||!c)return;el.dataset.sce=k;el.classList.add('sce-target');el.classList.toggle('sce-nowrap',!!c.nowrap);Object.assign(el.style,{position:'absolute',left:pct(c.x,'x')+'%',top:pct(c.y,'y')+'%',width:pct(c.w,'x')+'%',height:pct(c.h,'y')+'%',margin:'0',maxWidth:'none',boxSizing:'border-box',zIndex:'5'});if(ITEMS[k][3])Object.assign(el.style,{fontSize:c.font+'pt',color:c.color,fontWeight:String(c.weight),fontStyle:c.italic?'italic':'normal',textAlign:c.align,whiteSpace:c.nowrap?'nowrap':(k==='rules'?'pre-line':'normal'),overflow:c.nowrap?'visible':'hidden'})}
function applyRoot(root){const layouts=store[cardType()]||{};root.querySelectorAll('.card-face').forEach(f=>Object.entries(ITEMS).forEach(([k,v])=>{if(!f.classList.contains(v[1])||!layouts[k])return;style(f.querySelector(v[2]),k,layouts[k])}))}
function apply(){if(busy)return;busy=true;document.querySelectorAll('#samplePreview,.print-grid').forEach(applyRoot);bind();busy=false}
function bind(){preview.querySelectorAll('.sce-selected').forEach(x=>x.classList.remove('sce-selected'));preview.querySelectorAll('.sce-target').forEach(el=>{el.onpointerdown=begin;el.onclick=e=>{e.stopPropagation();select(el.dataset.sce)}});const el=target(chosen);if(el){el.classList.add('sce-selected');watch(el)}}
function fill(){const c=get(chosen);$('sceX').value=c.x.toFixed(1);$('sceY').value=c.y.toFixed(1);$('sceW').value=c.w.toFixed(1);$('sceH').value=c.h.toFixed(1);if(ITEMS[chosen][3]){$('sceFont').value=(c.font||8).toFixed(1);$('sceColor').value=c.color||'#10243a';$('sceWeight').value=String(c.weight||400);$('sceItalic').checked=!!c.italic;$('sceNowrap').checked=!!c.nowrap;$('sceAlign').value=c.align||'center'}}
function select(k){chosen=k;sel.value=k;const el=target(k);$('sceMissing').classList.toggle('d-none',!!el);$('sceText').classList.toggle('d-none',!ITEMS[k][3]);if(el){get(k);apply();fill()}}
function begin(e){if(e.button!==0)return;e.preventDefault();const el=e.currentTarget,k=el.dataset.sce;select(k);drag=true;const f=face(k),r=f.getBoundingClientRect(),d=size(),c=get(k),sx=e.clientX,sy=e.clientY,ox=c.x,oy=c.y;el.setPointerCapture(e.pointerId);el.onpointermove=v=>{c.x=Math.max(0,Math.min(d.w-c.w,ox+(v.clientX-sx)/r.width*d.w));c.y=Math.max(0,Math.min(d.h-c.h,oy+(v.clientY-sy)/r.height*d.h));style(el,k,c);fill()};el.onpointerup=()=>{drag=false;el.onpointermove=null;suppressResizeUntil=Date.now()+150;persist();apply()}}
function watch(el){if(ro)ro.disconnect();ro=new ResizeObserver(()=>{if(busy||drag||Date.now()<suppressResizeUntil)return;const f=face(chosen),r=f&&f.getBoundingClientRect(),a=el.getBoundingClientRect(),d=size(),c=get(chosen);if(!r||!r.width||!r.height)return;c.w=Math.max(2,a.width/r.width*d.w);c.h=Math.max(2,a.height/r.height*d.h);fill();persist()});ro.observe(el)}
function readControls(){const c=get(chosen),d=size();c.w=Math.max(2,Math.min(d.w,+$('sceW').value||2));c.h=Math.max(2,Math.min(d.h,+$('sceH').value||2));c.x=Math.max(0,Math.min(d.w-c.w,+$('sceX').value||0));c.y=Math.max(0,Math.min(d.h-c.h,+$('sceY').value||0));if(ITEMS[chosen][3]){c.font=Math.max(4,+$('sceFont').value||8);c.color=$('sceColor').value;c.weight=+$('sceWeight').value;c.italic=$('sceItalic').checked;c.nowrap=$('sceNowrap').checked;c.align=$('sceAlign').value}return c}
function updateDirect(){const c=readControls(),el=target(chosen);suppressResizeUntil=Date.now()+220;busy=true;if(el)style(el,chosen,c);document.querySelectorAll('.print-grid').forEach(root=>applyRoot(root));busy=false;persist()}
['sceX','sceY','sceW','sceH','sceFont','sceColor','sceWeight','sceItalic','sceNowrap','sceAlign'].forEach(id=>$(id)?.addEventListener('input',updateDirect));
['sceX','sceY','sceW','sceH','sceFont'].forEach(id=>$(id)?.addEventListener('change',()=>{updateDirect();fill()}));
sel.addEventListener('change',()=>select(sel.value));$('sceSave').onclick=()=>{updateDirect();persist();alert('Đã lưu bố cục mẫu '+(cardType()==='vertical'?'dọc':'ngang')+'.')};$('sceReset').onclick=()=>{delete cfg()[chosen];persist();const el=target(chosen);if(el){el.removeAttribute('style');el.classList.remove('sce-nowrap')}apply();select(chosen)};
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(()=>{apply();select(chosen)},100)}).observe(preview,{childList:true,subtree:true});document.querySelectorAll('.type-card').forEach(x=>x.addEventListener('click',()=>setTimeout(()=>{apply();select(chosen)},120)));apply();select(chosen);
})();
</script>
HTML;
    return preg_replace('/<\/body>/i', $addon . '</body>', $html, 1) ?? $html;
}
ob_start('student_card_element_editor_filter');
