<?php
require_once __DIR__ . '/csdl_store.php';

if (!defined('CDS_TIMETABLE_VERSIONS')) define('CDS_TIMETABLE_VERSIONS', DATA_PATH . '/timetable_versions.json');
if (!defined('CDS_TIMETABLE_MAPPINGS')) define('CDS_TIMETABLE_MAPPINGS', DATA_PATH . '/timetable_mappings.json');

function tt_rows(string $file): array { $rows=load_json($file,[]); return is_array($rows)?$rows:[]; }
function tt_save(string $file,array $rows): bool { return file_put_contents($file,json_encode($rows,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX)!==false; }
function tt_norm($value): string {$value=trim((string)$value);$value=preg_replace('/\s+/u',' ',$value)??$value;if(class_exists('Transliterator')){$tr=Transliterator::create('NFD; [:Nonspacing Mark:] Remove; NFC');if($tr)$value=$tr->transliterate($value);}return mb_strtolower($value,'UTF-8');}
function tt_versions(): array {$rows=tt_rows(CDS_TIMETABLE_VERSIONS);usort($rows,fn($a,$b)=>strcmp((string)($b['week_from']??''),(string)($a['week_from']??'')));return $rows;}
function tt_mappings(): array {return array_merge(['teacher'=>[],'class'=>[],'subject'=>[]],tt_rows(CDS_TIMETABLE_MAPPINGS));}
function tt_mapping_key(string $value): string {return hash('sha256',tt_norm($value));}
function tt_map_value(string $type,string $raw,array $mappings): array {$map=$mappings[$type][tt_mapping_key($raw)]??null;return is_array($map)?$map:[];}
function tt_active_version(?string $id=null): ?array {foreach(tt_versions() as $row)if(($id!==null&&($row['id']??'')===$id)||($id===null&&!empty($row['published'])))return $row;return null;}
function tt_catalogs(): array {
    $teachers=array_values(array_filter(csdl_teachers_all(),fn($r)=>!isset($r['active'])||!empty($r['active'])));
    $classes=array_values(array_filter(csdl_classes_all(),fn($r)=>!isset($r['active'])||!empty($r['active'])));
    $subjects=[];foreach($teachers as $teacher)foreach((array)($teacher['subjects']??$teacher['chuyen_mon']??[]) as $subject){$name=is_array($subject)?($subject['name']??''):$subject;if(trim((string)$name)!=='')$subjects[tt_norm($name)]=['id'=>tt_norm($name),'name'=>trim((string)$name)];}
    foreach(['Toán','Ngữ văn','Tiếng Anh','KHTN','Vật lí','Hóa học','Sinh học','Lịch sử','Địa lí','LS&ĐL','GDCD','GDKT&PL','GDQP&AN','GDTC','Tin học','Công nghệ','Nghệ thuật','Âm nhạc','HĐTN','GDĐP'] as $name)$subjects[tt_norm($name)]=['id'=>tt_norm($name),'name'=>$name];
    return ['teacher'=>$teachers,'class'=>$classes,'subject'=>array_values($subjects)];
}
function tt_auto_target(string $type,string $raw,array $catalogs): array {
    $norm=tt_norm($raw);$exact=[];foreach($catalogs[$type]??[] as $row){$name=(string)($row['name']??'');if(tt_norm($name)===$norm)$exact[]=$row;}
    if(count($exact)===1)return ['id'=>(string)($exact[0]['id']??''),'name'=>(string)$exact[0]['name']];
    return [];
}
function tt_dom($raw): ?DOMDocument {$dom=new DOMDocument();$old=libxml_use_internal_errors(true);$ok=$dom->loadXML((string)$raw,LIBXML_NONET|LIBXML_NOBLANKS);libxml_clear_errors();libxml_use_internal_errors($old);return $ok?$dom:null;}
function tt_cell_value(DOMElement $cell,DOMXPath $xp,array $shared): string {$type=$cell->getAttribute('t');$text='';foreach($xp->query('.//main:t',$cell)?:[] as $part)$text.=$part->textContent;if($type==='inlineStr'||$text!=='')return trim($text);$node=$xp->query('./main:v',$cell)->item(0);$raw=$node?$node->textContent:'';return trim($type==='s'?(string)($shared[(int)$raw]??''):$raw);}
function tt_parse_xlsx(string $path): array {
    if(!class_exists('ZipArchive')||!class_exists('DOMDocument'))return ['ok'=>false,'message'=>'Hosting cần bật PHP ZipArchive và DOM để đọc XLSX.'];$zip=new ZipArchive();if($zip->open($path)!==true)return ['ok'=>false,'message'=>'Không mở được file XLSX.'];
    $shared=[];$raw=$zip->getFromName('xl/sharedStrings.xml');if($raw!==false&&($dom=tt_dom($raw))){$xp=new DOMXPath($dom);$xp->registerNamespace('main','http://schemas.openxmlformats.org/spreadsheetml/2006/main');foreach($xp->query('//main:si') as $si){$s='';foreach($xp->query('.//main:t',$si) as $p)$s.=$p->textContent;$shared[]=$s;}}
    $wb=tt_dom($zip->getFromName('xl/workbook.xml'));$rels=tt_dom($zip->getFromName('xl/_rels/workbook.xml.rels'));if(!$wb||!$rels){$zip->close();return ['ok'=>false,'message'=>'File không đúng cấu trúc XLSX.'];}$rx=new DOMXPath($rels);$rx->registerNamespace('p','http://schemas.openxmlformats.org/package/2006/relationships');$targets=[];foreach($rx->query('//p:Relationship') as $rel)$targets[$rel->getAttribute('Id')]=$rel->getAttribute('Target');$wx=new DOMXPath($wb);$wx->registerNamespace('m','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$sheet=$wx->query('//m:sheet')->item(0);$rid=$sheet?$sheet->getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'):'';$target=ltrim(str_replace('\\','/',$targets[$rid]??''),'/');$sheetRaw=$zip->getFromName(str_starts_with($target,'xl/')?$target:'xl/'.$target);$zip->close();$dom=tt_dom($sheetRaw);if(!$dom)return ['ok'=>false,'message'=>'Không đọc được sheet đầu tiên.'];
    $xp=new DOMXPath($dom);$xp->registerNamespace('main','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$rows=[];foreach($xp->query('//main:sheetData/main:row') as $row){$values=[];foreach($xp->query('./main:c',$row) as $cell){if(!preg_match('/^([A-Z]+)/',$cell->getAttribute('r'),$m))continue;$col=0;foreach(str_split($m[1]) as $ch)$col=$col*26+ord($ch)-64;$values[$col]=tt_cell_value($cell,$xp,$shared);}$rows[(int)$row->getAttribute('r')]=$values;}
    $headerRow=0;$dayCols=[];foreach($rows as $rn=>$values){if(tt_norm($values[1]??'')==='lop'||tt_norm($values[1]??'')==='lớp'){$headerRow=$rn;foreach($values as $col=>$value)if(preg_match('/^thứ\s*([2-7])$/ui',trim($value),$m))$dayCols[(int)$m[1]]=$col;break;}}if(!$headerRow||!$dayCols)return ['ok'=>false,'message'=>'Không tìm thấy hàng tiêu đề Lớp – Buổi – Tiết và Thứ 2…Thứ 7.'];
    $entries=[];$rawValues=['teacher'=>[],'class'=>[],'subject'=>[]];foreach($rows as $rn=>$v){if($rn<=$headerRow)continue;$class=trim((string)($v[1]??''));$session=trim((string)($v[2]??''));$period=(int)($v[3]??0);if($class===''||$period<1)continue;foreach($dayCols as $day=>$col){$subject=trim((string)($v[$col]??''));$teacher=trim((string)($v[$col+1]??''));if($subject===''&&$teacher==='')continue;$entries[]=['day'=>$day,'session'=>$session,'period'=>$period,'class_raw'=>$class,'subject_raw'=>$subject,'teacher_raw'=>$teacher];$rawValues['class'][$class]=true;if($subject!=='')$rawValues['subject'][$subject]=true;if($teacher!=='')$rawValues['teacher'][$teacher]=true;}}
    return ['ok'=>true,'entries'=>$entries,'raw_values'=>array_map('array_keys',$rawValues),'message'=>'Đã đọc '.count($entries).' tiết học.'];
}
function tt_resolve_version(array $version): array {$maps=tt_mappings();$catalogs=tt_catalogs();$entries=[];$unmatched=['teacher'=>[],'class'=>[],'subject'=>[]];foreach((array)($version['entries']??[]) as $entry){foreach(['teacher','class','subject'] as $type){$raw=(string)($entry[$type.'_raw']??'');if($raw==='')continue;$target=tt_map_value($type,$raw,$maps)?:tt_auto_target($type,$raw,$catalogs);$entry[$type.'_id']=$target['id']??'';$entry[$type.'_name']=$target['name']??$raw;if(!$target)$unmatched[$type][$raw]=true;}$entries[]=$entry;}return ['entries'=>$entries,'unmatched'=>array_map('array_keys',$unmatched)];}
function tt_teacher_for_user(array $user): ?array {$ids=array_filter(array_map('tt_norm',[$user['teacher_name']??'',$user['name']??'',$user['username']??'']));foreach(csdl_teachers_all() as $teacher)if(in_array(tt_norm($teacher['name']??''),$ids,true)||in_array(tt_norm($teacher['id']??''),$ids,true))return $teacher;return null;}
function tt_dashboard_notices(): array {$now=time();$rows=[];foreach(tt_versions() as $v){if(empty($v['published'])||empty($v['dashboard_visible']))continue;$from=strtotime((string)($v['dashboard_from']??''));$to=strtotime((string)($v['dashboard_to']??''));if(!$from||!$to||$now<$from||$now>$to)continue;$rows[]=['id'=>'timetable-'.($v['id']??''),'kind'=>'notice','title'=>'Thời khóa biểu '.($v['name']??''),'url'=>BASE_URL.'thoikhoabieu.php?version='.rawurlencode((string)($v['id']??'')),'_dashboard_detail'=>'Đã công bố thời khóa biểu mới · '.($v['week_from']??'').'–'.($v['week_to']??''),'_dashboard_start'=>date('Y-m-d H:i',$from),'_dashboard_end'=>date('Y-m-d H:i',$to),'_dashboard_nearest'=>date('Y-m-d H:i',$to),'_dashboard_state'=>($now-$from<=2*86400?'Mới':'Đang hiệu lực'),'_dashboard_badge_class'=>($now-$from<=2*86400?'new':'active'),'_dashboard_assignees'=>[]];}return $rows;}
