<?php
/** Bộ xếp TKB độc lập: chỉ đọc PCCM, chỉ ghi kho nháp riêng cho tới khi công bố. */
if(!function_exists('tkb_weeks'))require_once dirname(__DIR__).'/chuyenmon/includes/timetable_store.php';
if(!defined('CDS_TTB_FILE'))define('CDS_TTB_FILE',DATA_PATH.'/timetable_builder.json');

function ttb_default():array{return ['enabled'=>true,'settings'=>['days'=>[2,3,4,5,6,7],'morning_periods'=>5,'afternoon_periods'=>5,'attempts'=>40,'run_seconds'=>8,'max_teacher_daily'=>7,'max_teacher_gaps'=>2,'max_teacher_days'=>6,'max_teacher_consecutive'=>5,'max_class_daily'=>10,'max_subject_class_daily'=>2,'avoid_edges'=>true,'optimize_teacher_days'=>true,'spread_same_subject'=>true],'blocked'=>[],'groups'=>[],'plans'=>[],'active_plan'=>'','updated_at'=>''];}
function ttb_data():array{$base=ttb_default();$raw=load_json(CDS_TTB_FILE,[]);if(!is_array($raw))return$base;$data=array_merge($base,$raw);$data['settings']=array_merge($base['settings'],is_array($raw['settings']??null)?$raw['settings']:[]);foreach(['blocked','groups','plans']as$key)if(!is_array($data[$key]??null))$data[$key]=[];return$data;}
function ttb_save(array$data):bool{$data['updated_at']=date('c');return save_json(CDS_TTB_FILE,$data);}
function ttb_pccm_dir():string{if(defined('PCCM_DATA_PATH')&&PCCM_DATA_PATH!=='')return rtrim(PCCM_DATA_PATH,'/\\');if(defined('TKB_WEEKS_FILE'))return rtrim(DATA_PATH,'/\\');return BASE_PATH.'/chuyenmon/data';}
function ttb_assignments():array{$dir=ttb_pccm_dir();$active=load_json($dir.'/active_version.json',[]);$vid=trim((string)($active['id']??''));if($vid===''){foreach((array)load_json($dir.'/versions.json',[])as$v)if(!empty($v['id'])){$vid=(string)$v['id'];break;}}$rows=$vid!==''?load_json($dir.'/assignments_'.$vid.'.json',[]):load_json($dir.'/assignments.json',[]);$manual=load_json($dir.'/manual_assignments.json',[]);foreach(is_array($manual)?$manual:[]as$r){$rv=trim((string)($r['version_id']??''));if($rv!==''&&$rv!==$vid)continue;$r['class']=$r['class']??$r['class_name']??'';$r['is_manual']=true;$rows[]=$r;}$out=[];foreach(is_array($rows)?$rows:[]as$r){$teacher=trim((string)($r['teacher']??''));$subject=trim((string)($r['subject']??''));$class=trim((string)($r['class']??$r['class_name']??''));$periods=(float)($r['periods']??0);if($teacher===''||$subject===''||$class===''||$periods<=0)continue;$id=trim((string)($r['id']??''))?:hash('sha256',$teacher.'|'.$subject.'|'.$class);$out[]=['id'=>$id,'teacher'=>$teacher,'subject'=>$subject,'class'=>$class,'periods'=>$periods,'note'=>(string)($r['note']??'')];}usort($out,fn($a,$b)=>strnatcasecmp($a['class'].'|'.$a['subject'],$b['class'].'|'.$b['subject']));return$out;}
function ttb_slot_key(int$day,string$session,int$period):string{return$day.'|'.$session.'|'.$period;}
function ttb_slots(array$settings):array{$out=[];foreach((array)($settings['days']??[2,3,4,5,6,7])as$day){foreach(['Sáng'=>(int)($settings['morning_periods']??5),'Chiều'=>(int)($settings['afternoon_periods']??5)]as$session=>$max)for($p=1;$p<=$max;$p++)$out[]=['day'=>(int)$day,'session'=>$session,'period'=>$p,'key'=>ttb_slot_key((int)$day,$session,$p)];}return$out;}
function ttb_group_map(array$groups):array{$map=[];foreach($groups as$g)foreach((array)($g['assignment_ids']??[])as$id)$map[(string)$id]=(string)($g['id']??'');return$map;}
function ttb_activities(array$assignments,array$groups):array{$byId=[];foreach($assignments as$a)$byId[$a['id']]=$a;$consumed=[];$out=[];
 foreach($groups as$g){$members=[];foreach((array)($g['assignment_ids']??[])as$id)if(isset($byId[$id]))$members[]=$byId[$id];if(count($members)<2)continue;$available=min(array_map(fn($m)=>max(0,(int)round($m['periods'])-(int)($consumed[$m['id']]??0)),$members));$count=min(max(1,(int)($g['periods']??1)),$available);if($count<1)continue;foreach($members as$m)$consumed[$m['id']]=(int)($consumed[$m['id']]??0)+$count;for($n=1;$n<=$count;$n++)$out[]=['id'=>(string)$g['id'].'_'.$n,'group_id'=>(string)$g['id'],'teacher'=>(string)($g['teacher']??$members[0]['teacher']),'subject'=>(string)($g['subject']??$members[0]['subject']),'classes'=>array_values(array_unique(array_column($members,'class'))),'fixed_day'=>(int)($g['day']??0),'fixed_session'=>(string)($g['session']??''),'fixed_period'=>(int)($g['period']??0),'credit_mode'=>(string)($g['credit_mode']??'per_class')];}
 foreach($assignments as$a){$remaining=max(0,(int)round($a['periods'])-(int)($consumed[$a['id']]??0));for($n=1;$n<=$remaining;$n++)$out[]=['id'=>$a['id'].'_'.$n,'assignment_id'=>$a['id'],'teacher'=>$a['teacher'],'subject'=>$a['subject'],'classes'=>[$a['class']],'fixed_day'=>0,'fixed_session'=>'','fixed_period'=>0,'credit_mode'=>'per_class'];}
 return$out;}
function ttb_blocked(array$data,string$teacher,string$key):bool{return!empty($data['blocked'][hash('sha256',$teacher.'|'.$key)]);}
function ttb_candidate_score(array$a,array$s,array$placed,array$settings):int{$score=random_int(0,9);$teacher=$a['teacher'];$day=$s['day'];$sameTeacherDay=[];$teacherDays=[];$sameSubjectDay=0;$classDay=0;foreach($placed as$p){if($p['teacher']===$teacher){$teacherDays[$p['day']]=true;if($p['day']===$day)$sameTeacherDay[]=$p;}if($p['day']===$day&&array_intersect($p['classes'],$a['classes'])){$classDay++;if($p['subject']===$a['subject'])$sameSubjectDay++;}}$score+=max(0,$sameSubjectDay+1-(int)($settings['max_subject_class_daily']??2))*180;if(!empty($settings['spread_same_subject']))$score+=$sameSubjectDay*25;$score+=max(0,$classDay+1-(int)($settings['max_class_daily']??10))*500;$score+=max(0,count($sameTeacherDay)+1-(int)($settings['max_teacher_daily']??7))*500;if(!isset($teacherDays[$day])&&count($teacherDays)>=(int)($settings['max_teacher_days']??6))$score+=600;if(!empty($settings['optimize_teacher_days'])&&!isset($teacherDays[$day])&&$teacherDays)$score+=10;if(!empty($settings['avoid_edges'])&&($s['period']===1||$s['period']===(($s['session']==='Sáng')?(int)$settings['morning_periods']:(int)$settings['afternoon_periods'])))$score+=8;if($sameTeacherDay){$periods=array_column(array_filter($sameTeacherDay,fn($p)=>$p['session']===$s['session']),'period');if($periods){$periods[]=$s['period'];sort($periods);$near=min(array_map(fn($p)=>abs($p-$s['period']),array_filter($periods,fn($p)=>$p!==$s['period']))?:[1]);$score+=max(0,$near-1)*12;$run=1;$best=1;for($i=1;$i<count($periods);$i++){$run=$periods[$i]===$periods[$i-1]+1?$run+1:1;$best=max($best,$run);}$score+=max(0,$best-(int)($settings['max_teacher_consecutive']??5))*250;}}return$score;}
function ttb_global_penalty(array$entries,array$settings):int{$byTeacher=[];foreach($entries as$e)$byTeacher[(string)$e['teacher']][(int)$e['day']][(string)$e['session']][]=(int)$e['period'];$penalty=0;$gapLimit=max(0,(int)($settings['max_teacher_gaps']??2));foreach($byTeacher as$days)foreach($days as$sessions)foreach($sessions as$periods){$periods=array_values(array_unique($periods));sort($periods);if(count($periods)>1){$gaps=max($periods)-min($periods)+1-count($periods);$penalty+=max(0,$gaps-$gapLimit)*35;}}return$penalty;}
function ttb_validate_entries(array$entries,array$activities):array{$errors=[];$classBusy=[];$teacherBusy=[];$activityMap=[];foreach($activities as$a)$activityMap[$a['id']]=$a;foreach($entries as$e){$key=ttb_slot_key((int)$e['day'],(string)$e['session'],(int)$e['period']);$aid=(string)$e['activity_id'];foreach((array)$e['classes']as$c){$ck=$c.'|'.$key;if(isset($classBusy[$ck])&&$classBusy[$ck]!==$aid)$errors[]='Trùng lớp '.$c.' tại '.$key;$classBusy[$ck]=$aid;}$tk=$e['teacher'].'|'.$key;if(isset($teacherBusy[$tk])&&$teacherBusy[$tk]!==$aid)$errors[]='Trùng giáo viên '.$e['teacher'].' tại '.$key;$teacherBusy[$tk]=$aid;}return array_values(array_unique($errors));}
function ttb_plan_diagnostics(array$data,array$assignments,array$plan):array{$activities=ttb_activities($assignments,(array)$data['groups']);$entries=(array)($plan['entries']??[]);$unplaced=(array)($plan['unplaced']??[]);$slots=ttb_slots($data['settings']);$classes=array_values(array_unique(array_column($assignments,'class')));$placedByClass=array_fill_keys($classes,0);$placedIds=[];$teacherBusy=[];$classBusy=[];foreach($entries as$e){$placedIds[(string)$e['activity_id']]=true;$key=ttb_slot_key((int)$e['day'],(string)$e['session'],(int)$e['period']);$teacherBusy[(string)$e['teacher'].'|'.$key]=true;foreach((array)$e['classes']as$c){$placedByClass[$c]=(int)($placedByClass[$c]??0)+1;$classBusy[$c.'|'.$key]=true;}}$missingByClass=[];$missingBySubject=[];$missingByTeacher=[];$bottlenecks=[];foreach($unplaced as$a){foreach((array)$a['classes']as$c)$missingByClass[$c]=(int)($missingByClass[$c]??0)+1;$missingBySubject[$a['subject']]=(int)($missingBySubject[$a['subject']]??0)+1;$missingByTeacher[$a['teacher']]=(int)($missingByTeacher[$a['teacher']]??0)+1;$base=0;$teacherFree=0;$classFree=0;foreach($slots as$s){if(!empty($a['fixed_day'])&&($s['day']!==$a['fixed_day']||(!empty($a['fixed_session'])&&$s['session']!==$a['fixed_session'])||(!empty($a['fixed_period'])&&$s['period']!==$a['fixed_period'])))continue;if(ttb_blocked($data,$a['teacher'],$s['key']))continue;$base++;if(empty($teacherBusy[$a['teacher'].'|'.$s['key']]))$teacherFree++;$ok=true;foreach((array)$a['classes']as$c)if(!empty($classBusy[$c.'|'.$s['key']])){$ok=false;break;}if($ok)$classFree++;}$reason=$base===0?'Bị khóa toàn bộ khung giờ':($teacherFree===0?'Giáo viên kín lịch':($classFree===0?'Lớp kín lịch':'Xung đột đồng thời giáo viên và lớp'));$bottlenecks[$reason]=(int)($bottlenecks[$reason]??0)+1;}$free=0;foreach($classes as$c)$free+=max(0,count($slots)-(int)($placedByClass[$c]??0));return['total'=>count($activities),'placed'=>count($entries),'unplaced'=>count($unplaced),'slot_capacity'=>count($slots)*count($classes),'free_class_slots'=>$free,'empty_classes'=>array_keys(array_filter($placedByClass,fn($n)=>$n===0)),'missing_class'=>$missingByClass,'missing_subject'=>$missingBySubject,'missing_teacher'=>$missingByTeacher,'bottlenecks'=>$bottlenecks];}
function ttb_generate(array$data,array$assignments,array$locked=[]):array{$settings=$data['settings'];$activities=ttb_activities($assignments,(array)$data['groups']);$slots=ttb_slots($settings);$best=null;$deadline=microtime(true)+max(3,min(30,(int)($settings['run_seconds']??8)));$attempts=max(1,min(100,(int)($settings['attempts']??40)));
 for($attempt=0;$attempt<$attempts&&microtime(true)<$deadline;$attempt++){$placed=[];$classBusy=[];$teacherBusy=[];$lockedIds=[];foreach($locked as$e)if(!empty($e['locked'])){$placed[]=$e;$lockedIds[$e['activity_id']]=true;$key=ttb_slot_key($e['day'],$e['session'],$e['period']);foreach($e['classes']as$c)$classBusy[$c.'|'.$key]=true;$teacherBusy[$e['teacher'].'|'.$key]=true;}$todo=array_values(array_filter($activities,fn($a)=>empty($lockedIds[$a['id']])));shuffle($todo);usort($todo,function($a,$b){$fa=($a['fixed_day']?1000:0)+count($a['classes'])*100;$fb=($b['fixed_day']?1000:0)+count($b['classes'])*100;return$fb<=>$fa;});$unplaced=[];$score=0;
  foreach($todo as$a){$candidates=[];foreach($slots as$s){if($a['fixed_day']&&($s['day']!==$a['fixed_day']||($a['fixed_session']!==''&&$s['session']!==$a['fixed_session'])||($a['fixed_period']&&$s['period']!==$a['fixed_period'])))continue;if(ttb_blocked($data,$a['teacher'],$s['key']))continue;if(isset($teacherBusy[$a['teacher'].'|'.$s['key']]))continue;$bad=false;foreach($a['classes']as$c)if(isset($classBusy[$c.'|'.$s['key']])){$bad=true;break;}if($bad)continue;$candidates[]=['slot'=>$s,'score'=>ttb_candidate_score($a,$s,$placed,$settings)];}if(!$candidates){$unplaced[]=$a;continue;}usort($candidates,fn($x,$y)=>$x['score']<=>$y['score']);$pick=$candidates[0];$s=$pick['slot'];$entry=array_merge($a,['activity_id'=>$a['id'],'day'=>$s['day'],'session'=>$s['session'],'period'=>$s['period'],'locked'=>false]);$placed[]=$entry;$score+=$pick['score'];$teacherBusy[$a['teacher'].'|'.$s['key']]=true;foreach($a['classes']as$c)$classBusy[$c.'|'.$s['key']]=true;}
  $score+=ttb_global_penalty($placed,$settings)+count($unplaced)*100000;$candidate=['entries'=>$placed,'unplaced'=>$unplaced,'score'=>$score,'errors'=>ttb_validate_entries($placed,$activities)];if($best===null||$candidate['score']<$best['score'])$best=$candidate;if(!$unplaced&&$score<20)break;}
 $best=$best??['entries'=>[],'unplaced'=>$activities,'score'=>PHP_INT_MAX,'errors'=>[]];$best['id']='plan_'.date('YmdHis').'_'.bin2hex(random_bytes(2));$best['name']='Phương án '.date('d/m/Y H:i');$best['created_at']=date('c');return$best;}
function ttb_plan(array$data,string$id):?array{foreach((array)$data['plans']as$p)if(($p['id']??'')===$id)return$p;return null;}
function ttb_replace_plan(array&$data,array$plan):void{$found=false;foreach($data['plans']as&$p)if(($p['id']??'')===($plan['id']??'')){$p=$plan;$found=true;break;}unset($p);if(!$found)$data['plans'][]=$plan;$data['active_plan']=$plan['id'];$data['plans']=array_slice($data['plans'],-12);}
function ttb_publish(array$plan,string$name,string$from,string$to,array$user,bool$overwrite=false,string$weekKey=''):array{if(!empty($plan['unplaced'])||!empty($plan['errors']))return['ok'=>false,'message'=>'Phương án còn tiết chưa xếp hoặc xung đột.'];$slots=[];$teacherMap=[];$classMap=[];foreach($plan['entries']as$e)foreach($e['classes']as$class){$teacher=(string)$e['teacher'];$slots[]=['day'=>(int)$e['day'],'session'=>(string)$e['session'],'period'=>(int)$e['period'],'class_raw'=>$class,'subject'=>(string)$e['subject'],'teacher_raw'=>$teacher,'group_session_id'=>(string)($e['group_id']??''),'teacher_credit'=>($e['credit_mode']??'per_class')==='per_class'?1:1/max(1,count($e['classes']))];$teacherMap[$teacher]=$teacher;$classMap[$class]=$class;}$weeks=tkb_weeks();$existing=[];foreach($weeks as$i=>$w)if((($w['start_date']??'')===$from&&($w['end_date']??'')===$to)||($weekKey!==''&&($w['school_week_key']??'')===$weekKey))$existing[]=$i;if($existing&&!$overwrite)return['ok'=>false,'message'=>'Tuần đã có thời khóa biểu. Hãy xác nhận ghi đè để tiếp tục.','needs_overwrite'=>true];foreach($weeks as&$w)$w['active']=false;unset($w);if($existing&&$overwrite)foreach($existing as$i){$weeks[$i]['replaced_at']=date('c');$weeks[$i]['replaced_by_plan']=(string)$plan['id'];}$week=['id'=>'tkb_'.date('YmdHis').'_'.bin2hex(random_bytes(2)),'label'=>$name,'school_week_key'=>$weekKey,'start_date'=>$from,'end_date'=>$to,'active'=>true,'uploaded_at'=>date('c'),'uploaded_by'=>$user['name']??'','source'=>'builder','builder_plan_id'=>$plan['id'],'slots'=>$slots];$weeks[]=$week;if(!tkb_save(TKB_WEEKS_FILE,$weeks))return['ok'=>false,'message'=>'Không lưu được tuần TKB mới.'];tkb_save_mapping($teacherMap,$classMap);return['ok'=>true,'version'=>$week,'message'=>'Đã công bố '.$name.' vào tuần đã chọn.'.($existing?' Bản cũ được giữ trong lịch sử.':'')];}
