<?php
$kind = $tab === 'surveys' ? 'survey' : 'poll';
$items = $kind === 'survey' ? $surveys : $polls;
if ($tab === 'polls' || $tab === 'surveys'):
?>
<div class="section-head"><div><span class="pill"><?=count(array_filter($items,fn($r)=>($r['status']??'active')==='active'))?> đang mở</span> <span class="pill"><?=count($items)?> tổng cộng</span></div><?php if($canEngagementManage):?><button class="btn btn-primary" onclick="document.getElementById('engagementDialog').showModal()"><i class="bi bi-plus-lg"></i> Tạo <?=$kind==='poll'?'bình chọn':'khảo sát'?></button><?php endif;?></div>
<div class="engage-grid">
<?php if(!$items):?><div class="card empty span-all"><i class="bi bi-ui-checks-grid"></i>Chưa có nội dung nào.</div><?php else:foreach($items as $item):
  $responses=(array)($item['responses']??[]);$joined=isset($responses[$userKey]);$closed=($item['status']??'active')!=='active'||(!empty($item['ends_at'])&&$item['ends_at']<date('Y-m-d'));$total=count($responses);
?>
<article class="card engage-card"><div class="engage-head"><div><span class="pill <?=$closed?'danger':'success'?>"><?=$closed?'Đã đóng':'Đang mở'?></span><span class="sub"><i class="bi bi-people"></i> <?=$total?> lượt</span></div><?php if($canEngagementManage):?><div class="row-actions"><form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="engagement_status"><input type="hidden" name="return_tab" value="<?=e($tab)?>"><input type="hidden" name="kind" value="<?=e($kind)?>"><input type="hidden" name="id" value="<?=e($item['id'])?>"><button class="btn btn-outline"><i class="bi bi-<?=$closed?'unlock':'lock'?>"></i></button></form><form method="post" onsubmit="return confirm('Xóa nội dung và toàn bộ kết quả?')"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="engagement_delete"><input type="hidden" name="return_tab" value="<?=e($tab)?>"><input type="hidden" name="kind" value="<?=e($kind)?>"><input type="hidden" name="id" value="<?=e($item['id'])?>"><button class="btn btn-danger"><i class="bi bi-trash"></i></button></form></div><?php endif;?></div>
<h2><?=e($item['title']??'')?></h2><p class="engage-description"><?=nl2br(e($item['description']??''))?></p><?php if(!empty($item['ends_at'])):?><div class="sub mb"><i class="bi bi-calendar-event"></i> Hạn: <?=vb_fmt_date($item['ends_at'])?></div><?php endif;?>
<?php if($kind==='poll'):$counts=vb_poll_counts($item);if($joined||$closed||$canEngagementManage):?>
<div class="result-list"><?php foreach((array)($item['options']??[]) as $i=>$option):$percent=$total?round(($counts[$i]??0)*100/$total):0;?><div class="result-row"><div><span><?=e($option)?></span><strong><?=$counts[$i]??0?> · <?=$percent?>%</strong></div><div class="result-bar"><span style="width:<?=$percent?>%"></span></div></div><?php endforeach;?></div>
<?php else:?><form method="post" class="choice-list"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="engagement_submit"><input type="hidden" name="return_tab" value="polls"><input type="hidden" name="kind" value="poll"><input type="hidden" name="id" value="<?=e($item['id'])?>"><?php foreach((array)($item['options']??[]) as $i=>$option):?><label class="choice"><input type="radio" name="answer" value="<?=$i?>" required><span><?=e($option)?></span></label><?php endforeach;?><button class="btn btn-primary"><i class="bi bi-send-check"></i> Gửi bình chọn</button></form><?php endif;?>
<?php else:if($joined||$closed||$canEngagementManage):?>
<div class="survey-results"><?php foreach((array)($item['questions']??[]) as $q=>$question):$counts=vb_survey_counts($item,$q);?><div class="survey-result"><strong><?=($q+1)?>. <?=e($question['question'])?></strong><?php foreach((array)$question['options'] as $i=>$option):$percent=$total?round(($counts[$i]??0)*100/$total):0;?><div class="result-row"><div><span><?=e($option)?></span><strong><?=$counts[$i]??0?> · <?=$percent?>%</strong></div><div class="result-bar"><span style="width:<?=$percent?>%"></span></div></div><?php endforeach;?></div><?php endforeach;?></div>
<?php else:?><form method="post" class="survey-form"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="engagement_submit"><input type="hidden" name="return_tab" value="surveys"><input type="hidden" name="kind" value="survey"><input type="hidden" name="id" value="<?=e($item['id'])?>"><?php foreach((array)($item['questions']??[]) as $q=>$question):?><fieldset><legend><?=($q+1)?>. <?=e($question['question'])?></legend><?php foreach((array)$question['options'] as $i=>$option):?><label class="choice"><input type="radio" name="answer[<?=$q?>]" value="<?=$i?>" required><span><?=e($option)?></span></label><?php endforeach;?></fieldset><?php endforeach;?><button class="btn btn-primary"><i class="bi bi-send-check"></i> Gửi khảo sát</button></form><?php endif;endif;?>
<?php if($joined):?><div class="joined-note"><i class="bi bi-check-circle-fill"></i> Bạn đã tham gia</div><?php endif;?></article>
<?php endforeach;endif;?></div>
<?php if($canEngagementManage):?><dialog class="modal" id="engagementDialog"><div class="modal-head"><strong><i class="bi bi-ui-checks-grid"></i> Tạo <?=$kind==='poll'?'bình chọn':'khảo sát'?></strong><button class="icon-btn" onclick="this.closest('dialog').close()">×</button></div><form method="post" class="modal-body"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="engagement_create"><input type="hidden" name="return_tab" value="<?=e($tab)?>"><input type="hidden" name="kind" value="<?=e($kind)?>"><div class="form-grid"><div class="field span-2"><label>Tiêu đề *</label><input class="input" name="title" required></div><div class="field"><label>Ngày kết thúc</label><input class="input" type="date" name="ends_at"></div><div class="field span-3"><label>Mô tả/hướng dẫn</label><textarea name="description"></textarea></div><?php if($kind==='poll'):?><div class="field span-3"><label>Các phương án * (mỗi dòng một phương án)</label><textarea name="options" required placeholder="Đồng ý&#10;Không đồng ý&#10;Ý kiến khác"></textarea></div><?php else:?><div class="field span-3"><label>Câu hỏi * (mỗi dòng: Câu hỏi | Lựa chọn 1 | Lựa chọn 2)</label><textarea name="questions" rows="7" required placeholder="Mức độ hài lòng? | Rất hài lòng | Hài lòng | Chưa hài lòng&#10;Nội dung có thiết thực? | Có | Không"></textarea></div><?php endif;?><button class="btn btn-primary span-3"><i class="bi bi-save"></i> Tạo và mở tham gia</button></div></form></dialog><?php endif;?>
<?php else:
  $visibleTickets=$canEngagementManage?$tickets:array_values(array_filter($tickets,fn($row)=>($row['owner_id']??'')===$userKey));
?>
<div class="section-head"><div><span class="pill"><?=count(array_filter($visibleTickets,fn($r)=>($r['status']??'')!=='completed'))?> đang xử lý</span> <span class="pill success"><?=count(array_filter($visibleTickets,fn($r)=>($r['status']??'')==='completed'))?> hoàn thành</span></div><button class="btn btn-primary" onclick="document.getElementById('feedbackDialog').showModal()"><i class="bi bi-plus-lg"></i> Gửi góp ý</button></div>
<div class="ticket-list"><?php if(!$visibleTickets):?><div class="card empty"><i class="bi bi-chat-square-text"></i>Chưa có góp ý nào.</div><?php else:foreach($visibleTickets as $ticket):$status=$ticket['status']??'new';$statusLabel=['new'=>'Mới','processing'=>'Đang xử lý','completed'=>'Hoàn thành'][$status]??$status;?><details class="card ticket-card"><summary><div><span class="ticket-code"><?=e($ticket['code']??'')?></span><strong><?=e($ticket['subject']??'')?></strong><div class="sub"><?=e($ticket['owner_name']??'')?> · <?=vb_fmt_date(substr((string)($ticket['created_at']??''),0,10))?> · <?=e($ticket['category']??'')?></div></div><span class="pill <?=$status==='completed'?'success':($status==='processing'?'warning':'')?>"><?=e($statusLabel)?></span></summary><div class="ticket-body"><div class="message sender"><strong><?=e($ticket['owner_name']??'Người gửi')?></strong><p><?=nl2br(e($ticket['content']??''))?></p></div><?php foreach((array)($ticket['messages']??[]) as $message):?><div class="message <?=($message['role']??'')==='handler'?'handler':'sender'?>"><strong><?=e($message['by_name']??'')?> <small><?=($message['role']??'')==='handler'?'· Phụ trách':''?></small></strong><p><?=nl2br(e($message['content']??''))?></p><time><?=e(date('d/m/Y H:i',strtotime($message['at']??'now')))?></time></div><?php endforeach;?><form method="post" class="reply-form"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="feedback_reply"><input type="hidden" name="return_tab" value="feedback"><input type="hidden" name="id" value="<?=e($ticket['id'])?>"><textarea name="message" placeholder="Nhập nội dung phản hồi..."></textarea><?php if($canEngagementManage):?><select name="status"><option value="new" <?=$status==='new'?'selected':''?>>Mới</option><option value="processing" <?=$status==='processing'?'selected':''?>>Đang xử lý</option><option value="completed" <?=$status==='completed'?'selected':''?>>Hoàn thành</option></select><?php endif;?><button class="btn btn-primary"><i class="bi bi-reply"></i> Phản hồi</button></form></div></details><?php endforeach;endif;?></div>
<dialog class="modal" id="feedbackDialog"><div class="modal-head"><strong><i class="bi bi-chat-square-heart"></i> Gửi góp ý</strong><button class="icon-btn" onclick="this.closest('dialog').close()">×</button></div><form method="post" class="modal-body"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="feedback_create"><input type="hidden" name="return_tab" value="feedback"><div class="form-grid"><div class="field span-2"><label>Tiêu đề *</label><input class="input" name="subject" required></div><div class="field"><label>Mức độ</label><select name="priority"><option>Bình thường</option><option>Quan trọng</option><option>Khẩn</option></select></div><div class="field span-3"><label>Nhóm góp ý</label><select name="category"><option>Góp ý chung</option><option>Chuyên môn</option><option>Nội trú</option><option>Cơ sở vật chất</option><option>Công nghệ/CSDL</option><option>Khác</option></select></div><div class="field span-3"><label>Nội dung *</label><textarea name="content" rows="6" required placeholder="Mô tả rõ nội dung cần góp ý hoặc hỗ trợ..."></textarea></div><button class="btn btn-primary span-3"><i class="bi bi-send"></i> Gửi góp ý</button></div></form></dialog>
<?php endif; ?>
