<?php require_once __DIR__ . '/vanban_views.php'; $shown = $tab === 'overview' ? array_slice($filteredDocuments, 0, 8) : $filteredDocuments; ?>
<div class="table-wrap desktop-table">
  <table class="table document-table <?= $tab === 'overview' ? 'overview-table' : 'manage-table' ?>">
    <thead><tr><th>Số, ký hiệu</th><th>Tên văn bản</th><th>Loại</th><th>Ngày ban hành</th><th>Đơn vị</th><?php if($tab==='documents'&&$canManage):?><th>Đã xem</th><th class="action-column">Thao tác</th><?php endif;?></tr></thead>
    <tbody>
    <?php if (!$shown): ?><tr><td colspan="<?= $tab==='documents'&&$canManage?7:5 ?>"><div class="empty"><i class="bi bi-inbox"></i>Chưa có văn bản phù hợp.</div></td></tr>
    <?php else: foreach ($shown as $row): $attachments=vb_document_attachments($row);$docId=(string)($row['id']??'');$openUrl=BASE_URL.'vanban_open.php?id='.rawurlencode($docId);$viewers=($tab==='documents'&&$canManage)?vb_document_views($docId):[];$mainPreviewable=(bool)preg_match('/\.(pdf|png|jpe?g)$/i',(string)($attachments[0]['name']??'')); ?>
      <tr>
        <td><strong><?=e($row['symbol']??'')?></strong><div class="sub"><?=e($row['field']??'')?> <?=!empty($row['dashboard_visible'])?'· 📌 Thông báo Tổng quan':''?></div></td>
        <td class="document-title-cell" data-full-title="<?=e($row['title']??'')?>"><a class="title doc-title-link preview-document" href="<?=e($openUrl)?>" data-previewable="<?=$mainPreviewable?'1':'0'?>" data-office-source="<?=e(vb_office_preview_source('document',(string)($row['id']??''),0))?>" data-title="<?=e($row['title']??'')?>" data-download="<?=e($openUrl.'&download=1')?>"><?=e($row['title']??'')?></a><div class="sub"><?=e($row['signer']??'')?><?php if(count($attachments)>1):?> · <?=count($attachments)?> tệp<?php endif;?></div><?php if(count($attachments)>1):?><div class="attachment-links"><?php foreach($attachments as $index=>$item):$itemPreviewable=(bool)preg_match('/\.(pdf|png|jpe?g)$/i',(string)($item['name']??''));?><a class="preview-document" href="<?=e($openUrl.'&file='.$index)?>" data-previewable="<?=$itemPreviewable?'1':'0'?>" data-office-source="<?=e(vb_office_preview_source('document',(string)($row['id']??''),(int)$index))?>" data-title="<?=e(($row['title']??'').' · Tệp '.($index+1))?>" data-download="<?=e($openUrl.'&file='.$index.'&download=1')?>"><i class="bi bi-paperclip"></i> Tệp <?=$index+1?></a><?php endforeach;?></div><?php endif;?></td>
        <td><span class="pill"><?=e($row['type']??'')?></span></td><td><?=vb_fmt_date((string)($row['issued_date']??''))?></td>
        <td><?=e($row['issuer']??'')?><div class="sub"><?=e($row['issuer_level']??'')?></div></td>
        <?php if($tab==='documents'&&$canManage):?><td><button type="button" class="btn btn-soft" onclick="document.getElementById('views-<?=e($docId)?>').showModal()"><i class="bi bi-eye"></i> <?=count($viewers)?></button><dialog class="modal" id="views-<?=e($docId)?>"><div class="modal-head"><div><strong>Người đã xem</strong><div class="sub"><?=e($row['symbol']??'')?> · <?=count($viewers)?> người</div></div><button class="btn btn-outline" type="button" onclick="this.closest('dialog').close()"><i class="bi bi-x-lg"></i></button></div><div class="modal-body"><?php if(!$viewers):?><div class="empty"><i class="bi bi-eye-slash"></i>Chưa có người dùng nào mở văn bản.</div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Người xem</th><th>Xem lần đầu</th><th>Gần nhất</th><th>Số lần</th></tr></thead><tbody><?php foreach($viewers as $viewer):?><tr><td><strong><?=e($viewer['name']??'')?></strong><div class="sub"><?=e($viewer['username']??'')?></div></td><td><?=e(isset($viewer['first_viewed_at'])?date('d/m/Y H:i',strtotime($viewer['first_viewed_at'])):'—')?></td><td><?=e(isset($viewer['last_viewed_at'])?date('d/m/Y H:i',strtotime($viewer['last_viewed_at'])):'—')?></td><td><span class="pill"><?=number_format((int)($viewer['view_count']??0))?></span></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></dialog></td><td class="action-column"><div class="row-actions"><button type="button" class="btn btn-outline edit-document" data-record="<?=e(json_encode($row,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>"><i class="bi bi-pencil"></i> Sửa</button><form method="post" onsubmit="return confirm('Xóa nội dung văn bản này? Tệp trên Drive vẫn được giữ.');"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete_document"><input type="hidden" name="return_tab" value="documents"><input type="hidden" name="id" value="<?=e($row['id']??'')?>"><button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i></button></form></div></td><?php endif;?>
      </tr>
    <?php endforeach; endif; ?>
    </tbody>
  </table>
</div>
<div class="doc-cards">
<?php if(!$shown):?><div class="empty"><i class="bi bi-inbox"></i>Chưa có văn bản phù hợp.</div>
<?php else:foreach($shown as $row):$attachments=vb_document_attachments($row);$docId=(string)($row['id']??'');$openUrl=BASE_URL.'vanban_open.php?id='.rawurlencode($docId);$viewers=($tab==='documents'&&$canManage)?vb_document_views($docId):[];$mainPreviewable=(bool)preg_match('/\.(pdf|png|jpe?g)$/i',(string)($attachments[0]['name']??''));?><article class="card doc-card">
  <a class="title doc-title-link preview-document" href="<?=e($openUrl)?>" data-previewable="<?=$mainPreviewable?'1':'0'?>" data-office-source="<?=e(vb_office_preview_source('document',(string)($row['id']??''),0))?>" data-title="<?=e($row['title']??'')?>" data-download="<?=e($openUrl.'&download=1')?>"><?=e($row['title']??'')?></a>
  <div class="sub"><?=e($row['symbol']??'')?> · <?=vb_fmt_date((string)($row['issued_date']??''))?></div><div class="meta"><span class="pill"><?=e($row['type']??'')?></span><span class="pill"><?=e($row['field']??'')?></span><?php if(count($attachments)>1):?><span class="pill"><?=count($attachments)?> tệp</span><?php endif;?><?php if(!empty($row['dashboard_visible'])):?><span class="pill success">📌 Tổng quan</span><?php endif;?></div><div class="sub"><?=e($row['issuer']??'')?></div>
  <?php if($tab==='documents'&&$canManage):?><div class="row-actions"><button type="button" class="btn btn-soft" onclick="document.getElementById('mobile-views-<?=e($docId)?>').showModal()"><i class="bi bi-eye"></i> <?=count($viewers)?> đã xem</button><button type="button" class="btn btn-outline edit-document" data-record="<?=e(json_encode($row,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>"><i class="bi bi-pencil"></i> Sửa</button><form method="post" onsubmit="return confirm('Xóa nội dung văn bản này?');"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete_document"><input type="hidden" name="return_tab" value="documents"><input type="hidden" name="id" value="<?=e($row['id']??'')?>"><button class="btn btn-danger"><i class="bi bi-trash"></i></button></form></div><dialog class="modal" id="mobile-views-<?=e($docId)?>"><div class="modal-head"><strong>Người đã xem (<?=count($viewers)?>)</strong><button class="btn btn-outline" type="button" onclick="this.closest('dialog').close()"><i class="bi bi-x-lg"></i></button></div><div class="modal-body"><?php if(!$viewers):?><div class="empty">Chưa có người dùng nào mở văn bản.</div><?php else:foreach($viewers as $viewer):?><div style="padding:.7rem 0;border-bottom:1px solid var(--line)"><strong><?=e($viewer['name']??'')?></strong><div class="sub">Gần nhất: <?=e(date('d/m/Y H:i',strtotime((string)($viewer['last_viewed_at']??''))))?> · <?=number_format((int)($viewer['view_count']??0))?> lần</div></div><?php endforeach;endif;?></div></dialog><?php endif;?>
</article><?php endforeach;endif;?></div>
